### ISSUE TITLE
suppress userwarnings for dandi ls

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#100]
currently userwarnings disrupt any output of dandi ls. should be suppressed for ls or routable to a file.

**Comment by yarikoptic** [comment]
knowing sample invocation and which warnings could help. I thought I have already prevented some

**Comment by satra** [comment]
```
dandi download https://dandiarchive.org/dandiset/000020
dandi ls 000020
```

but warnings go away after they are cached. so have to disable cache or remove it.

**Comment by yarikoptic** [comment]
I think we hidden them in that they are present only in the log file if any. ATM I fail to spot any (did only on the sample subset of 000020 locall).  If still emerges -- feel welcome to reopen
