### ISSUE TITLE
get_assets doesn't iterate over all assets

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#1018]
```python
    ...: for asset in ds.get_assets():
    ...:     if asset.path.endswith("ngff"):
    ...:         try:
    ...:             meta = asset.get_metadata()
    ...:         except ValidationError:
    ...:             check.append(asset)
    ...:             print(f"invalid: {asset.path}")
    ...:         else:
    ...:             meta.path = meta.path.replace(".ngff", ".ome.zarr")
    ...:             asset.set_metadata(meta)
    ...:             print(meta.path)
    ...: 
```
in this code `ds.get_assets()` does not go through all the assets in a dandiset. i have had to run the block multiple times on dandiset 108.

there are no errors, it just stops.

**Comment by jwodder** [comment]
@satra The following code runs fine for me:

```python
import logging
from dandi.dandiapi import DandiAPIClient

logging.basicConfig(
    format="%(asctime)s [%(levelname)-8s] %(name)s: %(message)s",
    datefmt="%H:%M:%S",
    level=logging.DEBUG,
)

with DandiAPIClient.for_dandi_instance("dandi") as client:
    d = client.get_dandiset("000108")
    for a in d.get_assets():
        print(a.path)
```

Can you determine exactly where your code is stopping?  Or produce an MVCE?

**Comment by satra** [comment]
it just stops after roughly 300ish assets, and i restart and it runs another set and then returns. do you get all 6000 assets in your loop?

**Comment by jwodder** [comment]
@satra I get 6040 assets, yes.

**Comment by satra** [comment]
the api server is under load at this point i think (i can't even get to the archive at the moment, the api is responding but slowly). 

a few resetting dropped connection. but since i have changed the names for most things, it's no longer doing the fetch metadata operation. once the load dies down, let me get metadata again.

**Comment by yarikoptic** [comment]
FWIW - snippet worked out for me just fine, and inspired to file #1019.

meanwhile, I wonder if we should increase default page_size and where  -- server or client?

we do 25 items by default (server) ATM. That takes that script 40 sec to run. Changing to 100 (on client side to be specified explicitly) -- goes down to 25 sec. Making it 500 -- 18 sec.  Overall, it feels that we should at least make it a hundred.  That should also reduce load on the server/logging.  I think we better change it on server side.  Most likely it would also affect default pagination of files in file navigator (which is imho ok).

WDYT? meanwhile also filed https://github.com/dandi/dandi-archive/pull/1107 to increase it on server side

**Comment by satra** [comment]
increasing number and parallelizing requests is good. it may be useful to also put in a throttle factor so one can control based on busy level of the server. 

unfortunately in a realistic scenario (i.e. when i first ran it), it was doing 3 calls per asset. in the current scenario it is only iterating over the assets endpoint, not making those other calls. i think the issue i ran into may have had something to do with the get/set metadata operations (more likely the latter). but there was no reported error, just that the loop stopped at about 5% of total number of assets.

**Comment by yarikoptic** [comment]
> ... just that the loop stopped at about 5% of total number of assets.

may be some `GET` call never returned/stalled?  I do not think we have any "stall" detection implemented yet. Not sure if `requests` which we IIRC use does, does it?  (I thought that there should be some stall detection at the level of TCP layer or smth like that for GET, but recently got `annex get` stalled  as well : https://git-annex.branchable.com/bugs/get_is_busy_doing_nothing/#comment-a9dd3fbeee226bff1a93048aed27f4f1)

**Comment by satra** [comment]
in this situation, i did get the ipython prompt back, so whatever happened, happened silently without exception.

**Comment by jwodder** [comment]
@satra Can this issue be considered resolved?

**Comment by yarikoptic** [comment]
I would say yes - there were good number of related changes on client and server sides and nobody but @satra ran into it, and we got no more detail to be able to resolve it to full satisfaction. @satra please reopen if you still observe this issue.
