### ISSUE TITLE
Tests are failing on Python 3.10 on macOS because numcodecs cannot build

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-cli#1032]
I'm not sure what changed, but starting between 10:55 and 12:29 EDT on June 16, our tests started failing on macOS with Python 3.10 because numcodecs (a dependency of Zarr) is no longer able to be built successfully, failing with numerous errors of the form `invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size`.

EDIT: It appears that the runner image used by GitHub Actions changed during this window.  The list of software for the older runner is [here](https://github.com/actions/virtual-environments/blob/macOS-11/20220605.1/images/macos/macos-11-Readme.md), and the software on the newer version is [here](https://github.com/actions/virtual-environments/blob/macOS-11/20220614.2/images/macos/macos-11-Readme.md).  The only possibly relevant difference I see with a quick look is that Python 3.10 was upgraded from 3.10.4 to 3.10.5.

**Comment by yarikoptic** [comment]
Issue known to numcodecs?

**Comment by jwodder** [comment]
@yarikoptic It is now: https://github.com/zarr-developers/numcodecs/issues/326

**Comment by yarikoptic** [comment]
Thanks!  since already fixed in `main` I guess we will just wait until some day it would release and finally we stop getting angry emails from cron jobs

**Comment by jwodder** [comment]
This has been resolved by a new numcodecs release.
