### ISSUE TITLE
support "upload" from external sources

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#104]
usecase the NWB post-presentation chat -- google drive.  
Difficulties in "supporting" it would be primarily requiring to download to our archive instance first for validation, possibly to just discover that file needs corrections.

**Comment by pankajkgupta** [comment]
Data storage is a central problem in big data neuroscience. We generate terabytes of data and storing them on clouds such as google drive is a good option for fast network access and scalable storage. I am right now using google-colab for data analysis on data stored at google-drive.
It would be great that DANDI can read data files from google drive. Google drive needs an access code everytime it mounts the drive.

**Comment by yarikoptic** [comment]
Note: hereby I am linking to freshier https://github.com/dandi/dandi-publish/issues/110 since it is the API layer where we should expose availability of such functionality. `dandi-cli` would just talk API to accomplish it.

**Comment by yarikoptic** [comment]
now it was transferred to https://github.com/dandi/dandi-api/issues/176 and I think we could close it on dandi-cli side since it would be implied to be supported by client whenever api supports it
