### ISSUE TITLE
Python 3.7 version for testing environment?

### ISSUE THREAD

**Issue by TheChymera** [dandi/dandi-cli#1045]
It appears that the testing environment, at least for typing, runs Python 3.7, and fails if the `dirs_exist_ok` parameter of `shutil.copytree()` ([introduced in 3.8](https://docs.python.org/3/whatsnew/3.8.html#shutil)) is used: https://ppb.chymera.eu/0c9c98

I looked through the repo and nowhere could I find the string `python3.7` mentioned, it appears to all be `python3.9`. Any idea how I could bump this? @jwodder 

Or are we trying to support 3.7 — in which case I should rather work around the fact that the older shutil copytree function has a glaring omission?

**Comment by jwodder** [comment]
@TheChymera We are trying to support 3.7.  For the record, the Python version used for type-checking on GitHub Actions is set [here](https://github.com/dandi/dandi-cli/blob/8b28039366753075feca03f7e1cd404f41f952d6/.github/workflows/typing.yml#L19).

**Comment by TheChymera** [comment]
ok, I will work around this then.
