### ISSUE TITLE
upload: only metadata

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#105]
Since we are still working out our schema of metadata to be kept on the remote dandiarchive server, it would be useful to have a mode of operation where it 
- would not upload file if it was not changed
- instead of removing a girder item it would just adjust its metadata with up-to-date information (current metadata schema, possibly new validations, etc)

**Comment by satra** [comment]
sounds good to me, but we should really nail a version of the schema down (added https://github.com/dandi/dandi-core/issues/3).

**Comment by yarikoptic** [comment]
BTW, in this issue I was concerned primarily with file level metadata and checksums and validation status. But that we don't have to nail file level schema down as well ;-)

**Comment by yarikoptic** [comment]
ha, as now discovered in a use case -- may be `--existing overwrite` should be tuned to provide such functionality.  That would also guarantee that uploaded file and metadata is in sync.  So we will skip uploading file if found to be the same, but will (re)upload metadata!

**Comment by yarikoptic** [comment]
was supposed to be closed by https://github.com/dandi/dandi-cli/pull/355 , not sure why didn't happen
