### ISSUE TITLE
download doesn't handle DANDI:<dandiset id>[/<version id>] although says that it does

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1058]
might be related to some prior issue with identifiers.org and/or our redirector (@satra might remember) which is not yet fixed. Then we should adjust documentation to not say that we support it.  If that is some internal bug -- should be fixed.

```
$> dandi download DANDI:000029/draft
2022-07-14 13:51:01,804 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20220714175100Z-591196.log
Error: We do not know how to map URL DANDI:000029/draft to our servers.
Accepted resource identifier patterns:
 - DANDI:<dandiset id>[/<version id>]
 - https://dandiarchive.org/...
...
```

**Comment by yarikoptic** [comment]
I thought for `DANDI:` we went to identifiers.org to get an ultimate location instead of duplicating/hardcoding it in the client... but running with `-l debug` shows

```
2022-07-14 15:21:38,112 [   DEBUG] Parsing url DANDI:000029/draft
2022-07-14 15:21:38,113 [   DEBUG] Caught exception We do not know how to map URL DANDI:000029/draft to our servers.
```
so I guess it is internal issue indeed.

**Comment by jwodder** [comment]
`DANDI:` identifiers do go through identifiers.org.  However, identifiers with a version of "draft" do not have entries on identifiers.org, and so they are not supported in this form, [as documented on the Read the Docs site](https://dandi.readthedocs.io/en/latest/ref/urls.html).

**Comment by yarikoptic** [comment]
cool. Can we just then output in error message that 

```
DANDI:<dandiset id>[/<version id>]  (note: <version id> must not be draft)
```
?

**Comment by satra** [comment]
but perhaps we can support `/draft` ? is there any reason not to?

**Comment by jwodder** [comment]
@satra Wouldn't that involve giving DOIs to drafts?  I don't believe that's an option.

**Comment by satra** [comment]
> Wouldn't that involve giving DOIs to drafts? I don't believe that's an option.

this is unrelated to DOIs. identifiers.org does not have any relation directly to the DOIs. 

i'm simply suggesting the CLI parse this as `DANDI:ID + /draft` and if the version is draft add that back in to the redirect link from `identifiers.org`.

**Comment by yarikoptic** [comment]
We support `DANDI:<dandiset id>/<version id>` because it is supported by identifiers.org. identifiers.org **does not** support `DANDI:<dandiset id>/draft`. If we start support it in `dandi-cli` it might suggest to the user that identifiers.org support it which is not the case. So -- shouldn't we better not introduce confusion?

For similar reasoning I think we would not add support `[DOI]/path` to point to some `/path` within DOI'ed dataset since dois do not support them.  We might provide some custom sugaring syntax though but would make it more obvious to avoid confusion.

**Comment by satra** [comment]
i don't think it's confusion. the id of a draft dandiset is `DANDI:<id>/draft` (it's in the metadata). hence we are saying that is the identifier for a draft dandiset. the reason we don't support it in identifiers.org is simply because we didn't want people to be able to resolve that to encourage people to publish to get resolution.

but the dandi cli is different. data uploaders also use it all the time, and therefore having access to that id would be useful to the user experience of the data submitter.

**Comment by yarikoptic** [comment]
> the id of a draft dandiset is `DANDI:<id>/draft` (it's in the metadata).

eh sneaky you -- tricked us all! ;) filed dedicated https://github.com/dandi/dandi-cli/issues/1065 for that
