### ISSUE TITLE
Allow to operate on an instance provided by URL, based on /server-info

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1085]
With https://github.com/dandi/dandi-archive/pull/1190 in dandi-archive we would (re-?)gain usable /server-info from the local instances.  But ATM `dandi` is not designed to be able to work with some arbitrary instance of dandi archive it doesn't know so without #1003 or replacing it #1084 it wouldn't even be able to download a dandiset from it:

```
$> curl http://localhost:8085/server-info/
{"schema_version":"0.6.3","schema_url":"https://raw.githubusercontent.com/dandi/schema/master/releases/0.6.3/dandiset.json","version":"0.2.39.post19+g9b92512f","services":{"api":{"url":"http://localhost:8000/api"},"webui":{"url":"http://localhost:8085"},"jupyterhub":{"url":"https://hub.dandiarchive.org/"}},"cli-minimal-version":"0.14.2","cli-bad-versions":[]}

$> dandi download http://localhost:8085/dandiset/000001
2022-07-26 17:00:36,014 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20220726210034Z-1548312.log
Error: No such Dandiset: '000001'
``` 

But `download` is not a single command which needs to know about instance, and we have `-i|--dandi-instance` to specify the instance.  I think we should 
- if instance cannot be deduced from URL, get that URLs top `/server-info` and create an instance with that URL as the name internally for the duration of that process to be used as the instance_name.
- allow for a URL (such as `http://localhost:8085/`) to be provided/used as the instance name, thus allowing for any other operation , such as `upload -i http://localhost:8085/`.

**Comment by jwodder** [comment]
First, see https://github.com/dandi/dandi-archive/issues/1200 for discussion on a potential alternative to `/server-info`.

> if instance cannot be deduced from URL, get that URLs top `/server-info`

Are you sure `/server-info` will always be at the top?  What if someone deploys a DANDI Archive GUI at `https://www.example.com/dandi/`?

---

As far as I can tell at the moment, this feature would require changing the following:

* The URL-parsing code would have to handle GUI URLs by determining their `/server-info` path, making a request to it, and combining the Dandiset ID etc. from the original URL with the API URL
* The `--dandi-instance` option would have to accept both known instance names and URLs
* Something somewhere would have to determine whether a user-supplied instance was an instance name or a URL and return either an appropriate `dandi.consts.DandiInstance` instance or just a final API URL

* We would have to do something about most or all uses of `known_instances` and `known_instances_rev` in the code, including:
    * [This spot](https://github.com/dandi/dandi-cli/blob/e74c5ac88d4a3af917c0ac9d773325058c09a185/dandi/dandiapi.py#L434-L435) in `DandiAPIClient.for_dandi_instance()`
    * [`DandiAPIClient._instance_id`](https://github.com/dandi/dandi-cli/blob/e74c5ac88d4a3af917c0ac9d773325058c09a185/dandi/dandiapi.py#L497-L503) (used in stringifying resource objects)
    * [This spot](https://github.com/dandi/dandi-cli/blob/e74c5ac88d4a3af917c0ac9d773325058c09a185/dandi/cli/cmd_download.py#L125) in the `dandi download` command
    * We would likely have to finally do something about [this TODO item](https://github.com/dandi/dandi-cli/blob/e74c5ac88d4a3af917c0ac9d773325058c09a185/dandi/dandiapi.py#L473)
    * Something would have to change in [`get_instance()`](https://github.com/dandi/dandi-cli/blob/e74c5ac88d4a3af917c0ac9d773325058c09a185/dandi/utils.py#L557)

**Comment by yarikoptic** [comment]
> Are you sure `/server-info` will always be at the top? What if someone deploys a DANDI Archive GUI at `https://www.example.com/dandi/`?

I would say that for now (or forever) we can rely on that.  If there would be some strong use case, then we would just need to introduce "sensing" for /server-info (like we do for `.git` folder or `dandiset.yaml` locally) down the URL to figure "the top". But I really wouldn't worry about that to be needed ATM.

**Comment by yarikoptic** [comment]
> * We would likely have to finally do something about [this TODO item](https://github.com/dandi/dandi-cli/blob/e74c5ac88d4a3af917c0ac9d773325058c09a185/dandi/dandiapi.py#L473)

```python
        if self.api_url in known_instances_rev:
            client_name = known_instances_rev[self.api_url]
        else:
            raise NotImplementedError("TODO client name derivation for keyring")
```
which is pretty much like "what is the realm" or "id" of that instance. I don't think that we would come up with those any time soon.  I think in general we can use `domain:port` as the client_name since unlikely we would have multiple under different sub-paths (i.e. not at the top, assumption above), but could have multiple on different ports (e.g. like during testing/development).

**Comment by yarikoptic** [comment]
please let me know if any other clarification is needed.

**Comment by yarikoptic** [comment]
https://dandiarchive.org/server-info is pretty much a redirect to `/api/info`. If `/server-info` is 404, and `/api-info` provides json record with expected field(s) -- let's use that one.

**Comment by jwodder** [comment]
@yarikoptic Do we still need the "redirector" element of `DandiInstance`?  It's only used [here](https://github.com/dandi/dandi-cli/blob/7a86c283ab926f4c53b791d4afc32f797f08e189/dandi/utils.py#L589) in `get_instance()` as the root of the `/server-info` request, but as https://gui.dandiarchive.org/server-info now exists, it seems redundant.

**Comment by yarikoptic** [comment]
right, we no longer use redirector, so I archived https://github.com/dandi/redirector .  For consistency I would just make it `None` while keeping the element  - no need to break ABI (happen some code for some reason uses it downstream) IMHO.

**Comment by jwodder** [comment]
@yarikoptic Also, what fields of the `/server-info`/`/api/info` response am I allowed to assume exist?  The Swagger docs state that all fields are required, yet the current client code for working with the response allows for some of them to be absent.

**Comment by yarikoptic** [comment]
> @yarikoptic Are we still using a Dandi instance at https://gui-beta-dandiarchive-org.netlify.app? It's the only instance in `known_instances` that doesn't have an API URL, and I'd like to get rid of it.

yeah -- I think we can kill it - seems to be NA etc.

> @yarikoptic Also, what fields of the `/server-info`/`/api/info` response am I allowed to assume exist? The Swagger docs state that all fields are required, yet the current client code for working with the response allows for some of them to be absent.

For detection of the record I would assume it needing to have "version" and "services". I would code robustly for "services" keys and do not assume any present, but if `"api"` is not present/empty -- error out.

**Comment by jwodder** [comment]
@yarikoptic Question: Resolution of arbitrary instance URLs uses `get_instance()`, which always (even if a known instance is specified) makes a request to `/server-info` to check allowed CLI versions and get the final API & GUI URLs.  Do we want to keep doing this when parsing Dandi URLs for arbitrary instances?  Doing so would slow things down and make testing without a network tricky.

**Comment by yarikoptic** [comment]
Overall: we definitely want to warrant "allowed CLI versions" and I think we should move away from relying on hardcoded records for  instances/services, and thus cannot avoid fetching `/server-info`.
For testing without network -- I would assume that we would still have connection to docker instance and thus as long as that one works - everything we test would still work.  Or is there tests you know which would be affected if we start (if we don't do atm) querying `/server-info` for every `get_instance()`?

I looked around the code (not tests) where we use `get_instance`: it seems that part of the slow down could be that we do not cache result of `get_instance` which gets invoked in `_dandi_url_parser.parse`  for every url -- so if we are to queries for multiple URLs - ATM we would rerun `get_instance` over and over again for the same instance. We would want to cache it.  I didn't analyze if we would be getting only top level sanitized (e.g. no trailing `/` and query options) URLs into it (thus a simple `@lru_cache` might suffice) or we would need to sanitize first. With that interactions should probably remain as fast as before if not faster for multiple URLs, or am I missing some specific code paths/use cases?

**Comment by yarikoptic** [comment]
is the instances used by the tests are the same, then with caching of the `get_instance` we at least would keep it efficient right?  Then the concern would remain only testing without network, right?

**Comment by jwodder** [comment]
@yarikoptic Correct.
