### ISSUE TITLE
move: add some examples in its --help

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1092]
see https://github.com/dandi/dandi-cli/issues/1081#issuecomment-1191798525 and therein to simplify life of a user needing to figure how it works.

**Comment by jwodder** [comment]
@yarikoptic What sort of actions do you want to see examples of?

**Comment by yarikoptic** [comment]
- local+remote simple rename of a file, e.g. `sub-01/sub-01_blah.nii.gz` to `sub-02/sub-02_useful.nii.gz`
- remote only moving of folder's content "upstairs" using regex like in https://github.com/dandi/dandi-cli/issues/1081#issuecomment-1191798525
