### ISSUE TITLE
Restore BIDS metadata integration for `dandi ls`

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-cli#1097]
See https://github.com/dandi/dandi-cli/pull/1076#issuecomment-1205304196 for more information.

**Comment by TheChymera** [comment]
@jwodder are you satisfied with this?

**Comment by jwodder** [comment]
@TheChymera If the tests pass, then I'm satisfied.

**Comment by TheChymera** [comment]
@jwodder how did you link the PR to close this issue? I thought the `Closes: ...` lines in the commit text body already do that — but those don't show up 🤔

**Comment by jwodder** [comment]
@TheChymera I added "Closes #1097" to the text of the top comment in the PR.  I think text in commit messages has to be on the first line in order for GitHub to recognize it.
