### ISSUE TITLE
Troubleshoot failing/stalling tests on master

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1099]
see https://github.com/dandi/dandi-cli/actions/runs/2837734398 which has

[test (ubuntu-18.04, 3.7, dev-deps)](https://github.com/dandi/dandi-cli/runs/7781214399?check_suite_focus=true#step:8:28741)
Process completed with exit code 1.
[test (ubuntu-18.04, 3.10, normal)](https://github.com/dandi/dandi-cli/runs/7781213938?check_suite_focus=true)
The job running on runner GitHub Actions 4 has exceeded the maximum execution time of 360 minutes.
[test (ubuntu-18.04, 3.10, normal)](https://github.com/dandi/dandi-cli/runs/7781213938?check_suite_focus=true#step:8:26430)
The operation was canceled.

**Comment by jwodder** [comment]
@yarikoptic
* For the 3.10 run, it looks like the cloning of https://github.com/dandi-datasets/nwb_test_data/ stalled somehow.  This is not happening when I run the tests locally, so it's likely to have been a transitory connection issue.
* For the 3.7 dev-deps run (which uses the development version of pynwb), the video file tests all failed [here](https://github.com/dandi/dandi-cli/blob/7c42ed91c084e978f9904fd7495f8fcf97239b1a/dandi/tests/fixtures.py#L520-L527) with `ValueError: ImageSeries 'MouseWhiskers0': The number of frame indices in 'starting_frame' should have the same length as 'external_file'.`  I'm going to see if I can fix this.
