### ISSUE TITLE
organize - cannot move files on Windows across drives

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1110]
IIRC we had similar issue in datalad-installer recently. IIRC boils down to using shutil's move instead.

e.g.

```
(dandi) C:\Users\Pluta lab\000301>dandi organize "D:\MATLAB Analysis\NWD\matnwb\nwd_files"
2022-08-30 13:10:28,635 [ INFO] Loading metadata from 14 files
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done 3 out of 14 | elapsed: 4.4s remaining: 16.3s
[Parallel(n_jobs=-1)]: Done 5 out of 14 | elapsed: 4.4s remaining: 8.0s
[Parallel(n_jobs=-1)]: Done 7 out of 14 | elapsed: 4.4s remaining: 4.4s
[Parallel(n_jobs=-1)]: Done 9 out of 14 | elapsed: 4.4s remaining: 2.4s
[Parallel(n_jobs=-1)]: Done 11 out of 14 | elapsed: 4.4s remaining: 1.1s
[Parallel(n_jobs=-1)]: Done 14 out of 14 | elapsed: 4.5s finished
2022-08-30 13:10:33,207 [ INFO] Hard link support autodetected; setting files_mode='hardlink'
2022-08-30 13:10:33,230 [ INFO] Logs saved in C:\Users\Pluta lab\AppData\Local\dandi\dandi-cli\Logs\20220830171021Z-9648.log
Error: [WinError 17] The system cannot move the file to a different disk drive: 'D:\MATLAB Analysis\NWD\matnwb\nwd_files\ecephys_t_26.nwb' -> '.\sub-M26\sub-M26_ses-20200319T153237_behavior+ecephys.nwb'
```

reported in https://github.com/dandi/helpdesk/discussions/80#discussioncomment-3511318

**Comment by yarikoptic** [comment]
also just noticed "hard link support autodetected" -- not sure if that is really supported on windows

**Comment by jwodder** [comment]
@yarikoptic Could you be precise about exactly what change you want done to the code for this?  We can't just switch to an unconditional `shutil` without throwing away the code for autodetecting hardlink/symlink support.

**Comment by yarikoptic** [comment]
`dandi organize PATH_ON_ANOTHERDRIVE` on windows should use "compatible" copy  operation.  

I am not sure why user also saw error about "move"ing since we should not move unless asked to be moved, we should copy.  So might need fix up of logic as well, unless that error was some kind of a sideeffect of trying to "hardlink"

**Comment by jwodder** [comment]
@yarikoptic 

> `dandi organize PATH_ON_ANOTHERDRIVE` on windows should use "compatible" copy operation.

How should it tell what operation to use?

> I am not sure why user also saw error about "move"ing

My best guess is that that's just a generic system message used for both moving and copying.

**Comment by yarikoptic** [comment]
> How should it tell what operation to use?

I would have first troubleshooted why it decided that hardlinking across drives was available!  if can be resolved at that stage "Generally" -- good.  If not -- disable hardlinking on windows altogether so it proceeds with `copy` and then ensure that copy works across drives

**Comment by jwodder** [comment]
@yarikoptic

> I would have first troubleshooted why it decided that hardlinking across drives was available!

The test of linking capabilities operates on two temp files in the dandiset root directory.  `os.link()` apparently works on Windows, so the test of it succeeded, and so the code proceeded to attempt a hardlink from the source path to the destination path.

Couldn't this be solved by the user just passing `--files-mode move` to `dandi organize`?

**Comment by yarikoptic** [comment]
> Couldn't this be solved by the user just passing `--files-mode move` to `dandi organize`?

Explicitly using `--files-mode copy` (AFAIK we should not `move` "by default") is [what I recommended to the user as a workaround](https://github.com/dandi/helpdesk/discussions/80#discussioncomment-3511824).  The point is that specification of `--files-mode` should not be necessary!  

> The test of linking capabilities operates on two temp files in the dandiset root directory. `os.link()` apparently works on Windows, so the test of it succeeded, and so the code proceeded to attempt a hardlink from the source path to the destination path.

oh, ok. Please then change that by testing hardlinking one sample source file (not just temp file) into " file in the dandiset root directory".  Then we would know better if hardlinking would be possible (on windows or not) for other files in the particular case like here (on different drives... could be similarly on different file systems on linux, so not windows specific then)

**Comment by jwodder** [comment]
@yarikoptic

> Please then change that by testing hardlinking one sample source file (not just temp file) into " file in the dandiset root directory".

Looking at the source code, I see some problems with that approach:

* `organize` can be passed multiple directories of NWB files to operate on at once, so the various input files can exist on multiple different filesystems.
* [`organize` accepts a file of JSON metadata instead of an NWB file path](https://github.com/dandi/dandi-cli/blob/ef097cc124629556d94544b4ca40f2f1ee567425/dandi/organize.py#L794-L796); I'm not clear what files it operates on in that case.

**Comment by yarikoptic** [comment]
- operate on `metadata["path"]` which I believe must be present in that loaded json metadata (list I assume)
- provide `detect_link_type` list of folders for those paths, inside loop through those folders and "trim down" list of possible choices `['symlink', 'hardlink', 'copy']` until you end up just with copy or you exit that loop with some other value (i.e. all folders are ok with symlink or hardlink)

**Comment by jwodder** [comment]
@yarikoptic To be clear, the metadata loaded from the file is a list of dicts, each of which contains a `"path"` field, correct?  Is this `"path"` a path to a file or a directory?

> provide `detect_link_type` list of folders for those paths, inside loop through those folders

Do you mean loop through just the folders passed to `dandi organize` (or through the containing folders for paths that point to files) or loop through all folders containing files found by `find_files()`?

**Comment by yarikoptic** [comment]
In theory `foo/bar/glarch` could be a different mount point from `foo/bar`, but pragmatically - let's just test the "top most" disjoint paths, e.g. for `foo/bar`, `foo/bar/glarch` and `a/b` it would be `foo/bar` and `a/b`.

**Comment by jwodder** [comment]
@yarikoptic Does "'top most' paths" here mean "those paths given on the command line that contain all other paths on the command line"?  For example, given just `foo/bar/baz` and `foo/gnusto/cleesh`, would the two directories be tested separately or would `foo/` be tested?

**Comment by yarikoptic** [comment]
> @yarikoptic Does "'top most' paths" here mean "those paths given on the command line that contain all other paths on the command line"?

correct

> For example, given just `foo/bar/baz` and `foo/gnusto/cleesh`, would the two directories be tested separately or would `foo/` be tested?

just `foo/`.

**Comment by jwodder** [comment]
@yarikoptic But `foo/` *isn't* a path given on the command line, which contradicts the definition you just agreed with.

**Comment by yarikoptic** [comment]
I guess   I got misguided by `foo/gnusto/cleesh` which was not mentioned before. Then it means that topmost paths are not necessarily the ones which were explicitly given!

**Comment by jwodder** [comment]
@yarikoptic So you still want `foo/` to be the one tested?  On Unix systems, this can easily end up with trying to test only `/`, which we likely won't have write access to and which won't serve the purpose of checking for differing mount points.

**Comment by yarikoptic** [comment]
you are right but let's say "that is ok". As I have mentioned [above](https://github.com/dandi/dandi-cli/issues/1110#issuecomment-1233260347) we need to consider paths from `metadata['path']` so we would not operate only with what is provided on CLI. 
Under assumption that all paths user would provide would come from the same mount point we can just take first (or last, doesn't matter) path on the list and use it for testing -- try to hardlink/symlink/... somewhere into destination path. So just make `detect_link_type` get a srcpath (instead of using the same workdir) and do not unlink srcpath at the end as it does now.

**Comment by jwodder** [comment]
@yarikoptic

> do not unlink srcpath at the end as it does now.

(Assuming you meant "do not unlink srcfile", where "srcfile" is the temporary file used as the src for copy-like testing) Why shouldn't srcfile be unlinked?  Not unlinking it would result in a junk temp file being left in the destination directory.

**Comment by yarikoptic** [comment]
I'm comment above I suggested to use actual path among those given to organize. So we don't need to create any temporary but just can stmymlink or hardlink it instead of creating some temporary one. This would also allow organize to symlink etc on source directories which do not belong to the user
