### ISSUE TITLE
[Bug]: cannot import name 'properties' from 'keyring.util'

### ISSUE THREAD

**Issue by CodyCBakerPhD** [dandi/dandi-cli#1111]
Just FYI

Ran into this earlier today: https://github.com/catalystneuro/neuroconv/runs/8136194375?check_suite_focus=true

Already been raised upstream on https://github.com/jaraco/keyring/issues/593

For now I'm pinning to <=23.8.2 downstream, IDK what y'all would prefer to do for now here though.

**Comment by yarikoptic** [comment]
Thanks for the alert!  Isn't there some `!= 23.8.2` syntax ?  I would assume it would get fixed.. will send a PR shortly.
