### ISSUE TITLE
add support for signed url location to access embargoed data with fsspec

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#1134]
can someone show how to access an embargoed asset with `fsspec` ? this is a bit urgent as some folks are trying to build some analysis scripts for embargoed assets.

also see dandi/dandi-archive#1317 

cc: @yarikoptic

**Comment by yarikoptic** [comment]
no need for header access etc, should work, and seems to work for me to get that download url as shown on https://pynwb.readthedocs.io/en/stable/tutorials/advanced_io/streaming.html#getting-the-location-of-the-file-on-dandi via `asset.get_content_url(follow_redirects=1, strip_query=True)`:

```
❯ cat embargo_url.py
from dandi.dandiapi import DandiAPIClient
import sys
dandiset_id = sys.argv[1] or '000006'  # ephys dataset from the Svoboda Lab
filepath = sys.argv[2] or 'sub-anm372795/sub-anm372795_ses-20170718.nwb'  # 450 kB file
with DandiAPIClient() as client:
    client.dandi_authenticate()
    asset = client.get_dandiset(dandiset_id, 'draft').get_asset_by_path(filepath)
    s3_url = asset.get_content_url(follow_redirects=1, strip_query=True)
    print(f"{dandiset_id}/{filepath} has {s3_url}")
❯ python embargo_url.py '000344' 'sub-private/sub-private.dat'
000344/sub-private/sub-private.dat has https://dandiarchive-embargo.s3.amazonaws.com/000344/blobs/127/efb/127efb7b-4261-4f91-80f3-43ba23f3f9f1
```
it was important though to authenticate via ` client.dandi_authenticate()` since if I don't do - kaboom with 401. Filed https://github.com/dandi/dandi-cli/issues/1137 for that but agreed with @jwodder that for library mode we might not want to do magic/prompts here.

What would also be needed to adjust also in those docs for embargoed dandisets to not do `strip_query=True` since it carries all needed auth args. And then we come to the next aspect:  as far as I see it caching would not work properly then since it would use the entire URL as the cache key. Asked https://github.com/fsspec/filesystem_spec/issues/1073 on the best course of action for that aspect.

After we figure out both aspects, we should adjust docs.

**Comment by satra** [comment]
@yarikoptic - take a look at the code above and try to get the bytes partially (as with s3fs). the existing content urls will not allow you to map via s3fs. in the client it retrieves the entire byte stream from the download endpoint.

**Comment by satra** [comment]
@yarikoptic - it's more about streaming not caching. i just used the same example as the pynwb docs which uses caching.

**Comment by yarikoptic** [comment]
@satra please give full example on what you want to achieve and/or how it doesn't work since I did try to get bytes partially and it worked for me on embargoed dandiset.  Here is a more complete example you can tune up:

```python
from dandi.dandiapi import DandiAPIClient
import fsspec
import pynwb
import h5py
from fsspec.implementations.cached import CachingFileSystem
import sys
import re

dandiset_id = '000344' # (len(sys.argv) > 1 and sys.argv[1]) or '000006'  # ephys dataset from the Svoboda Lab
filepath = 'sub-private/sub-private.dat'  # (len(sys.argv) > 2 and sys.argv[2]) or  'sub-anm372795/sub-anm372795_ses-20170718.nwb'  # 450 kB file

with DandiAPIClient() as client:
    client.dandi_authenticate()
    asset = client.get_dandiset(dandiset_id, 'draft').get_asset_by_path(filepath)
    s3_url = asset.get_content_url(follow_redirects=1)
    s3_url_sensored = re.sub('(X-Amz-Credential|X-Amz-Signature)=\w*', '\\1=___SENSORED___', s3_url)
    print(f"{dandiset_id}/{filepath} has {s3_url_sensored}")

fs = CachingFileSystem(
    fs=fsspec.filesystem("http"),
    cache_storage="nwb-cache",  # Local folder for the cache
)
with fs.open(s3_url, "rb") as f:
    f.seek(2)
    print("Read some byte ", f.read(1))
```

```
❯ python embargo_url2_fsspec.py
000344/sub-private/sub-private.dat has https://dandiarchive-embargo.s3.amazonaws.com/000344/blobs/127/efb/127efb7b-4261-4f91-80f3-43ba23f3f9f1?response-content-disposition=attachment%3B%20filename%3D%22sub-private.dat%22&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=___SENSORED___%2F20221013%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20221013T190723Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=___SENSORED___
Read some byte  b'r'
```

although I asked fsspec about stripping, I think we should just `follow_redirects=0` so we get api.dandiarchive.org URL and operate on that one.  We would just need to figure out how to authenticate https://docs.aiohttp.org  for which fsspec allows to pass via `client_kwargs` option to `HTTPFileSystem`.  Anyone @dandi/archive-maintainers @dandi/dandi-cli sees right away how to create authenticated aiohttp session?

**Comment by satra** [comment]
@yarikoptic - ok - i think i interpreted the 403 as an exception. is there a reason that is printed? 

so getting the signed url is there. i'll close this issue. 

the download endpoint does not pass on range requests i think. i don't believe i got fsspec to work with the download endpoint.

**Comment by yarikoptic** [comment]
> . is there a reason that is printed?

what is printed? if error if it happens  -- sounds logical to me.

> the download endpoint does not pass on range requests i think. i don't believe i got fsspec to work with the download endpoint.

I recall us trying smth but forgot detail... trying it out on a public one -- seems to work just fine!

```
❯ python public_url2_fsspec-range.py
000003/sub-YutaMouse20/sub-YutaMouse20_ses-YutaMouse20-140321_behavior+ecephys.nwb has https://api.dandiarchive.org/api/assets/d426ff9a-bab3-446d-8104-e373ae188bd3/download/
Read some byte  b'\x9c'
❯ du -sck nwb-cache/*
5124	nwb-cache/6044c4a6d96fafee40c79bb7fa45d2f8443648ac25e0fc461561e5aefe38fbca
4	nwb-cache/cache
5128	total
❯ cat public_url2_fsspec-range.py
from dandi.dandiapi import DandiAPIClient
import fsspec
import pynwb
import h5py
from fsspec.implementations.cached import CachingFileSystem
import sys
import re

dandiset_id = '000003'
filepath = 'sub-YutaMouse20/sub-YutaMouse20_ses-YutaMouse20-140321_behavior+ecephys.nwb'  # 11GB

with DandiAPIClient() as client:
    client.dandi_authenticate()
    asset = client.get_dandiset(dandiset_id, 'draft').get_asset_by_path(filepath)
    s3_url = asset.get_content_url(follow_redirects=0)
    print(f"{dandiset_id}/{filepath} has {s3_url}")

fs = CachingFileSystem(
    fs=fsspec.filesystem("http"),
    cache_storage="nwb-cache",  # Local folder for the cache
)
with fs.open(s3_url, "rb") as f:
    f.seek(200000000)
    print("Read some byte ", f.read(1))

```
so I seek deep into and then read 1 b, fetched is just 5 MB block... should have tried pynwb I guess ... so next would be to figure out aiohttp auth...

Meanwhile we got answer from fsspec folks -- we can split URL away from params
```
s3_url_parts = s3_url.split('?', 1)
from urllib.parse import unquote
with fs.open(s3_url_parts[0], "rb", params=unquote(s3_url_parts[1])) as f:
```

(just now noted that we have no versionId among them there?!) and then indeed we get clean cache with base url:

```
❯ python -c "import json, re, pickle; print(json.dumps(eval(re.sub('(X-Amz-Credential|X-Amz-Signature)=\w*', '\\1=___SENSORED___', str(pickle.load(open('nwb-cache/cache', 'rb'))))), indent=4))"
{
    "https://dandiarchive-embargo.s3.amazonaws.com/000344/blobs/127/efb/127efb7b-4261-4f91-80f3-43ba23f3f9f1": {
        "original": "https://dandiarchive-embargo.s3.amazonaws.com/000344/blobs/127/efb/127efb7b-4261-4f91-80f3-43ba23f3f9f1",
        "fn": "9a2b1361f9c4a3a436bdfc250c8393d7b5ae4cd651cd71de4712a38c98a7fd93",
        "blocks": true,
        "time": 1665694987.767868,
        "uid": "72dddceb347a2032e194736f160891bc",
        "blocksize": 5242880
    }
}
```
so we have a way.. might indeed want to have a helper of some kind.

**Comment by satra** [comment]
> what is printed? if error if it happens -- sounds logical to me.

Error 403 while sending HEAD request to https://api.dandiarchive.org/api/assets/463fc0cb-cea5-4cd9-b477-5b1747e0ccbf/download/: 

it just prints this, doesn't raise an exception.

**Comment by yarikoptic** [comment]
hm... again not sure what prints that and why just prints ... cut/paste code/output would have cleared it up... anyways -- seems to work this code on direct download url! try with hdf5 etc (originally posted to https://github.com/fsspec/filesystem_spec/issues/1073#issuecomment-1278203802 by mistake ;))

```python
from dandi.dandiapi import DandiAPIClient
import fsspec
import pynwb
import h5py
from fsspec.implementations.cached import CachingFileSystem
import sys
import re

dandiset_id = '000344' # (len(sys.argv) > 1 and sys.argv[1]) or '000006'  # ephys dataset from the Svoboda Lab
filepath = 'sub-private/sub-private.dat'  # (len(sys.argv) > 2 and sys.argv[2]) or  'sub-anm372795/sub-anm372795_ses-20170718.nwb'  # 450 kB file

# TODO: make helper
from dandi.keyring import keyring_lookup
client_name = 'dandi'
app_id = f"dandi-api-{client_name}"
keyring_backend, api_key = keyring_lookup(app_id, "key")
if not api_key:
    raise ValueError("empty key")
# fs._session.headers.update({"Authorization": f"token {api_key}"})

fs = CachingFileSystem(
    fs=fsspec.filesystem("http",
                         client_kwargs={'headers': {"Authorization": f"token {api_key}"}}
                         ),
    cache_storage="nwb-cache",  # Local folder for the cache
)

with DandiAPIClient() as client:
    client.dandi_authenticate()
    asset = client.get_dandiset(dandiset_id, 'draft').get_asset_by_path(filepath)
    down_url = asset.get_content_url(follow_redirects=0)
    print(f"{dandiset_id}/{filepath} has {down_url}")

with fs.open(down_url, "rb") as f:
    f.seek(2)
    print("Read some byte ", f.read(1))
```

with output

```
$> python embargo_url4_fsspec.py        
000344/sub-private/sub-private.dat has https://api.dandiarchive.org/api/assets/8f998a62-ac4c-465d-9989-656c90fb4668/download/
Read some byte  b'r'
```

**Comment by satra** [comment]
that's nice. we should document this in our handbook. can you try it on a larger file in jerome's embargoed dataset? it would also be good to know if the api will keep generating presigned url's each time a request is made or is smart enough to reuse one till it expires.

**Comment by yarikoptic** [comment]
which dandiset is that? (search probably doesn't search through embargoed ATM)
