### ISSUE TITLE
validate: do report HINTs from NWBI

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1151]
- add CLI option `--severity` which would take a value known to Severity and not report anything above that severity level
- make default rendering include the severity in rendering.

see in https://github.com/dandi/dandi-cli/issues/1031#issuecomment-1302816282 (and file available from there in) what we see with `dandi validate` now and additional items which nwbinspector provides as recommendations.

**Comment by TheChymera** [comment]
> add CLI option --severity which would take a value known to Severity and not report anything above that severity level

This I understand

> make default rendering include the severity in rendering.

This I do not.

**Comment by yarikoptic** [comment]
> > make default rendering include the severity in rendering.
> 
> This I do not. What do you mean by this?

see e.g. in https://github.com/dandi/dandi-cli/issues/1031#issuecomment-1302816282 nwbinspector output which groups by 

```
0  CRITICAL
===========

...
1  BEST_PRACTICE_SUGGESTION
===========================
```

could be similar way groups or could be just visualized in every entry ATM.

**Comment by yarikoptic** [comment]
@TheChymera what about progress on this issue? I have ran into "desire" of limiting output only to Errors today to only realize that we still do not have `--severity` option.

I think we might want that Severity Enum to map to integers so we make them comparable, e.g. `if severity <= Severity.ERROR`.  Or there is some better way to make `Enum` "ordered" and comparable similarly @jwodder ?

**Comment by yarikoptic** [comment]
`--ignore` is about ignoring based on ID, it is  orthogonal to the `severity`

**Comment by TheChymera** [comment]
Ok, started putting this together. However, when confronted with the practical aspect, new issues become evident with were not at all obvious in the abstract... or at least not to me.

You said:

> add CLI option --severity which would take a value known to Severity and not report anything above that severity level

is this a typo or do you really want something to suppress *higher* severity levels? I think suppressing *lower* severity levels would be the more useful feature 🤔 Though of course, someone might want both. Do we want to overengineer this with `--severity_max` and `--severity_min` (when we only have 3 levels), or just trust that whoever wants this is familiar enough to list what they want to suppress via something like `--ignore_severities`?

Also, as I brought up on the `--ignore` option. Is this really something we want to do, do you have an example where piping the output wouldn't achieve the same thing with more customization potential than we could feasibly parameterize?

**Comment by yarikoptic** [comment]
> > add CLI option --severity which would take a value known to Severity and not report anything above that severity level
> 
> is this a typo or do you really want something to suppress _higher_ severity levels?

yeah, was not clear semantic. You got it right: if `--severity ERROR`, we should not see any HINTS .  But indeed might be worth making it more explicit with naming it as `--min-severity` (no need for max one). (best to not mix `_` and `-` in CLI options names IMHO)

**Comment by TheChymera** [comment]
Fixed in https://github.com/dandi/dandi-cli/pull/1248
