### ISSUE TITLE
properly fix up test_validate_nwb_path_grouping and possibly others

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1158]
prompted by https://github.com/dandi/dandi-cli/pull/1157 which provides stop gap measure

docstrings suggest that they need to be expanded

**Comment by TheChymera** [comment]
@yarikoptic  Does the linked PR not address this? I would recommend closing the issue or expanding the description.

**Comment by yarikoptic** [comment]
didn't look in detail but at least those 2 tests have docstring which suggests that they are yet to be done

```shell
❯ git grep -p 'This is currently a placeholder test'
dandi/cli/tests/test_cmd_validate.py=def test_validate_bids_grouping_error(bids_error_examples, dataset="invalid_asl003"):
dandi/cli/tests/test_cmd_validate.py:    This is currently a placeholder test, and should be updated once we have paths with
dandi/cli/tests/test_cmd_validate.py=def test_validate_nwb_path_grouping(organized_nwb_dir3: Path) -> None:
dandi/cli/tests/test_cmd_validate.py:    This is currently a placeholder test and should be updated once we have
```

**Comment by TheChymera** [comment]
That's more of an issue with test `bids-examples` data and the `bids-specification` validator then, not the actual tests. I'll open issues there and link them here.

**Comment by TheChymera** [comment]
This isn't really an issue with DANDI, but with our dependencies. Moving the discussion over to NWB → https://github.com/NeurodataWithoutBorders/nwbinspector/issues/345

**Comment by TheChymera** [comment]
PR, better kept track of there than reopening this: https://github.com/dandi/dandi-cli/pull/1244
