### ISSUE TITLE
check that "re-upload"  of .zarr doesn't mint a new asset

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1160]
@slaytonmarx  is uploading more zarrs into 000108 but likely also is going through some already uploaded, right @slaytonmarx?  What is your `dandi upload` invocation ?

as I noted in https://github.com/dandi/dandisets/issues/298 it seems that we have changes to many (or all, didn't check) assets in 000108 whenever there is really no changes to zarr content or associated metadata, besides a new `urn:uuid` for metadata generation.  @jwodder could you please double check that we are not somehow causing minting a new asset upon reupload of a zarr which has nothing changed etc.

**Comment by jwodder** [comment]
@yarikoptic Uploading a Zarr to a path at which a Zarr is already located will reuse both the Zarr and the asset without minting anything new.  You can see the code for that [here](https://github.com/dandi/dandi-cli/blob/15ea79f3ed7aeb40159ae5f4430470f6ab061efd/dandi/files/zarr.py#L329-L347).
