### ISSUE TITLE
Validate .nwb files with our nwb validation routines even within BIDS dandisets

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1172]
Came up in https://github.com/dandi/dandi-cli/pull/1164/files#r1046140228

**Comment by TheChymera** [comment]
For referece: 
![darkhost_2022-12-12T14:06:35](https://user-images.githubusercontent.com/950524/207132536-b5e36f05-6cb6-4360-8442-541d5a34619e.png)

**Comment by TheChymera** [comment]
contingent on → https://github.com/bids-standard/bids-examples/pull/342
