### ISSUE TITLE
Provide warning log message with instructions if upload fails

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1197]
People keep running into situations where more recent version of dandi (or dependency) might have helped. I don't think we have to generally mandate (ie error out) if client version is not the most recent - new version might not only be fixing but also could introduce bugs, and trying to address one issue people might introduce another. Also this would entirely prevent inclusion into stable distributions.
We do announce minimal compatible version in archive api and some times do boost it up.

We announce availability of new version on top of run, but it gets lost in the terminal output.

To improve feedback to the user, if any upload fails - exit with non-O. If existing with non-0, check version again - if newer one available - add warning level message suggesting to update since might potentially address the issue. It will be suggestive.

Also if validation fails during upload - log warning to check the log (may be hint which line to look for) for details.

**Comment by yarikoptic** [comment]
> > To improve feedback to the user, if any upload fails - exit with non-O.
> 
> Should failing validation count as an upload failing? 

if it is not `--validation ignore`, ie. not resulted in failed upload - then not. If it resulted in failed upload - then yes, should count as upload failing.

> What about the various calls to `skip_file()` for things like a file not being found or failure to compute a digest?

they result in ERROR status for them, right? then exit with non-0 too.  Pretty much - `exit 0` only if uploads went fine per user instructions (ignore validation or not).

**Comment by jwodder** [comment]
@yarikoptic

> they result in ERROR status for them, right?

No, `skip_file()` results in `"status": "skipped"`.

**Comment by yarikoptic** [comment]
oh, indeed: we used `skip_file` without discriminating between skipping for "legit" (no update to upload,

- we do not skip but raise error if file `existing == "error"`:
```
    if existing == "error":
        # as promised -- not gentle at all!
        raise FileExistsError(exists_msg)
```

- for not found etc, we indeed to not raise an error but add "ERROR" into message for status `"skipped"`
```
                    try:
                        yield {"size": dfile.size}
                    except FileNotFoundError:
                        yield skip_file("ERROR: File not found")
                        return
                    except Exception as exc:
                        # without limiting [:50] it might cause some pyout indigestion
                        yield skip_file("ERROR: %s" % str(exc)[:50])
                        return
```
- we do `yield skip_file("failed validation")`  for `"required"` validation
- for benign `dandiset.yaml` skip we do `yield skip_file("should be edited online")` 
- for failing to digest : `yield skip_file("failed to compute digest: %s" % str(exc))` 

if we were to separate our `skip_file` and `error_file` scenarios, I think

<details>
<summary>this would be the diff (made status `ERROR` capitalized as found being done </summary> 

```patch
diff --git a/dandi/upload.py b/dandi/upload.py
index 29be508b..399ae135 100644
--- a/dandi/upload.py
+++ b/dandi/upload.py
@@ -129,11 +129,11 @@ def upload(
                     try:
                         yield {"size": dfile.size}
                     except FileNotFoundError:
-                        yield skip_file("ERROR: File not found")
+                        yield error_file("File not found")
                         return
                     except Exception as exc:
                         # without limiting [:50] it might cause some pyout indigestion
-                        yield skip_file("ERROR: %s" % str(exc)[:50])
+                        yield error_file(str(exc)[:50])
                         return
 
                 #
@@ -157,7 +157,7 @@ def upload(
                             )
                             for i, e in enumerate(validation_errors, start=1):
                                 lgr.warning(" Error %d: %s", i, e)
-                            yield skip_file("failed validation")
+                            yield error_file("failed validation")
                             return
                     else:
                         yield {"status": "validated"}
@@ -196,7 +196,7 @@ def upload(
                     try:
                         file_etag = dfile.get_digest()
                     except Exception as exc:
-                        yield skip_file("failed to compute digest: %s" % str(exc))
+                        yield error_file("failed to compute digest: %s" % str(exc))
                         return
 
                 try:
@@ -228,7 +228,7 @@ def upload(
                         digest=file_etag, ignore_errors=allow_any_path
                     ).json_dict()
                 except Exception as e:
-                    yield skip_file("failed to extract metadata: %s" % str(e))
+                    yield error_file("failed to extract metadata: %s" % str(e))
                     return
 
                 #
@@ -314,7 +314,7 @@ def upload(
                     else:
                         rec[tuple(rec_fields[1:])] = process_path(dfile)
                 except ValueError as exc:
-                    rec.update(skip_file(exc))
+                    rec.update(error_file(exc))
                 out(rec)
 
         if sync:
@@ -390,3 +390,7 @@ def check_replace_asset(
 
 def skip_file(msg: Any) -> Dict[str, str]:
     return {"status": "skipped", "message": str(msg)}
+
+
+def error_file(msg: Any) -> Dict[str, str]:
+    return {"status": "ERROR", "message": str(msg)}
```
</details>

and then we could exit non-0 if any reported `ERROR` status, but may be then there instead of `return`ing we should just raise some exception -- it then should be caught at https://github.com/dandi/dandi-cli/blob/master/dandi/upload.py#L255, list within `uploaded_paths` and yield ERROR status record.

**Comment by yarikoptic** [comment]
sorry I was cryptic -- I was thinking of what you suggested:

> making error_file() raise a custom exception containing the given message instead of returning a status dict so that the "ERROR" status is only emitted under line 255?
