### ISSUE TITLE
allow retrieving validation errors

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#1206]
thank you @jwodder for https://github.com/dandi/dandi-cli/issues/1205#issuecomment-1420816824.

opening a new issue here to allow retrieving validation errors in the call. since the endpoint returns it, i'm assuming it's discarded. let's add a parameter to not discard it.

**Comment by jwodder** [comment]
It's not explicitly discarded; the returned `Version` pydantic structure simply doesn't have fields for it.  The appropriate solution would be to add the fields to `Version` instead of adding a parameter; however, this would lead to inconsistencies, as other endpoints that return version information (i.e., `/dandisets/:id/` and `/dandisets/:id/versions/`) do not include validation error fields.

**Comment by satra** [comment]
> It's not explicitly discarded

but the bytes are downloaded, right? as in the `info` endpoint is called as opposed to those other endpoints that return version information. if that is the case, then adding that makes sense or using a specific Info object which shares and extends the Version model. 

if on the other hand, the `info` endpoint is not called, then adding a function to Dandiset class to call and return the contents of that endpoint would be good (more generally this can be something that returns the raw json as pydantic model for any API endpoint).

**Comment by jwodder** [comment]
@satra 

> but the bytes are downloaded, right? as in the info endpoint is called

Yes.

**Comment by satra** [comment]
in that case, please create an extended `Info` model that is exposed for the `Dandiset`.

**Comment by jwodder** [comment]
@satra @AlmightyYakob Are the `asset_validation_errors` and `version_validation_errors` fields always of the type `List[ValidationError]` where `ValidationError` has `field: str` and `message: str` fields?  [The Swagger docs](https://api.dandiarchive.org/swagger/) seem to be both wrong and incomplete on this point.

**Comment by yarikoptic** [comment]
> ... If having that documented in swagger is important, please file an issue in the API for it.

https://github.com/dandi/dandi-archive/issues/1487
