### ISSUE TITLE
enable downloading in parallel from asset URL list

### ISSUE THREAD

**Issue by colleenjg** [dandi/dandi-cli#1217]
`download()` in `dandi/download.py` takes the argument `jobs`. I thought it would allow downloading from multiple asset URLs at the same time, but it seems that either it's not implemented yet or `jobs` is for something else. Any way parallel downloading by URLs can be enabled?

Would allow users to efficiently download a specific subset of a dataset.

**Comment by yarikoptic** [comment]
Upon a quick attempt to use `download` from command line -- seems to be doing the right thing:

```
yoh@typhon:~/tmp$ dandi --version
0.49.1+15.g47a07b0
yoh@typhon:~/tmp$ dandi download -J4 DANDI:000003
PATH                                                   SIZE     DONE          DONE% CHECKSUM STATUS        MESSAGE
dandiset.yaml                                                                                done          updated
.....Mouse20_ses-YutaMouse20-140327_behavior+ecephys.nwb 8.4 GB   192.9 MB         2%          downloading             .Mouse20_ses-YutaMouse20-140321_behavior+ecephys.nwb 11.7 GB  327.2 MB         2%          downloading
...Mouse20_ses-YutaMouse20-140325_behavior+ecephys.nwb 17.3 GB  100.7 MB         0%          downloading
...Mouse20_ses-YutaMouse20-140324_behavior+ecephys.nwb 15.1 GB  58.7 MB          0%          downloading
...Mouse20_ses-YutaMouse20-140324_behavior+ecephys.nwb 15.1 GB  67.1 MB          0%          downloading
```
so you can see multiple (not sure why 5 not 4) files being downloaded.  Looking at the code I think I might see what might be an issue -- what value for `format` do you specify? ATM `download` parallelization is implemented through `pyout` threading of rendering per each item, so if you chose some other value, it would not parallelize.  Confirming

```
 python -c 'from dandi.download import download; download("DANDI:000003", jobs=4, output_dir="000003")'
```
did similar parallelization as from CLI, but 
```
python -c 'from dandi.download import download; download("DANDI:000003", jobs=4, output_dir="000003", format="debug")'
```
did it serially.  I will just clarify that via a warning to the user for now in https://github.com/dandi/dandi-cli/pull/1222 .

**Comment by colleenjg** [comment]
Sorry, I wasn't very clear! As you confirmed, it's possible to download in parallel if I just specify the full dandiset, but I cannot pass a list of URLs and download them in parallel. In fact, I took another look at the code and remembered that you can't in fact pass multiple URLs to `download()` (it raises an error). I should have phrased this clearly as a feature request (unless there is another way that I don't know about to download in parallel from a dandiset, using a list of URLs).

**Comment by yarikoptic** [comment]
@jwodder what do you think we should do here? i.e. possibly at what level of APIs provide a convenience to download multiple URLs in parallel and how?  e.g. we could fix it up on this top level by first explicitly verifying that all URLs come from the same dandiset or just not carrying about it at all (IIRC we just use for figuring out top directory to download to)

**Comment by jwodder** [comment]
@yarikoptic It shouldn't be too hard to just make `download()` with multiple URLs act like multiple calls to `download()` that just happen to be parallel (e.g., each URL would get its own output directory determined the same way as for a single URL argument).

**Comment by yarikoptic** [comment]
ok, let's do that then!

**Comment by colleenjg** [comment]
It works! Thank you so much.
