### ISSUE TITLE
do not log  pyout in the log file unless there was an explicit 

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1219]
`pyout` logs are overwhelming in the interactive commands log files which log unconditionally on DEBUG level.  
I think we should
- not log `pyout` at all (filter out) **unless** DEBUG level logging was explicitly requested via DEBUG `log_level` in that dandi/cli/command.py:main
- (unrelated to original issue but while at it): log to file at `min(log_level,10)` i.e. if we specify `--log-level 2` we would go deeper in the log file too

**Comment by jwodder** [comment]
@yarikoptic 

> log to file at `min(log_level,10)`

The code should already do that:

https://github.com/dandi/dandi-cli/blob/edbfe794ef0ccd770e21477912c937e7bdfa59e4/dandi/cli/command.py#L106

Are you seeing different behavior?
