### ISSUE TITLE
Organize tests are failing under pynwb 2.3.0 because test files lack subject_id

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-cli#1223]
pynwb 2.3.0 was released on the 23rd at 13:33 EST, and the `test_organize.py::test_organize_nwb_test_data` tests have been failing since because the test files used (from [this repository](https://github.com/dandisets/nwb_test_data)) are no longer recognized as having a `subject_id`.  This seems to have been a last-minute regression, as [the `dev-deps` scheduled test on the 22](https://github.com/dandi/dandi-cli/actions/runs/4239900402/jobs/7368382448) did not have this problem.

**Comment by yarikoptic** [comment]
attn @rly on a possible regression in pynwb 2.3.0.
So it seems to be some behavior change in PyNWB.  Do you @jwodder know already that it is something to report to pynwb or it might be some our idiosyncrasy to be fixed  in our code?

**Comment by yarikoptic** [comment]
seems to be in pynwb, filing an issue
