### ISSUE TITLE
validate: if path does not contain (and is not part of) any Dandiset

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1229]
```
❯ dandi --version
0.49.1+33.ga5a98fa2


❯ ls -l /tmp/test
total 4
lrwxrwxrwx 1 yoh yoh 108 Feb 20 16:16 blah -> .git/annex/objects/pF/Zf/MD5E-s4--ba1f2511fc30423bdbb183fe33f3dd0f/MD5E-s4--ba1f2511fc30423bdbb183fe33f3dd0f

❯ dandi validate /tmp/test
No errors found.
2023-02-27 18:14:47,705 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20230227231446Z-2749729.log

```

and I expect validation error.

**Comment by jwodder** [comment]
@yarikoptic Is the title supposed to be "if path does not contain (and is not part of) any Dandiset"?

**Comment by jwodder** [comment]
@yarikoptic For the validation error `ValidationResult` instance, what should the `id`, `scope`, `message`, `path`, and `dandiset_path` fields be?

**Comment by yarikoptic** [comment]
correct, retitled to your formulation.

We have already https://github.com/dandi/dandi-cli/blob/HEAD/dandi/files/bases.py#L562
```
                    ValidationResult(
                        id="DANDI.NO_DANDISET_FOUND",
                        origin=ValidationOrigin(
                            name="dandi", version=dandi.__version__
                        ),
                        severity=Severity.ERROR,
                        scope=Scope.FILE,
                        path=self.filepath,
                        message="File is not inside a Dandiset",
                    )
```
which I think matches it well, besides it is not per se File but could be a path to a folder. So message could say "Path is not inside a Dandiset" but the rest can IMHO stay the same

**Comment by jwodder** [comment]
@yarikoptic What exactly should trigger this error?  A lack of a `dandiset.yaml` file, or something else?

**Comment by yarikoptic** [comment]
right -- when path is not part of any dandiset.

**Comment by jwodder** [comment]
@yarikoptic Should the error be associated with individual files under the given path or with the directory path itself?  For example, if asked to validate an empty directory, should that be an error?
