### ISSUE TITLE
service-scripts reextract-metadata

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1230]
https://github.com/dandi/dandi-cli/pull/1202/ stripped `service-scripts` devel top level command , I think might be worth returning it now for this.

Given https://github.com/dandi/dandi-cli/pull/1214 functionality, we would need following command

```
reextract-metadata [--when newer-schema-version,always] [--diff show-united] URL
```

URL 
- if points to dandiset - take draft version and all assets of it
- if points to specific dandiset version which isn't draft - error out
- if points to some sub-paths within dandiset - take only assets under that path (recursively, so we could re-extract within some folder for faster testing etc)
- if points to specific file (asset) - works only on that asset

given a "list" of those assets it would
- get current `metadata` record
- if `when=="always": do_reextract = True
- if `when == "newer-schema-version"`:
  -  `if semver(metadata["schemaVersion"]) < DANDI_SCHEMA_VERSION`: `do_reextract = True`
  - `if semver(metadata["schemaVersion"]) > DANDI_SCHEMA_VERSION`: log warning that asset has higher version and which one
- `if do_reextract:` re-extract metadata using functionality of #1214 from remote location in the archive reusing current `digest` value and `path` and replace the asset with new asset with re-extracted metadata

if optional `--diff show-united`, before uploading a new asset show the diff between old and new one extracting useful https://docs.python.org/3/library/difflib.html for showing united diff between two formatted json records - old and new.

I still wonder if we need some extra check to prevent unnecessary changes (like if nothing changed really with re-extraction) , but so far let's try as this.

Ref: https://github.com/dandi/dandi-archive/issues/1450

**Comment by jwodder** [comment]
@yarikoptic

* What should the default value for `--when` be?
* Is there any reason for `--diff` to take an argument?

> if optional `--diff show-united`, before uploading a new asset show the diff between old and new one

To be clear, you just want the diff printed to stdout and then the upload to happen immediately, no paging of output or waiting for confirmation from the user, correct?

**Comment by jwodder** [comment]
@yarikoptic Also, I assume that this should (currently) only operate on NWB assets and skip any others?

**Comment by yarikoptic** [comment]
> @yarikoptic
> 
> * What should the default value for `--when` be?

`newer-schema-version`

> * Is there any reason for `--diff` to take an argument?
> 
> > if optional `--diff show-united`, before uploading a new asset show the diff between old and new one
> 
> To be clear, you just want the diff printed to stdout and then the upload to happen immediately, no paging of output or waiting for confirmation from the user, correct?

ATM I just want it to be shown/printed, so we would use `---diff show-united`.  If later we decide to use some other diff or page it , we could add another value without breaking API, only extending it.  At least that was my thinking.


> @yarikoptic Also, I assume that this should (currently) only operate on NWB assets and skip any others?

I think it should work for anything non-zarr but for now yeah, let's just limit to NWB.
