### ISSUE TITLE
validate: add --ignore REGEX to ignore some errors

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1232]
REGEX for ids, in light of https://github.com/dandi/dandi-cli/issues/1211 , so people on not yet organized files could use `dandi validate --ignore DANDI.NO_DANDISET_FOUND PATHs`

**Comment by TheChymera** [comment]
Do we really want this `ignore` parameter though? Is anybody really going to use it? why not just return all errors and people can pipe the output for whatever filtering they want?

**Comment by yarikoptic** [comment]
@TheChymera see https://github.com/dandi/dandi-cli/issues/1211 and https://github.com/dandi/handbook/pull/79 . I expect it to be used by some users during preparation of data
