### ISSUE TITLE
dandi version error in staging

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-cli#1249]
```pytb
def test_automatic_dandi_upload(self):
>       automatic_dandi_upload(dandiset_id="200560", nwb_folder_path=self.nwb_folder_path, staging=True)

tests/test_minimal/test_tools/test_dandi_transfer_tools.py:45: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/neuroconv/tools/data_transfers.py:[36](https://github.com/catalystneuro/neuroconv/actions/runs/4378541440/jobs/7663420144#step:9:37)4: in automatic_dandi_upload
    dandi_upload(paths=[str(x) for x in organized_nwbfiles], dandi_instance=dandi_instance)
/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/dandi/upload.py:70: in upload
    client.check_schema_version()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <dandi.dandiapi.DandiAPIClient object at 0x7f3f9cb34910>
schema_version = '0.6.3'

    def check_schema_version(self, schema_version: Optional[str] = None) -> None:
        """
        Confirms that the server is using the same version of the Dandi schema
        as the client.  If it is not, a `SchemaVersionError` is raised.
    
        :param schema_version: the schema version to confirm that the server
            uses; if not set, the schema version for the installed
            ``dandischema`` library is used
        """
        if schema_version is None:
            schema_version = models.get_schema_version()
        server_info = self.get("/info/")
        server_schema_version = server_info.get("schema_version")
        if not server_schema_version:
            raise RuntimeError(
                "Server did not provide schema_version in /info/;"
                f" returned {server_info!r}"
            )
        if server_schema_version != schema_version:
>           raise SchemaVersionError(
                f"Server requires schema version {server_schema_version};"
                f" client only supports {schema_version}.  You may need to"
                " upgrade dandi and/or dandischema."
            )
E           dandi.exceptions.SchemaVersionError: Server requires schema version 0.6.4; client only supports 0.6.3.  You may need to upgrade dandi and/or dandischema.
```

**Comment by yarikoptic** [comment]
yeap - staging already moved to new version while we are testing/getting ready in #1241 here as well .
unfortunately we just don't have a good smooth way to upgrade versions of schema  across all components yet :-/

**Comment by yarikoptic** [comment]
but it also made me wonder -- @satra - didn't we add at some point possibility of upgrading metadata from older versions to the newest exactly for such need that client could in principle be a little outdated and still be able to upload? restricting to exactly the same version makes it all too rigid IMHO.

**Comment by satra** [comment]
i don't think we ever agreed on autoupgrade on the server side, which is where that would need to happen. also there is currently no notion of failure of that kind on the server side.  in this case minimum could be set to `0.6.3` on the server, but it won't auto upgrade i think.

in general i would be in favor of autoupgrade, but the exception handling has to be robust. i.e. if it cannot we need to notify user and us.

**Comment by yarikoptic** [comment]
in response to @CodyCBakerPhD https://github.com/dandi/dandi-cli/pull/1241#issuecomment-1462785834 ( I think it would fit better here)

> > https://github.com/dandi/dandi-cli/issues/1249 I believe is against staging -- see dandiset id there.
> It's true, the CI tests upload to staging. Just wanted you to be aware as soon as it happened so same doesn't happen to 
the main server

to be clear -- it is not our dandi-cli CI but rather your tool (neuroconv) CI dos that.

To not appear hyppocritical -- I disclose that we also do such a drill in https://github.com/dandi/dandisets/ testing for specifics which I forgot about (I bet @jwodder remembers). But alternatively, as we do in dandi-cli, you can simply use our fixtures defined in https://github.com/dandi/dandi-cli/blob/HEAD/dandi/tests/fixtures.py#L342 to have your local docker-compose'd instance of dandi-archive for your tests, thus not relying on external staging instance at all (not that it would behave any differently ;-) )

**Comment by CodyCBakerPhD** [comment]
> thus not relying on external staging instance at all (not that it would behave any differently ;-) )

Our goal is to guarantee that the explicit workflow we, or any user, would call to the actual archive (or staging) works - am I wrong that there is some minimal difference between a local docker-compose'd instance of the 'dandi-archive' and the real thing?

Also then, in the event of this error, how would someone upload data to staging? Would they have to pin to some dev branch on the CLI to make the versions match?
