### ISSUE TITLE
Lock dandisets during modification

### ISSUE THREAD

**Issue by dchiquit** [dandi/dandi-cli#125]
`dandiarchive` now supports locking dandisets in girder so that other users cannot modify or publish them. The publish workflow is still unreleased (as of 6/24), but the functionality should be implemented in the CLI before release as a safeguard.

There are 3 new endpoints related to locking:
- [/dandi/{identifier}/lock](https://girder.dandiarchive.org/api/v1#!/dandi/dandi_wrapper_0_1) locks a dandiset with the currently authenticated user. If the dandiset is already locked, even by the currently authenticated user, the call will fail. If locking fails, the operation should abort.
- [/dandi/{identifier}/lock/owner](https://girder.dandiarchive.org/api/v1#!/dandi/dandi_wrapper_0_1_2) returns some info on the current owner of the lock on the dandiset. If the dandiset is unlocked, the response body will be `null`. If the dandiset is currently being published, the response will look like this:
```
{
  "email": "publish@dandiarchive.org",
  "firstName": "publish",
  "lastName": "service"
}
```
- [/dandi/{identifier}/unlock](https://girder.dandiarchive.org/api/v1#!/dandi/dandi_wrapper_0_1_2_3_4_5_6) unlocks the dandiset. If the dandiset is not locked by the currently authenticated user, the call will fail.

Before doing any modification to a dandiset in girder (i.e. upload), the CLI should call the lock endpoint. Afterwards, it should call the unlock endpoint.
I recommend a pattern like what was used in [`dandi-publish`](https://github.com/dandi/dandi-publish/blob/master/publish/girder.py#L78):
```
@contextlib.contextmanager
def dandiset_lock(client, dandiset_identifier: str):
    resp = client.post(f'dandi/{dandiset_identifier}/lock')
    if resp.status_code != 200:
        raise GirderError(f'Failed to lock dandiset {dandiset_identifier}')
    try:
        yield
    finally:
        resp = client.post(f'dandi/{dandiset_identifier}/unlock')
        if resp.status_code != 200:
            raise GirderError(f'Failed to unlock dandiset {dandiset_identifier}')
```
This will create a method that can be used in a python `with` statement (like [this](https://github.com/dandi/dandi-publish/blob/master/publish/tasks.py#L17)):
```
with dandiset_lock(client, dandiset.identifier):
    ... do things ...
```

**Comment by yarikoptic** [comment]
Cool! Thank you! Feel welcome to suggest a PR, or I will get to it in a day or two.

**Comment by mgrauer** [comment]
@yarikoptic, do you need any further help here?

**Comment by yarikoptic** [comment]
YES @mgrauer ! A PR would still be awesome, and also would be great to have some other eyes to see this code base ;) If appears to be too crude (code) and thus difficult to plug, let me know.

**Comment by yarikoptic** [comment]
If someone is going to do it - assign. If not - I hope to get some quality dandi cli time tomorrow, and will then assign myself
