### ISSUE TITLE
allow downloading by subject or matching string

### ISSUE THREAD

**Issue by colleenjg** [dandi/dandi-cli#1255]
As a DANDI dataset user, it is useful for me to work with some datasets locally, without an internet connection. For this, I often need to download only a subset of a full dataset.

I would like to suggest the following feature: to enable users to identify a subset of files they want to download from a dataset using either the subject name or a matching string. This can already be done manually by the user by retrieving a list of assets for a dataset, getting their paths and identifying the assets with the matching string, e.g. "sub-123". 

Would it be useful to integrate such a functionality into the repo, either directly in `download()` from `download.py` or into a separate function that retrieves urls for download?

**Comment by yarikoptic** [comment]
You already can download an arbitrary file(s) or folders at the high-level API which you see in command line or have in Python API, e.g. you can just cut paste a URL from dandiarchive.org web site while browsing a dandiset:

```
❯ dandi download https://dandiarchive.org/dandiset/000029/0.230317.1553/files?location=sub-anm369962/
PATH                                             SIZE    DONE    DONE% CHECKSUM STATUS          MESSAGE
sub-anm369962/sub-anm369962_behavior+ecephys.nwb 6.6 MB  6.6 MB   100%    ok    done                   
Summary:                                         6.6 MB  6.6 MB                 1 done                 
                                                         100.00%                                       
2023-03-21 09:00:47,239 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20230321130019Z-465662.log
```

you can as well point to specific file(s) even.

```
❯ dandi download --help
Usage: dandi download [OPTIONS] [URL]...

  Download files or entire folders from DANDI.

  Accepted resource identifier patterns:
   - DANDI:<dandiset id>[/<version>]
   - https://dandiarchive.org/...
   - https://identifiers.org/DANDI:<dandiset id>[/<version id>] (<version id> cannot be 'draft')
   - https://<server>[/api]/[#/]dandiset/<dandiset id>[/<version>][/files[?location=<path>]]
   - https://*dandiarchive-org.netflify.app/...
   - https://<server>[/api]/dandisets/<dandiset id>[/versions[/<version>]]
   - https://<server>[/api]/assets/<asset id>[/download]
   - https://<server>[/api]/dandisets/<dandiset id>/versions/<version>/assets/<asset id>[/download]
   - https://<server>[/api]/dandisets/<dandiset id>/versions/<version>/assets/?path=<path>
   - dandi://<instance name>/<dandiset id>[@<version>][/<path>]
   - https://<server>/...
      
```
gives full list of supported URL schemes -- just use the one with `<path>` in it.

Also all dandisets are available as DataLad datasets from github: https://github.com/dandisets/  so if you install datalad you can get yet another way to access all those files given desired pattern.

Also see "mid-level" API https://dandi.readthedocs.io/en/latest/modref/index.html#mid-level-user-interfaces which gives you lots of flexibility of interacting with archive, and with low-level https://dandi.readthedocs.io/en/latest/modref/index.html#low-level-user-interfaces you can get even more "native" with our API server.

I hope that such variety satisfy any curious need, or do you see some use case which cannot be fulfilled yet?

**Comment by satra** [comment]
don't forget `glob`. available in python and on the API. i'm not 100% download supports it, but @yarikoptic can clarify. definitely doable in the python side.

@colleenjg - for your specific use case, i think datalad is a good option. (you can get access to any dandiset via datalad, not just yours - see http://datasets.datalad.org/?dir=/dandi/dandisets).

**Comment by yarikoptic** [comment]
> @colleenjg - for your specific use case, i think datalad is a good option. (you can get access to any dandiset via datalad, not just yours - see http://datasets.datalad.org/?dir=/dandi/dandisets).

clarification: http://datasets.datalad.org/?dir=/dandi/dandisets is a "clone" of the https://github.com/dandi/dandisets/ which contains individual dandisets from https://github.com/dandisets/ . So the http://datasets.datalad.org/?dir=/dandi/dandisets might be lagging behind at times, thus I would recommend to work/navigate them directly on github.

**Comment by colleenjg** [comment]
Thanks @yarikoptic and @satra. I didn't know that for downloading individual subjects - great! I'm not getting successful `glob` expansion, though, using the \<path\> URL scheme - I don't know if I'm doing something wrong, or whether it's a functionality you'd even be interested in including. 

So, for example, 
- [x] `dandi download https://api.dandiarchive.org/api/dandisets/000037/versions/draft/assets/?path=sub-408021/` works, for the case where I want all files for subject 408021.
- [ ] `dandi download https://api.dandiarchive.org/api/dandisets/000037/versions/draft/assets/?path=sub-408021/*image*` doesn't work, for the case where I just want the files for subject 408021 that include the stimulus template images.

As mentioned, I do have my own solution to this, which just identifies the URLs I want to download via the asset paths:
```
from dandi import dandiapi
dandiset = dandiapi.DandiAPIClient().get_dandiset("000037", "draft")
asset_urls = [asset.download_url for asset in dandiset.get_assets() if "sub-408021" in asset.path and "image" in asset.path]
```
I just thought I'd check whether this kind of functionality, integrated into the download function, might be of broader interest. The answer may be that no, this is niche enough that users should just write their own code, as I've done.

**Comment by colleenjg** [comment]
I see! Ok, I'll definitely take a look at `get_assets_by_glob()`!

**Comment by jwodder** [comment]
@yarikoptic How would the paths at which to download assets specified by a glob URL be determined?  Cf. [this description of how determining download paths currently works for "exact" URLs](https://github.com/dandi/dandi-cli/issues/598#issuecomment-829426987).

**Comment by yarikoptic** [comment]
Since glob is concerned with the paths within a particular dandisets, for a glob behavior could either be
a. download paths are from the top of the dandiset, e.g. in above example would all fall under `sub-408021`
b. strip the `os.path.commonprefix()` of all those paths.

Overall I think `a.` makes it closer to the most common use cases (download some portion of the dandiset I am at), so I would choose that. WDYT?

**Comment by jwodder** [comment]
@yarikoptic How is (a) "closer to the most common use cases"?  When downloading a folder of assets, all path components before the folder name are stripped; that's closer to — though still not the same as — (b).

**Comment by yarikoptic** [comment]
> @yarikoptic How is (a) "closer to the most common use cases"? 

my thinking was that most common would be to either download same type (data modality) of files across different subjects, or a folder for a specific subject.  In both cases having subject folder(s) (which is the folder at the top level of dandiset) would be desired.  Even  when I want to collate files/subjects from different dandisets, I would probably like to keep them in original hierarchy, thus a subject folder from each dataset (although in this case conflicts could come for the subjects with the same id - but let's keep that of no concern at this point).

And as you mention in

> When downloading a folder of assets, all path components before the folder name are stripped; that's closer to — though still not the same as — (b).

"before" the folder name is stripped so the folder itself is kept as the common path part for all of them.

I don't like b. (Stripping common prefix ) because it would then depend on the state of dandiset, e.g. if I ask for `sub-*/*` and then if there is one subject - I would get files dumped without leading directory, if there is multiple -- into subfolders.

We might want it somehow explicit (e.g. like `git annex addurl` has `--pathdepth` which I somewhat dislike), but I don't think we should do that here since also not clear what/how that should be done.  Thus (a) sounded like most sensible thing to do.

**Comment by colleenjg** [comment]
Just tried it out! Works great! :) Thanks!!
