### ISSUE TITLE
SyntaxError when calling dandi

### ISSUE THREAD

**Issue by UCDNJJ** [dandi/dandi-cli#126]
Hi,

I am trying to use the dandi on the command line to download some data but I am receiving the following error:

> Traceback (most recent call last):
  File "/afs/genomecenter.ucdavis.edu/home/njjohans/pyv3/bin/dandi", line 5, in <module>
    from dandi.cli.command import main
  File "/afs/genomecenter.ucdavis.edu/home/njjohans/pyv3/lib/python3.5/site-packages/dandi/cli/command.py", line 78, in <module>
    from .cmd_organize import organize
  File "/afs/genomecenter.ucdavis.edu/home/njjohans/pyv3/lib/python3.5/site-packages/dandi/cli/cmd_organize.py", line 103
    raise ValueError(f"invalid has an invalid value {invalid}")
                                                             ^
SyntaxError: invalid syntax

Installed with pip for python 3.5.2 in a virtual environment.

Same error occurs when I try:  

`dandi ls --help`

**Comment by satra** [comment]
@UCDNJJ - i'm a little surprised it didn't complain when you tried to install. as it should only be available for  `Python >=3.6`

**Comment by UCDNJJ** [comment]
Ahh, let me update python to a tleast 3.6 and try again. It looks like your package is set the the requirement of: '>=3.5.1'

**Comment by UCDNJJ** [comment]
@satra Thanks, it's working after updating python!

**Comment by satra** [comment]
ah its possible there is a previous version that had that setting but according to this: https://github.com/dandi/dandi-cli/blob/master/setup.cfg#L28 it is set for 3.6+

@yarikoptic - if there is a previous version that supports <3.6, we should remove it.

**Comment by yarikoptic** [comment]
Remove from where? I think it might be just that setup.cfg version spec is ignored somehow... It may be we need more of explicit qualifiers to limit versions or check and error out in setup.py. @UCDNJJ how was it installed - Just regular pip install dandi?

**Comment by UCDNJJ** [comment]
@yarikoptic Correct, just regular `pip install dandi` on python 3.5.2.

**Comment by satra** [comment]
@yarikoptic - all versions prior to 0.4.0 indicates support for 3.5.x, so pip will try to install them in a 3.5.x environment. so my suggestion is to remove those from being installed. (btw, you are the sole maintainer, may be good to add me or someone else).
