### ISSUE TITLE
Saving a file after running nwbfile.generate_new_id() seems to lead to a DANDI validation error

### ISSUE THREAD

**Issue by colleenjg** [dandi/dandi-cli#1266]
I wanted to create a second version of the same NWB file, in which I add the full imaging stack as an acquisition object. To allow the versions to co-exist alongside one another, I ran `nwbfile.generate_new_id()` on the new file before saving it.

I had no problem loading the file, running my analyses on it, and the `nwbinspector` produced no validation errors. However, when it came time to run `dandi organize`, the new file was flagged as having a completely empty record:

> 2023-04-05 00:09:58,416 [ WARNING] Completely empty record for ../../VALID/sub-408021_ses-759189643_behavior+image+ophys+stack.nwb
> Error: 1 out of 2 files were found not containing all necessary metadata: ../../VALID/sub-408021_ses-759189643_behavior+image+ophys+stack.nwb

After a lot of testing, I concluded that the problem was specifically due to running `nwbfile.generate_new_id()` (which I believe changes the object IDs for all objects in the NWB file?). If I instead just update the `object_id` of NWB file itself manually using `h5py`, I don't encounter this problem.

**Comment by yarikoptic** [comment]
@bendichter @rly does it smell like some bug in pynwb/hdmf somewhere in that `object_id` gets somehow "killed"?

**Comment by rly** [comment]
That does not seem possible given [the code](https://github.com/hdmf-dev/hdmf/blob/79f5886e8f1fc505caa313f62597ed638db5a5f8/src/hdmf/container.py#L250-L257), but it's hard to say. @colleenjg could you share those two files with us? I'll send you a link over the dandi slack.

**Comment by colleenjg** [comment]
I just tested it out just downloading one of my files from dandi and updating the object IDs, and I was able to reproduce the problem. Here are the steps I followed (running on `Ubuntu` with the latest package versions (`dandi==0.52.0` and `pynwb==2.3.1`): 

1. `bash`: Get a file from **dandiset [000037](https://gui.dandiarchive.org/#/dandiset/000037)**.
```
mkdir test_files
mkdir organize_files
cd test_files
dandi download https://api.dandiarchive.org/api/assets/64fba8b4-7d7a-44e4-865e-595fec01e41e/download/
```

2. `python`: Make a new version of the file in which the **object IDs are updated** using `nwbfile.generate_new_id()`
```
filepath = "sub-408021_ses-758519303_behavior+ophys.nwb"
new_filepath = filepath.replace(".nwb", "_new_IDs.nwb")

import pynwb
with pynwb.NWBHDF5IO(filepath, "r") as read_io:
    nwbfile = read_io.read()
    nwbfile.generate_new_id()
    with pynwb.NWBHDF5IO(new_filepath, "w") as write_io:
       write_io.export(src_io=read_io, nwbfile=nwbfile)
```

3. `bash`: Run the **NWB inspector**.
```
nwbinspector . --config dandi
```

> ```
> Found 11 issues over 3 files: 
>        1 - CRITICAL
>       10 - BEST_PRACTICE_SUGGESTION
> ...
> ```

As an aside: I'm not sure why it calculates that there are 3 files - there are just 2.

The **critical error** is a `check_unique_identifiers` error, caused by the fact that I copied the file without changing its `identifier` (only changing its `object_id`). The next step is optional and just to **avoid the validation error** (it doesn't cause or prevent the `dandi organize` error.)

4. [optional] `python`: Optionally **change the identifier** for the new file. FYI, I don't know how to do this via `pynwb`, so I just use `h5py` :/. It's probably not ideal, but as said above, the `dandi organize` error occurs independently of this step.

```
import h5py
with h5py.File(new_filepath, "a") as f:
    identifier = f["identifier"][()].decode()
    f["identifier"][()] = f"{identifier}_test_IDs"
```

5. [optional] `bash`: Rerun the **NWB inspector**.
```
nwbinspector . --config dandi
```
> ```
> Found 10 issues over 2 files: 
>       10 - BEST_PRACTICE_SUGGESTION
> ...
> ```

The **critical error** is gone now.

6. `bash`: Run **`dandi organize`**.
```
cd ../organize_files  
dandi download DANDI:000037/draft --download dandiset.yaml
cd 000037
dandi organize ../../test_files -f dry
```

This is where the **`Completely empty record`** error occurs.

>```
> 2023-04-06 07:00:58,212 [    INFO] Loading metadata from 2 files
> [Parallel(n_jobs=-1)]: Using backend LokyBackend with 40 concurrent workers.
> /home/user/.conda/envs/nwbup/lib/python3.9/site-packages/hdmf/spec/namespace.py:531: UserWarning: Ignoring cached namespace 'core' version 2.5.0 because version 2.6.0-alpha is already loaded.
>   warn("Ignoring cached namespace '%s' version %s because version %s is already loaded."
> [Parallel(n_jobs=-1)]: Done   2 out of   2 | elapsed:    3.2s remaining:    0.0s
> [Parallel(n_jobs=-1)]: Done   2 out of   2 | elapsed:    3.2s finished
> 2023-04-06 07:01:01,429 [ WARNING] Completely empty record for ../../test_files/sub-408021_ses-758519303_behavior+ophys_new_IDs.nwb
> 2023-04-06 07:01:01,430 [    INFO] Logs saved in /home/user/.cache/dandi-cli/log/20230406110056Z-253278.log
> Error: 1 out of 2 files were found not containing all necessary metadata: ../../test_files/sub-408021_ses-758519303_behavior+ophys_new_IDs.nwb
>```


**NOTES**:
- I found that this error does **not** occur if I use `nwbfile.generate_new_id(recurse=False)` (in my case, this is a sufficient solution). So I assume it's caused by changes in the IDs of the objects in the NWB file.
- I tested the same code out on 2 other files. The test on a file from dandiset [000448](https://dandiarchive.org/dandiset/000448/draft/files?location=sub-002-F) doesn't result in this error. The test on a file from dandiset [000167](https://dandiarchive.org/dandiset/000167/0.220928.1306/files?location=sub-7) does reproduce the error. So I would imagine it's due to objects/modules in common between my file and this one. 

There ends my investigation...!

**Comment by rly** [comment]
Thank you @colleenjg for the detailed minimum working example. I can reproduce the error and will investigate.

**Comment by colleenjg** [comment]
I just tried it out, and even rerunning everything from scratch after reinstalling `hdmf` doesn't work on my end, unfortunately. I still get the metadata error.

Here is my `pip freeze` output:
```
appdirs==1.4.4
arrow==1.2.3
asciitree==0.3.3
asttokens==2.2.1
attrs==22.2.0
backcall==0.2.0
bidsschematools==0.6.0
blessings==1.7
boto3==1.24.96
botocore==1.27.96
certifi @ file:///croot/certifi_1665076670883/work/certifi
cffi==1.15.1
charset-normalizer==3.0.1
ci-info==0.3.0
click==8.1.3
click-didyoumean==0.3.0
cryptography==39.0.1
dandi==0.52.0
dandischema==0.8.2
decorator==5.1.1
dnspython==2.3.0
email-validator==1.3.1
entrypoints==0.4
etelemetry==0.3.0
executing==1.2.0
fasteners==0.18
fqdn==1.5.1
fscacher==0.3.0
h5py==3.8.0
hdmf @ git+https://github.com/hdmf-dev/hdmf.git@8af3ee7e0047e70b50ef389aafa6e468f313a25b
humanize==4.6.0
idna==3.4
importlib-metadata==6.0.0
interleave==0.2.1
ipython==8.10.0
isodate==0.6.1
isoduration==20.11.0
jaraco.classes==3.2.3
jedi==0.18.2
jeepney==0.8.0
jmespath==1.0.1
joblib==1.2.0
jsonpointer==2.3
jsonschema==4.17.3
keyring==23.13.1
keyrings.alt==4.2.0
matplotlib-inline==0.1.6
more-itertools==9.0.0
natsort==8.2.0
numcodecs==0.11.0
numpy==1.23.5
nwbinspector==0.4.26
packaging==23.0
pandas==1.5.3
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==3.0.36
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.21
pycryptodomex==3.17
pydantic==1.10.5
Pygments==2.14.0
pynwb==2.3.1
pyout==0.7.2
pyrsistent==0.19.3
python-dateutil==2.8.2
pytz==2022.7.1
PyYAML==6.0
requests==2.28.2
rfc3339-validator==0.1.4
rfc3987==1.3.8
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.7
s3transfer==0.6.0
scipy==1.10.0
SecretStorage==3.3.3
semantic-version==2.10.0
six==1.16.0
stack-data==0.6.2
tenacity==8.2.1
tqdm==4.64.1
traitlets==5.9.0
typing_extensions==4.5.0
uri-template==1.2.0
urllib3==1.26.14
wcwidth==0.2.6
webcolors==1.12
zarr==2.14.1
zarr-checksum==0.2.8
zipp==3.14.0
```

As an aside, I'm not surprised that you got `1 out of 2 paths are not unique. We will try adding _obj- based on crc32 of object_id`, since the `session_id` is used in generating the file name, but not the unique identifier is not part of the naming convention, at present.

**Comment by rly** [comment]
Thanks @colleenjg . I figured out the discrepancy -- my filepath had a "/" in it and apparently that makes a difference. I'll work on a fix.

**Comment by rly** [comment]
@colleenjg I pushed a fix. Could you please try again? Thanks for your patience on this!

**Comment by colleenjg** [comment]
It worked! :)

**Comment by rly** [comment]
Awesome. We'll release a fix later today.
