### ISSUE TITLE
Call asset download endpoint from publish app

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandi-cli#127]
For published dandisets, to download the files, call the asset download endpoint.

See dandisets_versions_assets_download in https://publish.dandiarchive.org/swagger/, and ask for any help in using that endpoint.

**Comment by mgrauer** [comment]
Will be fixed by https://github.com/dandi/dandi-cli/pull/134

**Comment by yarikoptic** [comment]
was fixed by #134
