### ISSUE TITLE
service-scripts update-dandiset-from-doi

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1280]
In our today's meeting attended by @waxlamp @bendichter @asmacdo and @weiglszonja we decided that https://github.com/dandi/dandi-archive/issues/1423 would be approached by first implementing needed logic in dandi-cli, at large reusing prototypes coded up in https://github.com/dandi/dandi-archive/issues/1423#issuecomment-1373745996 and https://github.com/dandi/dandi-archive/issues/1423#issuecomment-1408669132 .

In this issue we would **not** work to address https://github.com/dandi/dandi-archive/issues/772 , as to enhance authors' metadata with records from ORCID. For that we might later craft a dedicated `update-dandiset-contributors-from-orcid` or alike to be either chained or integrated with in `update-dandiset-from-doi`.

I think we need 

```shell
dandi service-scripts update-dandiset-from-doi -d|--dandiset DANDISET_ID[ --existing ask,overwrite,skip][ --fields contributor,name,description,relatedResource]  DOI
```

- decided to keep `-d|--dandiset DANDISET_ID` and option (not positional) so later if desired we could just pipe through stdin etc
- `--existing` is to instruct on how to behave while intending to place a value where there is a **different** value already. If "ask" - show existing value, offer a new one, ask it should be overwritten.  if "overwrite" -- just overwrite without interaction. if "skip" - skip
- `--fields` -- by default go through all listed below, but if option is specified (comma separated values?) - consider only those

The command will
- get metadata for DANDISET_ID
- request citation record from DOI
- based on information in DOI record
  - add "authors" to the `contributor:` list
    - while considering an author, check if there is already one which matches either by ORCID or if not present - name matches an already known contributor.  If so and not identical -- act based on `existing` value
    - ~~if corresponding author of the paper (if record provides that information) -- add with `dcite:ContactPerson` role,~~  for all - add as `dcite:Author`
    - see e.g. https://github.com/dandisets/000402/blob/b5e4ab7e991e1f91476da31c722be276ec08c8f3/dandiset.yaml#L121 for a sample of such automatically added entries and what default fields to take
  - use "title" for the "name:"
  - use "abstract" for the "description:"
  - add a record to `relatedResource:` list alike
 ```yaml
- identifier: {DOI}
  name: {title}
  relation: dcite:IsDescribedBy
  schemaKey: Resource
  url: https://doi.org/{DOI}
```
   - first check if there is one among possibly present and identify based on "identifier", act based on `--existing` 
- if anything was actually changed in the metadata record
  - add to `wasGeneratedBy:` a record like the one we are adding while extracting metadata for assets:

```json
        {
          "description": "Metadata ({','.join(modified_fields)}) was enhanced by DANDI cli from DOI {doi}",
          "endDate": "{now}",
          "id": "urn:uuid:{iirc random UUID}",
          "name": "Metadata extraction from DOI",
          "schemaKey": "Activity",
          "startDate": "{when started doing the mess}",
          "wasAssociatedWith": [
            {
              "identifier": "RRID:SCR_019009",
              "name": "DANDI Command Line Interface",
              "schemaKey": "Software",
              "url": "https://github.com/dandi/dandi-cli",
              "version": "{version}"
            }
          ]
        }
 ```
    which would then allow us to figure out dandisets which used this functionality.
   - ask to either show simple unified diff in rendering of the original and modified records
   - ask to either update dandiset record with this modified record, and if yes - do so

@bendichter @satra any other fields possibly to re-use or reference to from  dandiset?  Anything to add/remove from above?

**Comment by bendichter** [comment]
@yarikoptic this looks great! I looked up the metadata for a few DOIs and this looks like the key metadata to extract.

**Comment by jwodder** [comment]
@yarikoptic @dorota Where can I find documentation on the schema of the doi.org API's responses?

**Comment by yarikoptic** [comment]
I think the ultimate source of knowledge we can dig up is https://citation.crosscite.org/docs.html . Unfortunately
- link there to [Citeproc JSON](http://gsl-nagoya-u.net/http/pub/citeproc-doc.html) is 404 due to entire domain gone  -- I will file a ticket.  
- googling lead me to https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html which lead to yet another 404 (https://github.com/citation-style-language/schema/blob/master/csl-types.rnc) (I need to add to my quest adding linkchecking like we have in bids, uff) which is probably now https://github.com/citation-style-language/schema/blob/master/schemas/styles/csl-types.rnc but that one is not the one anyways
- https://github.com/citation-style-language/schema#csl-json-schema there lads to  https://github.com/citation-style-language/schema/blob/master/schemas/input/csl-data.json and https://github.com/citation-style-language/schema/blob/master/schemas/input/csl-citation.json which is I guess what you want?

**Comment by jwodder** [comment]
@yarikoptic https://github.com/citation-style-language/schema/blob/master/schemas/input/csl-data.json doesn't indicate how corresponding authors are denoted.  How can I determine whether an author is a corresponding author?

**Comment by yarikoptic** [comment]
hm, csl-data.json doesn't even describe `"sequence"` or `"ORCID"` or affiliation which I observe in sample output of https://github.com/dandi/dandi-archive/issues/1423#issuecomment-1373745996 . So may be that is either incomplete or some other schema used? don't know yet

**Comment by yarikoptic** [comment]
so far failed to find information about correspondence author anyways, so let's forget about that aspect.

**Comment by jwodder** [comment]
@yarikoptic 

* To be clear, where should the service script get the DOI for a Dandiset from?  I assumed that this would be using the `"doi"` field found only in published Dandiset metadata, but that doesn't square with your comment [here](https://github.com/dandi/dandi-cli/pull/1283#issuecomment-1520599853).
* How should authors with just a `"name"` field and no `"family"` or `"given"` field, like the below, be handled?  What about handling of other name-related fields?

```json
{
  "name": "The International Brain Laboratory",
  "sequence": "first",
  "affiliation": []
}
```

**Comment by yarikoptic** [comment]
> * To be clear, where should the service script get the DOI for a Dandiset from?  I assumed that this would be using the `"doi"` field found only in published Dandiset metadata, but that doesn't square with your comment [here](https://github.com/dandi/dandi-cli/pull/1283#issuecomment-1520599853).

It is a positional CLI  argument as I listed it in original https://github.com/dandi/dandi-cli/issues/1280 (CLI spec is too long, so might need to horizontally scroll)

> * How should authors with just a `"name"` field and no `"family"` or `"given"` field, like the below, be handled? 

it would probably only those composite names, probably pointing to institutions etc. For now -- let's just skip with a WARNING. May be later we would add them somehow (not as authors though).

>  What about handling of other name-related fields?

- `sequence` - I think we can just ignore
- `affiliation` - so far I saw only empty ones, didn't check those sample DOIs though. did you see a non empty one?   we should add to `affiliation` list for that person

what other fields do you have in mind? we seems do not have much more to enter in our dandischema for a `Person`

**Comment by jwodder** [comment]
@yarikoptic `csl-data.json` also lists "dropping-particle", "non-dropping-particle", "suffix", "comma-suffix", "static-ordering", "literal", and "parse-names".

**Comment by jwodder** [comment]
@yarikoptic 

> let's just skip with a WARNING

Should the warning include any information about the skipped author entry?  If so, what?  Should the message just show the `repr()` for the structure?

**Comment by yarikoptic** [comment]
> > let's just skip with a WARNING
> 
> Should the warning include any information about the skipped author entry? If so, what? Should the message just show the `repr()` for the structure?

if `repr` provides the `name` etc -- sure, could be that.

> @yarikoptic `csl-data.json` also lists "dropping-particle", "non-dropping-particle", "suffix", "comma-suffix", "static-ordering", "literal", and "parse-names".

hard to say since none of those I have downloaded

<details>
<summary>using this script</summary> 

```shell
#!/bin/bash

d=doi-citations
mkdir -p $d

for doi in 10.1101/2020.01.17.909838 10.1523/JNEUROSCI.6157-08.2009 10.1016/j.neuron.2019.10.012 10.7554/eLife.48198 10.1038/s41467-023-37704-5; do
    out="$d/$(echo $doi | sed -e 's,/,--,g').json"
    curl --silent -L -d "" --header "Accept: application/vnd.citationstyles.csl+json; charset=utf-8" "https://doi.org/$doi" | jq . >| "$out"
    echo $out
done

```
</details>

<details>
<summary>seems to have no hits for any of those fields</summary> 

```shell
❯ (for f in "dropping-particle" "non-dropping-particle" "suffix" "comma-suffix" "static-ordering" "literal" "parse-names"; do /bin/grep "$f" doi-citations/*; done; )
... no output
```
</details>

could you please add a WARNING stating that the `f"A non-empty value {!r} for the field {} was not used for the {!r} co-author"` or alike.

**Comment by jwodder** [comment]
@yarikoptic 

> could you please add a WARNING stating that the `f"A non-empty value {!r} for the field {} was not used for the {!r} co-author"` or alike.

What is the last `{!r}` supposed to be filled in with?  Replacing it with the entire author entry from the DOI data would mean that the field & value would appear twice in the log message, and this would get worse if there are multiple leftover fields.

> affiliation - so far I saw only empty ones, didn't check those sample DOIs though. did you see a non empty one? we should add to affiliation list for that person

I have not seen a non-empty one.  Should the script just assume that the elements of `affiliation` in DOI data are strings and use them as the `name` field of an `Affiliation` object?

**Comment by yarikoptic** [comment]
> > could you please add a WARNING stating that the `f"A non-empty value {!r} for the field {} was not used for the {!r} co-author"` or alike.
> 
> What is the last `{!r}` supposed to be filled in with? Replacing it with the entire author entry from the DOI data would mean that the field & value would appear twice in the log message, and this would get worse if there are multiple leftover fields.

The target our `Person` record which would have only the fields we added so there should be no duplication.

> > affiliation - so far I saw only empty ones, didn't check those sample DOIs though. did you see a non empty one? we should add to affiliation list for that person
> 
> I have not seen a non-empty one. Should the script just assume that the elements of `affiliation` in DOI data are strings and use them as the `name` field of an `Affiliation` object?

I think so. Then either users can extend with `RORID` for those institutions or we might even become fancy and match some.  Looking at https://ror.org/ -- it is over 100k records, so we are unlikely to download/cache the full list... well -- separate issue/development some time and may be
