### ISSUE TITLE
Adding release notes to dandiset version

### ISSUE THREAD

**Issue by colleenjg** [dandi/dandi-cli#1291]
As discussed recently on the DANDI slack, it would be very helpful to have release notes implemented for dandiset versions. 

Of course, there are many use cases for release notes. In my view, one that is rather urgent, derives from the following problem: When a dataset-related paper is published, it should typically be added to the dandiset's related resources. Updating the dandiset metadata requires a new dandiset version to be generated with its own DOI. Release notes would allow dandiset owners to clarify that only minor metadata differences exist between the dandiset version _the paper points to_, and the dandiset version _that points to the paper_. I think this could be very important to avoid confusion for end users.

**Comment by yarikoptic** [comment]
Thank you @colleenjg -- I am 100% with you! We have an issue for this https://github.com/dandi/dandi-archive/issues/189 and thanks to input like yours -- we will prioritize implementing this feature. As IMHO it should be implemented not in the client, and we have an issue for it already -- I would recommend subscribing to that issue I have mentioned and I will close this one.
