### ISSUE TITLE
`AttributeError: module 'urllib3.connectionpool' has no attribute 'VerifiedHTTPSConnection'` failure in network sandbox on `0.55.0`

### ISSUE THREAD

**Issue by TheChymera** [dandi/dandi-cli#1295]
This is the full build log → https://ppb.chymera.eu/54c03f.log

Any ideas what could be happening?

It's also weird that this blocks test collection.

Is this a question of making sure `DANDI_TESTS_NONETWORK=1` is handled properly?

**Comment by jwodder** [comment]
@TheChymera What versions of vcrpy and urllib3 are you using?

**Comment by TheChymera** [comment]
@jwodder `=vcrpy-4.2.1` and `=urllib-2.0.2`

**Comment by jwodder** [comment]
@TheChymera This is https://github.com/kevin1024/vcrpy/issues/688.  Downgrade `urllib3` to less than `<2`, and note that urllib3 should be `<1.27` anyway, as that's what botocore 1.29.137 (a dependency of boto3, a dependency of zarr-checksum) requires.

**Comment by TheChymera** [comment]
That fixed it, thanks!
