### ISSUE TITLE
should we list found (NWB:N?) specification versions?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#13]
reflecting upon https://github.com/NeurodataWithoutBorders/pynwb/issues/1077 -- PyNWB fails to open some (NWB 1.0? or just not NWB:N?) NWB files.  So I wondered if we should collect a list of specification versions (Groups) and list them with `dandi ls` before even trying to feed that file to PyNWB?

@bendichter what do you think?

**Comment by bendichter** [comment]
@yarikoptic I'm struggling to keep up with with what datasets you are working with and what software and versions you are using. Can we take this over to slack?
