### ISSUE TITLE
Issues with `dandi organize`

### ISSUE THREAD

**Issue by TheChymera** [dandi/dandi-cli#1302]
I'm trying to follow [this guide]() to upload some BIDS-NWB data to DANDI.
The NWB validation seems to find no critical errors:

It seems `dandi organize` edits the source dataset:
* removing the session intermediary directory (I guess this *could* make sense) but it seems a bit weird for DANDI to make decisions about the data hierarchy on its own
* removing the `dataset_description.json`

Demo:

```console
[deco]~/.local/share/dandi/000546 ❱ dandi organize ~/.local/share/datalad/vStr_phase_stim/bids/
2023-05-30 03:08:31,168 [    INFO] Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2023-05-30 03:08:31,168 [    INFO] NumExpr defaulting to 8 threads.
2023-05-30 03:08:32,560 [    INFO] Loading metadata from 1 files
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    1.9s
[Parallel(n_jobs=-1)]: Done   1 out of   1 | elapsed:    1.9s finished
2023-05-30 03:08:34,460 [    INFO] Symlink support autodetected; setting files_mode='symlink'
2023-05-30 03:08:34,467 [    INFO] Organized 1 paths. Visit /run/media/chymera/data2/dandi/000546/
2023-05-30 03:08:34,467 [    INFO] Logs saved in /home/chymera/.cache/dandi-cli/log/20230530070830Z-28068.log
[deco]~/.local/share/dandi/000546 ❱ tree
.
├── dandiset.yaml
└── sub-M322
    └── sub-M322_ecephys.nwb -> /home/chymera/.local/share/datalad/vStr_phase_stim/bids/sub-M322/ses-20220722/ieeg/sub-M322_ses-20220722_task-rest_run-01_ieeg.nwb

2 directories, 2 files
[deco]~/.local/share/dandi/000546 ❱ tree ~/.local/share/datalad/vStr_phase_stim/bids/
/home/chymera/.local/share/datalad/vStr_phase_stim/bids/
├── dataset_description.json
├── README.md
└── sub-M322
    └── ses-20220722
        └── ieeg
            └── sub-M322_ses-20220722_task-rest_run-01_ieeg.nwb -> ../../../../.git/annex/objects/KK/4V/MD5E-s7785862944--2851c1c5f6458d2d8431fa8a3eec6116.nwb/MD5E-s7785862944--2851c1c5f6458d2d8431fa8a3eec6116.nwb

4 directories, 3 files
```

Is this something we *want* to do? If so, why, if not, how can I prevent this from happening?

**Comment by TheChymera** [comment]
@yarikoptic if you have any ideas :)

**Comment by yarikoptic** [comment]
another possibly related to unification of DANDI layout and BIDS, on the topic of session folders (which might have little sense for electrophys data since would be one file per session folder, and many sessions) is a "mental exercise" I have done in https://github.com/bids-standard/bids-specification/issues/751#issuecomment-820800800 to possibly make BIDS (2.0?) to be more flexible - as to allow and arbitrary (but clearly specified)) layering of folders - not just `sub-/[ses-/]`. (I filed https://github.com/bids-standard/bids-2-devel/issues/54 on that regard now)

**Comment by TheChymera** [comment]
Ok so apparently `dandi organize` is not required. I think I should edit the guide.

**Comment by TheChymera** [comment]
Solved as of https://github.com/dandi/handbook/pull/93
