### ISSUE TITLE
add species: Macaca nemestrina

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-cli#1306]
email to help@dandiarchive.org from nicholas.mei@alleninstitute.org

> Hi DANDI folks!
> 
> In a recent NWB upload for Patch-Seq data (https://dandiarchive.org/dandiset/000569) I encountered an error with the `species` field in the NWB files I was trying to upload:
> 
> https://github.com/dandi/dandi-cli/blob/4cde72f9f1b813bc0752cf7b5a6c72cbd7323582/dandi/metadata.py#L610-L617
> 
> I was able to get around the issue in the short term by following the suggestion and replacing my `species` (Macaca nemestrina) with the NCBITaxon url: http://purl.obolibrary.org/obo/NCBITaxon_9545. That said, since there may be future uploads with the same organism, it would probably be a good idea to get the species added to the ones that DANDI supports.
> 
> Can you help get this species added? Once it is, please let me know as I'd like to re-upload the NWB files so that the `species` field in the NWBs remain `Macaca nemestrina` instead of the NCBITaxon URL that I used to get the uploads to work.
> 
> Many thanks for your help!
> 
> Best,
> 
> Nicholas Mei

**Comment by kabilar** [comment]
Thanks Ben.  Closing as this issue was fixed in #1327.

Hi @njmei, Our team may have already followed up with you via email, but wanted to let you know that `Macaca nemestrina` is supported in DANDI.  Thanks.
