### ISSUE TITLE
publications in asset metadata

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-cli#1308]
In https://github.com/dandi/helpdesk/discussions/100, @GaelleChapuis wanted to know how to query for NWB files within [the big IBL dandiset](https://dandiarchive.org/dandiset/000409) that are associated with a given publication. This dandiset contains data that are relevant to several different publications, and each NWB file lists which publications it is associated with under the field `nwbfile.related_publications`. It looks like the dandi cli currently extracts these values and adds them to the dandiset-level metadata, but not the asset-level metadata. As a result, our best approach to query for these files currently is it iterate over all of the NWB files in the dandiset, open them in stream mode, and read this value. This is very slow compared to iterating over the asset-level metadata.

The solution I would like is to use these extracted values to also populate the asset-level metadata so they can be differentiated by this attribute. Since `RelatedResource` is part of the `CommonModel` that `Asset` inherits, it looks like the schema can support this already. It's just a matter of having the dandi cli extract this information. Note that NWB files do not always contain reference to publications, and they should not be required to, since sometimes data is not associated with any publication, so this extraction logic should be robust to the case where `nwbfile.related_publication is None`.

**Comment by bendichter** [comment]
That could work. We could create a function for  mapping asset-level NWB metadata to the dandi schema for assets if the dandi cli team would be interested in incorporating this function

**Comment by yarikoptic** [comment]
To say I am not quite following why it should reside in nwbinspector which job is to inspect, not to map etc, although I do see that "inspection" could be carried out on a "mapped/converted" instance of the metadata I guess.  But I don't think that is what is happening anyways ATM.

Here it seems indeed just a matter of adding more extracted metadata, which is what we already do in dandi-cli so I think it should just be done in it.

**Comment by satra** [comment]
@yarikoptic - only suggested it because there was always the lingering notion of removing some of those dictionaries and mappings out the dandi library, but i leave it as your call.

**Comment by jwodder** [comment]
@bendichter When you say the field in question is `nwbfile.related_publications`, do you mean:

* The field is keyed by `"related_publications"` inside an NWB file
* The field is keyed by `"nwbfile.related_publications"` inside an NWB file
* The field is keyed by `"related_publications"` inside a mapping keyed by `"nwbfile"` inside an NWB file

Also, could you link me to an example NWB that contains this field?

**Comment by jwodder** [comment]
@bendichter 

> It looks like the dandi cli currently extracts these values and adds them to the dandiset-level metadata

I don't think that's true.  The only times when dandi-cli sets the metadata for a Dandiset in the Archive are (a) when running `dandi upload` — but that's only if the developer option `--upload-dandiset-metadata` is given, and then only the metadata in the `dandiset.yaml` file is sent to the Archive — and (b) when running `dandi service-scripts update-dandiset-from-doi`.  Are you sure it's not the Archive that's removing the values from asset metadata and adding them to Dandiset metadata?

**Comment by jwodder** [comment]
@bendichter Ping.

**Comment by jwodder** [comment]
@bendichter 

* Could you provide something smaller than 86 GiB?  I'm not going to download something that huge, and extracting metadata over the network takes five to ten minutes.
* I can confirm that, though the client extracts the `related_publications` field from NWBs, the field is discarded when converting NWB metadata to dandischema metadata.  The client is definitely not including this information in Dandiset metadata.
* I'm assuming that the `related_publications` field in an NWB can be either a sequence of strings or (based on some of our test cases) a single string.  Is this correct?
* How exactly should `related_publications` fields be converted to dandischema `Resource`s?  For the provided NWB in particular, the field is a list containing a single string containing two DOI URLs separated by a comma & space, and one of these DOI URLs was used as the `identifier` field in a `Resource` in the Dandiset metadata.  (CC @satra)

**Comment by bendichter** [comment]
@jwodder 

Here's one that's < 1GB: https://api.dandiarchive.org/api/dandisets/000409/versions/draft/assets/64c796e4-3935-4d43-b4ca-9d1df17a07c2/

> I'm assuming that the related_publications field in an NWB can be either a sequence of strings or (based on some of our test cases) a single string. Is this correct?

Yes, this field can be a list of strings. See the schema entry [here](https://github.com/NeurodataWithoutBorders/nwb-schema/blob/ec0a87979608c75a785d3a42f61e3366846ed3c2/core/nwb.file.yaml#L209-L213). I think in this case neurosift is doing the JS equivalent of `", ".join(related_publications)` for the text it is displaying.

> How exactly should related_publications fields be converted to dandischema Resources?

I think we should create one `Resource` object for each entry of `related_publications` where `Resource.identifier` is the value and `Resource.relation` should be "cite:IsDescribedBy".

**Comment by jwodder** [comment]
@bendichter 

> I think in this case neurosift is doing the JS equivalent of `", ".join(related_publications)` for the text it is displaying.

No, our `_get_pynwb_metadata()` also returns a list of one comma-separated string.

> I think we should create one `Resource` object for each entry of `related_publications` where `Resource.identifier` is the value

What about for cases like this where the value isn't a DOI URL (or whatever we require of an identifier)?

**Comment by CodyCBakerPhD** [comment]
> We can add a check for this in nwbinspector so that we can have more trust in future contributions.

We've always had a check for DOI format for all entries in the related publication list: https://github.com/NeurodataWithoutBorders/nwbinspector/blob/0e3640048f18838762af98ccbf071b07f0b39e48/src/nwbinspector/checks/nwbfile_metadata.py#L115

> @CodyCBakerPhD , do you know why the current IBL data is a comma-separated string instead of a list of string?

Not sure what you're talking about - the metadata encodes it as a list in the YAML: https://github.com/catalystneuro/IBL-to-nwb/blob/5195b4eada1f3c82416cd3f26d523fd72752fadf/ibl_to_nwb/brainwide_map/brainwide_map_metadata.yml#L6-L8

And the HDF5 file contents show each string written as a separate element on that dataset

![image](https://github.com/dandi/dandi-cli/assets/51133164/6f287385-3cca-4e22-bd2b-a05563c09235)

**Comment by bendichter** [comment]
OK, yes, I thought this was the case. Thanks for the clarification, @CodyCBakerPhD 

@jwodder , is it possible that `_get_pynwb_metadata()` is doing this join behind the scenes?

**Comment by CodyCBakerPhD** [comment]
@jwodder Right you are - the file with the bulk contents has top level metadata from an earlier draft version that hasn't been updated

We can definetely add an NWB Inspector check for someone adding single string with comma-separated entires instead of multiple listed entries

**Comment by jwodder** [comment]
@bendichter Repeating some questions from earlier:

* Can `related_publications` legitimately be a single string as an alternative to a list of strings?  I can't make any sense of [the schema entry](https://github.com/NeurodataWithoutBorders/nwb-schema/blob/ec0a87979608c75a785d3a42f61e3366846ed3c2/core/nwb.file.yaml#L209-L213).
    * If it is not allowed for a `related_publications` field to be a single string, what should happen if the client encounters one that is?

> I think we should create one `Resource` object for each entry of `related_publications` where `Resource.identifier` is the value and `Resource.relation` should be "cite:IsDescribedBy".

I'm assuming this is intended for the case where each entry of `related_publications` is a DOI URL.  What if an entry is a different kind of URL?  What if it's not a valid URL at all (as in the case of the two URLs joined by a comma)?

**Comment by jwodder** [comment]
@bendichter Ping.

**Comment by bendichter** [comment]
@jwodder "related publications" is a list of strings, and each string should be a DOI. It usually only has one entry (and is often empty). If there are multiple related publications, the proper way of entering that would be as a list of DOI strings. We do not do any validation to ensure users are not entering related publications as "[first_pub], [second_pub]" or any other kind of custom concatenation, so I do suspect we might run into that every now and then. We can make an NWB Inspector check that minimizes this. Another approach could be to test the validity of each entry as a URL and only accept those that are proper URLs.

**Comment by jwodder** [comment]
@bendichter You didn't answer the crucial question, which is: What should the code do when "related publications" *isn't* what you say it should be?

**Comment by bendichter** [comment]
Skip it

**Comment by jwodder** [comment]
The need to check for valid URLs makes this blocked on #1380.
