### ISSUE TITLE
environment incompatibilities between iblenv and dandi requirements

### ISSUE THREAD

**Issue by GaelleChapuis** [dandi/dandi-cli#1309]
When doing `pip install dandi` in `iblenv` I get this error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.2 requires numpy<1.24,>=1.18, but you have numpy 1.24.4 which is incompatible.
```

The instructions to install `iblenv` are here
https://github.com/int-brain-lab/iblenv

**Comment by GaelleChapuis** [comment]
I did not get this error after re-installing `iblenv` from scratch then doing `pip install dandi`. Apologies !

**Comment by yarikoptic** [comment]
Thanks for sharing @GaelleChapuis ! Now that it is known to issues of the github - it might come of value for someone.
