### ISSUE TITLE
dandi is not available on conda-forge for osx-arm64

### ISSUE THREAD

**Issue by rly** [dandi/dandi-cli#1313]
dandi is released on conda-forge for some OS's but not osx-arm64. I have to use pip on my Mac M1 (this is OK though!)

<img width="155" alt="image" src="https://github.com/dandi/dandi-cli/assets/310197/098bb1c0-8452-48f2-81e4-6e8a837b9615">

```
test ❯ mamba install dandi

Looking for: ['dandi']

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache

Pinned packages:
  - python 3.10.*


Could not solve for environment specs
The following package could not be installed
└─ dandi does not exist (perhaps a typo or a missing channel).
```

**Comment by yarikoptic** [comment]
filed https://github.com/conda-forge/dandi-feedstock/issues/101 ... please track there - I will close thise on. most likely dependency isn't yet "ready".  will try to check later in detail (attn @jwodder happen he ventures conda ways)
