### ISSUE TITLE
downloading dandiset.yaml without downloading the full dandiset

### ISSUE THREAD

**Issue by magland** [dandi/dandi-cli#1317]
Is it possible to download or somehow obtain the dandiset.yaml file without downloading the entire dandiset? This would be useful for amending a dandiset using the cli without downloading all the files. Alternatively, is there a more straightforward way to upload a file to an existing dandiset other than using the dandiset.yaml?

**Comment by yarikoptic** [comment]
- `dandi download` can do that for you

```shell
❯ dandi download --help | grep -e --download -A2
  --download [dandiset.yaml,assets,all]
                                  Comma-separated list of elements to download
                                  [default: all]
```

so e.g.
```shell
❯ dandi download --download dandiset.yaml DANDI:000026
2023-08-10 09:41:54,008 [ WARNING] Request to https://api.dandiarchive.org/api failed (404 Client Error: Not Found for url: https://api.dandiarchive.org/api/api/info/)
2023-08-10 09:41:54,008 [ WARNING] Using hard-coded URLs
PATH                 SIZE DONE    DONE% CHECKSUM STATUS MESSAGE   
000026/dandiset.yaml                             done   updated   
Summary:                  0 Bytes                1 done 1 updated 
                          <0.00%                                  
2023-08-10 09:41:54,438 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20230810134152Z-616416.log
dandi download --download dandiset.yaml DANDI:000026  1.92s user 3.13s system 197% cpu 2.559 total
```

- all dandisets are also provided as DataLad datasets from https://github.com/dandisets with super-dataset at https://github.com/dandi/dandisets to identify the versions of the entire archive.  You can simply git clone any of those to get to dandiset.yaml ;-)

**Comment by satra** [comment]
> Alternatively, is there a more straightforward way to upload a file to an existing dandiset other than using the dandiset.yaml?

you can do it programmatically using the python library (or replicate the functionality using the REST API in any language).
