### ISSUE TITLE
Move command PUT returns 200 but no change on archive

### ISSUE THREAD

**Issue by slaytonmarx** [dandi/dandi-cli#1325]
Good afternoon. I'm attempting to rename a single file of the 000108 dandiset today with `dandi move` but I'm not seeing any change, despite the process indicating success.

The command I'm running is:
```
dandi move sub-mEhm/ses-20220819h12m59s17/micr/sub-mEhm_ses-20220819h12m59s17_sample-mEhmAD-O6_R2_stain-ABETA_run-1_chunk-3_SPIM.ome.zarr sub-mEhm/ses-20220819h12m59s17/micr/sub-mEhm_ses-20220819h12m59s17_sample-ADO6R2_stain-ABETA_run-1_chunk-3_SPIM.ome.zarr -d https://dandiarchive.org/dandiset/000108
```
Here is the log it produced:
[20230908172312Z-2960477.log](https://github.com/dandi/dandi-cli/files/12562395/20230908172312Z-2960477.log)

Here's a link to the dandiset sub directory in question as well, the file to be renamed is on the second page:
https://dandiarchive.org/dandiset/000108/draft/files?location=sub-mEhm%2Fses-20220819h12m59s17%2Fmicr

Thank you!

**Comment by yarikoptic** [comment]
FTR: this is the same command but with filenames in separate lines to ease detecting what is changed 
```
dandi move  \
sub-mEhm/ses-20220819h12m59s17/micr/sub-mEhm_ses-20220819h12m59s17_sample-mEhmAD-O6_R2_stain-ABETA_run-1_chunk-3_SPIM.ome.zarr \
sub-mEhm/ses-20220819h12m59s17/micr/sub-mEhm_ses-20220819h12m59s17_sample-ADO6R2_stain-ABETA_run-1_chunk-3_SPIM.ome.zarr \
-d https://dandiarchive.org/dandiset/000108
```

so we go from `_sample-mEhmAD-O6_R2` to `_sample-ADO6R2` for `_stain-ABETA_run-1_chunk-3_SPIM.ome.zarr`, indeed I see still old name for that `_stain-ABETA_run-1_chunk-3_SPIM.ome.zar` on the 2nd page

![image](https://github.com/dandi/dandi-cli/assets/39889/acb487b3-089f-46ec-a429-c01e08f9cab6)

and I didn't spot anything odd in heroku logs.

@slaytonmarx was that just for that zarr? did you move any other zarr successfully?

I have tried on https://gui-staging.dandiarchive.org/dandiset/101267/ with

```
dandi -l 1 move -d https://gui-staging.dandiarchive.org/dandiset/101267 test_small.ome.zarr test_small-renamed.ome.zarr
```

and also so no rename happen... also tried on an individual file blob there (despite in .ngff -- was a blob):

```
dandi -l 1 move -d https://gui-staging.dandiarchive.org/dandiset/101267 test_01.ngff/0/0/0/0/0/{4,4-renamed}
```

all `dandi-cli` tests for `test_move` which are executed against docker-composed instance pass.... odd...

**Comment by satra** [comment]
and this is really a metadata change, which one can do it with a `PUT` quite easily. hence perhaps we can check what the `PUT` call and payload looks like and try it out on the api interface itself.

**Comment by yarikoptic** [comment]
filed https://github.com/dandi/dandi-archive/issues/1682 with some more information.

**Comment by slaytonmarx** [comment]
Great work! The update did the trick.

**Comment by yarikoptic** [comment]
Let's consider it resolved then. Thank you @slaytonmarx for confirming!!!!
