### ISSUE TITLE
Support upload of h264 video files

### ISSUE THREAD

**Issue by rly** [dandi/dandi-cli#1328]
DANDI allows upload of files with particular video extensions such as mp4 and avi
https://github.com/dandi/dandi-cli/blob/697af7c43c407ca8ccaa815cecd844d810174cbb/dandi/consts.py#L167

Loren Frank's lab at UCSF stores their video data as .h264 files. Can this be supported as well?

**Comment by satra** [comment]
should we consider whether we allow all formats, or all easy to read formats if there are formats supported by common libraries.

**Comment by rly** [comment]
Hm. I was under the impression that raw h264 was more popular than it actually is. Even though it is a common IP camera output format, it cannot be read by common video playing apps like VLC without additional steps. 

I think DANDI allowing only formats that can be read by common libraries makes sense; the data should be easily readable/accessible. It looks like h264 can be converted to mp4 straightforwardly and without loss: e.g., `ffmpeg -framerate 54 -i input.264 -c copy output.mp4`.

For other formats (and codecs), I guess it depends on whether it can be converted to an accepted format without loss.
