### ISSUE TITLE
Missing term in ETA calculation

### ISSUE THREAD

**Issue by sneakers-the-rat** [dandi/dandi-cli#1339]
Hello hello :) nice tool, am currently hypnotized watching the download counters complete.

I'm noticing the ETA timer counts up rather than down. a tiny tiny fix  that should hopefully be easy :)

This line: 
https://github.com/dandi/dandi-cli/blob/04e7c2011a95679baca696f1faa22f70e84cee17/dandi/download.py#L447

calculates ETA by dividing elapsed time by the proportion completed:
https://github.com/dandi/dandi-cli/blob/04e7c2011a95679baca696f1faa22f70e84cee17/dandi/download.py#L431

So ETA slowly converges to the time elapsed (rather than to 0) and then spikes to 0 once `r == 1`

I think we're missing a term there. Assuming a constant rate...

$t_{elapsed} = p_{completed} * t_{total}$
$t_{total} = t_{elapsed} + t_{remaining}$

Substituting...

$t_{elapsed} = p_{completed} * ( t_{elapsed} + t_{remaining} )$

$\frac{t_{elapsed}}{p_{completed}} =  t_{elapsed} + t_{remaining} $

$\frac{t_{elapsed}}{p_{completed}} - t_{elapsed} =  t_{remaining} $

or `(dt/r)-dt`

so say we are 10% complete after 1 second. we should have 9 seconds left.

`1/.1 - 1 = 9`

our download speed fluctuates wildly, and after 90 seconds we are 90% complete, we should have 10 seconds left (since we're not tracking download speed and can't make a better estimate based on recent history, we just use the average rate which converges to correct at 100%)

`90/.9 - 90 = 10`

Thanks again for the tool and the archive!

**Comment by yarikoptic** [comment]
> nice tool, am currently **hypnotized** watching the download counters complete.

please contact us separately on this potential business idea ;)

> (dt/r)-dt

or `dt*(1-r)/r` and d'oh, what a nice find! I am happy that hypnotization was so productive -- we should include that positive effect of spotting bugs and other insects in the business proposal! ;-)  

Would you mind submitting a PR so we acknowledge your contribution in the annals of the git history?  Going to SfN? then stop by to pick up some [extra ribbon](https://github.com/dandi/sfn2023/issues/5) for your badge ;)

**Comment by sneakers-the-rat** [comment]
yes i'll see what i can do about a test and open a PR in a moment, and thank you for your absolutely delightful issue-side manner. i would be honored to sport a ribbon
