### ISSUE TITLE
Versioneer isn't recent enough for Python 3.12

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-cli#1353]
The copy of `versioneer` that dandi-cli bundles is version 0.18, yet a minimum of version 0.19 (or possibly higher?) is needed in order to receive [this patch](https://github.com/python-versioneer/python-versioneer/pull/207) and thus support Python 3.12.

(Personally, I would recommend scrapping `versioneer` entirely and using `versioningit`, but I have an obvious bias.)

**Comment by yarikoptic** [comment]
in #1330 I was adding some recent snapshot https://github.com/dandi/dandi-cli/pull/1330/files#diff-18304872b75eda292f2b72a449de58182604394b8df4051c42205bb4a005a245L2

```
- # Version: 0.18
+ # Version: 0.29+8.gf9bbd1b
```

should be good enough?

I don't mind switching overall to `versioningit` in general

**Comment by jwodder** [comment]
Fixed in #1330.
