### ISSUE TITLE
How can I pull specific data from a dandiset?

### ISSUE THREAD

**Issue by AngCamp** [dandi/dandi-cli#1354]
I want to pull some files from this dataset: https://dandiarchive.org/dandiset/000409/draft  I am not interested in the raw video footage stored in the .mp4 files, but everything else is of interest.  Is there a way in the dandi-cli to pull only files containing a certain string?  If I run `dandi download https://dandiarchive.org/dandiset/000409/draft` that pulls way too much for my storage space to handle so I need to cut it down a bit.  I could start with some specific folders as well and just use a bash script with wget, but I was wondering if the dandi-cli has som functionality that I could take advantage of.

**Comment by satra** [comment]
you can do something like this:

```shell
dandi download 'https://dandiarchive.org/api/dandisets/000409/versions/draft/assets/?glob=sub-CSHL049/*behavior.nwb'
```

also you can use datalad which allows you to create a shell of a dandiset in your local system. 
```shell
datalad install -0
cd 000409/sub-CSHL049
datalad get sub-CSHL049_ses-c99d53e6-c317-4c53-99ba-070b26673ac4-processed-only_behavior.nwb
```

you can also remove the bytes of the file locally:

```
datalad drop sub-CSHL049_ses-c99d53e6-c317-4c53-99ba-070b26673ac4-processed-only_behavior.nwb
```

finally if you are programming you can access each file remotely without downloading all of it.

**Comment by AngCamp** [comment]
>finally if you are programming you can access each file remotely without downloading all of it.

Ok that's interesting, can I call it as I need it?  Is there a tutorial in the dandi-cli I can look at to do this?  Will this work if I'm working in a notebook for prototyping analysis code before I have a pipeline fully built?

**Comment by satra** [comment]
> can I call it as I need it? 

yes.

> Is there a tutorial in the dandi-cli I can look at to do this? 

https://pynwb.readthedocs.io/en/stable/tutorials/advanced_io/streaming.html#streaming-nwb-files
https://github.com/magland/remfile
https://dandi.readthedocs.io/en/latest/modref/index.html (look for midlevel

> Will this work if I'm working in a notebook for prototyping analysis code before I have a pipeline fully built?

https://alleninstitute.github.io/openscope_databook/intro.html# (this also has lots of nice bits and pieces more generally in addition to working with dandi).
