### ISSUE TITLE
Downloads hang indefinitely if connection interrupted from lack of `timeout`

### ISSUE THREAD

**Issue by sneakers-the-rat** [dandi/dandi-cli#1366]
tell me when you're getting sick of me <3

Downloads happen by [iterating](https://github.com/dandi/dandi-cli/blob/0971d02a0725d5e22c76e1bf32c45ca32e666c92/dandi/download.py#L685) over some `downloader` object, wrapped in some number of [`attempt`](https://github.com/dandi/dandi-cli/blob/0971d02a0725d5e22c76e1bf32c45ca32e666c92/dandi/download.py#L669)s, catching [`HTTPErrors`](https://github.com/dandi/dandi-cli/blob/0971d02a0725d5e22c76e1bf32c45ca32e666c92/dandi/download.py#L706)

The core of the downloading logic for the default downloader is here, standard `requests` streaming:

https://github.com/dandi/dandi-cli/blob/0971d02a0725d5e22c76e1bf32c45ca32e666c92/dandi/dandiapi.py#L1473-L1480

The zarr downloader is I think identical in this block?

https://github.com/dandi/dandi-cli/blob/0971d02a0725d5e22c76e1bf32c45ca32e666c92/dandi/dandiapi.py#L1903-L1911

A timeout is not used in either case, and the [`requests` docs](https://docs.python-requests.org/en/latest/user/quickstart/#timeouts) warn:

> Nearly all production code should use this parameter in nearly all requests. Failure to do so can cause your program to hang indefinitely

and elaborates further on how timeouts are handled after the initial connection [here](https://docs.python-requests.org/en/latest/user/advanced/#timeouts)

If the connection is interrupted, the downloader hangs indefinitely even if the connection is re-established. 

## MWE

- systems tested: MacOS and Debian 12
- dandi version: `0.58.0`

To replicate:
- Start downloading any dandiset with the `dandi download` command
- Toggle WiFi off and on or disconnect and reconnect ethernet cable briefly.

## Expected Behavior

Since there is already retry logic around the download command, I think it would be straightforward to
- set some timeout value in consts or read from env variable
- pass timeout value to `session.get` call
- catch `requests.exceptions.Timeout` in existing `requests.exceptions.HTTPError` block, which should already sleep for 5 seconds and retry.

Happy to PR this very minimal change :)

**Comment by jwodder** [comment]
@yarikoptic What should the timeout be set to?

**Comment by yarikoptic** [comment]
what would be your judgement?  I think `60 sec` is good enough to say that connection is dead if no response.

**Comment by jwodder** [comment]
@yarikoptic That seems high.  I was expecting something more like 5 or 10 seconds, but I'm having difficulty finding any resources on optimal timeout values.

**Comment by yarikoptic** [comment]
https://www.python-httpx.org/advanced/#fine-tuning-the-configuration gives an example of using 60 sec for connection time out... Ok, what about mid-ground of 30? ;)  here we are to prevent a complete "hang" - waiting for a minute or half of it is IMHO ok compromise.

**Comment by sneakers-the-rat** [comment]
`requests` has two timeouts :) one timeout for connections, and one timeout for read timeout (the amount of time to wait between bytes sent from the server after a connection is established).

So maybe a shorter connection timeout to raise on a nonresponsive server and a longer read timeout to let a connection heal?

**Comment by sneakers-the-rat** [comment]
Thanks y'all !
