### ISSUE TITLE
Make file upload  be robust to file size changes

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1373]
Per request of @jwodder in https://github.com/dandi/dandi-cli/issues/1257#issuecomment-1850127241 filing it as a separate issue.

Background: As discovered [in that issue](https://github.com/dandi/dandi-cli/issues/1257#issuecomment-1839101911) we caught NFS (or some layer above on the way to Python) lying about file size to be 0 whenever it is not: the reported size gets changed within few seconds.  We also spotted S3 failing some uploads due to "Content-MD5 you specified did not match what we received", an exact reason for which we do not know.
So, apparently we cannot really rely on file system to provide us robust file size, and thus we should 1. provide mitigation to the 0-size file issue and to possibly help isolate any other incorrect file size reporting add a safe-guard.  

I am filing it as a single issue since IMHO two aspects are very related and likely to be implemented in a concerted effort.   I will provide only high level description of desired behavior instead of mandating any particular implementation.

- Should be in effect for *any* file upload,  be it a blob or a file within zarr folder upload
- Upon initiation of upload do a *filesize check*: a file size reported to be 0, loop for up to 2 seconds (sleeping may be 100ms between) re-checking the file size. If it changes from 0 - can immediately proceed forward. If it remains 0 - proceed forward with 0 file size after those 2 seconds.
- Upon completion of upload, be it successful or failed with an error, compare filesize with the one obtained in previous *filesize check* step. If size differs: if upload finished    successfully - do raise an (`IOError` or other you find more appropriate) exception summarizing size changes, if upload errorred out - just log an ERROR level log message summarizing size changes.

**Comment by jwodder** [comment]
> loop for up to 2 seconds (sleeping may be 100ms between)

To be clear: Do you mean that the total time spent looping should be no more than two seconds or that the individual sleeps should increase up to a maximum of two seconds each?  Either way, how many iterations through the loop should there be?

**Comment by yarikoptic** [comment]
> > loop for up to 2 seconds (sleeping may be 100ms between)
> 
> To be clear: Do you mean that the total time spent looping should be no more than two seconds or that the individual sleeps should increase up to a maximum of two seconds each? Either way, how many iterations through the loop should there be?

individual sleeps of e.g. 100ms (no need to increase delay IMHO), total to 2 sec, so 20 iterations.
