### ISSUE TITLE
Use a dedicated URL-handling library

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-cli#1380]
There are various places in the code that would benefit from the use of a modern URL-handling library, such as [furl](https://github.com/gruns/furl), [purl](https://github.com/codeinthehole/purl), or [yarl](https://github.com/aio-libs/yarl).  These include:

* [x] [`is_same_url()` in `delete.py`](https://github.com/dandi/dandi-cli/blob/cb00a7cb8e92d86dd78a9330780fc4c1eab0cfea/dandi/delete.py#L248)
* ~[`extract_species()` in `metadata/util.py`](https://github.com/dandi/dandi-cli/blob/cb00a7cb8e92d86dd78a9330780fc4c1eab0cfea/dandi/metadata/util.py#L437-L443)~ *(yarl doesn't help here; see #1416 instead)*
* [x] [`get_content_url()` in `dandiapi.py`](https://github.com/dandi/dandi-cli/blob/cb00a7cb8e92d86dd78a9330780fc4c1eab0cfea/dandi/dandiapi.py#L1449-L1450)
* [x] [`get_instance()` in `utils.py`](https://github.com/dandi/dandi-cli/blob/cb00a7cb8e92d86dd78a9330780fc4c1eab0cfea/dandi/utils.py#L568-L569)
* [x] [`is_page2_url()` in `utils.py`](https://github.com/dandi/dandi-cli/blob/cb00a7cb8e92d86dd78a9330780fc4c1eab0cfea/dandi/utils.py#L779)
* [x] [`_get_instance()` in `utils.py`](https://github.com/dandi/dandi-cli/blob/f256a55389033f7655d4fd905e6dc973cd785dfc/dandi/utils.py#L620-L630)
* ~[`joinurl()` in `utils.py`](https://github.com/dandi/dandi-cli/blob/f256a55389033f7655d4fd905e6dc973cd785dfc/dandi/utils.py#L872)~ *(yarl doesn't help here)*
* ~Most of `dandi/dandiarchive.py`?~ *(I think rewriting this would be more trouble than it's worth)*
* implementing the URL validation needed for #1308

We should use such a library to improve the code.

**Comment by yarikoptic** [comment]
good idea.  Only yarl seems to be alive, the other two had no changes in years. And dang -- yarl already has precommit setup for use of codespell ;-)

**Comment by yarikoptic** [comment]
please proceed with making a decision on this one @jwodder to unblock 
- #1308
