### ISSUE TITLE
Make release workflow triggerable so we could release dandi-cli any time not only upon PR merge

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1388]
I think we have done such a drill somewhere else

And to test how it works let's cut release to facilitate fixing testing dandi-archive https://github.com/dandi/dandi-archive/issues/1804#issuecomment-1881663802

**Comment by jwodder** [comment]
@yarikoptic 

> I think we have done such a drill somewhere else

I don't think we have.  The closest we've come is https://github.com/datalad/release-action/issues/34.

Problem: We've configured `auto` (via `.autorc`) to not do anything unless a PR with the "release" label has been merged, and [`auto shipit` doesn't seem to have an option to reverse that setting](https://intuit.github.io/auto/docs/generated/shipit#options).

**Comment by yarikoptic** [comment]
oh.  Is there a way in auto to ignore adding "release PR" title into CHANGELOG? then we could gain a simple action to submit and merge a PR with `release` label but also annotated to be ignored from CHANGELOG.

**Comment by jwodder** [comment]
@yarikoptic I don't think so.

**Comment by yarikoptic** [comment]
I guess we are then doomed to send some PRs to cut release for now.
