### ISSUE TITLE
No module named 'rpds.rpds' when importing DandiAPIClient

### ISSUE THREAD

**Issue by NilsNyberg** [dandi/dandi-cli#1403]
When I try to run 'from dandi.dandiapi import DandiAPIClient' I get error message 'ModuleNotFoundError: No module named 'rpds.rpds''. I have tried on different computers and conda versions, as well as googling the issue, but haven't found a solution.

**Comment by NilsNyberg** [comment]
Sure, I just set up a new analysis computer with fresh anaconda and python installs, and the python packages have been installed using pip, so they should be generally be the latest versions available. The version of dandi is: 0.59.1 according to 'pip show dandi'

**Comment by jwodder** [comment]
@NilsNyberg What OS are you using?  What version of Python?  How did you install `dandi`?  Can you provide a complete series of commands for reproducing your broken environment?

**Comment by NilsNyberg** [comment]
Microsoft Windows 10 Enterprise, Python 3.11.7. Dandi was installed via the following steps: 1. install Anaconda (using Windows executable), 2. Create a conda environment with latest python version (conda create --name myenv python=3), which turns out to be 3.11.7. Then I used pip install to install the following packages: numpy, scipy, matplotlib, seaborn, dandi, h5py, pynwb, pynapple. 3. Then I open a Spyder session and tried the command: from dandi.dandiapi import DandiAPIClient. That is what gave me the error. 

As I said in a follow-up post (not sure its still visible after transferring this post to a different repository), I can successfully import DandiAPIClient when I uninstalled rpds-py (which I assume was installed with dandi) and then re-installed the package using the version of rpds-py released on 28th of Dec, via pip install rpds-py==0.16.2.

**Comment by jwodder** [comment]
@NilsNyberg If you create a fresh Conda environment and install the latest version of rpds-py in it, can you do `import rpds` in that environment?  I suspect the problem lies with rpds-py rather than with dandi.

**Comment by NilsNyberg** [comment]
I think you are right. When I create a new conda environment with the latest python version and try import rpds, I again get: ModuleNotFoundError: No module named 'rpds.rpds'.

So the problem indeed seems to lie with rpds-py.

Thanks for the help!
