### ISSUE TITLE
RemoteDandiset.download_directory doesn't appear to work?

### ISSUE THREAD

**Issue by rcpeene** [dandi/dandi-cli#1452]
Running `download_directory` in my notebook which demonstrates downloading from Dandi, appears not to work, 
described in this issue
https://github.com/AllenInstitute/openscope_databook/issues/398

I've attempted to replicate it and receive the same results. The function call does not yield an error, but simply seems to not actually run any download. I'm using dandi==0.61.2

**Comment by yarikoptic** [comment]
Thank you for the report!  Please just use `""` instead of `"./"`. Submitted
- https://github.com/AllenInstitute/openscope_databook/pull/399
but we also might make it more robust on our side:
- https://github.com/dandi/dandi-cli/pull/1454
