### ISSUE TITLE
Dandi organize not finding Dandiset

### ISSUE THREAD

**Issue by rcpeene** [dandi/dandi-cli#1479]
I am attempting to write a code ocean capsule that takes several NWB files as input and then runs dandi organize and dandi upload to an existing dandiset.

Running dandi organize on a directory containing my nwb files like the following snippet returns an error.

```python
result = subprocess.run(["dandi", "organize", '-d', str(dandiset_dir)], cwd='/root/capsule', capture_output=True, text=True)

```

```python
Error: No dandiset was found at /scratch, and no paths were provided
```

From the documentation, I have gleaned that I need some sort of metadata file for the directory to be identified as a dandiset. I couldn't find any further explanation in the dandi.Organize documentation as for what files are required or how I can make them

**Comment by satra** [comment]
@rcpeene - see step 5 here: https://www.dandiarchive.org/handbook/13_upload/ 

the first few lines are important to provide that dandiset metadata.
