### ISSUE TITLE
Add an option to dump content of `Audit` table from Docker env upon completion of testing

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1484]
Now that we have `audit` functionality merged into master of dandi-archive, it would be great to 
- do some stress testing of it
- inspect what kind of records it records, and either with desired properties etc

Could we hackup quickly the following :

- If `DANDI_TESTS_AUDIT_JSON` env var is set:
  - Do not just use docker image, install `master` of dandi-archive into it (I think we do smth similar already)
  - Before cleaning up the env in the fixture taking care about docker compose, connect to postgres DB and dump `Audit` table as a list of json records into the file pointed to by `DANDI_TESTS_AUDIT_JSON` env var

**Comment by jwodder** [comment]
> Do not just use docker image, install `master` of dandi-archive into it (I think we do smth similar already)

The Docker image is built from dandi-archive's `master` already.

> Before cleaning up the env in the fixture taking care about docker compose, connect to postgres DB and dump `Audit` table as a list of json records into the file pointed to by `DANDI_TESTS_AUDIT_JSON` env var

And then what?  Is this feature going to be used as part of the GitHub Actions CI — in which case, should the file be uploaded as a build artifact?

Also, how exactly is the dump supposed to be performed?  [`pg_dump`](https://www.postgresql.org/docs/current/app-pgdump.html) doesn't have a JSON option, and I do not want to add a Python database library to dandi-cli's test dependencies just for this feature, which I honestly don't expect to be used very much.

**Comment by yarikoptic** [comment]
> > Before cleaning up the env in the fixture taking care about docker compose, connect to postgres DB and dump `Audit` table as a list of json records into the file pointed to by `DANDI_TESTS_AUDIT_JSON` env var
> 
> And then what? Is this feature going to be used as part of the GitHub Actions CI — in which case, should the file be uploaded as a build artifact?

nah, just locally ATM

> Also, how exactly is the dump supposed to be performed? [pg_dump](https://www.postgresql.org/docs/current/app-pgdump.html) doesn't have a JSON option, and I do not want to add a Python database library to dandi-cli's test dependencies just for this feature, which I honestly don't expect to be used very much.

could you just add it to some optional extras_require (e.g. `dbdump`)?

**Comment by yarikoptic** [comment]
I thought that indeed we could just connect to DB from python and perform the dump. Is that too tricky?

**Comment by jwodder** [comment]
@yarikoptic If you're OK with CSV instead of JSON, it would be far easier to just do a `SELECT` via [`psql`](https://www.postgresql.org/docs/current/app-psql.html) instead of futzing with DB libraries.

**Comment by yarikoptic** [comment]
sure, csv would be just fine!

**Comment by yarikoptic** [comment]
note though that `details` is a json record so would be full of `,` so within csv those should be handled appropriately (not just dumped via ad-hoc `print`).
