### ISSUE TITLE
Python 3.8 tests failing 

### ISSUE THREAD

**Issue by asmacdo** [dandi/dandi-cli#1503]
We are installing nwbinspector from source, and upcoming release 0.6.0 drops support for 3.8.

`ERROR: Package 'nwbinspector' requires a different Python: 3.8.18 not in '>=3.9'`

**Comment by yarikoptic** [comment]
Just switch to use 3.9 in that CI run.

**Comment by asmacdo** [comment]
@yarikoptic that CI run is the python 3.8 run.
