### ISSUE TITLE
Create option to bypass untagged CLI versions to integration test code properly

### ISSUE THREAD

**Issue by aaronkanzer** [dandi/dandi-cli#1526]
While developing https://github.com/dandi/dandi-cli/pull/1519, it was not possible to bypass version checks when testing via the workflow described here: https://github.com/dandi/dandi-cli/pull/1519#issuecomment-2471300984

This is due to:

1.  the untagged nature of the built CLI tool, where a proper semantic version is not issued
2. The `/info` endpoint being hit (whether staging or prod) does not recognize the untagged version either

A plausible solution here would be to introduce a `--bypass-version-validation` flag into the CLI, so that testing against a production/staging environment can occur without commenting out code -- as displayed, for instance, here: https://github.com/dandi/dandi-cli/pull/1519#discussion_r1843905312

Let me know your thoughts @jwodder @yarikoptic -- perhaps you already have a workflow here that is yet to be documented -- thanks in advance

 Cc @kabilar

**Comment by jwodder** [comment]
I believe the problem comes from the fact that your fork at https://github.com/aaronkanzer/dandi-cli does not have any tags for some reason.  Fix that, and then pip-installing the fork should result in an actual version.

**Comment by aaronkanzer** [comment]
> I believe the problem comes from the fact that your fork at https://github.com/aaronkanzer/dandi-cli does not have any tags for some reason. Fix that, and then pip-installing the fork should result in an actual version.

I can do that -- however, this would force every other fork to do this setup, outside of just writing code

**Comment by aaronkanzer** [comment]
> @aaronkanzer I suspect this happened because you had "Copy the `master` branch only" checked when creating the fork. Without that, it'll work fine.

Thanks @jwodder -- that did work indeed - closing this issue
