### ISSUE TITLE
encapsulate relevant information within local_docker_compose and avoid hardcoded or duplicate fixture specific info

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#172]
ATM `local_docker_compose` returns a dict with only `api_key`, then code hardcodes instance id (`local-docker-tests`). Ideally all that information should come from a fixture.

I also wonder if we could may be make a "test level" fixture which would use the "session level local_docker_compose" fixture so it could also make any test specific changes, such as  `monkeypatch.setenv("DANDI_API_KEY", local_docker_compose["api_key"])`?

All that to possibly make fixture replaceable or used (later) in parametrization of the test, and to avoid duplicate code within tests using the fixture.

**Comment by yarikoptic** [comment]
I also wondered if that fixture record should just populate all the desired fields for the services or just at least include `"intance"` key to avoid use of the current known_instances mapping from consts:

```
dandi/tests/test_register.py:from ..consts import dandiset_identifier_regex, known_instances, dandiset_metadata_file
dandi/tests/test_register.py:    dandi_instance = known_instances["local-docker-tests"]
dandi/tests/test_register.py:    dandi_instance = known_instances["local-docker-tests"]
dandi/tests/test_upload.py:from ..consts import collection_drafts, dandiset_metadata_file, known_instances
dandi/tests/test_upload.py:        known_instances[dandi_instance],
dandi/tests/test_upload.py:    client = girder.get_client(known_instances[dandi_instance].girder)
dandi/tests/test_upload.py:        known_instances[dandi_instance],
```

**Comment by jwodder** [comment]
@yarikoptic I'm not clear on what you're suggesting in your second post.  Are you saying the return value of `local_docker_compose` should include a `dandi_instance` instance?  If that change were made, would there be any need to keep the "local-docker-tests" entry in `known_instances`?

**Comment by yarikoptic** [comment]
> Are you saying the return value of `local_docker_compose` should include a `dandi_instance` instance?

yes, either as an `instance` key  or may be even making entire returned value into another named tuple based on `dandi_instance` keys + `api_key`.  Then underlying code could just use `local_docker_compose.girder` etc directly without needing to jump through `local_docker_compose["instance"].girder`?

> If that change were made, would there be any need to keep the "local-docker-tests" entry in known_instances?

I think it would be beneficial for "centralized knowledge" about possible instances... e.g. may be while debugging some tests we might want to run some commands (like `upload`) manually from the cmdline, so should be able to specify that instance on command line.  Fixture BTW should just use information from `consts` instead of hardcoding/duplicating `"http://localhost:8081/api/"` url.
