### ISSUE TITLE
register (Python API): move dandi_instance to the tail of options and default to "dandi"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#173]
similar to how was done for `upload`.

`instance` is more of a development option ATM, so definetely should not be the first and positional argument

**Comment by jwodder** [comment]
While we're making this change, should the Python API functions take the Dandi instance as a `dandi_instance` tuple or as a `known_instances` key?  Or should they accept both types, with `str` values looked up in `known_instances` automatically?

**Comment by yarikoptic** [comment]
I think we should 

- stick to a single type
- an instance name (as is now) would be the easiest to use for anyone using Python API, unless we run into a use case where we need to allow some arbitrary (unknown) instance configuration

Then underlying code could ask to map it to a tuple as the first step.  I like decorators, so there could even be `@map_dandi_instance` which would convert string kwarg value into a tuple and pass into underlying function.   I would leave it to you to decide if decorator is worth it (affects the stack possibly making harder to debug etc).
