### ISSUE TITLE
download: DANDI: "targets" to support

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#183]
> @mgrauer - this is not an acceptable value for the dandi prefix presently in `identifiers.org`, so we would either have to add that as an allowed regex or force people not to use identifiers.org for drafts. also it would be `/` not `:` for version information
> 
> `dandi download DANDI:000007/0.200714.1807` downloads this specific published version
> `dandi download DANDI:000007/draft` downloads the draft dandiset in its current form

I would also prefer here to use what is supported by/through `identifiers.org`.

Notes:
- I would also to be able to specify a path (to a subject or a specific file)
- There is a "convention" to use `@version` in a url to signal version.
  -  Used to be used by stackbrew to build official docker images, but I think they migrated away from that but some remain: e.g. https://github.com/docker-library/official-images/blob/4967c82e52fe02c24d5c585989fb24ac9eb25ba6/library/couchbase
  - DataLad uses it within URLs for RIA remotes, BUT carefully within a `#fragment` since IIRC `@` is not 100% kosher with allowed symbols in url ;)   But since here it is not a URL, I think it could be Ok

So I wondered if it could be `DANDI:<ID>[@<VERSION>][/PATH]` or `@` isn't good for identifiers?

Re "interactive" `> $ dandi download DANDI:000007` from @satra -- "not sure".  I expressed similar desires for more "interactive" within datalad, but somewhat agree (with Kyle) that for commands which by default are expected to be non-interactive, behavior should be explicitly described (e.g. download latest released version if no version specified), and only with explicit `--interactive|-i` they should offer choices.  Similar to what `git` does.  We aren't git here, but we do expect `dandi` to be used in CIs etc.

_Originally posted by @yarikoptic in https://github.com/dandi/dandi-cli/pull/134#issuecomment-669498120_

**Comment by yarikoptic** [comment]
Note to myself: `DANDI:000007/0.200714.1807` aligns better with persistent URLs ATM, so may be `@` idea is not worth it.  We could always to start using `DANDI:<ID>[/<VERSION>][//PATH]`

**Comment by yarikoptic** [comment]
so, @satra @mgrauer -- what do you think about `//`? ;-)

**Comment by satra** [comment]
let's start with the api side of this first (which is already there i think) and then we can come back to the gui/redirector side.

**Comment by yarikoptic** [comment]
Well, since API is there for released, it could have been implemented in client now without redirector etc... But I am ok to wait

**Comment by mgrauer** [comment]
Something like:

- an asset by giving its full path within the dandiset, e.g DANDI:ID/<VERSION>//<FULL_PATH_TO_ASSET>
- a folder within a dandiset, and everthing under that folder, e.g. DANDI:ID/<VERSION>//<FULL_PATH_TO_FOLDER>

Is that what you are thinking?

**Comment by yarikoptic** [comment]
Yes

**Comment by satra** [comment]
i would suggest single `/` so that it could also translate to a URL

**Comment by yarikoptic** [comment]
We have `dandi://` which already supports designed patters AFAIK:

```
$> dandi download --help | grep dandi:
   - dandi://<instance name>/<dandiset id>[@<version>][/<path>]
```
so let's close
