### ISSUE TITLE
DX: make pytest "pre-create" session level fixtures if it knows they would be needed

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#190]
ATM, running full tests sweep initiates `local_docker_compose_env` fixture when it gets to the first test which needs it (e.g. `test_lock_dandiset`).  But before then it runs a good number of tests which do not need it.  I thought that may be there is some setting or additional pytest plugin which would "initiate" session level fixtures while other tests are running since theoretically it could be done, and it could then speed up local runs of `pytest` considerably.

@jwodder - may be you know some way?

**Comment by jwodder** [comment]
I'm not aware of a way to do this, and either my google-fu is failing me right now or there is no way to do this.

**Comment by yarikoptic** [comment]
also asked on IRC and will report back if I hear affirmative yes/no/maybe-worth-implementing.
