### ISSUE TITLE
Upload tests are failing

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-cli#199]
Currently, when I run the test suite on my computer, two tests fail that didn't before: `test_upload` and `test_upload_existing_error`, both from `dandi/tests/test_upload.py`.  They appear to both be failing because the just-uploaded file can't be found on Girder.  This happens when testing commits 82e1820, f31e469, and bee7d50 (the 0.6.0 tag), the last two of which succeeded when initially run on GitHub Actions.  All tests were run using tox in a clean repository with the most recent versions of the Docker images.

My current hypothesis is that a dependency released a new version that broke something.

**Comment by jwodder** [comment]
It appears that the new release yesterday of pynwb is to blame.  Now, `dandi.pynwb_utils.validate()` fails to validate the NWB test data files, with output such as:

```
[VectorIndex/description (units/electrodes_index): argument missing, VectorIndex (units/electrodes_index): incorrect type - expected 'uint8', got 'int32', VectorIndex/description (units/electrodes_index): argument missing, VectorIndex (units/electrodes_index): incorrect type - expected 'uint8', got 'int32', VectorIndex/description (units/spike_times_index): argument missing, VectorIndex (units/spike_times_index): incorrect type - expected 'uint8', got 'int32']
```

**Comment by satra** [comment]
woah - the index types definitely look weird - surely indices can exceed 256? i'm not saying we need int32, having indices be unsigned is good. perhaps something to ping on the pynwb issue. i can't remember where the test files originally came from.

**Comment by jwodder** [comment]
@satra I took the test files used for testing uploads from [Dandiset 000006](https://gui.dandiarchive.org/#/dandiset/000006/draft).

**Comment by yarikoptic** [comment]
It is probably just a matter of pynwb and its schema got "fixed up" to use uint instead of int, those files which we use `sub-anm369963_ses-20170228.nwb` were produced with previous version... and in this case they are so old that produced with even older version which didn't cache schema inside the files I guess:

```
$> dandi ls dandi/**/sub-anm369963_ses-20170228.nwb | grep nwb
- path: dandi/tests/data/dandifiles/sub-anm369963/sub-anm369963_ses-20170228.nwb
  nwb_version: 2.0.2
```
for "permanent fix" we should just switch to using pre-populated dynamically by fixtures files (as WiP for #182) which would (better) be "compatible" with current pynwb  since they would be produced by it.

**Comment by jwodder** [comment]
@yarikoptic Wouldn't dynamically generated NWB files still need to be "organized" before uploading?  How can I generate them with the proper paths?

**Comment by yarikoptic** [comment]
You could call organize as party of the fixture - it shouldn't take too long. Or just run it outside on the file it produced,v and see what name it gives it, but IMHO it would be do in code since we might change organize later

**Comment by yarikoptic** [comment]
Probably would need to be add additional shim fixture in top of the one producing the file to start with - only upload ATM would really need organized file names

**Comment by jwodder** [comment]
I seem to have fixed the upload tests by creating the uploaded files in fixtures, but in the middle of that process, two more unrelated tests started failing:

```
_____________________________ test_parse_dandi_url _____________________________
dandi/tests/test_download.py:32: in test_parse_dandi_url
    assert _assert_parse_girder_url("DANDI:000027") == (
dandi/tests/test_download.py:17: in _assert_parse_girder_url
    st, s, a, aid = parse_dandi_url(url)
dandi/download.py:143: in parse
    return cls.parse(new_url)
dandi/download.py:148: in parse
    return cls.parse(new_url)
dandi/download.py:155: in parse
    raise RuntimeError(
E   RuntimeError: https://gui.dandiarchive.org/#/dandiset/000027 did not redirect to another location which dandi client would know how to handle.
________________________ test_parse_dandi_url_redirect _________________________
dandi/tests/test_download.py:124: in test_parse_dandi_url_redirect
    assert _assert_parse_girder_url("https://dandiarchive.org/dandiset/000003") 
== (
dandi/tests/test_download.py:17: in _assert_parse_girder_url
    st, s, a, aid = parse_dandi_url(url)
dandi/download.py:148: in parse
    return cls.parse(new_url)
dandi/download.py:155: in parse
    raise RuntimeError(
E   RuntimeError: https://gui.dandiarchive.org/#/dandiset/000003 did not redirect to another location which dandi client would know how to handle.
```

My first guess is that something changed on Dandiarchive's end, but there haven't been any changes to it today.

**Comment by yarikoptic** [comment]
Redirector had some changes iirc from slack... But also this url we redirected to them redirects to draft version by JS frontend which we can't follow... Can't check ATM what https://dandiarchive.org/dandiset/000003  right now? To specific version (draft or not) or defers it to web client to do (which IMHO it shouldn't)? If defers - IMHO needs fixing in redirector

**Comment by jwodder** [comment]
https://dandiarchive.org/dandiset/000003 is currently an HTTP redirect to https://gui.dandiarchive.org/#/dandiset/000003, which then appears to perform a JavaScript redirect to the same URL with `/draft` added to the end.

**Comment by satra** [comment]
there are a few places to get info:

https://girder.dandiarchive.org/api/v1/dandi/000027 --> draft info

https://publish.dandiarchive.org/api/dandisets/000003/versions/  --> count 0
https://publish.dandiarchive.org/api/dandisets/000027/versions/  --> count 1

https://publish.dandiarchive.org/api/dandisets/000027/versions/0.200721.2222/

currently the gui logic is, if there is a published version (i.e. count returned from publish api is greater than 0, then the latest version is returned, else draft is returned.

the CLI can implement this logic directly or we could include it in the redirector (but then we are getting the redirector to look like an api). i would rather see this evolve to be the api itself.

**Comment by yarikoptic** [comment]
Sure we could duplicate logic in the clients but IMHO it is very suboptimal.. Given that dandi cli is installed on clients, updating it for another change in behavior would again require announcement of minimal version for consistency etc. Also note that it is already a change in behavior  - test was passing before.
