### ISSUE TITLE
Issue downloading draft dandiset

### ISSUE THREAD

**Issue by jeromelecoq** [dandi/dandi-cli#202]
I was following the instruction on Dandi to create datasets and upload NWB files.
Here : https://www.dandiarchive.org/handbook/10_using_dandi/
 
Upon running the following command :
https://www.dandiarchive.org/handbook/10_using_dandi/
 
I came upon this error:
2020-08-18 01:22:40,751 [ WARNING] Failed to lookup girder information for drafts\000036
Error: Cannot download from https://dandiarchive.org/dandiset/000036/draft
 
Do you have a sense what is happening? I am working from a win 10 machine and at this point, I have not pushed any data up. Just started to create the draft version.

**Comment by jeromelecoq** [comment]
From satra:
hi jerome,

this looks like a windows issue. there is a weird backslash i am seeing in one of the warning statements above.

two things:

1. do you have the latest CLI, or did it warn that you are not using the latest version? if so, please upgrade:

pip install --upgrade dandi

to version 0.6.0

2. if you were using 0.6.0 could you please post this issue to: https://github.com/dandi/dandi-cli/issues together with the full output from the command.

we should be able to resolve this quickly, but need to know which version to better understand the context.

cheers,

satra

**Comment by jeromelecoq** [comment]
I was using a fresh install of the CLI so this is 0.6.0

**Comment by jeromelecoq** [comment]
from : Yaroslav
Smells like some Windows specific bug in paths etc handling.  Please
make sure you have 0.6.0 (or if later - a later version, we might
release a bugfix soon).  Unfortunately we have not setup automated
testing of upload from windows yet (docker compose invocation on github
actions was limited only to Linux systems)

A new dedicated issue against dandi-cli would indeed be
appreciated .

**Comment by jeromelecoq** [comment]
I guess I could try to run this from a linux machine

**Comment by jeromelecoq** [comment]
Oh, I am going to try to run this into a linux docker. You guys have containers of dandy?

**Comment by jeromelecoq** [comment]
Yes, the same command works under a ubuntu docker

**Comment by jeromelecoq** [comment]
In case that docker is any helpful. Here it is: https://hub.docker.com/r/245412653747/dandi-ubuntu
This should allow anyone to run dandi, regardless of the os.

**Comment by yarikoptic** [comment]
I kicked out 0.6.1 just now which includes merged #203, which at least according to tests should have addressed this issue.  Please reopen if it is not so.
