### ISSUE TITLE
"tox" run failing tests on Windows

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#213]
I am a proud user of a VM with Windows 7 and conda + pip installed dandi development environment...  Running `tox` resulted in:

```
====================================================================================== short test summary info =======================================================================================
FAILED dandi/support/tests/test_cache.py::test_memoize_path - OSError: [WinError 1314] A required privilege is not held by the client: 'file.dat' -> 'C:\\Users\\DataLad\\AppData\\Local\\Temp\\pyte...

FAILED dandi/support/tests/test_iterators.py::test_IteratorWithAggregation - assert False
FAILED dandi/tests/test_organize.py::test_organize_nwb_test_data[simulate] - assert 1 == 0
FAILED dandi/tests/test_organize.py::test_organize_nwb_test_data[symlink] - assert 1 == 0
FAILED dandi/tests/test_organize.py::test_organize_nwb_test_data[auto] - assert False
FAILED dandi/tests/test_organize.py::test_detect_link_type[True-True-symlink] - AssertionError: assert 'hardlink' == 'symlink'
FAILED dandi/tests/test_organize.py::test_detect_link_type[True-False-symlink] - AssertionError: assert 'copy' == 'symlink'
============================================================================== 7 failed, 56 passed, 9 skipped in 39.81s ==============================================================================
Exception ignored in: <ssl.SSLSocket fd=460, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.0.2.15', 51095), raddr=('3.19.164.171', 443)>
ResourceWarning: unclosed <ssl.SSLSocket fd=460, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.0.2.15', 51095), raddr=('3.19.164.171', 443)>
ERROR: InvocationError for command 'C:\Users\DataLad\PycharmProjects\dandi-cli\.tox\py3\Scripts\coverage.EXE' run -m pytest -v dandi (exited with code 1)
______________________________________________________________________________________________ summary _______________________________________________________________________________________________
  lint: commands succeeded
ERROR:   py3: commands failed

```

not sure why does not fail for us on Windows github CI runs.

**Comment by jwodder** [comment]
Looks like symlink permission issues.  The Windows environments used for GitHub Actions are presumably already configured to allow symlinks.

**Comment by yarikoptic** [comment]
right -- I was blind -- majority seems to be symlink related!  Didn't enable symlinking somewhat on "purpose" since not sure if users would have symlinking enabled, so better have most conservative environment. 
IMHO we should then just skip those tests (or portions of them, like in cache/memoize one) on file systems which do not allow symlinking. I do not remember what about the "simulate" run needing symlinks -- should be looked at.
I guess all of the above would resurface if tests are ran on some vfat file system (usb stick or loop device).  On linux following helper could streamline it: https://github.com/datalad/datalad/blob/master/tools/eval_under_testloopfs

**Comment by yarikoptic** [comment]
> 1. Shouldn't os.symlink(fname, symlink1) on line 145 be changed to os.symlink(path, symlink1)? path includes a directory component; fname does not.

I don't think so... just a relative (not an absolute path) symlink in the target (`path`) directory.

> 2. 

YES -- that is a bug -- Thank you for eyeballing it!!!

> Whether or not these changes are made, I believe the correct way to handle symlink failure on Windows in this snippet is to wrap line 145 in try: ... except OSError: pass.

yes -- please!

> If I'm correct, do you want these changes in their own PR or as part of the PR for this issue?

totally up to you!

**Comment by jwodder** [comment]
I already submitted the PR: #222
