### ISSUE TITLE
Python API: design

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#249]
Development prior this moment was targeting the command line client, and making it informative and "nice looking" to the users.  So some functionality (e.g. `ls`) still exists only as a "click" interface without underlying Python function.

Some, more recently added or refactored, interfaces did get proper Python functions (e.g. `download`) but they seems
  to provide neither "the best" (if any) return value Python coders would expect to receive, nor visual feedback to
    the users using those functions "interactive" in Python shell or more likely - jupyter shell or notebook.  E.g. in    Jupyter notebook ATM `download` reports only INFO message that it is about to traverse the dandiset, and then no visual output until it is done (#246), and `download` returns no value.
`validate` - is a generator which returns some (cryptic) records. 
`ls` - I think lacks any "pure Python" interface, and I guess others are not much better.

So it is time to harmonize Python interfaces and display produced by dandi commands.  Overall I think we should adopt
 DataLad's approach(es) which I mention below

### Functions vs generators

`download`, `upload`, `validate`, `ls`, `organize`: I think those should become/stay **generators** since they are
 intended to be ran for notable amount of time, so we better "update" outside code as soon as we know.

`register`: could be just a function since it just needs to return a single value.

### Returned values

We should make "returned" (yielded) values sensible for Python coding, in particular by default (i.e. without tuning  any options we might introduce).  In DataLad majority of commands now operate by returning "result records" and there is quite elaborate wrappers and invocation kwarg options which tune up returned values and behavior (datalad's `--on-failure {ignore,continue,stop}` e.g. to stop iterating as soon as first problem happened or not, etc) - it makes it flexible to compose multiple "interfaces" etc (but brings pains to debug at times; but here we will not have deep nesting of them).  In Python API DataLad's interfaces have 

```
result_xfm : {'datasets', 'successdatasets-or-none', 'paths', 'relpaths', 'metadata'} or callable or None, optional
  if given, each to-be-returned result status dictionary is passed to
  this callable, and its return value becomes the result instead. This
  is different from `result_filter`, as it can perform arbitrary
  transformation of the result value. This is mostly useful for top-
  level command invocations that need to provide the results in a
  particular format. Instead of a callable, a label for a pre-crafted
  result transformation can be given. [Default: None]
return_type : {'generator', 'list', 'item-or-list'}, optional
  return value behavior switch. If 'item-or-list' a single value is
  returned instead of a one-item return value list, or a list in case
  of multiple return values. `None` is return in case of an empty
  list. [Default: 'item-or-list']
```

where those kwarg default values can be interface specific.
That allows to make default returned value most convenient depending on how it is used (CLI vs Python API) and also
 to tune returned values (e.g. return full records vs just paths or some instance) where desired by outside code to
  react more specifically. Default returned values could be 

- `download` -  file path(s) (`item-or-list`) as they are downloaded (or skipped if was so requested with `existing=` option).  If any path fails to download - at the end of the `download` we would raise an exception like `IncompleteDownloadError` (subclass of `IncompleteResultsError` - we have that one in datalad too) which would include paths for all files we failed to download.

- `upload` - similarly yield paths of uploaded files

- `register` - it is ok as a default;  but underlying record could be as returned from the API (coming) server (and
 only may be additionally annotated with the server information).

#### Records

Actual underlying records may be very close if not identical to the records returned by the API (WiP).
So that unification might wait for API to stabilize a bit first, but meanwhile we could use records inspired by what
 datalad returns (see https://github.com/datalad/datalad/blob/master/datalad/interface/results.py#L46 (`get_status_dict`)) with fields `path`, `type` (typically a `file` but could be a `dandiset`), and `status`.  The rest would be command specific.

### Display

If dandi-cli is used as a Python library for code to be ran in a terminal, or used interactively within ipython shell -- currently used pyout renders things nicely for `upload`, `download`, and `ls` commands.  Other commands do not use it.
But as mentioned above (#246) -- rendering in jupyter notebooks which are widely used now is problematic ATM with pyout.
Most likely pyout will be fixed up (https://github.com/pyout/pyout/issues/120) for jupyter. But even then - we might want to provide simpler/leaner output for many such cases, and use pyout as the default one for CLI, while resorting to more basic display in any other case.  In particular, for use of dandi as underlying library by default no "fancy" output should be provided at all and we better just rely on the logger (which outside library can configure to its liking) to inform about progress of operations (e.g. for upload/download each 10% or each half-hour, whatever comes sooner, report overall progress (X (out of Y) files, A (out of B)TBs done) of operations.

ATM some commands provide options which affect "display format":
- `ls`: ` -f, --format [auto|pyout|json|json_pp|yaml]`
- `download`: `-f, --format [pyout|debug]` . With "debug" just printing those records it would have otherwise provide to `pyout` for rendering
- `upload`: has no configurable display format, but with `--devel-debug` in `DEVEL_DEBUG=1` mode it disables use of pyout
- `organize`, `register`, `validate`: no configurable display option. (`organize` has `--devel-debug` but that one just disables joblib.Parallel)

I think we should aim to harmonize it: if all functions could return structured records, then we could pretty much adopt the approach of datalad to have `dandi -f {default,pyout,json,json_pp,yaml,tailored,'<template>'},` with `default` possibly varying per command (e.g. tailored if present;).

# Implementation

Decouple display from 'implementation'. ATM `ls`, `upload` and `download` all rely on providing pyout records with  callbacks so it is for pyout to parallelize the invocation of callbacks.
IMHO we should get away from that: may be it would still be allowed for records to have callbacks assigned to a tuple of fields, or just get a dedicated  `"_callback"` key and rely on the callback to return a `dict` which we would use to fill out returned fields. 
Then a corresponding generic logic would be used to either serialize or parallelize those callbacks, and feed corresponding  "renderer" (YAML, JSON, PyOUT etc like pretty much is done in `cmd_ls`) with either only a final record (e.g. yaml, json etc) or an "update" (in case of PyOUT).
This would allow for a consistent implementation and control of parallelization for any renderer (not just parallelize for pyout).

NB parallelization is not solved for datalad internally yet either.  Situation is more complex though with all the "subdatasets" etc.

**Comment by satra** [comment]
we could also have a datasets module that fetches relevant dandisets similar to keras/scikit-learn

but we should also consider a dandiset object and an asset object that allows extraction of data and metadata and eventually hands of to pynwb or nibabel or other things.

**Comment by jwodder** [comment]
I've been writing up my own thoughts on a Python API [here](https://gist.github.com/jwodder/9b9c251cb1dafe1e7d66e53887739663) (work in progress).  The main points are that (a) the new API should be accessed via dedicated Dandiset, Version, and Asset classes instead of entirely though the client class, and (b) upload & download functions should come in sets of two or three: one version blocks until everything is complete, while the other versions are (a)synchronous iterators over progress data.

**Comment by yarikoptic** [comment]
THANK YOU @jwodder, I will try to digest your thoughts later on (if you think it is time).  Let me just note: I wonder if it is worth dealing with asyncio for our case: on one hand it makes total sense, but due to fiascos we keep discovering in datalad (e.g. impossibility to have[ async/sync/async nesting](https://bugs.python.org/issue33523#msg349561)) thus likely us needing to have/support two implementations: async + blocking + `iter_`, where `blocking` one could probably be just a helper on top of  `iter_` thus avoiding need for duplicated implementations.

**Comment by jwodder** [comment]
On the OP, my only comment at the moment is that I dislike the idea of a function that returns its results as a generator, list, or scalar depending on a parameter.  Such a function would be better off always returning a generator, and then functions that wrap that function to return other types can be added depending on how useful or complex they are.

**Comment by jwodder** [comment]
On the topic of functions returning structured records that can then be fed to various formatters:
* The iterable download & upload functions (and possibly also the organize function) should return iterators of formattable records, which can then be fed to a formatter for display.
* For listing assets, normal listing of assets (returning `Asset`/`LocalAsset` objects) should be done through `Version.get_all_assets()`, `LocalDandiset.iter_assets()`, and the like.  Emulating the display of the `dandi ls` command should be done through an `ls()` function that wraps these methods and returns an iterator of formattable records.

**Comment by yarikoptic** [comment]
Agree on returns.  Not sure about `Version` -- is that a versioned `Dandiset`? I would have just made any `Dandiset` versioned (even if only just with a `"draft"` or better even `None`  version)

**Comment by jwodder** [comment]
@yarikoptic `Version` is here a version of a Dandiset retrieved from the API.  A Dandiset and its versions are different types of resources with their own fields (especially as far as the Django API is concerned) and thus should be represented by different classes.

**Comment by yarikoptic** [comment]
So relates to https://github.com/dandi/dandi-cli/issues/236 I guess.

**Comment by yarikoptic** [comment]
Although I see it nice to have Python API to "parallel" web API, I am not sure if making Python API parallel web API  too closely would make Python API a victim if web API changes, and just make Python API a bit odd to use while working solely in Python. And as far as I see it, you already "broke" (which is not a bad thing, per above) such a "parallel".  E.g. return structures of web API are heavily inflicted by underlying design/tables: e.g. `Version.identifier` you envisioned (and which is reasonable to have if `Version` is a "version of a dandiset") already needs to be "proxied" from the underlying `.dandiset.identifier` (and that is pretty much so in every data structure since API returns "dandiset" record in all similar cases). (May be that underlying rudimentary dandiset record could be a `BareDandiset`, and hide in `._bare_dandiset`, or alike if we need a structure/type?).

Also, whenever API has the composition of "dandiset + version" reflected in the query URL, we would not have that in Python API, and for a user seeing a `Version` object would be odd.  So am "Luke warm" about a bare (in name) `Version`. In the API the notion of a "dandiset" (table)  is somewhat of a "Dandiset Entity" or "Dandiset Versions" -- it is where all the versions of the particular dandiset reside. From a user perspective the `Version` is actually a specific versioned (even if it is a draft) Dandiset.  So I wonder if we should make it `DandisetVersions` (for what is `Dandiset` in your gist) and then a `Dandiset` (and `DraftDandiset`) for `Version` (and corresponding `DraftVersion`)? (note: there is no need for `Version.dandiset` if I see it right since `.identifier` should indeed be proxied up, although may be internally keep that `._bare_dandiset` record?).

Then proposed methods could reflect that and provide high(er) level constructs, e.g. proposed
```python
create_dandiset(name: str, metadata: DandiMeta) -> Dandiset
```
would become
```python
create_dandiset(name: str, metadata: DandiMeta) -> DraftDandiset
```
making a ready to be interacted with `DraftDandiset` (not just some top level dandisets table record).  And retain `get_dandiset(version: str)` to return a `Dandiset` (or DraftDandiset if `version=='draft'`), again as to provide users with an easy to use Python API to address their use cases.

WDYT @jwodder?  altogether -- I think you are on the right track and it would be great to see it implemented, and we could tune going forward.

**Comment by jwodder** [comment]
@yarikoptic For the record, `Version.identifier` is meant to be the version's `version_id`/"version" field, not the Dandiset ID (which would be retrieved through `Version.dandiset.identifier`).

I'm theoretically fine with renaming `Dandiset` and `Version` to `DandisetVersions` (or similar) and `Dandiset`, though I feel that might lead to some confusing or conflicting names elsewhere; do `dandiset_id` and `version_id` become `dandiset_versions_id` and `dandiset_id`?  Would we now have a `get_dandiset_versions()` method that returned a single object despite having a plural name?  What would we call the method for getting all `DandisetVersions`es?

> I am not sure if making Python API parallel web API too closely would make Python API a victim if web API changes

Currently, the client class already parallels the API in its methods, but without any Python-level guarantees about the structure of return values.  If the web API changes, code is going to change no matter what:

* Adding, removing, & renaming endpoints is about the same amount of effort the OO way and the God Class way.
* If the structure of the objects returned by the API changes, classes would still be able to maintain their interfaces through properties and the like.  If we stuck with just returning dicts from the client class instead, we'd need functions to completely rearrange the dicts into their old forms in order to avoid breaking any calling code.
* If the API completely changes its resource types from dandiset+version+asset to something else, the code would need massive rewrites either way.

**Comment by yarikoptic** [comment]
> For the record, `Version.identifier` is meant to be the version's `version_id`/"version" field

do you mean the "published version", like `0.210225.1423` now?

**Comment by jwodder** [comment]
@yarikoptic Right, or "draft" for draft versions.

**Comment by yarikoptic** [comment]
May be my brain is too "git rotten" but making parallels to it instead of the API internal design make more sense to me and I think would be easier for users.  What about melding current `Version` to become an inherent property of a `Dandiset` and adding ability to "switch" versions?  Names can change, but I decided to make the base class named `Dandiset` to signal that any `.get_dandiset` (or `.dandiset`) would return a `Dandiset` (or its subclass).

So what about the following:

- `Version` -- just that, the information about version with `.identifier: str`, `.created: date`, without back-referencing the dandiset itself. Largely to be used as an argument to specify desired version. (we might later expand it with `.description` to provide release description, etc. so should not succumb to make it just a str probably)
- `Dandiset` - the base/interface class. Defines abstract `.identifier`, `.created`, `.modified`, `version: Version`, `.get_*assets`, `get_metadata`
   - `RemoteDandiset(Dandiset)` - what the `Version` is now; does not have any `.dandiset`, but gets `.api_server` (for direct interactions with the server via its API interface), and  `get_versions: Iterator[Version]`, `get_version(Union[str, Version]) -> Union[RemoteDandiset, DraftDandiset])`, `get_asset_by_uuid` (not provided by `LocalDandiset`)
       - `DraftDandiset(RemoteDandiset)` - gains all the "mutator" methods + `publish`.    `.version == "draft"`
   - `LocalDandiset(Dandiset)` - it might as well have a `.version` if its `dandiset.yaml` contains one. Assets will be `BareAsset`s
      - `DataLadDandiset(LocalDandiset)` - would get closer to `Dandiset` in being able to switch versions etc (we might want to define some mixin interface class even at some point), while otherwise delegating the rest to `.dataset: datalad.Dataset`

PS
- may be we should rename in metadata `BareAssetMeta`, `AssetMeta` -> `AssetMeta`, `RemoteAssetMeta` to make a parallel?
- If we did not use "Publish" as "Release" (version a published instance, make it immutable), then we could have made a better parallel to Datalad where `publish` == `push` or "make it public" (not just local).  Then `Remote` above for a Dandiset or Asset could be `Published` which would be more harmonious. `PublishedAsset` would get its `contentUrl`, `uuid` etc.

**Comment by jwodder** [comment]
@yarikoptic Looks like a good idea.

**Comment by jwodder** [comment]
@yarikoptic I've revised [the gist](https://gist.github.com/jwodder/9b9c251cb1dafe1e7d66e53887739663) with your suggestions and further changes & details.  Should I move this to [the repository wiki](https://github.com/dandi/dandi-cli/wiki) so that you can edit it as well?

**Comment by yarikoptic** [comment]
What about a PR with that file eg under `doc/design/python-api-1.md` - that probably would make it easier to comment/discuss/refine?

**Comment by jwodder** [comment]
@yarikoptic PR: https://github.com/dandi/dandi-cli/pull/447

**Comment by yarikoptic** [comment]
we have current design, no point to keep this issue open
