### ISSUE TITLE
Update for h5py v3.0

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-cli#259]
Version 3.0 of h5py (a dependency of pynwb) was released on October 30, and it brought with it [changes to its string handling](https://docs.h5py.org/en/stable/strings.html) that make several tests (e.g., `dandi/tests/test_pynwb_utils.py::test_get_metadata`) fail.  For now, I have added `h5py ~= 2.9` to dandi-cli's dependencies so that the new version won't be installed alongside it, but at some point we need to update for the new library version.

**Comment by yarikoptic** [comment]
is it feasible to make test (or code) work with both 2.x and 3.x?

**Comment by jwodder** [comment]
@yarikoptic Probably, though at the moment I'm still unsure how just to update for 3.x given that we're using h5py through pynwb, which hasn't updated for the new h5py yet.

**Comment by yarikoptic** [comment]
gotcha, thanks!  I just shouldn't forget to adjust dependencies in conda package when I update it
