### ISSUE TITLE
Re-upload fails on final step

### ISSUE THREAD

**Issue by CodyCBakerPhD** [dandi/dandi-cli#262]
I'm trying to re-upload [dandiset ID 000003](https://gui.dandiarchive.org/#/dandiset/000003/draft), and validation/organization runs fine on the subset of files I currently want to re-upload, but upon attempting the `dandi upload` command, I encounter this error

`Error: Failed to create the collection: Prompt dismissed..`

I am also unable to find the location of this generic error in the repo - any ideas on how to isolate the issue and fix it?

I suspect it may have something to do with the fact that this is not an upload to a new dandiset, but rather a re-upload to update and correct the data currently on DANDI, as I've uploaded other dandisets from scratch without encountering this issue. To that extent, it is worth mentioning that this error is triggered even if I attempt to upload a file that is not currently on that dandiset, not just if I attempt to upload a source file of the same name as one currently on the set.

**Comment by yarikoptic** [comment]
sorry about that. My [memory supplement](https://github.com/dandi/dandi-cli/search?q=Error%3A+Failed+to+create+the+collection%3A+Prompt+dismissed.) suggests that it is something new. 

I have tried to replicate quickly with
```
35858  dandi download DANDI:000029
35859  cd 000029
35861  dandi download https://girder.dandiarchive.org/api/v1/item/5e70d3103da50caa9adaf30e/download
35864  dandi organize -f move sub-anm372793_ses-20170504.nwb
35867  dandi upload --validation ignore
```
and it seemed to be Ok.  So we might need your help indeed to figure out WTF

- make sure that `dandi-cli` is uptodate (today was a release 0.7.0)
- run `DANDI_DEVEL=1 dandi --pdb upload --devel-debug ...` and you (if we are lucky ;-)) should end up in `pdb` right at the point of the exception (or somewhere where it was intercepted if we are not so lucky)

**Comment by CodyCBakerPhD** [comment]
Thanks @yarikoptic,

a) It's a fresh install of DANDI as of today (on smaug, no less)
b) Running that did indeed find... something (?) the traces back to where this occurs. Attaching screenshots of this

![image](https://user-images.githubusercontent.com/51133164/98170447-031f4d00-1ebc-11eb-8993-47c6e4240d63.png)
![image](https://user-images.githubusercontent.com/51133164/98170481-116d6900-1ebc-11eb-9331-38f215e85b32.png)

**Comment by yarikoptic** [comment]
ha ha -- "collection" is too popular of a word.  I thought initially that the error message is about girder's collection.  Apparently it is secretservice complaining!  
We should streamline this: Since on smaug you have a non-desktop environment, there is no default "keyring backend" and keyring seems to not care to create one for you in such case.  As a workaround for now, try this : https://github.com/datalad/datalad/wiki/FAQ#how-to-configure-insecure-local-credentials-store

**Comment by CodyCBakerPhD** [comment]
@yarikoptic Success! With the caveat that in order to work with that 'version' of keyring, it complains that it needs to be in `~/.config/python_keyring/keyringrc.cfg` instead of `~/.local/share/python_keyring/keyringrc.cfg`
