### ISSUE TITLE
Establish some local keyring store if there is no default one available

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#263]
We use keyring (as well as we do in datalad).  That one by default considers the desktop's (be it a Mac, Gnome, whatever) credential store, but falls short if session is pure terminal session.  See https://github.com/dandi/dandi-cli/issues/262#issuecomment-721988907 .

What I think we should do (instead of just `get_password`)
- check with keyring if credential store(s) available.
- if not: ask user either we should establish one local in his/her account.  https://github.com/datalad/datalad/wiki/FAQ#how-to-configure-insecure-local-credentials-store provides howto for a simple insecure one but we could give an option to make it secure (protected by passphrase) -- I believe keyring allows for that.
- if yes and multiple: if we have that one explicitly created, it should be used instead probably or may be we could check if password available in any (unless keyring does it automagically)?

**Comment by jwodder** [comment]
> check with keyring if credential store(s) available.

There does not appear to be a way to check what backends are useable without making a query to each & every one in turn, which (I think) would involve the user being prompted for decryption passwords and the like for each & every one of them.

**Comment by yarikoptic** [comment]
well, if something prompts that means that the backend is available, but if it raises InitError or alike -- means that it is not... if we get to the end of the loop without any available, we need to make a new one.  Or you see scenario where such logic would be flawed?

**Comment by jwodder** [comment]
@yarikoptic So the flow you're proposing is:

* Query each available keyring backend
    * If it errors, go to the next one.
    * Maybe: If it doesn't contain a password for the given service & username, go to the next one.
* If none of the backends are suitable, ask the user whether we can use an encrypted file as the backend (`keyrings.alt.file.EncryptedKeyring` seems to be the candidate for this).

If we continue on when a candidate backend doesn't contain a password for us, this will lead to users being prompted about permission or credentials for multiple different backends (and there isn't a way to test whether a user's been prompted in such a way).  If we *don't* continue on, then we will always find a backend (as the PlaintextKeyring backend — and possibly others — is always available while `keyrings.alt` is installed) and we won't end up asking the user about setting up a backend that they very well might have never used before.

**Comment by yarikoptic** [comment]
Thanks for the analysis! What about following (in pseudo-python code) so we do not sweep backends?
```python
try:
    return keyring.get_password(...)
except keyring.errors.InitError as exc:
    if check_if_encrypted_keyring_available():
         lgr.info("Default keyring is not available, but encrypted keyring found. Original error: %s", exc)
         return encrypted_keyring.get_password(...)
    if ask("Default keyring is not available.  Would you like to establish an encryptedkeyring? Original error: %s", exc):
         establish_encrypted_keyring()
         return encrypted_keyring.get_password(...)
    raise exc
```

**Comment by yarikoptic** [comment]
BTW, in DataLad we have a home-brewed support for centralizing UIs, e.g. https://github.com/datalad/datalad/blob/master/datalad/ui/dialog.py#L178 for interactive.  I wonder if you might know some or we could/should adopt that one here?

**Comment by jwodder** [comment]
@yarikoptic That works if by "check if encrypted keyring available" you mean something like "check whether the file used by `EncryptedKeyring` to store secrets already exists."

(When I mentioned "available" backends in my last comment, I meant backends whose classes could be instantiated without error, which basically means backends for which the necessary dependency libraries are already installed.  By that definition, a backend that's not available can't be established without installing libraries, which I don't think dandi should be doing.)

One additional wrinkle: The `keyring` library lets a user specify a specific backend via either an environment variable or a `keyringrc.cfg` file, and only if neither of those are set does it fall back to looking up all backends.  I think we should do likewise, and furthermore, I think that if an explicitly-specified backend errors on a query, we should consider it the user's fault and not try to set up an encrypted backend.

Speaking of `keyringrc.cfg`, I got the implication from the initial post in this issue that you wanted `keyringrc.cfg` to be configured to specify `EncryptedKeyring` in the event an `EncryptedKeyring` was created.  Do you want that to happen or not?

**Comment by yarikoptic** [comment]
Can we know if failed backend was explicitly specified via config or env var?   if so, then we indeed should not do anything and just fail if explicitly specified was used.  If it was not explicitly specified -- then yes, lets create one, and explicitly specify in `keyringrc.cfg` on user's behalf (and inform user about that).

**Comment by jwodder** [comment]
> Can we know if failed backend was explicitly specified via config or env var?

Effectively, yes.  I can retrieve the explicitly-specified backend and, if it's non-`None`, use that, otherwise continue with the default backend.

**Comment by yarikoptic** [comment]
sounds good, thank you!
