### ISSUE TITLE
github workflow to mint .json rendering of the schema and populate dandi/schema

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#273]
Should be published to https://github.com/dandi/schema/tree/master/releases/ - https://github.com/dandi/schema/blob/master/scripts/makeRelease.py is the original script used to produce those (and remove it from that repo)

- should be triggered only upon merge, ie. whenever PR which merges any models related stuff is merged and either modify already existing "released" file or create a new directory for a release based on the schema version

- Since we are in rapid development I do not think it is worth breeding new rc for minor changes, so it will be at our discretion to either boost it or not

**Comment by jwodder** [comment]
@yarikoptic 
* To be clear, the generated JSON files should be stored in the `releases/` subdirectory with the same name as the default value for `CommonModel.schemaVersion`, correct?
* Should dandi/schema be updated via a pull request or by pushing directly to master?
* This will require a secret containing a GitHub token with permission to write to dandi/schema.

**Comment by yarikoptic** [comment]
> * To be clear, the generated JSON files should be stored in the `releases/` subdirectory with the same name as the default value for `CommonModel.schemaVersion`, correct?

correct. 

> * Should dandi/schema be updated via a pull request or by pushing directly to master?

I was thinking about a PR (could allow @AlmightyYakob to verify correct operation, but then we came up with the committish url as a "more specific" version which should be sufficient), but decided not to bother: we might add it later though ( so we could run that web form unittests etc, that is why I asked actually).  Commit message for the change should just list output of `git describe` here which introduced the change.

> * This will require a secret containing a GitHub token with permission to write to dandi/schema.

I will add `DANDI_GITHUB_TOKEN` secret.

**Comment by yarikoptic** [comment]
done, minted one in @dandibot account... 
apparently it is made an owner of the entire dandi organization.  Is that really necessary @satra for something?  IMHO bots etc should have more granular/as restricted as possible access - would be hard to blame anyone specifically :-)

**Comment by satra** [comment]
@yarikoptic - i made dandibot a member. now let's see what breaks!

**Comment by yarikoptic** [comment]
gy gy.  I have added him with write permissions for https://github.com/dandi/schema/
