### ISSUE TITLE
RF DandiAPIClient et al to use new WiP API

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#277]
Haven't looked yet either prior server is anyhow accessible at all, if not -- we can just migrate `master` to use what is coming to be provided https://github.com/dandi/dandi-api/ .
- [ ] RF DandiAPIClient
- [ ] RF tests fixture from installing old server to install this new one
- [ ] Implement `upload` using API (not girder)
     - If we are to do it straight in master -- RF `upload` so depending on the target server, it would either upload to girder or to API 
- [ ] ...

Eventually (after we test and migrate over to the new "API" server from girder)
- [ ] RM fixture/functionality interfacing girder altogether

**Comment by jwodder** [comment]
@yarikoptic What's the canonical location for the documentation for the new API?

**Comment by yarikoptic** [comment]
https://api.dandiarchive.org/swagger would be the "documentation" ATM besides that actual code ;)  it should be close if not identical to that API google doc document we had been working on (let me know if you can't locate it)

**Comment by jwodder** [comment]
@yarikoptic 
* What structure is required for the return value of `DandiAPIClient.get_dandiset()`?  The new API currently does not include the normal Dandiset metadata in its responses.
* For the first step, exactly what refactoring is required beyond using the new endpoints (and proper pagination)?

**Comment by jwodder** [comment]
@yarikoptic Can you set up builds on Docker Hub of [this Dockerfile](https://github.com/dandi/dandi-api/blob/master/dev/django-public.Dockerfile) under the name `dandiarchive/dandiarchive-api`?  When I try to do it, after selecting the "dandi" GitHub organization, the repository drop-down becomes greyed out.  This happens in both Safari and Firefox.

**Comment by jwodder** [comment]
@yarikoptic Is there a description of the upload workflow that matches what Swagger shows?  It looks like uploaders are supposed to:

* POST the file name & size to `/uploads/initialize/` and get back some keys and a list of how large each part should be and what URL to upload each one to (which strikes me as a very ... odd design)
* Upload each part to the respective URLs
* Collect ETags for the parts somehow?
* POST the keys and a list of each piece's size and ETag to `/uploads/complete/`
* At some point, POST to `/uploads/validate/` to make the server validate the asset's hash
* Wait for the validation to complete?

**Comment by yarikoptic** [comment]
> What structure is required for the return value of DandiAPIClient.get_dandiset()? The new API currently does not include the normal Dandiset metadata in its responses.
> For the first step, exactly what refactoring is required beyond using the new endpoints (and proper pagination)?

to be able to download/upload/ls -- those common operations which we provided for previous girder and "publish" mix, but now could all go through DANDI API for both drafts and "released" versions

**Comment by yarikoptic** [comment]
re upload: I will try to get a better sense of it as well tomorrow to comment on.  We might need to at least tune up API implementation right away to make initial initialization of upload endpoint closer to what we envisioned already etc, while "naming" this particular upload mechanism as "s3-multipart" or alike so (as we had "provisioned" for various in the initial API sketch document) we could keep the door open for other mechanisms (like later we might have `"s3-copy"`, to just perform copy within bucket from old store to new; or "s3-simple" which would not bother with multipart; be or later "dropbox"/... to download content from dropbox/... etc)

**Comment by yarikoptic** [comment]
Re upload, FWIW here is a workflow summary from @dchiquit 

```
Since it's not really obvious from the swagger page, this is the flow uploads should use if you're trying to implement upload from dandi-cli:
1. POST /uploads/validate/{sha256}/ - Don't supply object_key, since you don't know it yet. This checks if the blob already exists. If it does, skip to step 5. If it fails, you gotta upload
2. POST /uploads/initialize - give it the info on your file, it will return a list of URLs and sizes you can use to upload the parts. Keep track of the ETag header on the responses.
3. POST /uploads/finalize - give this the ETags you uploaded and it will give you a URL you can use to finalize the object.
4. POST /uploads/validations/ - Give it the object_key of the uploaded object and sha256 and it will run a validation. Right now this is a no-op that takes 10s to complete, just for testing.
5. GET /uploads/validations/{sha256}/ - check on the progress of the validation
6. POST /dandisets/{version__dandiset__pk}/versions/{version__version}/assets/ - Create the object. This checks that the validation has succeeded.
```

**Comment by jwodder** [comment]
@dchiquit 
> 1. POST /uploads/validate/{sha256}/

There's no such endpoint listed on the Swagger page.  Did you mean `GET /uploads/validations/{sha256}/`?  The docs for that endpoint have no mention of an `object_key`.

* Should the file name posted to `/uploads/initialize/` be just the basename of the file, or should the directory name (e.g., "sub-P10HMH") be included?  Or should the latter only be used for the "path" key in step 6?

* I assume that by `POST /uploads/finalize` and `POST /uploads/validations/` you mean `POST /uploads/complete/` and `POST /uploads/validate/`.

* What should be included in the metadata posted for the asset in step 6?

**Comment by dchiquit** [comment]
Excellent questions.
* I meant `POST /uploads/validate/`, which does have the correct documentation regarding `object_key`. That begins the validation process which can be checked on with `GET /uploads/validations/{sha256}/`.
* The behavior of `file_name` in `/uploads/initialize/` is still not quite fully implemented. No matter what you call it, it will be referenced by it's sha256 checksum, so in some sense it's arbitrary. The only thing it's used for is determining the name of the S3 object, so I guess use the full path to avoid collisions.
  The "real" path of the blob in the dandiset is set when you register the asset.
* You are correct, I got mixed up.
* That is the metadata of the file in the dandiset. My understanding is that there is dandiset level metadata and asset level metadata, so that metadata would describe the content of that NWB file.

**Comment by jwodder** [comment]
@dchiquit So when the POST request is made to `/uploads/validate/`, how does the client determine whether the blob already exists?  The endpoint doesn't return any data.  Am I expected to also make a request to `GET /uploads/validations/{sha256}/` before uploading anything?

> POST /uploads/finalize - give this the ETags you uploaded and it will give you a URL you can use to finalize the object.

What exactly do I do with this URL?  Just make an empty POST request?

**Comment by dchiquit** [comment]
Before uploading anything, you should do a `GET /uploads/validate/` with the sha256 of the data you would be uploading. If it fails, that data hasn't been uploaded yet, so you need to upload it. If it succeeds, you can skip uploading. There should be more docs for response codes #288 

I got that endpoint mixed up with `POST /uploads/complete/`. After you have uploaded the actual data to S3, you still need to confirm with S3 that you are finished and want to create the object. `POST /uploads/complete/` does describe the data you need to include; the most important thing is the `ETag` for each part you uploaded, which can be found in a special `ETag` header in the response from S3. `POST /uploads/complete/` returns another presigned URL that you need to visit.

**Comment by jwodder** [comment]
@dchiquit 

> POST /uploads/complete/ returns another presigned URL that you need to visit.

That's the URL that I was asking about.  Do I make a GET or a POST to this "presigned URL"?

**Comment by dchiquit** [comment]
`POST`. This is the operation that is being presigned: https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html

**Comment by jwodder** [comment]
@dchiquit How do I authenticate with the new API?  I'm working with a Docker Compose environment in which a superuser is created in the Django container with `./manage.py createsuperuser`, but querying http://localhost:8000/api/auth/token/ with the username & password used in the createsuperuser command returns "Invalid username/password."  I also tried setting the Authorization header to "bearer {token}", where the token is obtained from `./manage.py drf_create_token`, but that resulted in the error "Authentication credentials were not provided."

**Comment by dchiquit** [comment]
I generate mine by logging into the swagger page at http://localhost:8000/swagger/, clicking `Django Login`, logging in with superuser credentials, then using the swagger page to call `GET /auth/token/`.
Running `./manage.py drf_create_token` generates the same token for me, so I think your problem is specifying the token in the request. The header should be formatted as `Authorization: Token e9d103cdb6bb1907a501282ac02b3d5265dac487`, not 'bearer'. This is a curl that works for me:
```
curl -X POST "http://localhost:8000/api/auth/token/" -H  "accept: application/json" -H "Authorization: Token e9d103cdb6bb1907a501282ac02b3d5265dac487"
```

**Comment by jwodder** [comment]
@dchiquit Your explanations of the validation endpoints are inconsistent and keep conflicting with the endpoints listed [here](https://api.dandiarchive.org/swagger/).  Exactly what validation-related API requests do I make before starting an upload, what are the possible status codes of the responses, and what should I do based on those status codes?

Is it:

1. `POST /uploads/validate/`, which should always succeed, followed by `GET /uploads/validation/{sha256}/`, which fails if & only if the blob is unknown to the server (i.e., if & only if the client should go through with the upload), or ...

2. Just `POST /uploads/validate/`, which fails if & only if the blob is unknown to the server (i.e., if & only if the client should go through with the upload)

Additionally, once the upload is complete, what requests does the client make to the validation endpoints to ensure that the validation completes?  Does this differ from the requests that would be made if there were no upload?

**Comment by dchiquit** [comment]
Option 2) is correct. `POST /uploads/validate/` tries to start an asynchronous task to do the validation. If anything would prevent that from happening, like the object not existing in S3, it will return a 400. To avoid unnecessary uploading, you can call `POST /uploads/validate/` without an `object_key`. if an object with that checksum has been validated before, it will look up the object key used in the previous validation and use it to start a new validation; if that checksum is unrecognized, it will fail. `GET /uploads/validation/{sha256}/` returns the state of the asynchronous vaidation task.

Once `POST /uploads/validate/` has returned 204, calling `GET /uploads/validation/{sha256}/` will return the current state of the validation as a JSON blob. There is a field called `state` (poorly named, sorry) that is one of `"IN_PROGRESS"`, `"SUCCEEDED"`, or `"FAILED"`. The client needs to keep calling `GET /uploads/validation/{sha256}/` until the state is no longer `IN_PROGRESS`.

**Comment by jwodder** [comment]
@dchiquit OK, now that I'm actually uploading, the response to the first (and only?) chunk is:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>testing/simple1.nwb</Key><BucketName>dandi-dandisets</BucketName><Resource>/dandi-dandisets/testing/simple1.nwb</Resource><RequestId>164CF40A1086394C</RequestId><HostId>3b7230f2-2264-4096-83bd-89ea2c3552f3</HostId></Error>
```

I'm quite certain I'm calculating the hash and uploading the exact piece correctly.

**Comment by dchiquit** [comment]
Perhaps you are using POST instead of PUT? This is the operation that is being performed: https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPart.html

Here's a code snippet I pieced together from our test suite that uploads a file:
```

def initialize_upload(filename):
    print(f'Initializing upload of {filename}...')
    filesize = os.path.getsize(filename)
    resp = requests.post(
        f'{URL_ROOT}/api/uploads/initialize/',
        headers={'Authorization': f'Token {AUTH_TOKEN}'},
        json={'file_name': filename, 'file_size': filesize},
    )
    assert resp.status_code == 200
    return resp.json()


def complete_upload(object_key, upload_id, transferred_parts):
    print('Presigning upload completion...')
    resp = requests.post(
        f'{URL_ROOT}/api/uploads/complete/',
        headers={'Authorization': f'Token {AUTH_TOKEN}'},
        json={
            'object_key': object_key,
            'upload_id': upload_id,
            'parts': transferred_parts,
        },
    )
    assert resp.status_code == 200
    return resp.json()


def upload(filename):
    initialization = initialize_upload(filename)
    object_key = initialization['object_key']
    upload_id = initialization['upload_id']
    parts = initialization['parts']

    transferred_parts = []
    part_number = 1
    with open(filename, 'rb') as f:
        for part in parts:
            print(f'Uploading part {part_number}...')
            data = f.read(part['size'])
            part_transfer = requests.put(part['upload_url'], data=data)
            etag = part_transfer.headers['etag']
            transferred_parts.append(
                {'part_number': part_number, 'size': part['size'], 'etag': etag}
            )
            part_number += 1

    completion = complete_upload(object_key, upload_id, transferred_parts)

    print('Completing upload...')
    completion_response = requests.post(completion['complete_url'], data=completion['body'])

    return object_key
```

I can find examples for the rest of the flow as well if that would be easier than this back and forth.

**Comment by jwodder** [comment]
@dchiquit OK, now when I do `POST /uploads/validate/` after completing the upload in order to validate the blob, I get a 400 response.  If you have a code sample that addresses this part of the flow, I'd be glad to see it.

**Comment by dchiquit** [comment]
```

def wait_for_validation(sha256):
    print(f'Waiting for blob {sha256} to finish validating...')
    state = None
    while state != 'SUCCEEDED':
        time.sleep(1)
        resp = requests.get(
            f'{URL_ROOT}/api/uploads/validations/{sha256}/',
            headers={'Authorization': f'Token {AUTH_TOKEN}'},
        )
        state = resp.json()['state']
        if state == 'FAILED':
            raise Exception('Validation failed.')


def validate_existing_blob(sha256):
    print(f'Attempting to validate a blob with checksum {sha256}...')
    resp = requests.post(
        f'{URL_ROOT}/api/uploads/validate/',
        headers={'Authorization': f'Token {AUTH_TOKEN}'},
        json={'sha256': sha256},
    )
    if resp.status_code == 204:
        wait_for_validation(sha256)
    elif resp.status_code == 400:
        print('No validation found for that blob.')
        raise ObjectIsNotUploaded() # This is a special exception to indicate that the blob needs to be uploaded
    else:
        raise Exception(f'Unknown response status code {resp.status_code}.')


def validate_uploaded_blob(sha256, object_key):
    print(f'Validating a newly uploaded blob {object_key} with checksum {sha256}...')
    resp = requests.post(
        f'{URL_ROOT}/api/uploads/validate/',
        headers={'Authorization': f'Token {AUTH_TOKEN}'},
        json={'sha256': sha256, 'object_key': object_key},
    )
    if resp.status_code == 204:
        wait_for_validation(sha256)
    else:
        raise Exception(f'Unknown response status code {resp.status_code}.')

```

**Comment by dchiquit** [comment]
Also, 400 responses should also include useful error messages in the response body. I cannot make the same promise for 500 errors though.

**Comment by jwodder** [comment]
@dchiquit That code was helpful, but now my code has been polling `/uploads/validations/{sha256}/` for more than ten minutes without the state changing from `IN_PROGRESS`.  I don't think validating a 17KB file should take that long.

**Comment by dchiquit** [comment]
I agree, it should only be calculating the checksum of the file and verifying that it matches. FWIW I have verified that very small files work correctly. I will look in to that behavior.

**Comment by dchiquit** [comment]
I just verified uploads of around that size work correctly locally and on api.dandiarchive.org. The most likely cause is that you aren't running celery, which is what runs the asynchronous task. I'm not 100% confident in the docker compose file if that's what you're using, so I will verify that it's working correctly later today.

**Comment by jwodder** [comment]
@dchiquit [This](https://github.com/dandi/dandi-cli/blob/gh-277/dandi/tests/data/dandiarchive-docker/docker-compose.yml) is the Docker Compose file I'm using.  Both the django and celery containers are brought up towards the end of the startup process, and Celery seems to be running fine.

**Comment by dchiquit** [comment]
The problem is that the validation task has to download the data from the object store, but cannot because of some unfortunate docker-compose networking quirks.
When the `celery` service needs to communicate with other services (specifically `minio`), it needs to address them directly by service name like `http://minio:9000/whatever` instead of `http://localhost:9000/whatever`. When generating the URL to download the data for validation, it looks something like `http://localhost:9000/dandi-dandisets/test.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioAccessKey%2F20201202%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20201202T223646Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=6ba8022bd45a5e9242c71adc891f3f724a4ac4ac1f83ed7b2f221f00d9ced7ec`. This is arguably correct, because this link works correctly from outside the containers. When the `celery` service tries to use that URL however, it does not know to associate `localhost` with the `minio` service, so it just fails. This is a hard problem that will probably not be fixed this week.

The easiest solution for right now is to just use `https://api.dandiarchive.org` to test it. It will be cleaned up anyway and I've verified that it works correctly.
For local development, the README has instructions on `Develop Natively (advanced)` that uses docker compose for the backing services (postgres, minio, rabbitmq) and runs django and celery as native processes, avoiding this problem.

The error handling for this failure is very lackluster, so I will be fixing it so it fails with a meaningful error rather than hanging indefinitely.

**Comment by jwodder** [comment]
@yarikoptic If we go with testing against https://api.dandiarchive.org instead of Docker Compose, I'll need a secret containing an API key for the new API.

**Comment by dchiquit** [comment]
I've been developing locally using the `Develop Natively (advanced)` instructions from the README.
You should be able to generate your own API key. Go to https://api.dandiarchive.org/swagger/, click `Django Login`, sign up with github, go back to the swagger page, then use `GET /auth/token/` to get an API key.

**Comment by jwodder** [comment]
@dchiquit I know I can generate my own key, but it'll need to be added as a GitHub secret to be available to the automated tests, and I don't have permission to do that.

**Comment by yarikoptic** [comment]
I would really prefer not to test full upload/download cycle on the central api.dandiarchive.org (assuming that at some point it would be the one hosting real data).  I bet there must be a way to pre-seed or automagically grab some token for docker compose setup, or add some API endpoint available only if ran in some "devel" mode (e.g. if some env var is set) for that until we do not figure some better way.

**Comment by jwodder** [comment]
@yarikoptic There is a way to get a token for the Docker Compose setup; the problem is that the Docker Compose setup has a networking issue that's currently preventing uploads from finishing.
