### ISSUE TITLE
Freshly merged "publish the model" workflow didn't work out

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#280]
https://github.com/dandi/dandi-cli/runs/1443526277?check_suite_focus=true

```
Run actions/checkout@v2
  with:
    repository: dandi/schema
    path: schema
    ssh-strict: true
    persist-credentials: true
    clean: true
    fetch-depth: 1
    lfs: false
    submodules: false
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.6/x64
Error: Input required and not supplied: token
```

**Comment by jwodder** [comment]
@yarikoptic The `DANDI_GITHUB_TOKEN` secret ([ref](https://github.com/dandi/dandi-cli/issues/273#issuecomment-729939727)) is apparently not set.  It needs to be set on dandi/dandi-cli; did you set it on dandi/schema instead?

**Comment by yarikoptic** [comment]
I might have, will check/do, thank you!

**Comment by yarikoptic** [comment]
done, reran action, all green, said "No changes to commit" so I guess the version we have is the same. We will need to check if all is good after we merge #226 .  The issue is resolved though AFAIK, closing, thanks!
