### ISSUE TITLE
dandi/schema "auto-updates" seems to be not working

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#289]
https://github.com/dandi/dandi-cli/pull/287#discussion_r532919987 should have triggered a new commit in https://github.com/dandi/schema but according to workflow there were no changes: https://github.com/dandi/dandi-cli/runs/1476406805?check_suite_focus=true

**Comment by jwodder** [comment]
I've created a PR on dandi/schema to apply the changes that should have been made: https://github.com/dandi/schema/pull/15

**Comment by satra** [comment]
ping @jwodder
