### ISSUE TITLE
Download minio data in celery container

### ISSUE THREAD

**Issue by dchiquit** [dandi/dandi-cli#300]
When the `celery` service needs to communicate with other services (specifically `minio`), it needs to address them directly by service name like `http://minio:9000/whatever` instead of `http://localhost:9000/whatever`. When generating the URL to download the data for validation, it looks something like `http://localhost:9000/dandi-dandisets/test.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioAccessKey%2F20201202%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20201202T223646Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=6ba8022bd45a5e9242c71adc891f3f724a4ac4ac1f83ed7b2f221f00d9ced7ec`. This is arguably correct, because this link works correctly from outside the containers. When the `celery` service tries to use that URL however, it does not know to associate `localhost` with the `minio` service, so it just fails. 

_Originally posted by @dchiquit in https://github.com/dandi/dandi-cli/issues/277#issuecomment-737543809_

**Comment by yarikoptic** [comment]
@dchiquit should this be against dandi-api and not dandi-cli?

**Comment by dchiquit** [comment]
You are correct

**Comment by yarikoptic** [comment]
FWIW @dchiquit it is possible to just transfer issues between repositories -- look at the bottom of the right column - there is `--> Transfer issue`

**Comment by dchiquit** [comment]
I think I don't have permissions on dandi-cli, so I just took the path of least resistance and copy+pasted ¯\_(ツ)_/¯

**Comment by yarikoptic** [comment]
ah, added you to dandi-cli team: https://github.com/orgs/dandi/teams/dandi-cli/members
