### ISSUE TITLE
Automatically mint "title" for entities in json schema if not explicitly given

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#301]
This is a continuation to changes/discussion in https://github.com/dandi/dandi-cli/pull/299#issuecomment-737522905 . That PR adds a good number of explicit `title` entries even when they could be trivially created, e.g. `title="Value Reference"` for `valueReference` at https://github.com/dandi/dandi-cli/pull/299/files#diff-295856c56542fa0dda691f493995baed932f49e94744fbacfbd7412db8c79f17R135

So we should remove hardcoded "duplicate" entries and produce title for all entries where no explicit one is defined, so all UIs could consistently display them

**Comment by jwodder** [comment]
@yarikoptic I'm not clear on what you're asking for.  Do you want each field's title to be hardcoded in the source or not?  Do you want those that aren't set in the source to be determined algorithmically at runtime?  Should this algorithmic determination be done by a standalone function that the user of the code calls, passing one field at a time to get a title, or should the code somehow automatically populate all the titles of all the fields before making anything available to the user?

**Comment by yarikoptic** [comment]
- we should not hardcode in `dandi/models.py` where mapping is obvious, but allow for title to be specified there if "custom", e.g. ATM for `includeInCitation` we should keep `title="Include Contributor in Citation"`, but we should remove hardcoded title where no custom is needed (e.g. `valueReference` in original description)
- we should make https://github.com/dandi/dandi-cli/blob/master/tools/pubschemata.py populate titles where missing upon `schema_json` call.  Most likely for that we need to overload `.schema_json` in our `DandiBaseModel` unless we find some more native way to achieve that with `pydantic` (may be it allows for defining some "default" handling of attributes?)

Does it make it clearer @jwodder ?

Does that sound sensible @satra @AlmightyYakob ?

**Comment by jwodder** [comment]
@yarikoptic I've figured out a way to do this, but it currently only seems to work for `Field`s, not `TypeModel`s like `MeasurementTechniqueType`.  Is that acceptable?  Should I make the PR against master or the branch in #299 (or wait for #299 to be merged first)?

**Comment by yarikoptic** [comment]
tests of #299 are still failing, so may be we better just wait for it to be finished (or fix it up) to proceed on this to not cause conflicts to resolve etc.

Re for `TypeModel` -- we should always be able to just tune up `.schema_json` so it handles any type of record if there is no clean "general" pydantic way (if the way you are mentioning is such).
