### ISSUE TITLE
consider rclone like listing

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#311]
There are several related list commands

  * `ls` to list size and path of objects only
  * `lsl` to list modification time, size and path of objects only
  * `lsd` to list directories only
  * `lsf` to list objects and directories in easy to parse format
  * `lsjson` to list objects and directories in JSON format

**Comment by yarikoptic** [comment]
well, we have 
```
 -f, --format [auto|pyout|json|json_pp|yaml]
                                  Choose the format/frontend for output. If
                                  'auto', 'pyout' will be used in case of
                                  multiple files, and 'yaml' for a single
                                  file.
```
so `lsjson` == `ls -f json`.  `lsf` is IMHO not needed as long as we have all the standard json/yaml.  

We might want to add e.g. `-F` which would take that as a string for `.format()` (in datalad it is "automagically" switched to if there is `{` in `-f`, so could be taken here as well) so you could list whatever fields you like and come up with `alias dandi-lsl="dandi ls -F '{modified} ...'"` and alike

as for filtering -- directories only, we have no directories - only dandisets and assets.  We list only dandiset record unless `-r` ;-) if pointing to a file / asset, we already list only asset AFAIK.

**Comment by satra** [comment]
i was thinking of the upcoming bids datasets, but we can visit it once we get those data online.
