### ISSUE TITLE
Establish logging into a persistent file within user's cache (e.g.  ~/.cache/dandi-cli/logs on linux) for each invocation

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#316]
Probably should be just an additional log handler dumping the logs into such directory with a filename like `{datetime}-{pid}.log`.   
This way we could possibly later instruct users to share the logs for debugging and in general would be helpful.  
- Since we do not have a notion of "local dandiset" directory (e.g. like `.git/` for git) which is not to be shared/uploaded - I think user-wide cache directory is a good choice
- We need to make sure that logs reflect the path on which `dandi-cli` is invoked and what was the original command (`sys.argv`).  That would allow to associate logs with a particular dandiset when needed.
- We should log at INFO level the path to the log at the end of running the command.
- I wonder if we should make that log more verbose (DEBUG?) and/or provide a separate verbosity level , probably not for now.

**Comment by jwodder** [comment]
> We need to make sure that logs reflect the path on which dandi-cli is invoked and what was the original command (sys.argv). That would allow to associate logs with a particular dandiset when needed.

Do you mean that this information should be logged in both the file and console?  Should it be prepended to the logfile before starting logging?  Something else?

**Comment by yarikoptic** [comment]
> Do you mean that this information should be logged in both the file and console?

if easily possible to log only in the file -- then only in the file since on console is not really that needed.  If not  -- then ok in both I guess

> Should it be prepended to the logfile before starting logging? 

pre- or ap-pended, do not have preference.

> Something else?

nothing else comes to mind at this point - we can improve later as/when needed.
