### ISSUE TITLE
test against API server started to fail on master (ubuntu):  Error 401 

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#322]
```
_________________________________ test_upload __________________________________
dandi/tests/test_dandiapi.py:11: in test_upload
    r = client.create_dandiset(name="Upload Test", metadata={})
dandi/dandiapi.py:389: in create_dandiset
    return self.post("/dandisets/", json={"name": name, "metadata": metadata})
dandi/dandiapi.py:183: in post
    return self.send_request(
dandi/dandiapi.py:144: in send_request
    raise requests.HTTPError(
E   requests.exceptions.HTTPError: Error 401 while sending POST request to http://localhost:8000/api/dandisets/
```

not sure if that is something to fix within client or -api.

**Comment by jwodder** [comment]
@dchiquit `docker-compose run --rm django ./manage.py drf_create_token admin` is currently outputting some extra cruft that messes with the token extraction:

```
System check identified some issues:

WARNINGS:
?: (rest_framework.W001) You have specified a default PAGE_SIZE pagination rest_framework setting, without specifying also a DEFAULT_PAGINATION_CLASS.
HINT: The default for DEFAULT_PAGINATION_CLASS is None. In previous versions this was PageNumberPagination. If you wish to define PAGE_SIZE globally whilst defining pagination_class on a per-view basis you may silence this check.
Generated token f98a70cafdd9c891690c32e95657d8799136cb2e for user admin
```

**Comment by jwodder** [comment]
@dchiquit Even after correcting the token extraction, I'm still getting a 401 when trying to create a Dandiset in the new API, and the response body says:

```
{"detail":"Authentication credentials were not provided."}
```

I'm currently generating the token using `docker-compose run --rm django ./manage.py drf_create_token admin` and passing it in request headers as "`Authorization: token {token}`"; did something in the auth process change recently?

**Comment by dchiquit** [comment]
https://github.com/dandi/dandi-api/pull/43 should temporarily resolve the auth issues, and https://github.com/dandi/dandi-api/pull/44 should resolve the warning.
I updated a helper library that tweaked some unexpected configurations under the hood, causing the warning and breaking token authentication. Things should be running smoother now.

**Comment by yarikoptic** [comment]
Nice, especially then it would be nice to setup CI to set smoothness in stone ;-) @jwodder wdyt?

PS holidays are upon us, so happy holidays, replies can be delayed until after ;-)

**Comment by jwodder** [comment]
The tests are passing again now.

@yarikoptic What would this CI setup be testing that isn't already tested?

**Comment by yarikoptic** [comment]
tests were passing 10 hours ago and #323 was just merged as well "just in case".  I guess we will be getting some fails/errors like the one listed [above](https://github.com/dandi/dandi-cli/issues/322#issuecomment-748307421) so indeed probably no need for additional CI setup/tests for now. Thanks!
