### ISSUE TITLE
ENH: provide hint on needing to adjust scope for the token

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-cli#325]
```bash
$ dandi upload
2020-12-22 15:36:54,975 [    INFO] Found 341 files to consider
Error: Failed to lock dandiset 000053 due to: You must be logged in.
```

**Comment by bendichter** [comment]
I am logged in to DANDI with Safari but I am having trouble logging in with Chrome

**Comment by yarikoptic** [comment]
hm, I wonder if that is some issue on the dandiarchive side if you can't login in Chrome. is it specific to that dataset?

**Comment by yarikoptic** [comment]
It boiled down to another manifestation of https://github.com/dandi/dandi-cli/issues/238#issuecomment-693478473 .  Hopefully we would not have similar issues with API-based setup, but meanwhile we might want to provide a hint when raising that exception for this specific (`You must be logged in`) message that it might need token scope adjustment (or complete "delete" + regenerate)

**Comment by jwodder** [comment]
Closing as we no longer use Girder.
