### ISSUE TITLE
python library

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#33]
turn dandi cli into pydandi/dandipy/...

related to this i think if we turned dandi into a library, one should be able to do:

```
import dandi as di
di.get_dataset('ds00001', dataset_base_dir='/data/', mmap=True)
```

and this call could use whatever necessary (datalad, dandi api, etc.,.) under the hood. in some ways this is similar to what reactopya does, but it does not provide direct access to the object. it would be nice if we had a zarr-based mode (https://zarr.readthedocs.io/en/stable/).

**Comment by yarikoptic** [comment]
we kinda have it already for some commands, e.g.

```
$> python -c 'from dandi.download import download; download("DANDI:000006", ".")'   
2020-08-12 17:25:02,048 [    INFO] Traversing remote dandisets (000006) recursively
PATH                 SIZE DONE    DONE% CHECKSUM STATUS    MESSAGE         
dandiset.yaml                                    skipped   already exists  
Summary:                  0 Bytes                1 skipped 1 already exists
                          <0.00%                                           
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/venvs/dev3-installfrompip/lib/python3.8/site-packages/dandi/download.py", line 306, in download
    for rec in gen_:
  File "/tmp/venvs/dev3-installfrompip/lib/python3.8/site-packages/dandi/download.py", line 450, in download_generator
    for resp in _download_generator:
  File "/tmp/venvs/dev3-installfrompip/lib/python3.8/site-packages/dandi/download.py", line 662, in _download_file
    raise FileExistsError(block)
FileExistsError: File './000006/sub-anm369962/sub-anm369962_ses-20170309.nwb' already exists
```
but we should unify and decide on their consistent behavior (on how to fail) and returned values. Also I guess we better have a dedicated `dandi.api` or `dandi.ui` (we have `datalad.ui`) module which collects all those methods -- I would not want to bring them up into the "imported by default" `__init__.py` - they might be heavy on imports etc, which might slow things (like `--help`) down.

**Comment by yarikoptic** [comment]
ref: #249 outlines my thinking about API design for the Python interface -- go "datalad way" is the summary

**Comment by yarikoptic** [comment]
we have Python library already. documentation could be found at https://dandi.readthedocs.io/en/latest/modref/index.html
