### ISSUE TITLE
dandi-api: improve download functionality

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#340]
TODOs
- [x] add support for downloading a specific folder (that was disabled)
- [x] replace hardcoded to consider "draft" to be the "latest version" . We should remove that and allow for version to be left unspecified, and then DandiAPIClient code handle it properly (get the latest version, download for it)

**Comment by jwodder** [comment]
@yarikoptic 

> add support for downloading a specific folder (that was disabled)

Is the disabled code still present somewhere?  Does adding support for this consist of just editing `navigate_url()` to only return files within a specified folder?

**Comment by yarikoptic** [comment]
> Is the disabled code still present somewhere?

it is the `path` within
```
    def get_dandiset_assets(self, dandiset_id, version, page_size=None, path=None):
        """ A generator to provide asset records """
        resp = self.get(
            f"/dandisets/{dandiset_id}/versions/{version}/assets/",
            parameters={"page_size": page_size, "path": None},
        )
```

> Does adding support for this consist of just editing `navigate_url()` 

yes (in addition to above `get_dandiset_assets`).

> to only return files within a specified folder?

or just a specified path, if it is not a folder but a single asset (I think it would be nice to have  a unittest where we have an asset under path `blah` and then directory `blah_dir`, and specifying `blah` as location should not match `blah_dir`).

**Comment by jwodder** [comment]
@yarikoptic To be clear, these changes are only for the new API code, not the Girder code, right?

**Comment by yarikoptic** [comment]
yeap -- first one is supported by girder version. 2nd one is specific to api version since we no longer have published versions on girder one.

**Comment by jwodder** [comment]
@yarikoptic How do I test downloading a folder?  The "location" parameter is only recognized in URLs for the GUI, which the Docker Compose setup lacks.

**Comment by yarikoptic** [comment]
Thinking... Ideas?

**Comment by jwodder** [comment]
@yarikoptic My only idea is to define some dummy URL to be used as the Docker Compose's GUI URL, though I don't know whether that would break anything.

**Comment by yarikoptic** [comment]
ok, I am coming up with an ad-hoc URI somewhat following prior discussion in https://github.com/dandi/dandi-cli/issues/183 . Will push to #377

**Comment by jwodder** [comment]
@yarikoptic I already implemented my idea using the URL `http://dandi-api-docker-gui.nil`.  See my PR.

**Comment by yarikoptic** [comment]
I pushed my idea on top in 129f61e322820580187d00edf8e9bb976fc584da ... we could stash it for a separate PR if you have reservations against it, but it should be quite flexible and "convenient" ;)

**Comment by jwodder** [comment]
@yarikoptic Your idea is better; I've removed my implementation in favor of it.
