### ISSUE TITLE
dandi-api: upload - (re)introduce handling of existing files

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#345]
We should reintroduce handling of existing files similar to girder based implementation 
https://github.com/dandi/dandi-cli/blob/master/dandi/upload.py#L342
since dandi-api does verify that there is no asset with a given path (https://github.com/dandi/dandi-api/issues/65). Since
 we have no locking, it would be a "racy" code but ATM I do not see another way around: we just would need to report an error if having uploaded an new file we still fail to mint a new asset for it (if another process uploaded for that path meanwhile as well).

TODOs
- [x] Test for correct behavior upon possible values of `existing`
- [x] Test should be added which would
  - trigger 'publish', i.e. making a release
  - upload a new file (into a draft)
  - verify that we can still get released file from the published version and from a draft version
  - remove file in the draft version
  - verify that we can still get released file from the published version

**Comment by satra** [comment]
as far as i know @dchiquit designed the api to work with no race condition, so would be good to highlight where race would happen.

**Comment by jwodder** [comment]
@yarikoptic

> we just would need to report an error if having uploaded an new file we still fail to mint a new asset for it

You mean that the code should error if [this call](https://github.com/dandi/dandi-cli/blob/30e06950adb81c80ea89b7c88577c48499aef33d/dandi/dandiapi.py#L459) fails?  Assuming the request returns 4xx on failure, the code will already raise an exception.

Aside from the tests, exactly what changes are you asking for?  The new upload already parallels the old upload's handling of pre-existing files (https://github.com/dandi/dandi-cli/blob/30e06950adb81c80ea89b7c88577c48499aef33d/dandi/upload.py#L711); the biggest differences are that "refresh" does nothing in the new code, and the new code doesn't bother deleting any pre-existing files, as the server and its garbage collections should take care of that.

**Comment by yarikoptic** [comment]
oh, missed that the logic is there.  So we are almost there then.

I think we should just record which asset UUID (from [extant](https://github.com/dandi/dandi-cli/blob/30e06950adb81c80ea89b7c88577c48499aef33d/dandi/upload.py#L710) ) is to be removed right before  we `client.iter_upload(`, like we do in old code by storing it in `delete_before_upload` : https://github.com/dandi/dandi-cli/blob/master/dandi/upload.py#L362 . This way we do not remove it ahead of time (validation might fail etc)

**Comment by jwodder** [comment]
@dchiquit `POST /dandisets/{version__dandiset__pk}/versions/{version__version}/assets/` is returning a 500 when completing an upload to a path that an asset was previously uploaded to.  The response body begins with:

```
IntegrityError at /api/dandisets/000006/versions/draft/assets/
duplicate key value violates unique constraint "api_asset_path_version_id_0267c3d9_uniq"
DETAIL:  Key (path, version_id)=(subdir/file.txt, 6) already exists.
```

**Comment by yarikoptic** [comment]
Filed https://github.com/dandi/dandi-api/issues/70 -- I have not realized there is no DELETE endpoint to the asset.  We would need it one way or another.

**Comment by jwodder** [comment]
@yarikoptic While that endpoint would be useful, it was my understanding that the API would be able to handle multiple uploads to the same path automatically without having to make a DELETE call.

**Comment by yarikoptic** [comment]
and then that endpoint should be called before upload (i.e. here in the WiP PR: https://github.com/dandi/dandi-cli/pull/347/files#diff-4e39d697f6d28e2e5d67ba80609f3bc7ceebe2d6be0ff9ae3020331c4bfe48a2R797 ) although I would have actually preferred more atomic operation for replacement of asset on the -api side (filed https://github.com/dandi/dandi-api/issues/71)

**Comment by yarikoptic** [comment]
> @yarikoptic While that endpoint would be useful, it was my understanding that the API would be able to handle multiple uploads to the same path automatically without having to make a DELETE call.

Well, our thinking and API is still WiP ;) I think we should not just silently and unconditionally replace an asset (for the path), and we are not aiming to support having multiple assets for the PATH ATM (AFAIK) since that would open a bigger can of warms.

**Comment by yarikoptic** [comment]
BTW, may be @satra has ideas which are different...?

**Comment by jwodder** [comment]
@yarikoptic 

> verify that we can still get released file from the published version and

You didn't finish this sentence.

**Comment by jwodder** [comment]
@dchiquit @yarikoptic What is the "dandiset" field in the body of `POST /dandisets/{dandiset__pk}/versions/{version}/publish/` supposed to be?  The Dandiset metadata?  I would expect that to be named "metadata".

**Comment by dchiquit** [comment]
@jwodder https://github.com/dandi/dandi-api/issues/68 will replace the 500 error with something more informative, I plan to fix it this week.

That shouldn't be there at all. Peeking at the code, that view already specifies `request_body=None`, so I'm not sure why it's still there. I made https://github.com/dandi/dandi-api/issues/72 to address that.

**Comment by jwodder** [comment]
@yarikoptic Should the method for publishing a version construct the version ID itself (I assume as `time.strftime("0.%y%m%d.%H%M", time.gmtime())`), or should that be left to the method caller?

**Comment by dchiquit** [comment]
When you use the publish endpoint, the response body is the newly published version object, version ID included. The server calculates the new version ID and has some extra logic to ensure the version ID is unique, even if there were multiple publishes in the same minute.

**Comment by jwodder** [comment]
@dchiquit If the server calculates the version ID, what's the `{version}` parameter in the request URL then?  The ID of the pre-existing version (usually "draft") to publish as a new version?

**Comment by dchiquit** [comment]
Correct. Behind the scenes, the `publish` operation simply calculates the new version ID based on time stamp, then creates a copy of the given version with that new version ID. Realistically you would only publish `draft` versions, but the source version ID is still included in the URL to make it clear that you are publishing the draft.

**Comment by jwodder** [comment]
@yarikoptic I'm not sure if you saw [my comment above](https://github.com/dandi/dandi-cli/issues/345#issuecomment-768360596), but I'm still not 100% clear on what the publish test should do.  After publishing, should a separate file be uploaded to the draft version, or should a file in the draft version be overwritten with an modified file?  What exactly should the test verify?

**Comment by yarikoptic** [comment]
Thank you @jwodder for the buzz. I have finished the description for that item
