### ISSUE TITLE
incomplete info for a file

### ISSUE THREAD

**Issue by djarecka** [dandi/dandi-cli#349]
Can't get enough info about `/sub-mouse-ZZPUG/sub-mouse-ZZPUG_ses-20181207-sample-1_slice-20181207-slice-1_cell-20181207-sample-1_icephys.nwb` from `DANDI:000008` when running `dandi ls`: no `metadata`, no `sha256` etc.

can't find this info also on website: https://gui.dandiarchive.org/#/dandiset/000021/draft/files?_id=5f2de703ee8baa608594ba82&_modelType=folder

**Comment by yarikoptic** [comment]
could you provide an exact command 

<details>
<summary>cannot reproduce on a local copy</summary> 

```shell
(git-annex)lena:~/proj/dandi/dandisets/000008[master]git
$> datalad get sub-mouse-ZZPUG/sub-mouse-ZZPUG_ses-20181207-sample-1_slice-20181207-slice-1_cell-20181207-sample-1_icephys.nwb
get(ok): sub-mouse-ZZPUG/sub-mouse-ZZPUG_ses-20181207-sample-1_slice-20181207-slice-1_cell-20181207-sample-1_icephys.nwb (file) [from web...]   
(dev3) 1 54696 [1].....................................:Mon 01 Feb 2021 10:53:08 AM EST:.
(git-annex)lena:~/proj/dandi/dandisets/000008[master]git
$> dandi ls sub-mouse-ZZPUG/sub-mouse-ZZPUG_ses-20181207-sample-1_slice-20181207-slice-1_cell-20181207-sample-1_icephys.nwb
/usr/lib/python3/dist-packages/hdmf/spec/namespace.py:484: UserWarning: Ignoring cached namespace 'hdmf-common' version 1.1.3 because version 1.3.0 is already loaded.
  warn("Ignoring cached namespace '%s' version %s because version %s is already loaded."
/usr/lib/python3/dist-packages/hdmf/spec/namespace.py:484: UserWarning: Ignoring cached namespace 'core' version 2.1.0 because version 2.2.5 is already loaded.
  warn("Ignoring cached namespace '%s' version %s because version %s is already loaded."
- age: P98D
  cell_id: 20181207_sample_1
  date_of_birth: 2018-08-31 00:00:00-04:00
  experiment_description: Current clamp square
  experimenter:
  - Matteo Bernabucci
  genotype: Pvalb-Cre/wt; Ai9/wt
  identifier: a4ec4579-5d87-4d0b-bcea-9da129b2d6ab
  institution: Baylor College of Medicine
  keywords: null
  lab: Tolias
  nd_types:
  - CreSubject
  - CurrentClampSeries (79)
  - CurrentClampStimulusSeries (79)
  - DandiIcephysMetadata
  - Device (161)
  - IZeroClampSeries
  - IntracellularElectrode (160)
  - SweepTable
  number_of_electrodes: 0
  number_of_units: 0
  nwb_version: 2.1.0
  path: sub-mouse-ZZPUG/sub-mouse-ZZPUG_ses-20181207-sample-1_slice-20181207-slice-1_cell-20181207-sample-1_icephys.nwb
  related_publications: null
  session_description: Current clamp square
  session_id: 20181207_sample_1
  session_start_time: 2018-12-07 00:00:00-05:00
  sex: M
  size: 9456345
  slice_id: 20181207_slice_1
  species: null
  subject_id: mouse_ZZPUG
2021-02-01 10:53:15,857 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210201155313Z-411932.log

```
</details>

dandiset is available via datalad on http://github.com/dandisets/000008

Confirming though that metadata is missing if tried on web UI : most likely there was an issue with extracting it when uploading, so was not uploaded, and we do not yet "automagically" re-extract on the server.  Not sure if that is something to fix on dandi-cli side.

**Comment by yarikoptic** [comment]
With migration to new API, we will reextract metadata anyways in a harmonized way across all dandisets, so that would be the point I guess where this particular file(s) would be fixed.

**Comment by satra** [comment]
unless this migration takes place in the next week or two, we will need this metadata available in the current server. we are going to have to start fixing dandisets for the BICCN paper and this is one of them.

**Comment by djarecka** [comment]
the command I used: `ls -f json -r https://identifiers.org/DANDI:000008`

The output is long, but as an example, most look like this
```
{"attrs": {"ctime": "2020-08-07T23:56:25.670000+00:00", "mtime": "2020-07-03T13:09:38.340000-04:00", "size": 9389431}, "girder": {"id": "5f2dea29ee8baa608594bafe"}, "metad\
ata": {"ALM_VISp_top3": "pvalb reln tac1 (90.0%), pvalb reln itm2a (9.0%)", "RNA_family": "pvalb", "RNA_type": "pvalb calb1_2", "RNA_type_top3": "pvalb calb1_2 (58.0%), pv\
alb reln (27.7%), pvalb gpr149 (9.6%)", "age": "p98d", "cell_id": "20181207_sample_2", "date_of_birth": "2018-08-31T00:00:00-04:00", "experiment_description": "current cla\
mp square", "genotype": "pvalb-cre/wt; ai9/wt", "identifier": "390fcd5a-1ae9-4f8e-91a3-33c158b8c336", "institution": "baylor college of medicine", "lab": "tolias", "md5": \
"3ec1e752c25964bd1b2bfb9236badad0", "nwb_version": "2.1.0", "session_description": "current clamp square", "session_id": "20181207_sample_2", "session_start_time": "2018-1\
2-07T00:00:00-05:00", "sex": "m", "sha1": "323b8a7fd660c6d3a0abdd8f9d4cd543b25f097f", "sha256": "874ec74460efaead0c60366bf91ac67f313b0cb4f86a7bd89a1706e232e3eef3", "sha512\
": "e2f2a6cb6b6b92f0385f53314dd8d653b3f15d85b00b8c09cdf0af8b1547d5cf71620436d1cc717c63ea2f5dc47d8e54afc8e04f6ead4d38ed0cfdc9a57d4339", "slice_id": "20181207_slice_1", "sub\
ject_id": "mouse_zzpug", "uploaded_datetime": "2020-08-07T19:56:22.214388-04:00", "uploaded_mtime": "2020-07-03T13:09:38.340000-04:00", "uploaded_nwb_object_id": "d62fd6f5\
-790a-4ad3-a0d1-c5c99b9caf1e", "uploaded_size": 9389431}, "modified": "2020-07-03 13:09:38.340000-04:00", "name": "sub-mouse-ZZPUG_ses-20181207-sample-2_slice-20181207-sli\
ce-1_cell-20181207-sample-2_icephys.nwb", "path": "/sub-mouse-ZZPUG/sub-mouse-ZZPUG_ses-20181207-sample-2_slice-20181207-slice-1_cell-20181207-sample-2_icephys.nwb", "sha2\
56": "874ec74460efaead0c60366bf91ac67f313b0cb4f86a7bd89a1706e232e3eef3", "size": 9389431, "type": "file"}
```

but for `/sub-mouse-ZZPUG_ses-20181207-sample-1_slice-20181207-slice-1_cell-20181207-sample-1_icephys.nwb` it looks like this:
```
{"attrs": {"ctime": "2020-08-07T23:45:04.947000+00:00", "size": 9456345}, "girder": {"id": "5f2de780ee8baa608594baa4"}, "metadata": {}, "modified": "2020-08-07 23:45:04.94\
7000+00:00", "name": "sub-mouse-ZZPUG_ses-20181207-sample-1_slice-20181207-slice-1_cell-20181207-sample-1_icephys.nwb", "path": "/sub-mouse-ZZPUG/sub-mouse-ZZPUG_ses-20181\
207-sample-1_slice-20181207-slice-1_cell-20181207-sample-1_icephys.nwb", "size": 9456345, "type": "file"}
```

so no `metadata`, no `sha256`

**Comment by yarikoptic** [comment]
> unless this migration takes place in the next week or two, we will need this metadata available in the current server. we are going to have to start fixing dandisets for the BICCN paper and this is one of them.

I have doubts that we will accomplish migration that fast (even if it would work, and we could upload, we are still in flux on everything and new platform is untested) I guess we indeed need to resolve https://github.com/dandi/dandi-cli/issues/105 and just sweep through archive and upload all metadata according to the old idea of its schema... But then we would not be able to provide persistent URLs to the files since they might be gone with migration, or we don't need to do that for this metadata dump @satra ? (also "publish" functionality is ripped away from classical girder interface)

If we are to provide URLs, I wonder if we should add a redirector to 
Anyways -- for the files we

**Comment by yarikoptic** [comment]
> Can't get enough info about `/sub-mouse-ZZPUG/sub-mouse-ZZPUG_ses-20181207-sample-1_slice-20181207-slice-1_cell-20181207-sample-1_icephys.nwb` from `DANDI:000008` when running `dandi ls`: no `metadata`, no `sha256` etc.
> 
> can't find this info also on website: https://gui.dandiarchive.org/#/dandiset/000021/draft/files?_id=5f2de703ee8baa608594ba82&_modelType=folder


oh... almost started complaining against dandiarchive -- it is `000008` but then you @djarecka listed a url which has `000021` in it.  that webfrontend at large ignores that ID in the url since I guess it gets all the information based on the folder `_id`.  But I wonder -- how did you arrive with such a url (i.e. 21 instead of 8 in it) -- any recollection?    When I browse from https://gui.dandiarchive.org/#/dandiset/000008/draft to "View Data" I have the correct dataset id in the url: https://gui.dandiarchive.org/#/dandiset/000008/draft/files?_id=5f2de703ee8baa608594ba82&_modelType=folder

**Comment by yarikoptic** [comment]
ok, reporting, using the 370e57f57ce0394d35b2027378ac3df3e37c30b0 version of #355 which I had to tune to allow upload of metadata if remote file has no metadata at all (so we cannot compare mtime etc), I managed to screw up and remove that file from the archive.  I had it locally, hopefully of the correct version, so I just reuploaded.  Now that file has metadata record.  I then
```
dandi ls -f json_pp -r https://gui.dandiarchive.org/#/dandiset/000008/draft >| /tmp/000008.ls
```
and verified that there is no empty metadata records with `grep -A1 '"metadata": {.*}' /tmp/000008.ls` and visually quickly checked that there is metadata record for each path with `grep -e '"path' -e '"metadata' /tmp/000008.ls` .  So I think we are all set for this one.  Please open a new issue @djarecka if you find other files like this.  Also I am still interested to possibly discover the answer to the question in the comment above

**Comment by djarecka** [comment]
i was talking about `0008` not `0021`. When I run `dandi ls` now it gives me a different output for this one file i mentioned, so must have been updated

**Comment by yarikoptic** [comment]
I know that you are taking about 8 and not 21, but check url in your top message. And yes, file was updated

**Comment by djarecka** [comment]
oh yes, the link! I've just tried to repeat it and success!

- open dandi archive `https://gui.dandiarchive.org/#/`
- open `public dandisetssets`: https://gui.dandiarchive.org/#/dandiset
- click on random one: https://gui.dandiarchive.org/#/dandiset/000003
- click `view data`: https://gui.dandiarchive.org/#/dandiset/000003/draft/files?_id=5e6eb2b776569eb93f451f8d&_modelType=folder
- click on `drafts` folder and choose a different dandiset, e.g. 0008: https://gui.dandiarchive.org/#/dandiset/000003/draft/files?_id=5e7115073da50caa9adaf419&_modelType=folder
