### ISSUE TITLE
Sorting import statements

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-cli#350]
The ordering of `import` statements in the code is all over the place.  Fortunately, there are two major projects that can help out in different ways (using one or the other, not both):

* [`flake8-import-order`](https://github.com/PyCQA/flake8-import-order) — a plugin for flake8 that, if used, would cause the linter to fail if any imports are out of order
    * The plugin supports a variety of import order styles.  I would recommend either the `appnexus` style or [my custom `jwodder` style](https://pypi.org/project/flake8-import-order-jwodder/).
* [`isort`](https://github.com/PyCQA/isort) — a program that can be added to the pre-commit configuration to automatically edit source files to put `import` statements in a reasonable order.
    * I recommend the following configuration for isort:

            profile = "black"
            force_sort_within_sections = true
            known_first_party = ["dandi"]

**Comment by yarikoptic** [comment]
I have no experiences with autosorters for this.  I am ok with any which is easy to "enforce" (though pre-commit).
