### ISSUE TITLE
pyout + logging: make them co-exist

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#358]
NB A rough idea ATM

ATM logging interfers with pyout (used for upload/download/ls) output: log line would be printed to stderr but then overriden by pyout on display thus only screwing up pyout rendering since a new line added, and otherwise not visible to the user.  There is really no ideal solution to make them co-exist peacefully. E.g. even if we use (could not find ATM) pyout's ability for "write through" - those log lines would appear above rendering, and likely off the screen already.
But we already store all logs into a temp file which we announce to the user.  So I think a viable way forward would be
- when using pyout, define our logging handler to be only the file one + "pyout handler"
- when logging during pyout, "pyout handler" should inform pyout display that a log line was issued, and we add a counter (ideally actually separating by different log levels, e.g. ERRORS:1, WARNINGS:2 etc) to LOG column for that item
- tricky part is association between log lines and pyout records, but I think could be worked out

**Comment by yarikoptic** [comment]
For now, let's just overload `PYOUTFormatter` `__call__` filter logging handlers so logs go only into the log file and not on the screen (stdour or stderr), and restore the handlers upon `__exit__`

**Comment by jwodder** [comment]
@yarikoptic Can you give an example of a command where the output collides?  `PYOUTFormatter` only applies to `dandi ls`, and if I run just `dandi ls -r` on 000003, I don't seem to see anything odd.  What exactly am I looking for?

**Comment by yarikoptic** [comment]
right -- missed that this formatter is solely for `ls`.  Please subclass `pyout.Tabular` into e.g. `LogSafeTabular` and then inherit `PYOUTFormatter` from it and also use it instead of other places where `pyout.Tabular` is used.  Immediate frequently encountered case is `upload` where our code would spit out some logging and it would ruin rendering of pyout

**Comment by yarikoptic** [comment]
Let's just consider addressed by #401
