### ISSUE TITLE
"migrate" existing dandisets (only dandiset.yaml for now) to new API  server

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#360]
Blockers (AFAIK should be easy to address, so may be just send a PR @jwodder ):
- [x] ~~https://github.com/dandi/dandi-api/issues/57~~ no longer pertinent

Overall workflow:

- Given a full collection of dandisets (so later we could upload data files as well), which is at `dandi@drogon:/mnt/backup/dandi/dandisets` or for now (since no data) just on a local copy which could be obtained quickly using `datalad install -r -J5 https://github.com/dandi/dandisets`
- make a script which takes path(s) of dandisets to operate on, and for each given dandiset, 
  - uses `POST ​/dandisets​/`  to create a new one while providing metadata with original identifier (now possible, thanks to https://github.com/dandi/dandi-api/pull/87)
  - uploads dandiset.yaml to that new dandiset (I am still a bit reluctant to merge it in, but we could do that if would make things easier)

Script should have option to delete a dataset if already exists so we would just recreate it with that identifier for a "clean start"

**Comment by dchiquito** [comment]
* You don't need to worry about `DELETE`ing anything. Just `POST /scripts/map_ids/` whenever there is a dandiset that has the wrong identifier, and the script will move it if it is able. That includes creating a new dandiset, copying the owners, making all the existing versions point to the new dandiset, and deleting the old dandiset. 
* Nope, he just needs to be logged in. This is a temporary hack on a non-deployed system, so security is laxer in the name of convenience.

**Comment by dchiquito** [comment]
I also put in https://github.com/dandi/dandi-api/pull/86 to address https://github.com/dandi/dandi-api/issues/57

**Comment by jwodder** [comment]
@yarikoptic 

> uses `POST ​/dandisets​/` to create a new one (with some ID above 1000s)

That endpoint doesn't have an option for setting the ID.

**Comment by yarikoptic** [comment]
> > uses `POST ​/dandisets​/` to create a new one (with some ID above 1000s)
> 
> That endpoint doesn't have an option for setting the ID.

it will mint (and return I suppose) a new one.  That is why we need to do the "remap" dance.  Relevant issue is https://github.com/dandi/dandi-api/issues/69

> Also, is there a reason to set the metadata via `client.set_dandiset_metadata()` (as #357 does) rather than just including the metadata in the `POST /dandisets/` request?

I guess it will set it with the minted identifier and we would need to overload it with the "target" (original) one so remap does its job later.  It it would not overwrite identifier with the minted one (didn't check) - might be considered a bug IMHO

**Comment by jwodder** [comment]
@yarikoptic But what do you mean by "with some ID above 1000s"?  How is the client supposed to ensure that?  Are you saying that `POST /scripts/map_ids/` should be called twice for each Dandiset, once to move post-1000 and again to move to the final ID?

> I guess it will set it with the minted identifier and we would need to overload it with the "target" (original) one so remap does its job later. It it would not overwrite identifier with the minted one (didn't check) - might be considered a bug IMHO

I don't understand what you're trying to say here.  My question was about setting the entire metadata — not just the identifier — for the Dandiset based on the contents of `dandiset.yaml` and when that should happen.

**Comment by jwodder** [comment]
Also, should this script do anything with assets, or is it only manipulating metadata & identifiers?

**Comment by yarikoptic** [comment]
> @yarikoptic But what do you mean by "with some ID above 1000s"?

sorry for not being descriptive -- it is just how dandi-api now mints IDs if you create a new datataset -- they will all be above 1000.

> Are you saying that POST /scripts/map_ids/ should be called twice for each Dandiset, once to move post-1000 and again to move to the final ID?

nah - just once.  It would take that "original" ID (`<1000`) from metadata and map that dandiset from its minted `>1000` id into it.

> Also, should this script do anything with assets, or is it only manipulating metadata & identifiers?

for now - not.  Only dandiset level metadata.  Later I will try "manually" on a few dandisets

**Comment by jwodder** [comment]
@dchiquito Is the `{dandiset_id}` in the path of `POST ​/scripts​/map_ids​/{dandiset_id}​/` supposed to be the ID that the Dandiset is being moved *from* or *to*?  How do I specify the other ID?

**Comment by dchiquito** [comment]
Moved from. If you have a dandiset with identifier `111111` in Django, but the metadata specifies `"identifier": "DANDI:222222"`, you would call `POST /scripts/map_ids/111111`. Afterwards, `111111` would no longer exist and the original dandiset will have identifier `222222`. 

Alternatively, calling `POST /scripts/map_ids/` will just check all dandisets. If there's nothing to move, it won't move anything.

**Comment by jwodder** [comment]
@dchiquito @yarikoptic I've written a script and am testing against the latest version of dandi-api, but:

* The IDs for new Dandisets are still starting at 000001, not 1000
* Regardless of whether the metadata is set at Dandiset creation or via `client.set_dandiset_metadata()` (i.e., `PUT /dandisets/{dandiset_id}/versions/draft/`), the ID in the metadata for the resulting Dandiset version object always gets set to the autogenerated ID instead of the ID in the supplied metadata read from `dandiset.yaml`.  As a result, `POST ​/scripts​/map_ids​/{dandiset_id}​/` does nothing.

**Comment by yarikoptic** [comment]
> * The IDs for new Dandisets are still starting at 000001, not 1000

FWIW I have just tried on https://api.dandiarchive.org/swagger/ and it created
```
{
  "identifier": "001008",
  "created": "2021-02-05T16:00:12.520948Z",
  "modified": "2021-02-05T16:00:12.520986Z",
  "most_recent_version": {
    "version": "draft",
    "name": "the name",
    "asset_count": 0,
    "size": 0,
    "created": "2021-02-05T16:00:12.625912Z",
    "modified": "2021-02-05T16:00:12.625955Z",
    "dandiset": {
      "identifier": "001008",
      "created": "2021-02-05T16:00:12.520948Z",
      "modified": "2021-02-05T16:00:12.520986Z"
    }
  }
}
```

> the ID in the metadata for the resulting Dandiset version object always gets set to the autogenerated ID instead of the ID in the supplied metadata read from dandiset.yaml

hm, haven't tried, but if so - mapping cannot be done... I guess needs to be fixed, or a proper way (just allow to provide identifier) be implemented, please advise @dchiquito

**Comment by AlmightyYakob** [comment]
> @dchiquito @yarikoptic I've written a script and am testing against the latest version of dandi-api, but:
> 
> * The IDs for new Dandisets are still starting at 000001, not 1000
> * Regardless of whether the metadata is set at Dandiset creation or via `client.set_dandiset_metadata()` (i.e., `PUT /dandisets/{dandiset_id}/versions/draft/`), the ID in the metadata for the resulting Dandiset version object always gets set to the autogenerated ID instead of the ID in the supplied metadata read from `dandiset.yaml`.  As a result, `POST ​/scripts​/map_ids​/{dandiset_id}​/` does nothing.

@yarik Is it an issue to temporarily disable metadata population of identifier until the migration has been done?

**Comment by dchiquito** [comment]
As Jacob mentioned, the identifier in the metadata is now being set to the identifier of the dandiset in Django, which breaks the map_ids script :cry: I am working on adding the ability to create a dandiset with a specific identifier, as requested.

**Comment by yarikoptic** [comment]
@jwodder Now thanks to https://github.com/dandi/dandi-api/pull/87 workflow is simplified, I adjusted the description to reflect that, and we should be ok to proceed

**Comment by jwodder** [comment]
@yarikoptic 

> uploads dandiset.yaml to that new dandiset

Do you mean that `dandiset.yaml` should be uploaded by using it to set the Dandiset's metadata — which is already done when the Dandiset is created — or that it should be uploaded as an asset — which (as far as I understand it) is not what assets are for?

**Comment by yarikoptic** [comment]
I just meant `dandi upload dandiset.yaml` call, but indeed if full converted metadata is passed during create, this might not even be necessary now!
