### ISSUE TITLE
add test workflow for running tools/populate_dandiset_yaml.py of https://github.com/dandi/dandi-api-datasets.git 

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#361]
- should be active for PRs, and pushes and daily (we might update the version of dandisets/ submodule)
- should just clone that repo and initialize (recursively) all submodules (dandisets) (or `datalad install -r`)
- run `tools/populate_dandiset_yaml.py`
  - if any fails (we do not exit with non-0 ATM or that) -- error out

Ideally it could also push to that repo if ran on push to master, but I think we can do that manually once in a while

**Comment by jwodder** [comment]
> if any fails (we do not exit with non-0 ATM or that)

I created a PR to fix that; please merge it: https://github.com/dandi/dandi-api-datasets/pull/1

**Comment by jwodder** [comment]
@yarikoptic What are the arguments to `tools/populate_dandiset_yaml.py` supposed to be?  `[0-9]*` or `dandisets/[0-9]*`?

**Comment by yarikoptic** [comment]
> @yarikoptic What are the arguments to `tools/populate_dandiset_yaml.py` supposed to be? `[0-9]*` or `dandisets/[0-9]*`?

https://github.com/dandi/dandi-api-datasets/commit/01b617590e7cbc754090e03d5d0e0981e0662823 : `"dandisets/0*/dandiset.yaml"`
