### ISSUE TITLE
dandiset metadata migration got broken

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#362]
Initially reported by @AlmightyYakob on slack in `#internal` and reproduced

Running our script within https://github.com/dandi/dandi-api-datasets.git which converts metadata
```
(git-annex)lena:~/proj/dandi/dandi-api-datasets[master]git
$> datalad rerun
[INFO   ] run commit 01b6175; (convert/populate ...) 
[INFO   ] Making sure inputs are available (this may take some time) 
[INFO   ] == Command start (output follows) ===== 
dandisets/000003: EXCEPTION (000003/EXCEPTION) - C
dandisets/000004: EXCEPTION (000004/EXCEPTION) - C
dandisets/000005: EXCEPTION (000005/EXCEPTION) - C
dandisets/000006: EXCEPTION (000006/EXCEPTION) - C
dandisets/000007: EXCEPTION (000007/EXCEPTION) - C
dandisets/000008: EXCEPTION (000008/EXCEPTION) - C
dandisets/000009: EXCEPTION (000009/EXCEPTION) - C
dandisets/000010: EXCEPTION (000010/EXCEPTION) - C
...

$> cat 000003/EXCEPTION
Traceback (most recent call last):
  File "/home/yoh/proj/dandi/dandi-api-datasets/tools/populate_dandiset_yaml.py", line 34, in <module>
    new_meta = migrate2newschema(dandiset_meta)
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/metadata.py", line 535, in migrate2newschema
    newmeta = convertv1(meta)
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/metadata.py", line 430, in convertv1
    newvalues.append(getattr(models.LicenseType, val.split(":")[-1]))
  File "/usr/lib/python3.9/enum.py", line 352, in __getattr__
    raise AttributeError(name) from None
AttributeError: C
```

after addressed, would be nice to automate such a "check", so filed separate https://github.com/dandi/dandi-cli/issues/361

**Comment by satra** [comment]
this should be an easy fix. for some reason the json document i had already lists the license as `dandi:CCBY40` and hence the line above is doing a split. instead line 430 should just do: `val.replace("-", "")` - would be good to run the conversion on all the yaml files. 

this would also require fixing the json record in test_metadata.py

**Comment by satra** [comment]
also would need to remove `.` so `val.replace("-", "").replace(".", "")`

**Comment by jwodder** [comment]
> this would also require fixing the json record in test_metadata.py

Should the `license` strings in `test_dandimeta_migration` be changed to `CCBY40` or something else?

**Comment by satra** [comment]
it should be changed to the string that is in the current dandiset.yaml files so `CC-BY-4.0`
