### ISSUE TITLE
upload: provide path within metadata record

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#368]
follow up to https://github.com/dandi/dandi-api-datasets/issues/3#issuecomment-776023982

I think it would be valuable to add a test that whenever we provide different path as a parameter and also within metadata -- server errors out.

**Comment by yarikoptic** [comment]
yeah, `-api` and `-cli` look too close ;) moving

**Comment by jwodder** [comment]
@yarikoptic 

> I think it would be valuable to add a test that whenever we provide different path as a parameter and also within metadata -- server errors out.

The server currently does not error out.  Should the test just be marked xfailing for now?  Is there an issue to change the server's behavior?

**Comment by yarikoptic** [comment]
I think this one was resolved by #371
