### ISSUE TITLE
validate: add an option to force validation against current (new, API) schema

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#375]
ATM `dandi validate` is ignorant about the bright future of having schema etc.  We should add ability to validate against new schema/model. 

I see a possible way (any other alternative is ok with me, we just need to keep moving ATM): add (devel for now) option `--schema` which if not empty, would provide version of the schema to use, and ATM would just need to match current schema version (and error otherwise).  And if schema version is provided, validate against current schema model.

The immediate demand is `dandi upload` failing because validation fails, but it would not provide any detail, so there is no way to determine what needs to be fixed up.

**Comment by jwodder** [comment]
@yarikoptic Is for only validating assets or also `dandiset.yaml` files?  As far as I'm aware, the latter are still only stored in the old format, so they'd have to be converted and then validated.

**Comment by yarikoptic** [comment]
yes, if we detect that they are in old format (ultimately no `schemaVersion`) - convert and validate
