### ISSUE TITLE
fscache checksum computation on a file

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#389]
Inspired by the necessity of #388.

I initially had reservations about that but I think it should be ok - we can always disable caching using `DANDI_CACHE` to troubleshoot etc.    I guess we just need a helper function 

```python
@checksums.cache
def get_digest(filepath, digest='sha256'):
    return  Digester([digest])(filepath)[digest]
```
?

that should help significantly rerunning `upload` on files.

If we cached the checksum, we could call it even twice (in context of #388) and actually take advantage of that -- if checksum changes from one point to another during upload - we have an good indication that user is trying to upload a file which is still being modified.  WDYT @jwodder  ?

**Comment by satra** [comment]
@yarikoptic - can you at least add mtime to the function signature, so that it would recompute if local mtime has changed?

**Comment by jwodder** [comment]
@satra mtime is already used by `dandi.support.cache.PersistentCache` for cache-breaking.
