### ISSUE TITLE
add a test run which would test against dev of hdmf and pynwb

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#398]
later we will also add some testing on sample .nwb files with various nwb extensions of direct interest to DANDI (relates to https://github.com/NeurodataWithoutBorders/pynwb/issues/1338).  Meanwhile, although with a fear of having not immediately treatable failed CI runs for PRs, I think should benefit from having at least a single run (python and OS of personal preference) which would ensure that our state/changes are still ok with the direction where hdmf/pynwb is going.

**Comment by jwodder** [comment]
@yarikoptic The dev version of pynwb requires `hdmf<3`, so it presumably does not support the dev version of hdmf.

**Comment by yarikoptic** [comment]
ok, let then just install dev of pynwb
