### ISSUE TITLE
Inform users that API keys will expire and they will need to create a new one

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandi-cli#404]

**Comment by waxlamp** [comment]
I can't put a label on this issue--could someone grant me enough permission to do so?

If that's not possible, could you create a label `migration: CLI/API` with color #7914C0 and put it on this issue? Thanks!

**Comment by jwodder** [comment]
@waxlamp Label added.

**Comment by waxlamp** [comment]
Thank you, @jwodder!

**Comment by yarikoptic** [comment]
@waxlamp I see that you are already part of the dandi-cli team (may be just added?) - can you check if you could add labels now?

**Comment by waxlamp** [comment]
> @waxlamp I see that you are already part of the dandi-cli team (may be just added?) - can you check if you could add labels now?

Yup, just added, and yup, can now add/remove labels! Thanks!

**Comment by yarikoptic** [comment]
re original issue.  could you please expand the description to inform how client could discover that a known API key is no longer good -- shouldn't it be just an informative (403?) error message  from the dandi-api server which would be presented to the user (I would assume we already do that in the -cli but I could be wrong)

**Comment by yarikoptic** [comment]
ping on above comment: @waxlamp @dchiquito - what is the server response upon attempt to use expired key, e.g.  is there a difference in response from the server side between "expired" and "invalid" key?

**Comment by dchiquito** [comment]
@yarikoptic Have you ever encountered an expired API key? My understanding was they were permanent. The only way to invalidate an API key is to generate a new one using `POST /auth/token/`, at which point you will have a new API key.

**Comment by yarikoptic** [comment]
me -- not, but I thought that it is coming since @waxlamp has filed this issue

**Comment by waxlamp** [comment]
Sorry, I should have left more context in the original issue report: this is specific to migration, where API keys for the Girder system will have to be retired (i.e., they just won't work with the Django API), whereupon anyone using the CLI with such a key would get failures. We thought putting in a one-time message about what's going on might be a good idea. If not, we can definitely close this as `wontfix`.

**Comment by jwodder** [comment]
Closing as the migration has already completed.
