### ISSUE TITLE
dandi-api: for upload to S3 add integrity "marker"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#407]
@satra reminded about this feature of uploads to S3: https://aws.amazon.com/premiumsupport/knowledge-center/data-integrity-s3/ to provide base64 encoded md5sum.  If possible, we better provide it as well, although it would require now adding computation of md5 in addition to sha256 used by the archive - Digester can do that, so at least we will not re-read the file twice.

**Comment by satra** [comment]
perhaps this is quite simple to just add md5 of the content for a part: https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPart.html
