### ISSUE TITLE
dandi-api: more logging to troubleshoot problems

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#410]
ATM we only yield messages that validation failed but do not log.  Messages (as displayed by pyout) are truncated to be visible on the screen and thus might not actually show what has happened, e.g.

```
drogon:/mnt/backup/dandi/dandisets/000003
*$> DANDI_DEVEL=1 dandi -l 1 --pdb upload -i dandi-api --existing=force sub-YutaMouse33/
PATH                                                            SIZE        ERRORS         UPLOAD STATUS            MESSAGE                                      CURRENT
.../sub-YutaMouse33_ses-YutaMouse33-150218_behavior+ecephys.nwb 11.9 GB        3                  skipped           failed validation
.../sub-YutaMouse33_ses-YutaMouse33-150219_behavior+ecephys.nwb 19.6 GB        0                  done
.../sub-YutaMouse33_ses-YutaMouse33-150220_behavior+ecephys.nwb 22.9 GB        0                  done
.../sub-YutaMouse33_ses-YutaMouse33-150221_behavior+ecephys.nwb 28.9 GB        0                  done
.../sub-YutaMouse33_ses-YutaMouse33-150226_behavior+ecephys.nwb 27.5 GB        0                  done
.../sub-YutaMouse33_ses-YutaMouse33-150222_behavior+ecephys.nwb 160.5 GB       0                  ERROR             Server-side asset validation failed!  Err...
.../sub-YutaMouse33_ses-YutaMouse33-150223_behavior+ecephys.nwb 143.5 GB       0             100% ERROR             Server-side asset validation failed!  Err... 143508573281
.../sub-YutaMouse33_ses-YutaMouse33-150224_behavior+ecephys.nwb 143.8 GB       0                  ERROR             Server-side asset validation failed!  Err...
.../sub-YutaMouse33_ses-YutaMouse33-150225_behavior+ecephys.nwb 97.5 GB        0                  ERROR             Server-side asset validation failed!  Err...
Summary:                                                        656.1 GB 1 with errors  19.8 MB/s 1 skipped         1 failed validation
                                                                                                  4 done            4 Server-side asset validation failed!  E...
```

We originally avoided logging in all the "under pyout" operation, but now (thanks to #401) that logging is not interfering with pyout, we should log as much as useful:
- `lgr.warning` or even `lgr.error` whenever validation or upload or validation has failed
- `lgr.info` upon successful finish of upload/download operation
- `lgr.debug` for anything extra we feel might come handy while troubleshooting

**Comment by yarikoptic** [comment]
may be even just add smth like `lgr.log(2, "%s: %s", msg, result.text)` within `RESTFullAPIClient.send_request` for every response? (ATM we log at .debug only if `not result.ok`)?

**Comment by jwodder** [comment]
@yarikoptic `result.text` is going to be large and binary when downloading assets.  I think it would be better to just log the URL and method for each request without logging the response.

**Comment by yarikoptic** [comment]
> @yarikoptic `result.text` is going to be large and binary when downloading assets. We're already logging the URL, method, and response code for each request; that should be enough.

ok, let's just then do more of targetted logging (in `upload`)
