### ISSUE TITLE
age and text don't match on one asset

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#421]
> curl -X GET "https://api.dandiarchive.org/api/dandisets/000008/versions/draft/assets/812181a1-50c0-40c8-9f09-a3e75d31a40e/" -H  "accept: application/json" 

returns age as `"age":{"value":"P49D","unitText":"Years from birth"}`

the value says 49 days but text says years from birth.

**Comment by satra** [comment]
@djarecka - perhaps this is an easy starting issue. the two functions are here:

https://github.com/dandi/dandi-cli/blob/master/dandi/metadata.py#L96 (parse_age and extract_age).

the metadata flow involves reading from the nwb file and updating the asset metadata structure through parsing.

**Comment by djarecka** [comment]
@satra - and what exactly you expect? Should unit be a part of `value`? I'd think that `"age":{"value":"49","unitText":"Days from birth"}` should be enough

**Comment by yarikoptic** [comment]
I think there was a number of issues addressed in dandischema .
