### ISSUE TITLE
dandi-api: download - make verification of the checksum "guaranteed"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#427]
ATM in the code we verify download digests only if digests are provided to https://github.com/dandi/dandi-cli/blob/master/dandi/download.py#L446 .   I think we need to remove "if" for dandi-api instances - there always must be a digest.

**Comment by jwodder** [comment]
@yarikoptic Unlike the upload code, the download code uses the same function for both Girder and Django, so removing that "if" would break download of any Girder assets that lack digests.  Or should the code just require a digest for all assets and error if it can't get one?

**Comment by yarikoptic** [comment]
we have `server_type` so for the api one must verify that checksum is available within `download_generator`
