### ISSUE TITLE
dandi-schema: add nwb extensions information

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#433]
soon (https://github.com/hdmf-dev/hdmf/pull/527) we should get a robust way to get information about NWB extensions present in a file.  Ideally we should contain that information in the metadata record. I was thinking about `wasGeneratedBy` but I am not sure if that one is actually appropriate since we are to restore namespace names and versions, and not necessarily tools (we don't know for sure) which produced them.

As for name spaces, for a sample https://github.com/dandi/dandi-api-datasets/blob/master/000045/sub-00778394-c956-408d-8a6c-ca3b05a611d5/sub-00778394-c956-408d-8a6c-ca3b05a611d5_ses-00594aec-bb70-4601-862d-63a31ef0e1c0_behavior%2Bimage.nwb.yaml#L25 for we have

```
$> ../tools/hdmf-get-namespaces.py /mnt/backup/dandi/dandisets/000045/sub-00778394-c956-408d-8a6c-ca3b05a611d5/sub-00778394-c956-408d-8a6c-ca3b05a611d5_ses-00594aec-bb70-4601-862d-63a31ef0e1c0_behavior+image.nwb
Extracting spaces... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00

Summary:
  Files: 1
  Counts: 
    core: {'2.2.5': 1}
    hdmf-common: {'1.2.0': 1}
    ndx-ibl-metadata: {'0.1.0': 1}
    ndx-spectrum: {'0.2.2': 1}
```

Also sooner or later I expect us to extract more of NWB metadata beyond what we already harmonize.  It would be useful for search, analysis etc, but I do not think it is feasible to harmonize it beyond what nwb-schema provides.  And aforementioned extensions names/versions are more of relevance/interest to dandi-cli than anything (although could already help developers of those extensions to possibly find dandisets which used them -- accountability).

WDYT @satra ?

**Comment by satra** [comment]
we should indeed push as many things to nwb schema as possible and minimize even transformation. but this may take some work (let's bring this up at the sync today as a potential item for the hackathon).

regarding where to put it, i thought i already saw a place where @jwodder added information about the file being uploaded by dandi cli. how about we add something similar about the file be generated by some unknown activity that was associated with some nwb generator where those extensions are noted.

however, you are correct, this is really a notion of metadata about the nwb file, but related to software interaction. let's think about a good property/key that generalizes this to beyond nwb (i'm thinking nifti extensions, and other future things), and more generically a place to store such information.

**Comment by yarikoptic** [comment]
sure. Let's just keep in mind that aiming for "generic" we should not make it too hard for tools (e.g. `dandi-cli`) interested in a specific item (e.g. nwb extensions) to find that information.

**Comment by satra** [comment]
yup - we can consider things like this:

if file format is `application/x-nwb` then `nwb_extensions` is an allowed property. the key will be how to maintain this and validate this in a robust way. or you can have a list of allowed properties, but not necessarily validated as being meaningful. 

we can also make a more specific asset type, the `NWBAsset`, the `NIFTIAsset`, the `BIDSJSONAsset` and so on.

**Comment by yarikoptic** [comment]
eh - and it is a duplicate of #395 -- so I guess we had this boiling for too long :-/
