### ISSUE TITLE
ls: add --schema VERSION  Validate against new schema version

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#441]
similar to the one present for `validate` already

probably no need to worry about pyout output rendering ATM if it would fail to render, main aspect - to be able to `ls` quickly "converted" metadata for a file

**Comment by jwodder** [comment]
@yarikoptic Do you want this option to just output the converted metadata or also perform validation on the converted metadata?

**Comment by yarikoptic** [comment]
no validation -- only conversion for `ls`.

**Comment by yarikoptic** [comment]
closed by #445
