### ISSUE TITLE
schema: add date modified to BareAssetMeta

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#448]
https://schema.org/dateModified

should be non optional, ready only in mediator

will correspond to file mtime, uploaded, and used for refresh (#367 )

Any objections @satra ?

**Comment by satra** [comment]
you could add `dateModified` but isn't that somewhat weird given that UUID is minted for any modification to metadata or blob? and thus object creation time exists. 

i also thought you implemented local caching.

**Comment by yarikoptic** [comment]
Well, the db modified date isn't part of metadata afaik (and that is good IMHO ;-)).

Local caching - we cache many things now, which one do you have in mind? ;-) I was thinking about adding dateModified so user could tell either local file is newer or older, not just different (what checksum can tell us, and yes we cache checksums)

**Comment by satra** [comment]
what happens if i download a dandiset. won't it show that my local mtime is ahead of the remote mtime?

**Comment by yarikoptic** [comment]
For girder downloads we set mtime of the downloaded file to match the one from metadata iirc. Iirc wget does the same if last-modified is provided (makes me think to check if we could feed that was well into s3 urls as well... Hmm)

**Comment by satra** [comment]
feel free to add some of the time properties, but i don't know which `Last-Modified` you will attach to the blob when used in multiple assets :)

**Comment by yarikoptic** [comment]
Well, this metadata isn't available for blobs, so they will go without mtime

**Comment by satra** [comment]
but just like we will add `content-disposition` to blob, we can add `Last-Modified` to blob as well. but i guess for this need you only care about metadata.

**Comment by yarikoptic** [comment]
yeap, that is the idea.

FWIW: double checked about wget -- I remembered it right:

```shell
$> wget -S 'https://api.dandiarchive.org/api/dandisets/001001/versions/draft/assets/872ad8bf-ee32-4b3d-8659-c85c4995cc86/download' 2>&1 | grep Last-Modified
  Last-Modified: Mon, 25 Jan 2021 21:06:14 GMT
$> stat download
 ...
Modify: 2021-01-25 16:06:14.000000000 -0500
```
and apparently it is probably the mtime of the file whenever it was uploaded to the blob store since that date is nowhere in the metadata associated with the asset:
```
$> curl --silent -X GET -H "accept: application/json" https://api.dandiarchive.org/api/dandisets/001001/versions/draft/assets/872ad8bf-ee32-4b3d-8659-c85c4995cc86/ | jq . | grep 2021
  "created": "2021-02-02T15:05:27.045124Z",
  "modified": "2021-02-02T15:05:27.045168Z",
    "created": "2021-02-02T15:02:27.024880Z",
    "modified": "2021-02-02T15:24:57.435116Z",
      "created": "2021-02-02T15:02:27.002581Z",
      "modified": "2021-02-02T15:02:27.002622Z"
```

@jwodder -- please add dateModified to BareAssetMeta, and add handling for it in API based upload (thus addressing #367 by adding proper "refresh" mode)/download.

**Comment by jwodder** [comment]
@yarikoptic What exactly do you want the upload behavior of "refresh" to be?  For Girder, refresh proceeds iff the local & remote files differ in size or mtime (without taking digests into account) and the remote file is older than the local file.  Should the new API use the digests instead of the file sizes?

**Comment by yarikoptic** [comment]
yes - use digest as the first check and then if differ, proceed iff remote file is older than the local file.
