### ISSUE TITLE
schema: make digest into a Dict

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#451]
ATM https://github.com/dandi/dandi-cli/blob/master/dandi/models.py#L835 we have
```python
digest: Digest = Field(nskey="dandi")
```
but as discussing possibly using another checksuming (multihash) for validation of the uploads, we need to tune up to make this into a list or better a dict to populate/use more efficient checksum

**Comment by satra** [comment]
indeed this should be `List[Digest]` . the digest itself has type, so one can use that. we could make that more clean (but that's the jsonld representation work i have not done). for the moment change it to list and i will turn that into a map later.

**Comment by yarikoptic** [comment]
> for the moment change it to list and i will turn that into a map later.

how would it look if were to be made into a map?  if we are contemplating to change later -- that would be more painful since would require major version boost (since breaking change)

**Comment by yarikoptic** [comment]
@jwodder please change to a list
