### ISSUE TITLE
pre-commit catch do not catch length of the line

### ISSUE THREAD

**Issue by djarecka** [dandi/dandi-cli#463]
I got an error from `linters` even after passing all of the `pre-commit` checks

**Comment by jwodder** [comment]
I suspect that the error involved a line with a very long string, which `black` (the primary pre-commit formatter) does not do anything about.  Also, note that pre-commit now runs flake8, so long lines will still be reported by pre-commit.

@djarecka Given that, is there still anything that needs to be done for this issue?

**Comment by djarecka** [comment]
Don't really remember what was complaining about, likely it was solved, let's close it now
