### ISSUE TITLE
NF: dandi.core to contain dandi-s3-etag logic

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#464]
The main purpose is to provide a collection of core utilities (very "stable") for reuse by both dandi-api and dandi-cli, such as the S3 ETag chunking strategy which ATM resides outside of "dandi" (ref: https://github.com/dandi/dandi-api/issues/146).  We definitely do should not maintain copies of such code, or have it outside of dandi space.
 
I think it would have been better as a dedicated `dandicore` module but if dandi-api would depend on `dandi-cli` anyways (e.g. for metadata validation etc), so the benefit is not so obvious, and I dislike proliferation of modules/packages (requires more effort to maintain distributions etc).

WDYT (attn: @dandi/dandiarchive and @dandi/dandi-cli ) ?

**Comment by satra** [comment]
is there a reason not to have it in dandi-cli and have dandi-api import it?  especially, since others may want to build on top of dandi "library"

**Comment by yarikoptic** [comment]
well, my thinking was that if `dandi-api` does not need any other functionality from `dandi-cli`, `dandi-cli` might be unnecessarily heavy dependency (with all the click, pydantic, etc).  Also, it felt that having separate/dedicated versioning of core functionality could be helpful instead of trying to figure out when `dandi-api` should progress dependency on dandi-cli, where it might just be changing the CLI etc.

But for now, unless @dchiquito would object, we could just keep it here and  `dandi-api` would need to add `dandi` into dependencies of dandi-api.

We might need though to adjust our logging setup in https://github.com/dandi/dandi-cli/blob/master/dandi/__init__.py#L43 to not interfere with global logging configuration (filed https://github.com/dandi/dandi-cli/issues/466)

**Comment by dchiquito** [comment]
I think for now adding `dandi` as a dependency of `dandi-api` would be fine. We're not particularly concerned about package size and it keeps things simpler for now while we're iterating.

**Comment by dchiquito** [comment]
I just learned that heroku does have a maximum package size, so maybe we are particularly concerned. Still, I think it's worth doing it the easy way for now and breaking it into it's own package if we run into problems.
