### ISSUE TITLE
dandi:sha-X -> dandi:sha-2-X

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#483]
more of future proofing I guess... I just paid attention that in https://github.com/multiformats/multicodec/blob/master/table.csv it is `sha-2-256` and `sha-3-256`... so I wondered if we should right away to switch away from ambigous `sha-X` (where X not a version like in `sha-1`)?

related: #482 and https://github.com/dandi/dandi-cli/pull/481/files#issuecomment-804347832 (on use of `-` in `@id` itself)

**Comment by satra** [comment]
i can change this in my current set of schema updates that are forthcoming. which sha are we using? while we can keep adding later, for the moment i was just restricting to things we use.

**Comment by yarikoptic** [comment]
I believe that dandi-api computes sha256 offband but I didn't check

**Comment by satra** [comment]
@yarikoptic - i looked into this. i think they are using the `-` to signify bit-width for those algorithms that have that. the base algorithm is still `sha2`, `sha3`, `blake2b` etc.,. in our uses we were only using SHA256.

so i'm keeping digest as is (added blake3, which itself supports parallelism). we should figure out which ones to use for out-of-band digesting. i'm leaning towards fast and available. we can expand the digest types as we add support ourselves.

**Comment by satra** [comment]
i don't think dandi api has any offband compute yet. since that was punted to a post migration task.

**Comment by yarikoptic** [comment]
> i don't think dandi api has any offband compute yet. since that was punted to a post migration task.

https://github.com/dandi/dandi-api/blob/e6dd13301876047501e9125a1c67e203ada8d757/dandiapi/api/views/upload.py#L213

**Comment by satra** [comment]
@yarikoptic  - do you know if this actually works? seems like this would run into the same issue that we discussed about long running jobs. and also if this works we should be returning it with the asset metadata as an additional digest. i will post in dandi-api.

**Comment by yarikoptic** [comment]
> @yarikoptic - i looked into this. i think they are using the `-` to signify bit-width for those algorithms that have that. the base algorithm is still `sha2`, `sha3`, `blake2b` etc.,. in our uses we were only using SHA256.

My point is that we should ideally use names which are "standardized" according to some listing, and that table is one of them. There is no sha256 in it since it is only assumed that sha256 is sha version 2 if 256 bits length. sha version 3 is completely different algorithm and could also be of that length.

> so i'm keeping digest as is (added blake3, which itself supports parallelism). 

FWIW - blake3 in the table. Sounds good. Yet to familiarize myself with it, never encountered it being used in the wild.

**Comment by yarikoptic** [comment]
> @yarikoptic - do you know if this actually works? 

I didn't check. I think I did see log messages about those jobs being started

**Comment by satra** [comment]
> use names which are "standardized"

roger - i will update the names.
