### ISSUE TITLE
schema option has no effect

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#485]
i don't believe the schema flag has any effect here. i also tried 0.1.0.

`$ dandi ls --format  yaml --schema 0.1.1 https://dandiarchive.org/dandiset/000037/draft`

**Comment by jwodder** [comment]
@satra I believe that's because you're fetching data from the server.  `--schema` should have an effect when operating on local files.

**Comment by satra** [comment]
can the code be updated to behave similarly (preferred)? or generate an exception in this case (perhaps temporarily)?

**Comment by yarikoptic** [comment]
I think we should just `raise NotImplementedError("records conversion between schema versions is not implemented. Found schemaVersion=%s whenever %s was requested" % ...)` for such case(s) whenever online resource provides metadata of a different version.
