### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#487]
so we provide DandiETag to outside code like dandi-api.   I also some notification that "release workflow failed" recently, so might need some fixes to the `auto` setup?

**Comment by jwodder** [comment]
@yarikoptic Releases are triggered by merging PRs.  What PR should cause this release?

**Comment by yarikoptic** [comment]
Could be be #486 I guess

**Comment by yarikoptic** [comment]
0.10.0 is out
