### ISSUE TITLE
question about metadata

### ISSUE THREAD

**Issue by djarecka** [dandi/dandi-cli#497]
I have two questions:

* I don't understand some changes between old metadata and new metadata, if I do this:
```
 url = "https://dandiarchive.org/dandiset/000027/draft"
 ret = download(url, tmpdir)
 meta = Dandiset(Path(tmpdir) / "000027").metadata
 newmeta = migrate2newschema(meta)
```
`meta` looks like this:
```
{'age': {'maximum': 12.0, 'minimum': 12.0, 'unitText': 'TODO'}, 'contributors': [{}], 'description': 'Should be ignored by regular mortals.\n\nATM contains only a few files from http://github.com/dandi-datasets/nwb_test_data which more or less appropriate (do not lack critical metadata) for testing', 'identifier': '000027', 'keywords': ['development'], 'name': 'Test dataset for testing dandi-cli.', 'number_of_subjects': 1, 'organism': [{'species': 'Rattus norvegicus'}], 'sex': ['M']}
```
and `newmeta`:
```
DandisetMeta(contributor=[Person(roleName=[<RoleType.Author: 'dandi:Author'>], identifier='0000-0003-3456-2493', name=None, email=None, url=None, includeInCitation=True, awardNumber=None, affiliation=None, schemaKey='Person')], description='Should be ignored by regular mortals.\n\nATM contains only a few files from http://github.com/dandi-datasets/nwb_test_data which more or less appropriate (do not lack critical metadata) for testing', identifier='DANDI:000027', keywords=['development'], name='Test dataset for testing dandi-cli.', schemaVersion='0.1.1', about=None, studyTarget=None, license=None, protocol=None, ethicsApproval=None, acknowledgement=None, access=[AccessRequirements(status=<AccessType.Open: 'dandi:Open'>, contactPoint=None, description=None, embargoedUntil=None)], url=None, repository='https://dandiarchive.org/', relatedResource=None, wasGeneratedBy=None, citation=None, assetsSummary=None, manifestLocation=None, version=None, doi=None)
```
it's "longer" but it's missing many important info, e.g. `age`, `number_of_subjects`, etc. Is it on purpose?

* the second questions -- if I'm not using `download`, but create `Dandiset` from dandisets that I got using `datalad install -J5 -r https://github.com/dandi/dandi-api-datasets`, I had yet another version of metadata (this one also missing `age` etc.
```
{'access': [{'status': 'dandi:Open'}], 'contributor': [{'identifier': '0000-0003-3456-2493', 'includeInCitation': 'true', 'roleName': ['dandi:Author'], 'schemaKey': 'Person'}], 'description': 'Should be ignored by regular mortals.\n\nATM contains only a few files from http://github.com/dandi-datasets/nwb_test_data which more or less appropriate (do not lack critical metadata) for testing', 'identifier': 'DANDI:000027', 'keywords': ['development'], 'name': 'Test dataset for testing dandi-cli.', 'repository': 'https://dandiarchive.org/', 'schemaVersion': '1.0.0-rc1'}
```

I guess it might be a similar unification issue as in #484, but I'm not sure at the end how to get information to `datesite` jsonfile. @yarikoptic suggestion to take `newmeta` wouldn't work IMO

**Comment by satra** [comment]
the newmeta is the appropriate one, and some of those other info is missing on purpose. they will be aggregated on the server side from all the assets that are available. 

the second question i leave to yarik or john, but the first code clip that you have us fine to use.

**Comment by yarikoptic** [comment]
just FYI: for https://github.com/dandi/dandi-api-datasets you do not need `-r` really -- we do reference `dandisets/` there but I am afraid we are cheating and not updating the state of that `dandisets` subdataset

and we concentrated on validating assets so much that we forgot to repopulate/update dandiset.yaml files.  Filed https://github.com/dandi/dandi-api-datasets/issues/23 (I better don't do anything possibly destructive ATM).  When it gets fixed those dandiset.yaml will get updated and should reflect newer version.

But in your case @djarecka it shouldn't matter much -- just load straight from a dandiset using that code snippet to have it converted to the most up to date schema, and proceed from there.

BTW -- of interest and immediate relevance https://github.com/dandi/dandi-api/issues/180
