### ISSUE TITLE
upload: (dandi-api) parallelize upload of parts

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#498]
I see upload speeds jumping between 1-50 MBps from drogon with dandi-cli reporting 22 MB/s average ATM.  I do not think it is network bottlnecked really, and neither it seems to be CPU bound.

With all the multiple upload urls we should be able to handle blocks (including digests per block) in parallel with benefit even if simply using threads. With original girder based upload I think there were no way to parallelize individual file upload, so we resorted to parallization across files.  I think we might reconsider that (although it would still benefit initial digestion and validation) or just compliment with parallelization within file (across parts) upload.

**Comment by jwodder** [comment]
@dchiquito Question: When POSTing to `/uploads/{upload_id}/complete/`, do the parts have to be in order?

**Comment by dchiquito** [comment]
@jwodder I just tried it and no, they do not have to be in order.

**Comment by yarikoptic** [comment]
FWIW, uploading 000003 (large but in GBs not TBs range) with more than a single file ATM in parallel to that monster.  Speed on the wire is 150-250MBps and reported by dandi-cli to average to 113 MBps.  So definitely it was not network bottleneck but related to  serial parts upload .

**Comment by jwodder** [comment]
@yarikoptic I was going to use 000003 to test my PR for this issue.  Are there any folders in that Dandiset you're not uploading, or is there another Dandiset with files that are many multiples of 64 MB in size?
