### ISSUE TITLE
delete command

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#501]
By popular request of @satra and to reflect that web ui would never become as flexible as shell globbing, we need `dandi delete`.

- should be pretty much a trimmed down copy of `download` in terms of interface/handling inputs (paths or URLs) and just instead of `download` to `delete` of local and remote files
  - may be worth adding an option `--remote-only` to not bother with possibly present local files
- before jumping to the action, should ask user confirmation alike "Do you want to delete {len(assets)} from the {dandiset} on the server and {len(files)} local files?"  (later we might want to add a cmdline option to avoid this interaction, ok without for now since we better make it uniform with other commands like `upload` etc)
- tests should test against an instance of fixtured dandi-api that
  - deletion is forbidden by API server for assets in released versions
  - deletion in the draft does not delete assets (by downloading so we are certain that blobs are not removed from keystore) present in prior released versions
- no need for `girder` support - just raise NotImplementedError
 
Just ideas for later
- we might like to inform user on deletion of how many assets on remote server would cause those assets to no longer be present in the archive (i.e. not present in any other prior version of the dandiset)

**Comment by satra** [comment]
i think there are two possible sets of operations:

1. what happens with a sync with `--delete` option. sync can be in both directions. 
2. what one can do in a shell like mode. it would be nice to have `dandi [ls, delete, rename]` to operate like a shell on the server.

**Comment by jwodder** [comment]
@yarikoptic To be clear:
* This command is only for deleting local and remote assets, not deleting Dandisets.
* The command should take a set of URLs and/or paths on the command line.
    * URL arguments must specify assets, which will be deleted on the remote end.
    * Path arguments are only valid when running inside a local Dandiset.  They cause the corresponding remote assets to be deleted, along with the local assets if `--remote-only` is not given.

Is that how you want this to work?

> deletion is forbidden by API server for assets in released versions

This would be better as a test in `test_dandiapi.py` rather than as a test of the command.

> deletion in the draft does not delete assets (by downloading so we are certain that blobs are not removed from keystore) present in prior released versions

We already have a test of that in `test_dandiapi:test_publish_and_manipulate`.

**Comment by yarikoptic** [comment]
re @satra :
> 1. what happens with a sync with `--delete` option. sync can be in both directions.

Let's keep non-existing `sync` (#365) mode or command out of this issue for now.

> 2. what one can do in a shell like mode. it would be nice to have `dandi [ls, delete, rename]` to operate like a shell on the server.

yeap, we have `ls` already. This issue for `delete`  and eventually we might want `rename` indeed.  Then implemented interfaces could be used for `sync`.

**Comment by yarikoptic** [comment]
> @yarikoptic To be clear:
> 
> * This command is only for deleting local and remote assets, not deleting Dandisets.

I would say - if provided specification resolves to a dandiset without specification of any path, we could as well call out to `DELETE /dandisets/{dandiset__pk}/` end-point.  It would be a good test for dandi-api to disallow that (unless admin) ;-)

> * The command should take a set of URLs and/or paths on the command line.

yeah, to the same degree as `download` does (I believe mixing of paths and URLs is not allowed)

>   * URL arguments must specify assets on a new Dandi API instance, and the assets will be deleted on the remote end.

might be an asset, a "folder" (location?) or entire dandiset (see above) -- similarly to `download`.

>   * Path arguments are only valid when running inside a local Dandiset. 

I think that is true if the same is true for download ATM (i.e. could I `download  /tmp/000001/` which has `dandiset.yaml` and I am outside of `/tmp/000001`?)

>  They cause the corresponding remote assets to be deleted, along with the local assets if `--remote-only` is not given.

correct... not sure if we should worry about possible empty directories left locally 
   
>     * Should paths only be accepted if `-i` is given with a new Dandi API instance?

I would say "no" in a sense that we should default to some instance (ATM girder - NotImplemented).
If remote dandiset is not found - error out stating that this dandiset does not exist on server.

> Is that how you want this to work?
> 
> > deletion is forbidden by API server for assets in released versions

yes (although I am not sure if admin user is allowed ATM, better not for now I would say)
 
> This would be better as a test in `test_dandiapi.py` rather than as a test of the command.

up to you
 
> > deletion in the draft does not delete assets (by downloading so we are certain that blobs are not removed from keystore) present in prior released versions
> 
> We already have a test of that in `test_dandiapi:test_publish_and_manipulate`.

I see it indeed having `client.delete_asset_bypath(dandiset_id, "draft", "subdir/file.txt")` and that one in turn queries first for asset uuid and then calls delete on it -- great!  I hope that would be sufficient!

**Comment by jwodder** [comment]
@yarikoptic 

>> The command should take a set of URLs and/or paths on the command line.
>
> yeah, to the same degree as download does (I believe mixing of paths and URLs is not allowed)

It appears that `download` only accepts URLs, and no more than one per invocation.  What should `delete` do?

**Comment by yarikoptic** [comment]
oh, I guess I confused myself with all the datalad dandisets and/or `dandi ls` which IIRC does take both paths and URLs. So let's proceed with support of both, if needed adopting the same logic as ls on deciding if url is given or a path

**Comment by jwodder** [comment]
@yarikoptic New write-up of command behavior; is this what you want?

* The command takes a set of URLs and/or paths on the command line.
* URL arguments must specify Dandisets or assets (the latter by pointing to either folders or individual items).
    * A URL pointing to a Dandiset indicates that the Dandiset should be deleted on the server.
        * **Question:** Should each Dandiset be deleted (after prompting for confirmation) as its URL is processed, or should they all be saved up for the end of the command and deleted with a single confirmation?  If the latter, should the Dandiset deletion confirmation be part of the asset deletion confirmation, or should they be two separate confirmations?
    * A URL pointing to one or more assets indicates that the given assets should be deleted on the server.
    * A URL pointing to a Girder instance results in an error.
    * **Question:** What should happen if a non-asset URL includes a version component?
* Path arguments are only valid when running inside a local Dandiset. They cause the corresponding remote assets to be deleted, along with the local assets if `--remote-only` is not given.
    * The server from which to delete the assets is specified by the `-i` option.  By default, this points to the Girder server, which raises an error.
    * Local Dandisets which do not exist on the server should be detected and result in an error.
    * **Question:** Should path arguments require the current directory to be the root of the local Dandiset, or is it also acceptable for the current directory to be a subdirectory of the Dandiset?
* **Question:** If the `-i` option is given with URL arguments and the URLs point to a different instance than that given by `-i`, should anything happen?

> before jumping to the action, should ask user confirmation alike "Do you want to delete {len(assets)} from the {dandiset} on the server and {len(files)} local files?"

This implies that you want a separate confirmation for each Dandiset from which assets are being deleted.  Do you?

**Comment by yarikoptic** [comment]
I feel that we should not even support operations across dandisets ATM, so multiple dandisets are "detected" and we can abort right away with ValueError.

I composed the reply but all good questions made me decide that we should not bother about any local files deletion whatsoever.  `delete` though should still allow for paths as to determine what to delete on the remote server.  Later all the `--sync` command/modes could be used for more "advanced" operation which could lead to local files deletion.

With that in mind let me give answers:

On per-file/path basis ideally we should provide similar to other commands pyout based interface which would allow for errors to be reported but operation would continue, with non-0 exit code if any error was detected.

> * **Question:** What should happen if a non-asset URL includes a version component?

I guess if it is a path or full dandiset -- proceed with request to server, and it should error (thus again we would test dandi-api)

> Question: What should happen when a given local path does not exist on the server?

`dandi.exceptions.NotFoundError`

> Question: When a path to a directory is given, how should the assets within be identified? Should all files be searched for on the server, with those not found simply ignored?

let's operate "semantically", i.e. if `dandi delete --delete-local sub-X` is given, we take it to query remote for that path on remote side and delete those assets, without traversing local `sub-X` which might have different ones.

> Question: Should path arguments require the current directory to be the root of the local Dandiset, or is it also acceptable for the current directory to be a subdirectory of the Dandiset?

yes - allow to be in a subdirectory, I believe we already have code to deduce top directory of the dandiset to compose paths relative to it.

> Question: If the -i option is given with URL arguments and the URLs point to a different instance than that given by -i, should anything happen?

Let's make URLs simply supersede what `-i` might say.  Alternatively we could play safer and default it to `None` so if any value specified explicitly, only then abort with an error that URL is pointing to a different than explicitly specified archive.

**Comment by jwodder** [comment]
@yarikoptic

* Do you want this to be implemented as a `delete()` function that does all the work and is simply called by the `delete` command?  Because, if not, I don't see the point of specifying what types of exceptions to raise, since they'll all be the same to the user.
* Should each Dandiset be deleted (after prompting for confirmation) as its URL is processed, or should they all be saved up for the end of the command and deleted with a single confirmation? If the latter, should the Dandiset deletion confirmation be part of the asset deletion confirmation, or should they be two separate confirmations?

> > * **Question:** What should happen if a non-asset URL includes a version component?
> 
> I guess if it is a path or full dandiset -- proceed with request to server, and it should error (thus again we would test dandi-api)

Do you mean that the request should be made to the Dandiset deletion endpoint, ignoring the version?  And what kind of path argument would include a version component?

> > Question: When a path to a directory is given, how should the assets within be identified? Should all files be searched for on the server, with those not found simply ignored?
> 
> let's operate "semantically", i.e. if `dandi delete --delete-local sub-X` is given, we take it to query remote for that path on remote side and delete those assets, without traversing local `sub-X` which might have different ones.

What exactly is `--delete-local` supposed to do?  What happens if the user runs `dandi delete sub-X` without `--delete-local`?

**Comment by yarikoptic** [comment]
> * Do you want this to be implemented as a `delete()` function that does all the work and is simply called by the `delete` command?  Because, if not, I don't see the point of specifying what types of exceptions to raise, since they'll all be the same to the user.

ideally yes so we have Python API for it as well

> * Should each Dandiset be deleted (after prompting for confirmation) as its URL is processed, or should they all be saved up for the end of the command and deleted with a single confirmation? If the latter, should the Dandiset deletion confirmation be part of the asset deletion confirmation, or should they be two separate confirmations?

as I have mentioned in the opening of previous comment -- could we just check if all URLs point to the same dandiset and error out if multiple are pointed to?  that would avoid the need for "per-dataset" prompts etc.

> > > * **Question:** What should happen if a non-asset URL includes a version component?
> > 
> > I guess if it is a path or full dandiset -- proceed with request to server, and it should error (thus again we would test dandi-api)
> 
> Do you mean that the request should be made to the Dandiset deletion endpoint, ignoring the version? And what kind of path argument would include a version component?

oh sorry -- I have not spotted that there is no API end-point for deletion of a specific version of the dandiset ATM.  So I guess in such a case (if versioned dandiset is specified): `raise NotImplementedError("DANDI API server does not support deletion of individual versions of a dandiset")`

> > > Question: When a path to a directory is given, how should the assets within be identified? Should all files be searched for on the server, with those not found simply ignored?
> > 
> > let's operate "semantically", i.e. if `dandi delete --delete-local sub-X` is given, we take it to query remote for that path on remote side and delete those assets, without traversing local `sub-X` which might have different ones.
> 
> What exactly is `--delete-local` supposed to do? What happens if the user runs `dandi delete sub-X` without `--delete-local`?

I am sorry -- that was a leftover from my initial response before I decided that we should not bother with local deletions at all.  So just remove `--delete-local` , i.e. command was intended to be `dandi delete sub-X`

**Comment by jwodder** [comment]
@yarikoptic Should the user be allowed to specify assets from multiple different versions of the same Dandiset?  Or should specifying any asset in a non-draft version be an automatic error?

**Comment by satra** [comment]
> should the user be allowed to specify assets from multiple different versions of the same Dandiset? Or should specifying any asset in a non-draft version be an automatic error?

for the moment i would raise an exception. this would be the kind of thing that only admins have access to but even then to be used very sparingly. let's be safe with this one for now and restrict it to drafts.
