### ISSUE TITLE
upload: "too CPU heavy" with ~~10~~ 1 parallel threads upload

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#504]
trying the reupload of the 3.6T monster stating to use 10 threads... 
```
*$> DANDI_DEVEL=1 dandi -l 1 upload -i dandi-api --allow-any-path  --validation skip --jobs 1:10 --devel-debug largeuploads/blobs/f5d/aac/79d9c6c1ba2439200d45680f1cb941087750a000e484ea2973232709d2
2021-03-25 14:12:44,011 [   DEBUG] Running a newer version (0.12.1+4.gd41969c) of dandi/dandi-cli than available (0.12.0)
2021-03-25 14:12:45,494 [   DEBUG] Found identifier DANDI:000029 in top level 'identifier'
2021-03-25 14:12:45,504 [    INFO] Found 1 files to consider
{'size': 3628888939868}
{'status': 'digesting'}
{'status': 'extracting metadata'}
{'status': 'failed to extract metadata'}
{'status': 'uploading'}
{'status': 'calculating etag'}
{'status': 'initiating upload'}
{'status': 'uploading', 'upload': 0.010000000000363747}
{'status': 'uploading', 'upload': 0.020000000000727495}
...
```
the wire is running thin (15MBps) and CPU busy  at 100% for that process.  Some profiling/troubleshooting should be done to see why it is so CPU heavy given that it should be just sending data over the net.  May be some intermediate buffer (at requests level?) should be increased or smth like that.

**Comment by yarikoptic** [comment]
or are we also 'digesting' to get the md5 for the part to compare with resultant etag? that might explain why cpu bound.  Then may be it is easy/safe to switch to subprocess pool?

**Comment by jwodder** [comment]
@yarikoptic All of the etag digestion happens before any uploading takes place.  Note that I also noticed the drogon CPU hitting max usage a couple days ago when you were uploading files, before the file-multithreading was implemented.

**Comment by yarikoptic** [comment]
When I was uploading a single file it was just 20% . What you observed was probably due to parallelization above that at pyout level

**Comment by yarikoptic** [comment]
well, even with `--jobs 1:1` I see 100% cpu load and that slow speed.  So needs debugging etc.  Please also add some `lgr.log(5, "Thread %s, Uploading block %d of size %d", ... )` so we have some "easy" ways to debug without code changes

**Comment by jwodder** [comment]
@yarikoptic There's already an "Uploading part %d/%d (%d bytes)" debug message, and the logs written to the log directory include the thread ID.

**Comment by yarikoptic** [comment]
oh right -- only in the log and that is why I didn't see then my original invocation output... and damn -- due to https://github.com/dandi/dandi-api/issues/185 can't even troubleshoot ATM but 

<details>
<summary>looking at existing log of run with --jobs 1:5</summary> 

```shell
drogon:~/.cache/dandi-cli/log
*$> awk '{print $5;}' 20210325201510Z-13694.log | sort | uniq -c
   1102 13694:140085540464384
     14 13694:140086146082176
```
</details>
it seems that there is only a single thread (`13694:140085540464384`) running uploads.

**Comment by jwodder** [comment]
@yarikoptic With the default threading settings, I see numerous threads being used for uploads, and `py-spy top` seems to indicate that most time is spent in the `send()` method of some `ssl.py`.

**Comment by jwodder** [comment]
@yarikoptic I believe I've figured out why you were only seeing one thread: https://github.com/dandi/dandi-cli/pull/519

**Comment by yarikoptic** [comment]
oh -- I wonder if that is all the encryption for ssl which spends the time...  I wonder if it is worth it in our case at all given that I do not think we really need encryption and I would prefer to see higher throughput .  I guess we could parallelize through subprocess pool instead of threads, but before jumping on trying that: @satra @dchiquito - do you see https transport to see mandatory (e.g. S3 allows only for https uploads?) or could it be just http?

**Comment by yarikoptic** [comment]
> @yarikoptic I believe I've figured out why you were only seeing one thread: #519

GREAT! Trying out on that 3.6TB but now it would take time to redigest it again...

**Comment by yarikoptic** [comment]
tried instead on 000019 meanwhile.  With a single file at `1:5` -- rocketed to 230MBps.  With multiple and without `--devel-debug` and `4:5` speeds spiked to 500-600 MBps with nice stable rates of 200-400MBps whenever multiple files upload in progress. `dandi-cli` cpu wise was spiking over 100% (parallel processes across files if I got it right) but never very much over 100%.  So may be https is not that much of a bottleneck overall.

**Comment by dchiquito** [comment]
@yarikoptic I think using HTTP may be possible, but it would be difficult and involve a whole lot of personalized network configuration in AWS. I would consider that an absolute last resort for speeding up uploads.

**Comment by yarikoptic** [comment]
Thank you @dchiquito . With the fixed up multi-threaded upload (thanks @jwodder) I see reasonable upload speeds per file (3.6TB file upload was averaged at 283.3MBps) so let's indeed then not bother with http.
