### ISSUE TITLE
migrate-dandisets.py: add --only-metadata option

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#510]
ref: https://github.com/dandi/dandi-cli/pull/505#issuecomment-808305767

To facilitate introducing fixes to dandiset level metadata

I do not think we should torture `dandi upload` for this and just add an option to update (well -- overwrite) metadata for the dandiset (error out if dandiset does not exist is ok).

Please then run it across all dandisets from drogon

**Comment by jwodder** [comment]
@yarikoptic I successfully ran the script on all Dandisets on drogon.

**Comment by yarikoptic** [comment]
Awesome, thank you @jwodder !
