### ISSUE TITLE
make client more robust than the server: reissue request to dandi-api service if errors out with 503

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#520]
ATM happened only for `/initialize` (https://github.com/dandi/dandi-api/issues/185) but I wonder if we should make it available to other invocations as well.

**Comment by jwodder** [comment]
@yarikoptic Would you prefer me to extend `try_multiple` to take predicates in place of exception types, or would just replacing `try_multiple` entirely with [tenacity](https://github.com/jd/tenacity) be better?

**Comment by yarikoptic** [comment]
tenacity seems to be nice, omni-present, and not heavy in depends (well -- still has `six` for python2, but I guess it would go away) so seems worthwhile switching to use it instead of an ad-hoc handler
