### ISSUE TITLE
Get rid of distutils

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-cli#522]
[Distutils is deprecated and slated for removal from the Python standard library.](https://www.python.org/dev/peps/pep-0632/)  Currently, dandi-cli uses distutils in one place: using `LooseVersion` to compare pynwb versions.  The recommended replacement for `distutils.version` is [`packaging.version`](https://packaging.pypa.io/en/latest/version.html); however, its equivalent(?) of `LooseVersion`, [`LegacyVersion`](https://packaging.pypa.io/en/latest/version.html#packaging.version.LegacyVersion), is also deprecated.  Finding the proper version class to use depends on just how pynwb versions are structured.

@yarikoptic What do we know about the format of pynwb versions?

**Comment by yarikoptic** [comment]
I don't recall any special knowledge on the life cycle of pynwb versions. LooseVersion might have been used to become resilient to not exactly semver versions: e.g. now I see `__version__` to be reported `'1.4.0.post.dev8'` for pynwb, and with versioneer we get `0.12.1+38.g834985e` for dandi.  So whatever "comparator" to be used , it should not blow up with those.

**Comment by jwodder** [comment]
@yarikoptic Both of those are valid PEP 440 versions, parseable with `packaging.version.Version`.

Upon closer inspection, it seems that `LooseVersion` is not used for handling of versions of pynwb itself but for handling of "version of the NWB standard used by a file".  I'm not sure how relevant the pynwb version is to that.

**Comment by yarikoptic** [comment]
yeah, nwb version -- there were some pains with prior versions and thus we have all this special handling of it in https://github.com/dandi/dandi-cli/blob/master/dandi/pynwb_utils.py#L41 .  The critical point seems is 2.1.0 version and I unfortunately I do not think we have a "complete metadata" dump for before migrating to new schema, where it seems we have not yet "represented it yet", so can't quickly check for all values we might encounter in the archive
