### ISSUE TITLE
Give DigestType aliases for common names of algorithms

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-cli#524]
The constant changes to `DigestType`'s names & values are getting annoying, and the names are getting less intuitive.  It would be nice if the enum had aliases ([members with different names but the same value](https://docs.python.org/3/library/enum.html#duplicating-enum-members-and-values)) allowing the use of more common names of digest algorithms as alternatives to the canonical names — for example, allowing `DigestType.SHA1` as an alias for `DigestType.sha1` and allowing `DigestType.sha256` & `DigestType.SHA256` as aliases for `DigestType.sha2_256`.

@satra How would we do this without messing up the JSON Schema & JSON-LD stuff?

**Comment by satra** [comment]
we can keep things consistent in rdfs:label and use that. but this operation in the last change was to move us closer to expected things. how about we pay attention to changes from here on out, but update things to the current state.

**Comment by yarikoptic** [comment]
do you think @jwodder it is something we would still need to tackle?

**Comment by jwodder** [comment]
@yarikoptic Not really.

**Comment by yarikoptic** [comment]
Then let's just close, but feel free to reopen if your opinion changes
