### ISSUE TITLE
test demo workflow of satra

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#53]
which tries to use `-d` to specify dandiset to operate on:
```shell
dandi register
dandi download dataset-permalink 
dandi organize -d folder_download-typically-datasetid source_folder -f some_mode
dandi upload -d folder_download-typically-datasetid
```

**Comment by satra** [comment]
i was able to do all of this. except `dandi register`, which hopefully will be addressed next week.

**Comment by yarikoptic** [comment]
as mentioned in #52, will remove `-d` from upload for now, so this issue would also be deferred to 0.4.2

**Comment by yarikoptic** [comment]
`-d` was removed and "satra's workflow" hardcoded in the handbook should work, so I will just close this one for now
