### ISSUE TITLE
`readOnly` meaning

### ISSUE THREAD

**Issue by djarecka** [dandi/dandi-cli#531]
when do we use `readOnly` flag in `Field`? 

I can't find it in the `pydantic.Field` documentation and I don't think it works. I can easily overwrite fields that have `readOnly=True`

**Comment by satra** [comment]
`readOnly` is for the Web ui to not allow individuals to fill those fields. they can be filled by automatic processes. they have no impact on pydantic. to truly make `pydantic` readonly a `Literal` should be used, but we don't have a use case for that beyond the class names (see `schemaKey`).

**Comment by djarecka** [comment]
so what do you get by adding `readOnly` to `doi` field?

**Comment by satra** [comment]
> so what do you get by adding readOnly to doi field?

the Web ui to not allow individuals to fill those fields.

**Comment by djarecka** [comment]
I see, so it's only for the web, thanks
