### ISSUE TITLE
ls: provide ability to list individual asset from a download url

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#533]
ATM:
```
$> dandi ls -f json_pp https://api.dandiarchive.org/api/dandisets/000003/versions/draft/assets/0a748f90-d497-4a9c-822e-9c63811db412/download/
2021-04-06 12:20:16,926 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210406162015Z-1963932.log
Error: Response for getting https://api.dandiarchive.org/api/dandisets/000003/versions/draft/assets/0a748f90-d497-4a9c-822e-9c63811db412/download/ to redirect returned 403. Please verify that it is a URL related to dandiarchive and supported by dandi client

```
although URL is valid and wget follows redirect nicely.  Might be that dandi-api does not handle HEAD request correctly while we are trying to get redirect url (so something to file and issue or submit a PR about to dandi-api).  But I do not think in this case we should even try to follow any redirect since all pertinent information is in the URL and we just need to parse it and request metadata record for the asset

**Comment by satra** [comment]
HEAD is supported, but perhaps you are following redirects which for the link indeed gets you eventually to a 403. but that's true of the girder link as well.
