### ISSUE TITLE
ls: -r is "insufficient" to get detailed information about assets in a folder

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#534]
ATM
```
(git)lena:~/proj/dandi/dandi-cli-master[master]git
$> dandi ls -f json_pp -r 'https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000003/draft/files?location=sub-YutaMouse20%2F'       
{
  "asset_count": 101,
  "created": "2021-04-05T15:25:03.799071Z",
  "metadata": {
 ...
  "path": "000003",
  "size": 2559248010229,
  "version": "draft"
}
{
  "asset_id": "ca90f128-4e55-4d5b-8f0e-647bd2cf78b2",
  "created": "2021-04-05T15:29:02.570155Z",
  "modified": "2021-04-05T15:29:02.570211Z",
  "path": "sub-YutaMouse20/sub-YutaMouse20_ses-YutaMouse20-140327_behavior+ecephys.nwb",
  "size": 8417855886
}
...
```
so we do provide detailed record on the dandiset but not for each individual asset.  I think we should provide a way to make individual asset metadata returned as well. 

Obviously then a single `-r` cannot tell between the two desires (just a list of assets from end point as API returns or query/include metadata per asset).  We could have made it into an option `--recursive `None`,"auto","assets"`  (we tend to go for such style in datalad more these days acknowledging that flags eventually become insufficient) but I think it would make unnecessarily harder to split `-r|--recursive` from positional arguments (would require `--` in cases where value is not provided).

So let's go for an explicit `--metadata api,all,dandiset,assets` ?  `api` -- just return what API returns for a given case, and that would be current behavior. `all`/`dandiset`/`assets` -- would query metadata (for the dandiset or an asset) if no `metadata` in the corresponding record. 

I am open to other ideas as well. WDYT @jwodder @satra ?

**Comment by jwodder** [comment]
@yarikoptic Should this option have any effect when interacting with the Girder instance?

**Comment by yarikoptic** [comment]
Sorry I wasn't clear - front bother about girder at all. API is the near future, let's look forward

**Comment by jwodder** [comment]
@yarikoptic And when would `--metadata dandiset` ever make a difference?

**Comment by yarikoptic** [comment]
ATM I guess never since we do provide it. Feel free to drop, or just add code which would ensure that if that metadata is requested, we have it.
