### ISSUE TITLE
download: do "download" dandiset.yaml if changed

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#540]
Just for new dandi-api code

ATM we just report "skipped   already exists " for the dandiset.yaml:
```
$> dandi download https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/010005/draft/files?location=
PATH                                                                                                 SIZE    DONE    DONE% CHECKSUM STATUS    MESSAGE             
dandiset.yaml                                                                                                                       skipped   already exists      
sub-17715189-8c56-4c3a-81c6-eec2f68bbf10/sub-17715189-8c56-4c3a-81c6-eec2f68bbf10_behavior+image.nwb                                skipped   same time and size  
Summary:                                                                                             0 Bytes 0 Bytes                2 skipped 1 already exists    
                                                                                                     +7.6 MB 0.00%                            1 same time and size
```
but it could have changed online.  I think we should produce that file (in memory) and if nothing changed -- report "skipped  same", and if any changes -- do save a new version and not "skip" it

**Comment by jwodder** [comment]
@yarikoptic Your desired behavior is basically what happens with `--existing overwrite`.  Is using that option acceptable, or do you want this regardless of the value of `--existing`?

**Comment by yarikoptic** [comment]
default for `existing` is `refresh`. Let's 

- use `modified` timestamp from metadata to adjust file's mtime upon download of `dandiset.yaml` (like we do for assets IIRC).
- use that `modified` timestamp to establish "refresh" logic for dandiset.yaml as well - so if local file mtime is older than on server - we refresh with the one from the server

the only side effect now would be that changes to assets also change modified timestamp for entire dandiset.  But I am ok with that.  We will just treat dandiarchive's record as the canonical source for such cases.

NB found elderly https://github.com/dandi/dandi-cli/issues/154 - so the desire is "old".  And just today closed that issue (failed to find ATM) where I begged for dandiset.yaml to be an asset. we might come back to that :-/

**Comment by satra** [comment]
should we validate and upload changes if changed locally? or do we not allow any local changes? for programmers they could use the API to update.

**Comment by yarikoptic** [comment]
> should we validate and upload changes if changed locally? 

validate local file during upload of a remote "one"?

> or do we not allow any local changes? 

"allow" is too strong of a word.  ATM we "do not care for `upload`" (besides getting a dandiset identifier).  But the use case here is with the download -- since there is not dandiset.yaml asset, we need to provide this custom logic to ensure that users who download a dandiset, do get up to date dandiset.yaml.  Validation by modification time might prevent some overwrites if they happened to modify it locally for some good reason.

> for programmers they could use the API to update.

yeap, those who do not instantiate metadata record into a file get away easy ;)

**Comment by jwodder** [comment]
@yarikoptic 

> default for `existing` is `refresh`. Let's
> 
> * use `modified` timestamp from metadata to adjust file's mtime upon download of `dandiset.yaml` (like we do for assets IIRC).
> * use that `modified` timestamp to establish "refresh" logic for dandiset.yaml as well - so if local file mtime is older than on server - we refresh with the one from the server

I assume that the first bullet should always be done and the second is for when `existing == "refresh"`.  What should happen when `refresh` is `"error"` or `"skip"`?

**Comment by yarikoptic** [comment]
> I assume that the first bullet should always be done

yes

> What should happen when refresh is "error" or "skip"?

what happens for other files -- error or skip, i.e. no modifications to local one
