### ISSUE TITLE
Using DANDI CLI on windows/anaconda

### ISSUE THREAD

**Issue by lydiang** [dandi/dandi-cli#548]
Hi,

I am trying to upload data to DANDI from a Windows 10 machine and I ran into this error.

(ccf) PS C:\Users\lydia\Documents\Work\MouseBrainAnatomy\atlas_helper_tools> C:\users\lydia\anaconda3\envs\ccf\Scripts\dandi.exe
Fatal error in launcher: Unable to create process using '"d:\bld\dandi_1616536553469\_h_env\python.exe"  "C:\users\lydia\anaconda3\envs\ccf\Scripts\dandi.exe" ': The system cannot find the file specified.

**Comment by yarikoptic** [comment]
Have no immediate ideas. Did you pip install'ed it, please try to pip uninstall dandi, and then conda install -c conda-forge dandi

**Comment by yarikoptic** [comment]
<details>
<summary>for me it doesn't install using pip</summary> 

```shell
Successfully built click-didyoumean girder-client pyrsistent
ERROR: hdmf 2.4.0 has requirement h5py<3,>=2.9, but you'll have h5py 3.2.1 which is incompatible.
ERROR: hdmf 2.4.0 has requirement numpy<1.19.4,>=1.16, but you'll have numpy 1.20.2 which is incompatible.
```
</details>

So I did `conda create -n test-dandi-install-condaforge -c conda-forge -y dandi ` to create a new environment with dandi from conda-forge, and reproduced your case

```
(test-dandi-install-condaforge) C:\Users\DataLad>dandi
Fatal error in launcher: Unable to create process using '"d:\bld\dandi_1616536553469\_h_env\python.exe"  "C:\Users\DataLad\miniconda3\envs\test-dandi-install-condaforge\Scripts\dandi.exe" ': The system cannot find the file specified.
```

yet to figure out.  @jwodder @satra - any ideas?

**Comment by satra** [comment]
you may need an entrypoint option for windows. see: https://github.com/conda-forge/scrapy-feedstock/pull/40/files

**Comment by yarikoptic** [comment]
d'oh -- must be it for conda!  Forgot that it is needed to specify them explicitly even if specified in setup.cfg, and I could have sworn that I had tested conda installation of dandi to operate correctly.  Weird.  Fixing that and depends for 0.13.0 build in https://github.com/conda-forge/dandi-feedstock/pull/24 . Will check later and merge if builds fine.

**Comment by yarikoptic** [comment]
just for a proof of my sanity, did aforementioned install on linux and it worked out just fine:
```
$> which dandi
/home/yoh/anaconda-5.2.0-2.7/envs/test-dandi-install-condaforge/bin/dandi
$> dandi --version
0.12.0
```
so it is a windows specific issue (and original scrapy issue also mentions windows: https://github.com/conda-forge/scrapy-feedstock/issues/37), and that is how I had missed it... linux and osx builds passed, so I have just blindly merged that PR for feedstock without awaiting windows build -- will check later.  But now someone should be able to test in an hour or so without waiting for me to come back to laptop.

**Comment by yarikoptic** [comment]
ok, did `conda update -c conda-forge dandi` and now
```
(test-dandi-install-condaforge) C:\Users\DataLad>dandi --version
0.13.0
```
so we are good!
