### ISSUE TITLE
Restructure parse_dandi_url() return type

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-cli#554]
As `parse_dandi_url()` grows to support a greater variety of URLs that require fetching assets in different ways, I think it's past time we change the function to return object instances with methods for retrieving a URL's client, Dandiset, and assets.

Specifically, I propose the following type hierarchy:

* The return type of `parse_dandi_url()` will be an instance of the abstract class `DandiURL`, whose attributes & methods are:
    * `api_url: str` — the base URL of the API
    * `server_type: Literal["girder", "api"]`
    * `dandiset_id: str`
    * `version_id: Optional[str]`
    * `get_client()` — Returns either a Girder or DandiAPIClient instance, as appropriate
    * `get_dandiset(client) -> dict`
    * `get_version_id(client) -> str` — Returns `version_id` if it is set or else determines it based on the Dandiset's state
    * `abstractmethod get_assets(client, include_metadata=False) -> Iterator[dict]`
        * Note that some subclasses may always include metadata regardless of the value of `include_metadata`.

* The concrete subclasses of `DandiURL` include:
    * `DandisetURL` — for URLs that only refer to a Dandiset (possibly with a version); `get_assets()` returns all assets in the Dandiset
    * `AssetIDURL` — for URLs that identify an asset by ID
    * `AssetPathPrefixURL` — for URLs that identify a collection of assets by path prefix
    * `AssetItemURL` — for URLs that identify a specific asset by path
    * `AssetFolderURL` — for URLs that identify a collection of assets by folder path

@yarikoptic Thoughts?

**Comment by satra** [comment]
@jwodder - i would stay away from a notion of a folder and simply consider a filter on a set of assets. note that the CLI will not need to support anything in girder, so any future support should be from the perspective of the api server models. i think any refactor at this point should eliminate girder from consideration.

i would also encourage us not to support anything that has gui.dandiarchive.org and instead focus on our api surface and any identifiers we release. in the ui we should provide a download link for a folder via a path regex, but the client should not think of it as a folder (just a returned collection of asset objects).

**Comment by jwodder** [comment]
@satra 

> i think any refactor at this point should eliminate girder from consideration.

That's only viable if the refactor occurs after we remove Girder support from the codebase.  Do we know yet when that's going to happen?

**Comment by yarikoptic** [comment]
> That's only viable if the refactor occurs after we remove Girder support from the codebase.

I think so too.

> Do we know yet when that's going to happen?

any moment now I guess ;) we should finalize migration roadmap/dates today at 2pm meetup.

As for @satra s

> i would stay away from a notion of a folder and simply consider a filter on a set of assets

on one hand - yes.  On another -- we should decide on what behavior of the client would be in delivering those assets to local file system .  With a folder - they are all placed into that folder.  With a list of assets coming from various folders - not that clear.

**Comment by satra** [comment]
>  With a folder - they are all placed into that folder. With a list of assets coming from various folders - not that clear.

i would say the CLI should first evaluate if there are clashes on path location. (i'm assuming future search results across dandisets).  for now, since the path search is only within a dandiset, it can just create the locations as referred to by path. (for example a search on behavior may return multiple assets across participants).

so the CLI should respect the path info returned and deal with that.

**Comment by yarikoptic** [comment]
re clashes: it would lead to problems with consecutive invocations -- e.g first - no clashes, then reran - and getting clashes, need folders - what to do with old assets -- move? (then could break analysis scripts) etc... makes it ambiguous etc.  We already have a similar problem with incremental `organize`, so better stay away from doing "clashes resolution" IMHO ;)

At this point in time, directories are present all around -- web UI, datalad dandisets, we have API call to list directory content etc.  So I would cater to those immediate use-cases ATM.  For a loose collection of assets from various dandisets -- we would decide what to do whenever we get there.  E.g. there could be a mode which downloads assets into filenames based on `asset.identifier`, or file path gets formatted based on the metadata record (pretty much like `git annex view`) thus allowing arbitrary hierarchy composition, or mode which would do what `organize` does in composing the path to organize into (and that is the one which takes care about clashes). But overall -- there could be various modes (in the future)

**Comment by yarikoptic** [comment]
further thoughts: whenever we get those "meta-dandisets" functionality (create a dandiset from assets of other dandisets eg. based on a search) -- if  we create them on dandi-api level and create a new dandiset, things would still work since it would again be just a dandiset.  If we are to make it possible on dandi-cli level - there could then be `SearchResultURL` which would provide a list of assets (and we add aforementioned modes to give options on how to present them locally, without establishing a dandiset).

So, overall IMHO @jwodder 's proposal is ok with me and we could extend it in the future if it would be necessary.
