### ISSUE TITLE
delete: gave me a message I never saw before

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#558]
```shell
$> time dandi delete https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/010007
2021-04-12 15:02:22,648 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210412190217Z-3179431.log
Error: TODO client name derivation for keyring
```
I wonder why it came up now specifically for `delete`?  any idea @jwodder ?

**Comment by jwodder** [comment]
@yarikoptic That happens when `DANDI_API_KEY` is not set and the API URL isn't in `known_instances_rev`.  (I think the latter condition may be getting triggered due to a trailing slash.)

**Comment by yarikoptic** [comment]
As the `dandi download 'https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/010007'` works ok, I guess it is something specific to `delete` as for resolving URL to the dandiset, assets to work on.  Something to fix to make it consistent in URLs handling.
