### ISSUE TITLE
add test for get_instance obtaining information from redirector's server-info

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#569]
A follow up to https://github.com/dandi/redirector/issues/42#issuecomment-819487756 . Apparently we dropped covering that part of code testing against a "live" redirector whenever we removed (now gone) support for downloading multiple files given a URL from web ui (used to be supported in girder instance).

edit: test should smoke test that code and also test that provided version is greater than current one used, and that either girder or api URL is provided (but not both)

**Comment by jwodder** [comment]
@yarikoptic Would it be sufficient for the test to just call `get_instance("dandi")` and test that the return value has either the Girder or API field set?  How are you envisioning testing of the version check to work?

**Comment by yarikoptic** [comment]
> @yarikoptic Would it be sufficient for the test to just call `get_instance("dandi")` and test that the return value has either the Girder or API field set? 

yes, but not both

> How are you envisioning testing of the version check to work?

semver of `record.get("version")` `>= '1.2.0`

**Comment by yarikoptic** [comment]
pretty much test for all the fields the client is expecting to have in that record , ie
```
"cli-minimal-version":
"cli-bad-versions": 
```
