### ISSUE TITLE
FOI: codecov security breach

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#572]
alerted by https://about.codecov.io/security-update/ and looking at the secrets/codecov use
```
$> git grep secret 
.github/workflows/publish-schemata.yml:          token: ${{ secrets.DANDI_GITHUB_TOKEN }}
.github/workflows/release.yml:          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
.github/workflows/release.yml:          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
.github/workflows/test.yml:        token: ${{ secrets.CODECOV_TOKEN }}

$> git grep codecov
.github/workflows/test.yml:      uses: codecov/codecov-action@v1
.github/workflows/test.yml:        # name: codecov-umbrella
.github/workflows/test.yml:        # yml: ./codecov.yml
DEVELOPMENT.md:   extension](https://sourcegraph.com/extensions/sourcegraph/codecov)
README.md:[![codecov.io](https://codecov.io/github/dandi/dandi-cli/coverage.svg?branch=master)](https://codecov.io/github/dandi/dandi-cli?branch=master)
```
so we could expose CODECOV_TOKEN to that malicious bash script. although I am also not sure why we need it since repo is public.  Anyways, I have updated it to a new (?) value here 

WDYT @jwodder - is that enough or there is some other aspect I am missing? (if all good , just close)

**Comment by jwodder** [comment]
@yarikoptic The only secret that could possibly have been compromised is `CODECOV_TOKEN`, as that's the only one in the environment when the codecov step runs.  I don't see the need for that secret either.
