### ISSUE TITLE
assign cmd- labels to issues/PRs

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#574]
I have used a prefix for issue titles to point to specific component, but those are not easy to filter on.
I have created a set of `cmd-` labels for the issues https://github.com/dandi/dandi-cli/labels?q=cmd- - such setup seems to work nicely in datalad.  Most of the (open) issues should be labeled accordingly.

**Comment by jwodder** [comment]
Done.

**Comment by yarikoptic** [comment]
Thank you!
