### ISSUE TITLE
500 during upload

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#584]
happened on 000003:
```
sub-YutaMouse54/sub-YutaMouse54_ses-YutaMouse54b160701_behavior+ecephys.nwb 25.7 GB                52% ERROR                 Error 500 while sending PUT request to https://dandiarchive.s3.amazonaws...
```
log has
```
2021-04-20T16:15:40-0400 [ERROR   ] dandi 19865:140535826212608 Error 500 while sending PUT request to https://dandiarchive.s3.amazonaws.com/blobs/b2b/6a8/b2b6a8ba-66ce-407b-956d-d36fcfab27e2?uploadId=SENSORED&partNumber=204&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=SENSORED%2F20210420%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20210420T201318Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=content-length%3Bhost&X-Amz-Signature=SENSORED: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>A2WBVWNM8MTP2JFV</RequestId><HostId>YzhuTkXULFtayJ5g1aQykXxSENSORED=</HostId></Error>
```

full log: drogon:/mnt/backup/dandi/upload-logs/20210420191600Z-19865.log

dandi 0.14.1+4.g350843c

Should/could we retry upload for the part? or part upload URL could not be reused and some other mitigation is needed/possible (beyond reupload of the entire file)?

**Comment by jwodder** [comment]
@dchiquito How should the client respond when a 500 error occurs during upload?

**Comment by dchiquito** [comment]
The request was being made to `dandiarchive.s3.amazonaws.com` to upload a part, and the AWS S3 servers returned the 500. I would assume that you can just retry the request in that case. The presigned URL should still be valid, and I would sincerely hope that any AWS 500 errors are transient.

**Comment by jwodder** [comment]
@yarikoptic Currently, the REST client only retries connection errors and 503 responses.  Would it be acceptable to retry all 5xx responses?

**Comment by satra** [comment]
would suggest doing retries (unless you can interpret the error exactly), and perhaps retries with exponential backoff up to maybe 3 times, wherever calls are critical (like uploads).

**Comment by yarikoptic** [comment]
> @yarikoptic Currently, the REST client only retries connection errors and 503 responses. Would it be acceptable to retry all 5xx responses to all requests?

I do not think we should retry for every POST/PUT 500 (might result in some duplicates etc, should be approached consciously I think).  But in the case of S3 upload -- yes, we should.
