### ISSUE TITLE
RM girder support code/logic/instances

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#587]
migration is ongoing - there is no way back to girder and we are not yet supporting some independent installations which might have it. So time to rip it out!

Merge of the PR addressing this should wait until we "stabilize" the migration since currently redirector is not ready and urls might (were?) changed for web ui etc.

**Comment by jwodder** [comment]
(Not sure whom to @-mention for this) The dandi-api Docker image currently requires a `DJANGO_DANDI_GIRDER_API_URL` environment variable to be set that points to a Girder instance.  When will this be removed, thereby allowing the Girder setup to be removed from dandi-cli's tests' docker-compose.yml?

**Comment by jwodder** [comment]
@yarikoptic The "register" command & function are only defined for Girder.  Should they be removed entirely?

**Comment by yarikoptic** [comment]
re `register`: I think so. We will ask users to register online so they have a better chance to provide more detailed metadata record.

re `DJANGO_DANDI_GIRDER_API_URL`: dear @dandi/dandiarchive - docker images seems in need for de-girdification, correct?

**Comment by jwodder** [comment]
@yarikoptic Should the "gui" field of the "dandi-api" instance be updated from https://gui-beta-dandiarchive-org.netlify.app to https://gui.dandiarchive.org?  If so, should the old URL be retained anywhere?

**Comment by yarikoptic** [comment]
May be rename `dandi-api` to `dandi-devel` with only the same api server -- eventually I hope it would become the one for some a dedicated beta instance (with its own api server, redirector etc).

**Comment by jwodder** [comment]
@yarikoptic So rename dandi-api (keeping what fields?), and update the "dandi" instance to point to Django instead of Girder?

**Comment by yarikoptic** [comment]
> @yarikoptic So rename dandi-api (keeping what fields?)

I guess only the `api` since none other relate ATM (web-ui works with the deployed instance of the dandi-api)

> and update the "dandi" instance to point to Django instead of Girder?

yeap -- `None` for girder...

I think overall could be

```
    "dandi": dandi_instance(
        1,
        None,
        "https://gui.dandiarchive.org",
        "https://dandiarchive.org",
        "https://api.dandiarchive.org/api",
    ),
    "dandi-devel": dandi_instance(
        1,
        None,
        "https://gui-beta-dandiarchive-org.netlify.app",
        None,
        None,
    ),
```

Well, `dandi-devel` web ui talks to the current deployed `api` but I think we should disassociate and not mix them in.
