### ISSUE TITLE
add --force to delete to skip for assets not found on the server

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#592]
first deleted one folder, then decided to delete all
```
$> dandi delete sub-anm3*    
2021-04-22 18:00:18,439 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210422220016Z-1515879.log
Error: No assets under path 'sub-anm369962/' found in Dandiset 000029
```

**Comment by jwodder** [comment]
@yarikoptic The name "force" is already used for the (non-CLI) option for skipping the confirmation step.  What should the "skip nonexistent assets" option be named instead?  And should it also apply to nonexistent Dandisets?

**Comment by yarikoptic** [comment]
Ok, yes (may be skip_missing?), and yes
