### ISSUE TITLE
ls -r dandi:// url with /path lists only the dandiset  and not assets

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#598]
```
$> dandi ls -F path -r "dandi://000026"             
[]
2021-04-27 15:38:45,191 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210427193845Z-2089678.log
Error: We do not know how to map URL dandi://000026 to our servers.
Patterns for known setups:
 - DANDI:<dandiset id>
 - https://dandiarchive.org/...
 - https://identifiers.org/DANDI:<dandiset id>
 - https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/<dandiset id>[/<version>][/files[?location=<path>]]
 - https://*dandiarchive-org.netflify.app/...
 - https://<server>[/api]/dandisets/<dandiset id>[/versions[/<version>]]
 - https://<server>[/api]/dandisets/<dandiset id>/versions/<version>/assets/<asset id>[/download]
 - https://<server>[/api]/dandisets/<dandiset id>/versions/<version>/assets/?path=<path>
 - https://<server>[/api]#/dandiset/<dandiset id>[/draft][/files[?_id=<id>[&_modelType=folder]]]
 - dandi://<instance name>/<dandiset id>[@<version>][/<path>]
 - https://<server>/...
```

says that we support `dandi://<instance name>/<dandiset id>[@<version>][/<path>]`  URLs. But if `/<path>` is provided it seems to not how assets:

```shell
$> dandi ls -F path -r "dandi://dandi/000026/sub-I46"   
- asset_count: 1196
  created: '2020-06-24T18:34:50.022000Z'
  metadata:
... 
```
so it uses yaml since a single entry (dandiset) and no assets from under sub-I46 are listed.

Also, whenever some path is provided (even if just the trailing `/`) no dandiset record should probably be shown.

**Comment by satra** [comment]
do you want to support paths at `dandiarchive.org`? we should perhaps consider.

**Comment by yarikoptic** [comment]
> do you want to support paths at `dandiarchive.org`? we should perhaps consider.

<details>
<summary>well, we already do, but apparently not for all types of URIs</summary> 

```shell
$> dandi ls -r 'https://gui.dandiarchive.org/#/dandiset/000027/draft/files?location=sub-RAT123%2F'
- asset_count: 1
  created: '2020-07-08T21:54:42.543000Z'
  metadata:
    access:
    - status: dandi:Open
    contributor:
    - identifier: 0000-0003-3456-2493
      includeInCitation: true
      name: Last, First
      roleName:
      - dandi:Author
      schemaKey: Person
    description: 'Should be ignored by regular mortals.


      ATM contains only a few files from http://github.com/dandi-datasets/nwb_test_data
      which more or less appropriate (do not lack critical metadata) for testing'
    id: DANDI:000027/draft
    identifier: DANDI:000027
    keywords:
    - development
    name: Test dataset for testing dandi-cli.
    repository: https://dandiarchive.org/
    schemaVersion: 0.3.0
  modified: '2020-08-31T21:41:16.957000Z'
  name: Test dataset for testing dandi-cli.
  path: '000027'
  size: 18792
  version: draft
- asset_id: ff453f4c-a435-4a5d-a48b-128abca5ec47
  created: '2021-04-21T09:38:11.327899Z'
  modified: '2021-04-21T09:38:11.327928Z'
  path: sub-RAT123/sub-RAT123.nwb
  size: 18792
```
</details>

**Comment by satra** [comment]
i meant at the redirector level.

**Comment by yarikoptic** [comment]
ah, sure, why not ... but would be useless somewhat until either gui adopts them (no `#`) or dandiarchive.org becomes a reverse proxy on top of `gui.` ;-)

**Comment by jwodder** [comment]
@yarikoptic This is because a path without a trailing slash is treated as an exact path to an asset, and there is no `sub-I46` asset in 000026.  If you invoke the command as `dandi ls -F path -r "dandi://dandi/000026/sub-I46/"` (with trailing slash), you get all of the assets beneath the `sub-I46/` folder.

**Comment by yarikoptic** [comment]
since, unlike girder etc, we do not have a notion of a "directory" -- let's add logic that if `location` is specified, but no assets returned and does not end with `/` -- try the one with `/`.

edited/changed original additional note: Also, whenever some location (path) is provided (but not just the trailing /, which should then include `dandiset.yaml` thus - dandiset meta) no dandiset record should be shown.  So if someone points to a directory - we show that directory assets only

**Comment by jwodder** [comment]
@yarikoptic I'll implement this change as part of #554.

**Comment by jwodder** [comment]
@yarikoptic 

> since, unlike girder etc, we do not have a notion of a "directory" -- let's add logic that if location is specified, but no assets returned and does not end with / -- try the one with /.

This would create issues when determining the path to download an asset to.  Currently, if `download` is given a URL with an asset path component of, say, `foo/bar/baz/`, then the `foo/bar/` is stripped off and the assets are placed in `baz/` in the output directory.  However, if the path is an item path without a trailing slash, it is used as-is, so `foo/bar/baz` gets downloaded to `foo/bar/baz` in the output directory.  The determination of whether to treat a URL as pointing to a single asset or not is based on how it's parsed, and there isn't really any room to indicate whether the asset-retrieval is falling back to treating an item path as a folder path.

**Comment by yarikoptic** [comment]
well, to not introduce such "heterogeneity" ATM let's then do the query with `/` and if returns any asset just crash with e.g.
```
ValueError(f"Provided {url} points to a path} which is a directory but lacks trailing /")
```
My reasoning is: we must not just silently do nothing about the path whenever URL has it: it should be either some analog of `FileNotFoundError` or `ValueError`.

**Comment by yarikoptic** [comment]
probably related:  does not list assets if no path is provided but `-r` given

<details>
<summary>`$> dandi ls -f json_pp -r dandi://dandi/000027/draft/`</summary> 

```shell
{
  "asset_count": 1,
  "created": "2020-07-08T21:54:42.543000Z",
  "metadata": {
    "access": [
      {
        "status": "dandi:Open"
      }
    ],
    "contributor": [
      {
        "identifier": "0000-0003-3456-2493",
        "includeInCitation": true,
        "name": "Last, First",
        "roleName": [
          "dandi:Author"
        ],
        "schemaKey": "Person"
      }
    ],
    "description": "Should be ignored by regular mortals.\n\nATM contains only a few files from http://github.com/dandi-datasets/nwb_test_data which more or less appropriate (do not lack critical metadata) for testing",
    "id": "DANDI:000027/draft",
    "identifier": "DANDI:000027",
    "keywords": [
      "development"
    ],
    "name": "Test dataset for testing dandi-cli.",
    "repository": "https://dandiarchive.org/",
    "schemaVersion": "0.3.0"
  },
  "modified": "2020-08-31T21:41:16.957000Z",
  "name": "Test dataset for testing dandi-cli.",
  "path": "000027",
  "size": 18792,
  "version": "draft"
}

```
</details>

**Comment by jwodder** [comment]
@yarikoptic Is that on the master branch or #605?

**Comment by yarikoptic** [comment]
master as of 0.14.2-33-g914a9cf

**Comment by jwodder** [comment]
@yarikoptic And your desired behavior is that the Dandiset is listed if & only if there is no path in the URL and `-r` is not given, and otherwise (if there is a path *or* `-r` is given) the assets (and only the assets) are listed?

**Comment by yarikoptic** [comment]
yes.  
Note - if `-r` and path points to the top (i.e. empty or just just trailing `/` in dandi://dandi/000027/draft/) - we should list dandiset metadata as well, since it is what we would provide locally for/from `dandiset.yaml`.   if there is a path which limits to some directory -- then indeed no dandiset metadata

**Comment by jwodder** [comment]
@yarikoptic #605 updated.
