### ISSUE TITLE
`dandi ls` should support dandi identifiers

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#600]
currently `dandi ls` does not support dandi identifiers such as below.

```
$ dandi ls DANDI:000008
$ dandi ls DANDI:000008/draft
$ dandi ls DANDI:000008/<version>
```

unfortunately, identifiers.org is not case sensitive, so the above identifiers also work in lowercase.

**Comment by yarikoptic** [comment]
yeah.  ATM decision between PATH vs URL is made based on `is_url`.  Let's generalize to `is_uri` which would be `s.startswith('DANDI:') or is_url(s)` and use that one.

@satra -- we are not adding support for paths in DANDI identifiers.org, right (relates to #598)?

**Comment by satra** [comment]
> we are not adding support for paths in DANDI identifiers.org

yes at present, we are not adding paths to identifiers.org

**Comment by jwodder** [comment]
@satra 

> unfortunately, identifiers.org is not case sensitive, so the above identifiers also work in lowercase.

Meaning that `dandi:000008` should also be supported?

**Comment by satra** [comment]
> Meaning that `dandi:000008` should also be supported?

yes
