### ISSUE TITLE
Add shell completion support and a helper to "activate"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#608]
e.g. in datalad we added
```
  shell-completion
      Display shell script for enabling shell completion for DataLad
```
command so I could just do `source <(datalad shell-completion)` wherever datalad is installed

@jwodder pointed to https://click.palletsprojects.com/en/7.x/bashcomplete/ for click, so might be the one to try/use.

**Comment by yarikoptic** [comment]
I think we should do it.

**Comment by jwodder** [comment]
@yarikoptic Are you sure adding a dedicated subcommand is necessary instead of just following the steps in Click's documentation?

**Comment by yarikoptic** [comment]
to my taste generic doc of fish would be a scary place for a user to figure out what he/she needs to do.  Also there are differences between shells.  With a tiny command we have a chance to streamline it so they could 
- discover they can do it (from `dandi --help` listing of commands)
- discover how they can do it (from `dandi  shell-completion --help`)

I thought that we should be able to detect which shell  they are invoking it from based on SHELL since should be done via `source ` as well, didn't  check, but we should have option `--shell={auto,bash,zsh,fish}` and for auto try to deduce from the environment.

**Comment by jwodder** [comment]
@yarikoptic I presume you want tests for this?  What exactly should they test for?

**Comment by yarikoptic** [comment]
test would indeed be lovely. Here is what we did in datalad: https://github.com/datalad/datalad/blob/HEAD/datalad/interface/tests/test_shell_completion.py  so pretty much smoke test that code runs and produces output, and that it could be sourced.  Do not skip on windows but condition on `distutils.spawn.find_executable('bash')` or alike.

**Comment by jwodder** [comment]
@yarikoptic The tests are failing on GitHub Actions' Windows environments because, even though `bash` is present in the `PATH`, running it fails with "Windows Subsystem for Linux has no installed distributions."
