### ISSUE TITLE
play nicely with datalad datasets: do not download what is already present

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#622]
It seems that download of files from S3 directly using `datalad get` results in files just to have current date/time as mtime.  git-annex version locally is 8.20210223-1~ndall+1 .  And I thought that in general git-annex does preserve mtime as known to remote and we uploaded that key awhile back.  

ATM `dandi-cli` first relies on mtime to decide to either redownload/overwrite the file since default mode is `--existing=refresh` (well - may be not that good of an idea). So I think we should

- ~~check if it is git-annex or our (using URLs from S3) issue which results in files with current date time~~
- [ ] make default `--existing=error` or add `--existing=ask` (should be made to play nicely with pyout). Related: non-interactive confirmations #620 
- [ ] become smart about git-annex: ideally ask datalad about key (could be unlocked, or adjusted branch if on windows) and deduce checksum from key.  If used backend one (we use sha256 ATM) present as digest in asset metadata - we could state "identity" the same and avoid 'refresh' altogether

<details>
<summary>full demo:</summary> 

```shell
(git)lena:/tmp[master]git-annex
$> datalad install -g ///dandi/dandisets/000027
[INFO   ] Scanning for unlocked files (this may take some time)                                                                                                                                                      
[INFO   ] access to 1 dataset sibling dandi-dandisets-dropbox not auto-enabled, enable with:                                                                                                                         
| 		datalad siblings -d "/tmp/000027" enable -s dandi-dandisets-dropbox 
install(ok): /tmp/000027 (dataset)
get(ok): /tmp/000027/sub-RAT123/sub-RAT123.nwb (file) [from web...]                                                                                                                                                  
action summary:
  get (ok: 1)
  install (ok: 1)
(dev3) (dandi-py3.9-troubleshoot) 1 79290.....................................:Fri 07 May 2021 05:54:00 PM EDT:.
(git)lena:/tmp[master]git-annex
$> stat -L 000027/sub-RAT123/sub-RAT123.nwb 
  File: 000027/sub-RAT123/sub-RAT123.nwb
  Size: 18792     	Blocks: 40         IO Block: 4096   regular file
Device: 10305h/66309d	Inode: 16400896    Links: 1
Access: (0400/-r--------)  Uid: (47521/     yoh)   Gid: (47522/     yoh)
Access: 2021-05-07 17:54:00.792805280 -0400
Modify: 2021-05-07 17:54:00.788805286 -0400
Change: 2021-05-07 17:54:00.792805280 -0400
 Birth: 2021-05-07 17:54:00.744805350 -0400
(dev3) (dandi-py3.9-troubleshoot) 1 79291.....................................:Fri 07 May 2021 05:54:10 PM EDT:.
(git)lena:/tmp[master]git-annex
$> ls -l -L 000027/sub-RAT123/sub-RAT123.nwb
-r-------- 1 yoh yoh 18792 May  7 17:54 000027/sub-RAT123/sub-RAT123.nwb
(dev3) (dandi-py3.9-troubleshoot) 1 79292.....................................:Fri 07 May 2021 05:54:19 PM EDT:.
(git)lena:/tmp[master]git-annex
$> dandi download --sync dandi://dandi/000027
PATH                      SIZE     DONE    DONE% CHECKSUM STATUS          MESSAGE         
dandiset.yaml                                             skipped         already exists  
sub-RAT123/sub-RAT123.nwb 18.8 kB  18.8 kB  100%    ok    done                            
Summary:                  18.8 kB  18.8 kB                1 skipped       1 already exists
                                   100.00%                1 done                          
2021-05-07 17:54:49,463 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210507215446Z-3813791.log
(dev3) (dandi-py3.9-troubleshoot) 1 79293.....................................:Fri 07 May 2021 05:54:49 PM EDT:.
(git)lena:/tmp[master]git-annex
$> dandi download --sync dandi://dandi/000027
PATH                      SIZE     DONE    DONE% CHECKSUM STATUS    MESSAGE             
dandiset.yaml                                             skipped   already exists      
sub-RAT123/sub-RAT123.nwb                                 skipped   same time and size  
Summary:                  0 Bytes  0 Bytes                2 skipped 1 already exists    
                          +18.8 kB 0.00%                            1 same time and size
2021-05-07 17:54:54,369 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210507215452Z-3813835.log
(dev3) (dandi-py3.9-troubleshoot) 1 79293.....................................:Fri 07 May 2021 05:54:54 PM EDT:.
(git)lena:/tmp[master]git-annex
$> ls -l -L 000027/sub-RAT123/sub-RAT123.nwb 
-rw------- 1 yoh yoh 18792 Oct 21  2020 000027/sub-RAT123/sub-RAT123.nwb

```
</details>

**Comment by jwodder** [comment]
@yarikoptic 

> check if it is git-annex or our (using URLs from S3) issue which results in files with current date time

Did you leave a word out here, perhaps around "our"?  What issue?  And if it is git-annex or whatever, exactly what should change?

> become smart about git-annex: ideally ask datalad about key

Do you want to add datalad as a dependency of dandi?  That would add a lot of packages to the final installation.

**Comment by yarikoptic** [comment]
> @yarikoptic
> 
> > check if it is git-annex or our (using URLs from S3) issue which results in files with current date time
> 
> Did you leave a word out here, perhaps around "our"?

"our" as of DANDI (somewhere -- client or how we store on s3 or ...)

> What issue? 

the one which opens the description of the issue: "It seems that download of files from S3 directly using datalad get results in files just to have current date/time as mtime."

> And if it is git-annex or whatever, exactly what should change?

probably it is not feasible to expect keys on S3 somehow reflect the original modification time, so `datalad get` would not be able to set it for downloaded files.  So cross-ed out the first item.

So I think we should 
- default to `--existing=error`
- for `--existing=refresh` -- if we detect that we are in a dandiset if/which we are under git-annex (there is `.git/annex` in top directory), error out
- for `--existing=overwrite` get/compare checksum of the file locally with the one in the metadata.  Here we could rely on fscacher'ed digest but before that we could do the similar ad-hoc trick we do in https://github.com/dandi/dandisets/blob/master/tools/backups2datalad.py#L254 to get checksum which annex might know.  And if it is known to digests in metadata -- take that one instead of explicitly computing.  And if the same -- skip as the same.

this is just my thinking, so not set in stone.  WDYT @jwodder ?

> Do you want to add datalad as a dependency of dandi? 

no -- it is too heavy indeed.  Although it could be sensed via `import datalad` and used if present, but let's probably just do ad-hoc analysis although it would work only in some cases.  Then it would just fallback to regular explicit digest computing.
