### ISSUE TITLE
PR changing schema managed to commit/push

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#630]
may be I am just confused.

this one: https://github.com/dandi/dandi-cli/pull/628
and it resulted in https://github.com/dandi/schema/commit/a0e4ca85c39c6c2f69a695708717dbd61cc9707b (I have reverted it since then in `schema` repo) although never merged.

We have:
```shell
$> head .github/workflows/publish-schemata.yml
name: Publish model schemata

on:
  # ATM, this is the closest trigger to a PR merging
  push:
    branches:
      - master
    paths:
      - dandi/model*.py
      - tools/pubschemata.py
```
so may be it is not sufficient somehow to not trigger the workflow or workflow should check that it is not ran for a PR?

it logs in https://github.com/dandi/dandi-cli/runs/2547296311 indeed show that it committed and pushed.

**Comment by jwodder** [comment]
@yarikoptic This is because I accidentally pushed the schema change to master at first before almost immediately undoing it.
