### ISSUE TITLE
Make updates to released schema "conscientious" 

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#631]
Although we have added "protection" mechanism now with #626, which is good on its own. I wonder if we should not directly push within .github/workflows/publish-schemata.yml but rather submit a PR (against schema repo) so it could be reviewed also for the effects of changes to the schema etc.  

Cons:
- If PR doesn't get merged then we might get out of sync between schema in dandi-cli and "released" in `schema`

A possibly better alternative long term might be if we now split away `schema` handling into its dedicated repo, and probably could even be just within `schema` repo, but then it would
- gain its own `auto` for releases, so we would have clear separate release cycles of `dandi-cli` and `schema`
- provide jsonschema rendering upon releases with pushes under `releases/`
  - probably some CI run there should always show what changes since the last version would be at any given state of development?
  - or we could just make it into a separate repo, e.g. `dandi-schema` and keep `schema` only for releases.  May be with `pre-commit` providing current "development" rendering for schema directly within that repo so we could easily assess effects
- entrypoint for `dandi-cli` to use to access pydantic models etc for validation etc.  

WDYT @satra and @jwodder ?

**Comment by yarikoptic** [comment]
sorry - by `schema` I mean https://github.com/dandi/schema (which is the repo with jsonschemas)

**Comment by yarikoptic** [comment]
yeap

**Comment by yarikoptic** [comment]
could also provide a pros: a way to try any given version of dandi-cli with some prior version of that `dandi-schema` in its pydantic form (as long as dandi-cli just needs to operate with basic "stable" structures such as `AssetMeta` etc.

**Comment by satra** [comment]
wherever the library is it will need to support multiple schemas. so that has to start happening. since CLI will likely encounter many different schemas and will have to present to the user dandisets/assets from different versions. as we have discussed with NWB, each instance of Dandiset/Asset needs to conform to its own metadata schema. 

it may make sense to start doing this in it's own repo.

**Comment by yarikoptic** [comment]
how to handle multiple schema versions etc worth its own issue/discussion.  Let's start with #638 move  which will make schema releases just be as any other release and have their own life cycle (and then later discuss how we could support validation of various versions in an issue there)
