### ISSUE TITLE
Move metadata functionality to a dedicated dandischema

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#638]
A dedicated follow up to #631.

After #596 is merged we should split away all schema components into an independent python package. Rationale:

- dandi-cli depends on heavy h5py/hdmf/libhdf5 - complicates considering it for use by dandi-api which wouldn't need those
- we do not have a clean path toward staging metadata schema for a release -- we always release from master as soon as it gets a new version

So the decision was made to split away all the metadata schema (pydantic models, validation of them) into `dandischema`.  All metadata extraction/harmonization from files (nwb and later bids etc) will remain in dandi-cli, but we would validate using functionality moved to `dandischema`.

Attn @satra , @jwodder (not yet assigning since we probably want to have #596 merged first or WDYT?)

**Comment by yarikoptic** [comment]
may be should call it `dandi-schema` and provide python module `dandi_schema`, to not make it into a mouth full of `dandischema` (even though we do still have `dandiarchive`, we have `dandi-api`, `dandi-cli`, etc).  WDYT @satra @jwodder ?

**Comment by satra** [comment]
i would prefer the mouthfull. dandischema is fine i believe.

**Comment by yarikoptic** [comment]
ok, #596 is merged, passing over to @jwodder : please initiate `dandischema` project  and move all corresponding metadata (non-nwb specific -- models, validation etc) functionality and workflows (to release jsonschemas into `schema/`  etc), making `dandi-cli` depending/using it.

**Comment by satra** [comment]
@jwodder - it would be great, not essential, if the history of those files could be preserved.

**Comment by yarikoptic** [comment]
> @jwodder - it would be great, not essential, if the history of those files could be preserved.

I guess `git filter-branch` would be most appropriate, given that we did not have all schema related stuff in a subfolder -- then `subtree` could have been easier to accomplish that -- we used to do that for http://github.com/dandi/dandi-core (README has some details)

**Comment by jwodder** [comment]
@yarikoptic Should `due.py` and related settings be kept?

**Comment by satra** [comment]
i would suggest keeping the schema library as lean as possible with minimal dependencies, so the bare essentials should be targeted.

**Comment by jwodder** [comment]
I've moved the code to https://github.com/dandi/dandischema.

Things that still need to be done:

- Before creating any proper releases with `auto`:
    - [ ] Some revision needs to be tagged (with the version before the desired version for the proper release) and have a GitHub release created for it.  Note that I have tagged the first post-dandi-cli revision as `0.0.0`.
    - [ ] An initial upload to PyPI must be done manually, after which a PyPI token for uploading the project must be saved as a secret named `PYPI_TOKEN`.
- [ ] Add a README
- [ ] Add a `DANDI_GITHUB_TOKEN` secret so that the `publish-schemata.yml` workflow will work.
- [ ] Remove schema code from dandi-schema

**Comment by yarikoptic** [comment]
Sounds good.  Let me know if you lack information (token etc) for any step (I think I shared all we have).
Just a clarification (I also changed from dandi-schema to dandi-cli):

> Remove schema code from dandi-cli (#643)

should make `dandi-cli` depend/use `dandischema`

**Comment by jwodder** [comment]
@yarikoptic @satra So should I release the current code in https://github.com/dandi/dandischema to PyPI now?  What version number should it have?

**Comment by jwodder** [comment]
@yarikoptic I don't know what token dandi-cli used for `DANDI_GITHUB_TOKEN`.

**Comment by satra** [comment]
> So should I release the current code in https://github.com/dandi/dandischema to PyPI now? What version number should it have?

i would decouple the library version number from the schema version number. so let's go with 0.1.0 for the release to PyPI. 

for the README, perhaps just use the following for now. we can update in the next step of PRs.

A Python Library for maintaining and managing DANDI metadata schemas. The library helps create and validate DANDI schema compliant metadata for dandisets and assets.

**Comment by jwodder** [comment]
Project released to PyPI: https://pypi.org/project/dandischema/

**Comment by satra** [comment]
nice work @jwodder - thank you.

**Comment by yarikoptic** [comment]
> i would decouple the library version number from the schema version number. so let's go with 0.1.0 for the release to PyPI.

It makes sense (since it is also a library) but "oh crap" -- we are back in the same boat again ;) it is something I have missed while proposing the split: https://github.com/dandi/dandischema/issues/2

**Comment by yarikoptic** [comment]
> @yarikoptic I don't know what token dandi-cli used for `DANDI_GITHUB_TOKEN`.

I found in the notes one for "access key for updating dandi-schema etc" (says key but looks like a token) so I added that one (to `dandischema` secrets, not sure if works)
