### ISSUE TITLE
Establish con/tinuous setup

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#639]
probably under `dandi@drogon` account along with other cron jobs, to simplify analysis of failing batteries of tests.
AFAIK, should not worry about artifacts for releases (since we don't have any) - just workflows/build logs

**Comment by jwodder** [comment]
@yarikoptic Do you want logs for all workflows saved or just specific ones?  The set of workflows changed recently (9fff44d1117a6134106789126ea86c9b8d5c640a) and will likely change again for #638, but automatic lookup of available workflows hasn't been released yet.

**Comment by yarikoptic** [comment]
- let's release current version of con/tinuous (empty PR or whatever it takes ;-))
- I do not think we need to go retroactively back.  if will be desired -- we will do later.  So can start as of e.g. yesterday (sunday)
- also forgot to mention - let's do subdatasets by year (not by month).  If we do grow too much, we will look into splitting etc, but I think we might be ok. I think I will establish `dandi-logs` organization under which we will push all the goodness eventually using datalad helpers to create all the subdatasets on github, but for now could just live on drogon.

**Comment by jwodder** [comment]
@yarikoptic I've added the "release" label to https://github.com/con/tinuous/pull/48, so we just need to merge that.

**Comment by jwodder** [comment]
@yarikoptic I've set up a cronjob to run every 6 hours that saves dandi-cli logs to `~/cronlib/tinuous-logs/dandi-cli`.

**Comment by yarikoptic** [comment]
- it shouldn't take long to run, should we may be run it each hour?
- shouldn't we add flock to avoid possible conflicts if some eager one of us decides to "fetch now"?

**Comment by jwodder** [comment]
@yarikoptic Changed to once an hour, and flock added.
