### ISSUE TITLE
improve API key check

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#653]
could the cli try to use the API-key to `GET` the `/auth/token` and if it returns the same value the key is valid, if the GET fails due to an authorization error, then the key is invalid. in the latter case,  ask the user to refresh their key and then provide it to the cli.

valid
```shell
$ curl --request GET --header "Authorization: token ${DANDI_API_KEY}" --url \
https://api.dandiarchive.org/api/auth/token/

<DANDI_API_KEY>
```

invalid

```shell
$ curl --request GET --header "Authorization: token ${DANDI_API_KEY}bad" --url \
 https://api.dandiarchive.org/api/auth/token/

{"detail":"Invalid token."}
```

**Comment by yarikoptic** [comment]
Even though I might not completely eliminate possibly desired "reaction" to 401s e.g. during upload etc, I think it would indeed be nice to first do auth "pre-check" for any command which would require authentication (`upload`, `delete`) and request a replacement token if the known is no good before proceeding to the action (which might be parallelized etc).
