### ISSUE TITLE
upgrade to dandischema 0.2.1

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#658]
spotted after adding dandischema to depends of dandi conda feedstock
```
...
2021-06-07T19:42:11.7740941Z     from .metadata import get_metadata
2021-06-07T19:42:11.7742066Z ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/dandi/metadata.py:307: in <module>
2021-06-07T19:42:11.7743071Z     ) -> models.BareAssetMeta:
2021-06-07T19:42:11.7743869Z E   AttributeError: module 'dandischema.models' has no attribute 'BareAssetMeta'
```

and indeed we are still at 0.1.0:
```
setup.cfg:    dandischema ~= 0.1.0
```
Let's progress forward to `~=0.2.1` and release

**Comment by jwodder** [comment]
@yarikoptic Where are you seeing this error message?  Is it part of a test run?  Running the test suite locally with the current code & set of dependencies succeeds for me.

**Comment by jwodder** [comment]
@yarikoptic On further inspection, it appears that `BareAssetMeta` was removed in dandischema 0.2.0.  What version of dandischema was in use for whatever generated that message?

**Comment by jwodder** [comment]
@yarikoptic To be clear: Are you asking me to just update the dependency specification — thinking that alone will solve everything — or are you also asking me to update the dandi-cli code to support dandischema 0.2.1?

**Comment by yarikoptic** [comment]
to "support".  yes - it might be largely about rename of `BareAssetMeta`  to `BareAsset`.  It was 0.2.1 version

**Comment by jwodder** [comment]
@yarikoptic I've run into a bunch of incompatibilities with the new dandischema that are going to take a while to sort out.  For now, I suggest you restrict the dandischema version for dandi-cli 0.19.0 on conda-forge to `<0.2.0`.

**Comment by satra** [comment]
please see this PR https://github.com/dandi/dandi-cli/pull/644

**Comment by yarikoptic** [comment]
Doh, right, so we "just" need to finish up that PR and make up our mind about object id placement. Thank you @satra
