### ISSUE TITLE
age parsing silently ignores value

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#668]
example file: https://gui.dandiarchive.org/#/dandiset/000004/draft/files?location=sub-P10HMH%2F

`'age': '37',`

but after metadata extraction there is no age value for participant. this patch should at least raise an error if not being interpreted.

```python
diff --git a/dandi/metadata.py b/dandi/metadata.py
index 831ca54..b791a9a 100644
--- a/dandi/metadata.py
+++ b/dandi/metadata.py
@@ -250,6 +250,8 @@ def extract_age(metadata):
         try:
             duration = parse_age(metadata["age"])
         except (KeyError, TypeError, ValueError):
+            if metadata.get("age"):
+                raise
             return ...
     else:
         duration = timedelta2duration(start - dob)
```

**Comment by djarecka** [comment]
if `metadata["age"] is "37"`, than `parse_age(metadata["age"])` will raise an error...

**Comment by djarecka** [comment]
oh, wait, I forgot that we catch this in `extract_age`, didn't realize
