### ISSUE TITLE
Default to the dandi instance API url

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#673]
ATM (as as of #660 0.19.0-17-g7d4541f) DandiAPIClient requires API URL to be passed into constructor.  Since the majority (if not 99%) of the use cases would be against our main instance, I think we should make not necessary to explicitly specify API server endpoint.  

But then may be we should still allow to specify the "default instance" for a run.  grep'ing through the codebase I see
```shell
(git)lena:~/proj/dandi/dandi-cli-master[api-01]git
$> git grep DANDI.*INST
DEVELOPMENT.md:- `DANDI_INSTANCEHOST` -- defaults to `localhost`. Point to host/IP which hosts
dandi/consts.py:instancehost = os.environ.get("DANDI_INSTANCEHOST", "localhost")
doc/demos/basic-workflow1.sh:: "${DANDI_INSTANCE:=local-docker}"
doc/demos/basic-workflow1.sh:dandi register -i "$DANDI_INSTANCE" -n "$(basename $SRCPATH)" -D "description"
doc/demos/basic-workflow1.sh:dandi upload -i "$DANDI_INSTANCE"

$> git grep instancehost
dandi/consts.py:instancehost = os.environ.get("DANDI_INSTANCEHOST", "localhost")
dandi/consts.py:        None, None, f"http://{instancehost}:8000/api"
```
but from a brief git log archaeological expedition I don't think we ever supported `DANDI_INSTANCE` env variable to point to the default instance to use.  I think it might be worth bringing it in, and defaulting to `"dandi"` instance, and using its "api" end point.

**Comment by jwodder** [comment]
@yarikoptic Done: https://github.com/dandi/dandi-cli/pull/660/commits/24b46ae6f594aa580544279f6768b73205c65880
