### ISSUE TITLE
need to clarify subject id or parse part of it.

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#68]
This dataset created 87 folders, but there are only 59 subjects: https://dandiarchive.org/dandiset/000004/draft

very likely the NOID* is an appendix to the ID, but would have been impossible for cli to know.

perhaps we can provide an option to clean up IDs during conversion.

**Comment by satra** [comment]
@bendichter - since you are a co-author of this dataset, perhaps you can tell us why the NOID* suffix exists for every subject id.

**Comment by bendichter** [comment]
@satra Good catch. "NOID5" corresponds to the task: "New/Old recognition task for ID: 5," and should not be part of the subject_id. The subject_id should be 9, H09 or P9HMH. I'll report this error to their team.

**Comment by bendichter** [comment]
Opened here: https://github.com/rutishauserlab/recogmem-release-NWB/issues/3

**Comment by yarikoptic** [comment]
> This dataset created 87 folders, but there are only 59 subjects:

I am a bit confused -- I see only those 59 subject folders on https://gui.dandiarchive.org/#/folder/5e6ff4140fe0ec33e6b3d5d2 -- where is the rest? (or was it already fixed up?)

in general, I guess there could be some heuristic in the future glorious `validate` which would alert to obvious problems like that, e.g. if some subject id starts with another subject id.  I do  not think it is for `organize` to do anything like that -- we just should run `validate` at the end and alert about detected possible gotchas so they fix up nwb files.

**Comment by satra** [comment]
@yarikoptic - this dataset was updated - but this issue was not closed.

i don't think organize would have detected it without proper regex for subject id. i saw it based on the abstract of the dataset descriptor paper that there was a mismatch.

**Comment by yarikoptic** [comment]
> but this issue was not closed.

your act says otherwise ;)

> i don't think organize would have detected it without proper regex for subject id

hm... still missing it... but I guess it would be indeed nice to add a regex to check that  subject id doesn't contain any screwy characters, unlike BIDS we haven't yet limited it to alphanumerics

**Comment by satra** [comment]
if you look at the metadata here: https://gui.dandiarchive.org/#/folder/5e7b9e41529c28f35128c741/selected/item+5e7b9e41529c28f35128c743

you will see subject id was modified. so now this dataset correctly has 59 subjects.
