### ISSUE TITLE
increase wait time for aws upload

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#714]
given errors on upload of fragments for a given pre-signed url that is unrelated to actual expiry of the url, the cli could wait longer to see if the upload succeeds. waiting for longer is often more efficient than restarting the upload.

**Comment by yarikoptic** [comment]
what do you mean "waiting for longer"?  
if I get it right -- we just send a PUT request  for that fragment and analyze the returncode... I guess the "low level" code we have is at https://github.com/dandi/dandi-cli/blob/master/dandi/dandiapi.py#L123 :

```python
        # urllib3's ConnectionPool isn't thread-safe, so we sometimes hit
        # ConnectionErrors on the start of an upload.  Retry when this happens.
        # Cf. <https://github.com/urllib3/urllib3/issues/951>.
        doretry = tenacity.retry_if_exception_type(
            requests.ConnectionError
        ) | tenacity.retry_if_result(lambda r: r.status_code == 503)
        if retry is not None:
            doretry |= retry

        try:
            result = try_multiple(5, doretry, 1.1)(
                f,
                url,
                params=params,
                data=data,
                files=files,
                json=json,
                headers=headers,
                **kwargs,
            )
        except Exception:
            lgr.exception("HTTP connection failed")
            raise
```

but may be we somehow stepping into that thread-unsafe invocation and need to establish one of the workarounds for that?

attn @jwodder

**Comment by satra** [comment]
i think i'm simply asking to change either 5 or 1.1 or both to allow for a longer retry period up to a minute. the current set of retries only waits up to a 10s at most i think.

**Comment by yarikoptic** [comment]
ah, gotcha.  @jwodder - any objections and what would be your favorite combination to make it wait up to a minute or so?  unlikely we need to propagate it all the way to become configurable, so I guess we just need to make the curve more "exponential" and may be try a few more times ;-)

**Comment by jwodder** [comment]
@yarikoptic No objections.  Fiddling with the numbers a bit, I find `ntrials=12`, `base=1.25`, which gives a total wait time of 67.76 seconds and a maximum wait between requests of 14.56 seconds.

**Comment by yarikoptic** [comment]
I wonder if in the long run we should even make `requests.ConnectionError` ("cats chew through the wire, need time to run to store and get a replacement") special and allow for those to take nearly whatever it takes to reestablish the connection and get some sensible error or to proceed.  That is what I kinda liked about Globus -- just leave it running and it will eventually succeed, while taking care about all reconnections etc.
