### ISSUE TITLE
Fix RTD build of sphinx docs in master

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#717]
as noted in 
```
WARNING: [autosummary] failed to import 'dandi.tests.fixtures': no module named dandi.tests.fixtures
WARNING: [autosummary] failed to import 'dandi.tests.skip': no module named dandi.tests.skip
```
https://github.com/dandi/dandi-cli/issues/713#issuecomment-881735957

**Comment by yarikoptic** [comment]
hm, it seems to still fail , see e.g. https://readthedocs.org/projects/dandi/builds/14294249/ although did pass the build a few hours back... not sure what is going on

**Comment by yarikoptic** [comment]
also builds seems to come in triples, so some are failing because duplicates, odd

**Comment by jwodder** [comment]
@yarikoptic The "stable" builds are failing because they're building the latest tagged version, which doesn't have #718.  I can't tell why the "latest" build failed.
