### ISSUE TITLE
Support downloading from top level `/assets` endpoint

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#723]
web-ui in the recent past switched to use top level `/assets/<id>/download/` end point for download urls, from previous original one which was bound to a particular dandiset version.  A quick attempt to just add a new url pattern:
```diff
diff --git a/dandi/dandiarchive.py b/dandi/dandiarchive.py
index 6d183f9..41ff4e6 100644
--- a/dandi/dandiarchive.py
+++ b/dandi/dandiarchive.py
@@ -289,6 +289,13 @@ class _dandi_url_parser:
             "https://<server>[/api]/dandisets/<dandiset id>/versions/<version>"
             "/assets/<asset id>[/download]",
         ),
+        (
+            re.compile(
+                rf"{server_grp}api/assets/(?P<asset_id>[^?/]+)/download/?"
+            ),
+            {},
+            "https://<server>/api/assets/<asset id>/download",
+        ),
         (
             re.compile(
                 rf"{server_grp}(?P<asset_type>dandiset)s/{dandiset_id_grp}"
```
is not sufficient since then logic "downstream" expects knowing dandiset, and also needs adjustments.

edit: example url https://api.dandiarchive.org/api/assets/2847011b-f9fb-4933-a6b5-1641e0c1886b/download/                                              
```

**Comment by jwodder** [comment]
@yarikoptic The download process requires the asset's metadata in order to check the digest, but getting the metadata requires knowing the Dandiset and version IDs, which the `/assets/<id>/download/` endpoint does not provide.

**Comment by yarikoptic** [comment]
eh heh -- filed https://github.com/dandi/dandi-api/issues/436

**Comment by yarikoptic** [comment]
removed `blocked`, support is implemented in dandi-api (https://github.com/dandi/dandi-api/pull/450)

**Comment by jwodder** [comment]
@yarikoptic The dandi-api Docker image on Docker Hub seems to have stopped building, so the latest image does not include support for the new endpoint.

**Comment by yarikoptic** [comment]
> @yarikoptic The dandi-api Docker image on Docker Hub seems to have stopped building, so the latest image does not include support for the new endpoint.

doh -- right. I guess we need to setup github action to build/push to docker hub. https://hub.docker.com/repository/docker/dandiarchive/dandiarchive-api shows that it was updated last time 10 days ago. [dandihub](https://hub.docker.com/repository/docker/dandiarchive/dandihub) - 4 days ago.  @satra - did you push it manually?
I remember you @satra mentioned setting up some "open source privileges" with docker for some of the repos etc.  Is that something we could do for `dandiarchive`  organization to bring back automated builds or we are doomed to build in github actions and push?
