### ISSUE TITLE
Move etelemetry logic to become in effect also when used as a Python library

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#726]
ATM we have etelemetry under `cli/command.py:main` so it is only in effect for CLI.  As we will use it now to prevent "bad" versions (https://github.com/dandi/dandi-cli/pull/725), we should make it used consistently between CLI and when used as a Python module.

Not yet sure how to not bother with etelemetry if user does use CLI but merely for `--help` -- I guess it is ok to do all etelemetry checks/etc, but if we are to fail on bad version, we should not bother with etelemetry for "every import".

Since the main rationale is for "interactions with dandiarchive" I think we should 

- make etelemetry check helper a "run once" (so even if invoked multiple times - checks only once)
- keep it at CLI level where it is
- add to top level `DandiAPIClient.__init__` 

@satra - do you foresee any other aspects I forgot, or locations where to do the check? e.g. `organize` in principle also a worthy location to perform the check, but since used most likely through CLI -- should be covered.

**Comment by satra** [comment]
i think CLI is our main use case at the moment, more than library, so i think it should happen in the CLI, but possibly for any command (including ls and organize, which could be affected by schema versions).

once the library is actually released, we can check how to inform user then. in other projects we tend to call it once in init and never gets called again. but is called each time for a python process (but we pass on `NO_ET` to subprocesses).

**Comment by yarikoptic** [comment]
we are using it as a library already in many ad-hoc scripts, and who knows what users do on the hub etc.  library was released from day 1 of the CLI release if not before, we just do not promote it too heavily I guess ;)

`NO_ET` -- hm, we probably should not "alter" behavior for "other libraries", so may be as part of the fix for this issue, @jwodder we should introduce `DANDI_NO_ET` and

- if present - do not do the test
- after test is done, assign it in `sys.environ`

again -- who knows how users would use the beast.  WDYT @satra ?

**Comment by satra** [comment]
sounds good and indeed dandi should use `DANDI_NO_ET`
