### ISSUE TITLE
retry redirect if 400

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#727]
from https://github.com/dandi/dandi-cli/pull/725/checks?check_run_id=3135699904

```
_ test_download_000027_metadata_only[https://dandiarchive.org/dandiset/000027/draft] _
395
dandi/tests/test_download.py:65: in test_download_000027_metadata_only
396
    ret = download(url, tmpdir, get_assets=False)
397
dandi/download.py:59: in download
398
    parsed_url = parse_dandi_url(urls[0])
399
dandi/dandiarchive.py:378: in parse
400
    new_url = cls.follow_redirect(url)
401
dandi/dandiarchive.py:482: in follow_redirect
402
    f"Response for getting {url} to redirect returned {r.status_code}."
403
E   dandi.exceptions.FailedToConnectError: Response for getting https://dandiarchive.org/dandiset/000027/draft to redirect returned 400. Please verify that it is a URL related to dandiarchive and supported by dandi client
```

attn @satra -- may be smth to be tuned up on redirector.  I think this is not first/unique incident

**Comment by jwodder** [comment]
@yarikoptic How many times should it be retried, and with how long of a wait?

**Comment by satra** [comment]
perhaps the same thing we did for the upload connector

**Comment by jwodder** [comment]
@satra What "upload connector"?

**Comment by satra** [comment]
the CLI pr where we extended the tenacity timeout schedule for uploads.

**Comment by jwodder** [comment]
@satra That applied to all requests made with DandiAPIClient, not just uploads.

**Comment by satra** [comment]
are you saying this particular issue is timing out past that set of retries. that seems weird.

**Comment by jwodder** [comment]
@satra No, the "follow redirect" code doesn't use the client.  My point was more that the recent PR applied to more than just uploads.

Regardless, @yarikoptic, how do *you* want the retries to be configured?

**Comment by yarikoptic** [comment]
I have no strong personal preference, just thinking that we should try at least 3 times and at most for 10 seconds .  So 5ish retries at 0.1, 1sec, etc delays should be sufficient. if we run into it again -- we would reconsider
