### ISSUE TITLE
RemoteDandiset download_directory -> download_assets_under_path ?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#732]
since we have get_assets_and_path and `path` there corresponds to a directory .  I think naming should be unified one way or another

**Comment by yarikoptic** [comment]
- just now spotted that there is a `RemoteAsset.download_url` which is a property which provides a url. 
- there is also RemoteAsset.download
- may be should become just `download` with `recursive: bool = False` (raising NotImplementedError for True for now) and defaulting to path `/` (top) ?

**Comment by jwodder** [comment]
@yarikoptic I'm not a fan of merging the two methods into a single `download()`, especially with an unimplemented `recursive` option.  Also, are you still in favor of the name `download_assets_under_path()` given #738?

**Comment by yarikoptic** [comment]
> Also, are you still in favor of the name `download_assets_under_path()` given #738?

apparently not - so we might need both renamed :-/  and as #738 showed, I got a wrong meaning of `download_assets_under_path` from its name... I will think more about it -- WDYT names should be @jwodder ?

**Comment by jwodder** [comment]
@yarikoptic On closer inspection (I thought there was already a separate `download()` method for downloading an entire Dandiset), I'd be fine with renaming to `download()` and defaulting the path to the root.

**Comment by yarikoptic** [comment]
I think there is only `download` for an asset, not a dandiset:

```shell
(git)lena:~/proj/dandi/dandi-cli-master[master]git
$> git describe
0.24.0

$> git grep -p 'def download.*('
dandi/cli/cmd_download.py=class ChoiceList(click.ParamType):
dandi/cli/cmd_download.py:def download(
dandi/dandiapi.py=class RemoteDandiset:
dandi/dandiapi.py:    def download_directory(
dandi/dandiapi.py=class RemoteAsset(APIBase):
dandi/dandiapi.py:    def download_url(self) -> str:
dandi/dandiapi.py:        def downloader(start_at: int = 0) -> Iterator[bytes]:
dandi/dandiapi.py:    def download(
dandi/download.py=lgr = get_logger()
dandi/download.py:def download(
dandi/download.py:def download_generator(
dandi/tests/test_dandiapi.py=def test_publish_and_manipulate(local_dandi_api, monkeypatch, tmp_path):
dandi/tests/test_dandiapi.py:    def downloaded_files():
```

**Comment by jwodder** [comment]
@yarikoptic So what exactly do you want done for this issue?

**Comment by yarikoptic** [comment]
I think "nothing" for now.  This method is used only internally in a single test

```shell
(git)lena:~/proj/dandi/dandi-cli-master[master]git
$> git grep -p download_directory      
dandi/dandiapi.py=class RemoteDandiset:
dandi/dandiapi.py:    def download_directory(
dandi/tests/test_dandiapi.py=def test_upload(new_dandiset: SampleDandiset, simple1_nwb: str, tmp_path: Path) -> None:
dandi/tests/test_dandiapi.py:    d.download_directory("", tmp_path)

$> git describe
0.35.0-207-g533eeb9
```

In general we should strive to have a single implementation for download, but current `dandi.download.download` is heavily CLI oriented etc.  Let's close this issue for now
