### ISSUE TITLE
DandiAPIClient.number_of_dandisets

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-cli#752]
This is minor but I'd like to do

```python
from tqdm import tqdm
from dandi.dandiapi import DandiAPIClient

with DandiAPIClient() as client:
    for dandiset in tqdm(client.get_dandisets()):
        # do stuff here
```

`tqdm` works like this but it would work better if I knew the number of dandisets, which I can't get from `client.get_dandisets()` because it returns a generator that does not have a `len` property. I could convert it to a list, but it seems like that is hitting the API more than necessary. Could we add a method for something like `DandiAPIClient.number_of_dandisets`?

**Comment by yarikoptic** [comment]
>  I could convert it to a list, but it seems like that is hitting the API more than necessary. 

Not really if you are too go through the loop anyways. So I would just do that. I don't think getting a dedicated method for just the number of dandisets would really help anything

**Comment by bendichter** [comment]
I ran into this problem again. Aggregating metadata across all dandisets can take ~30 seconds and I think it would be nice to have a progress bar. I'm not able to create a progress bar because I don't know how many dandisets there are. Would it be possible to add this feature? I'd like to be able to run:

```python
from tqdm import tqdm
from dandi.dandiapi import DandiAPIClient

with DandiAPIClient() as client:
    for dandiset in tqdm(client.get_dandisets(), total=client.number_of_dandisets):
        # do stuff here
```

**Comment by yarikoptic** [comment]
just do not use generator form - make it into a list of dandisets, try:

```
from tqdm import tqdm
from dandi.dandiapi import DandiAPIClient
from time import sleep

with DandiAPIClient() as client:
    for dandiset in tqdm(list(client.get_dandisets())):
        # do stuff here
        sleep(0.001)
```

**Comment by bendichter** [comment]
ok, this was much faster than I thought it would be

**Comment by yarikoptic** [comment]
;) hopefully we will enter some bright future at some point when listing would take considerable amount of time, but then it would still remain negligible to "do-ing stuff"  ;)
