### ISSUE TITLE
provide main modules docstring describing their purpose, giving some example

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#755]
Part of #731

example could be a "poor man search + get" along the lines of
- go through all dandisets
- list assets which have `two-photon` in their `metadata.measurementTechnique[].name`
- download those assets (under the path `{dandiset}/{path_within_dandiset}`

**Comment by jwodder** [comment]
@yarikoptic 

> list assets which have `two-photon` in their `metadata.measurementTechnique[].name`

Note that, as asset metadata is not guaranteed to be valid, retrieving asset metadata as a `dandischema.models.Asset` is not guaranteed to work.  How should the example handle this?

**Comment by yarikoptic** [comment]
Look only through published versions of dandisets -- those should have all metadata valid (either dandischema can load gracefully older versions is an independent topic, let's assume it can)

**Comment by yarikoptic** [comment]
if you see (an)other nice example, would be as fine

**Comment by jwodder** [comment]
@yarikoptic Exactly what modules do you want documented, and in how much detail?

**Comment by yarikoptic** [comment]
for now no great detail, but "large picture" and some examples of how you would work via new API , i.e. via `DandiAPIClient` and returned datatypes (such as `RemoteDandiset` and `RemoteAsset`).

**Comment by jwodder** [comment]
@yarikoptic Could you elaborate on what exactly you want?  And for what modules?

**Comment by yarikoptic** [comment]
For https://github.com/dandi/dandi-cli/blob/master/dandi/dandiapi.py so that someone who runs pydoc or `?` in ipython on that module knows what that module is about and see some example on how it could be used.    I am not saying to go into such gory details or use same formatting but see e.g. https://github.com/numpy/numpy/blob/HEAD/numpy/polynomial/__init__.py https://github.com/numpy/numpy/blob/HEAD/numpy/__init__.py and other `__init__` files in numpy -- such docstrings allow for user to get a good idea on how to use any particular (sub)module and also get rendered by sphinx into docs.

Ideally that documentation should be doctested as part of the tests run.
