### ISSUE TITLE
issues with test_parse_api_url tests

### ISSUE THREAD

**Issue by djarecka** [dandi/dandi-cli#773]
One of the test is not able to finish (waiting 5min+, tried a couple of times) on my OSX (py3.8):
dandi/tests/test_dandiarchive.py::test_parse_api_url[DANDI:000027-parsed_url10]

**Comment by jwodder** [comment]
@djarecka Is this still occurring?

**Comment by djarecka** [comment]
no it  looks it's fine now (at least on my new laptop)
