### ISSUE TITLE
Consider/use typer for CLI/Python API?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#791]
On my way to NYC I have listened to the podcast (may be it was this one https://talkpython.fm/episodes/show/284/modern-and-fast-apis-with-fastapi) and discovered `typer`: "Typer, build great CLIs. Easy to code. Based on Python type hints."

I think it might be a nice match for dandi-cli and beyond to "replace" (it uses `click` underneath) `click` to
- avoid duplication of params specification in decorators AND function signature
- **provide both Python and CLI interfaces to the same functionality**! (which click AFAIK doesn't give us)
- there is automated shell completion support for virtually all used shells -- quite nice

Here is an example from https://typer.tiangolo.com/#an-example-with-two-subcommands which I ran from CL, and also imported as python module in 

<details>
<summary>the example and use in CLI, python, ipython</summary> 

```shell
lena:~/proj/dandi/trash
$> cat trytyper.py
#!/usr/bin/env python3
import typer

app = typer.Typer()


@app.command()
def hello(name: str):
    """hello docstring

    very long
    """
    typer.echo(f"Hello {name}")


@app.command()
def goodbye(name: str, formal: bool = False):
    """goodbye will be short"""
    if formal:
        typer.echo(f"Goodbye Ms. {name}. Have a good day.")
    else:
        typer.echo(f"Bye {name}!")


if __name__ == "__main__":
    app()
1 18481.....................................:Wed 06 Oct 2021 11:59:37 AM EDT:.
lena:~/proj/dandi/trash
$> ./trytyper.py goodbye --help
Usage: trytyper.py goodbye [OPTIONS] NAME

  goodbye will be short

Arguments:
  NAME  [required]

Options:
  --formal / --no-formal  [default: False]
  --help                  Show this message and exit.
1 18482.....................................:Wed 06 Oct 2021 12:00:00 PM EDT:.
lena:~/proj/dandi/trash
$> ./trytyper.py goodbye --formal me
Goodbye Ms. me. Have a good day.
1 18483.....................................:Wed 06 Oct 2021 12:00:07 PM EDT:.
lena:~/proj/dandi/trash
$> python3 -c 'import trytyper as m; m.goodbye("me", True)'
Goodbye Ms. me. Have a good day.
1 18484.....................................:Wed 06 Oct 2021 12:00:16 PM EDT:.
lena:~/proj/dandi/trash
$> ipython3
Python 3.9.7 (default, Sep  3 2021, 06:18:44) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import trytyper as m

In [2]: m.goodbye?
Signature: m.goodbye(name: str, formal: bool = False)
Docstring: goodbye will be short
File:      ~/proj/dandi/trash/trytyper.py
Type:      function

In [3]: m.hello?
Signature: m.hello(name: str)
Docstring:
hello docstring

very long
File:      ~/proj/dandi/trash/trytyper.py
Type:      function

In [4]: m.hello??
Signature: m.hello(name: str)
Source:   
@app.command()
def hello(name: str):
    """hello docstring

    very long
    """
    typer.echo(f"Hello {name}")
File:      ~/proj/dandi/trash/trytyper.py
Type:      function

In [5]:                                                                                                   
Do you really want to exit ([y]/n)? 
1 18485.....................................:Wed 06 Oct 2021 12:00:48 PM EDT:.
lena:~/proj/dandi/trash
$> ./trytyper.py --help
Usage: trytyper.py [OPTIONS] COMMAND [ARGS]...

Options:
  --install-completion [bash|zsh|fish|powershell|pwsh]
                                  Install completion for the specified shell.
  --show-completion [bash|zsh|fish|powershell|pwsh]
                                  Show completion for the specified shell, to
                                  copy it or customize the installation.

  --help                          Show this message and exit.

Commands:
  goodbye  goodbye will be short
  hello    hello docstring very long
```
</details>

so the only gotcha I spotted right away in above with typer 0.3.2-1 in Debian -- multiline docstring was not shown in ipython for `?`.

WDYT @jwodder ?

**Comment by jwodder** [comment]
@yarikoptic 

> avoid duplication of params specification in decorators AND function signature

To an extent.  If you want to give an option both a long and a short form (like `-e`/`--existing`), typer requires you to write out the name of the option twice: `def func(existing: bool = typer.Option(False, "-e", "--existing"))`.

> provide both Python and CLI interfaces to the same functionality!

Only for the most trivial commands.  If you want an option to have something as simple as help text, you lose the ability to have a default argument when called like a function (regardless of whether you apply an `app = typer.Typer()` decorator or not).  For example, given the following module:

```python
import typer

app = typer.Typer()

@app.command()
def func(foo: str = typer.Option("bar", help="What to foo")) -> None:
    print(f"{foo=}")

if __name__ == "__main__":
    typer.run(func)
```

`foo` will be `"bar"` when the script is run as a command without any arguments, but if you call `func()` directly, you get:

```
foo=<typer.models.OptionInfo object at 0x103414d60>
```

There's also the fact that typer doesn't support defining options as reusable decorators.  In a related vein, you can't use environment variables like `DANDI_DEVEL` to control whether an option exists.  The best ways I can think of to reimplement `DANDI_DEVEL` with typer are to either do something like this:

```python
if os.environ.get("DANDI_DEVEL"):
    def download(
        ### all the public options go here
        dandi_instance: str = typer.Option("dandi", "--dandi-instance, "-i"),
        ### any other devel options go here
    ):
        _download(**public_options, **devel_options)
else:
    def download(
        ### all the public options again
    ):
        _download(**public_options, dandi_instance="dandi", ...)
```

or just set the options' `hidden` configuration to `bool(os.environ.get("DANDI_DEVEL"))` so that they are usable regardless of the value of `DANDI_DEVEL` but only show up in `--help` output when the envvar is set.

**Comment by yarikoptic** [comment]
Thank you @jwodder for a very fine cold shower ;)

**Comment by yarikoptic** [comment]
with that in mind, let's just close
