### ISSUE TITLE
Network sandboxing for tests doesn't work, in spite of `DANDI_TESTS_NONETWORK=1`

### ISSUE THREAD

**Issue by TheChymera** [dandi/dandi-cli#796]
I get the following failures while running the tests in the network sandbox: https://ppb.chymera.eu/8a10b2.log
This is with `DANDI_TESTS_NONETWORK=1` exported in the environment, but a lot of tests using `curl` etc. don't seem to be skipped.

In any case, not high priority, no tests fail if run as user now, but it would be good to have this sorted out so we can distribute dandi-cli it for Gentoo.

Maybe there's a better way to skip them (other than skipping them manually, I mean :) )?

**Comment by yarikoptic** [comment]
Is localhost available in such sandbox env?
