### ISSUE TITLE
Replace auto with GitHub's automatically generated release notes?

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-cli#805]
GitHub [recently added](https://github.blog/2021-10-04-beta-github-releases-improving-release-experience/#introducing-auto-generated-release-notes) the ability to automatically generate release notes when creating a release, which could theoretically almost entirely replace auto.  We'd just need a new GitHub Actions workflow that creates a tag, creates a GitHub release with autogenerated release notes using the GitHub API, and builds & uploads the project to PyPI.  The only problem would be triggering the workflow; the best option I can think of is to make the workflow manually triggered via a workflow dispatch event, but no matter what we pick, it seems we'd lose auto's ability to autodetermine the new version.

**Comment by jwodder** [comment]
On further investigation, it may be possible to autogenerate the CHANGELOG entry before creating the release using [this API endpoint](https://docs.github.com/en/rest/reference/repos#generate-release-notes-content-for-a-release).

**Comment by satra** [comment]
@jwodder - is there a reason not to continue using auto ?

**Comment by jwodder** [comment]
@satra It has a notable design flaw that makes it very difficult to integrate extra actions while also making releases with large changelogs.

**Comment by yarikoptic** [comment]
the issue in question is https://github.com/intuit/auto/issues/1294 . I still hope that some solution would be implemented. If not - indeed it would be worth reimplementing at least in the limited set of functionality we need for our projects.  The cutest/trickiest part is IMHO CHANGELOG construction from labeled PRs.  It would also give a chance to add support for releasing from multiple branches etc.
