### ISSUE TITLE
Bad UX for `dandi download DANDI:000023/0.210914.1900`

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-cli#828]
Attempting to download a Dandiset with a URL of the form `DANDI:{dandiset_id}/{version_id}` causes the client to attempt to access `https://identifiers.org/DANDI:{dandiset_id}/{version_id}`, [which currently does not work](https://github.com/dandi/helpdesk/issues/37#issuecomment-962037772) and produces a 400 response.  The client, due to #762, [responds to this by sleeping for increasing amounts](https://github.com/dandi/dandi-cli/blob/d42938c9793adbd4be654bc159a49235c9a47203/dandi/dandiarchive.py#L661-L664) for a grand total of over 18 and a half minutes, all with no indication to the user as to what it's doing (unless the log level is DEBUG, in which case the user will get occasional messages about HTTP connections but no indication as to the reason for delays in between).  This needs to change.

**Comment by satra** [comment]
at least while identifiers.org is broken, the CLI should translated the url to lowercase.
