### ISSUE TITLE
TwoPhotonSeries with no raw data

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-cli#833]
I would like to be able to filter to only dandisets that have raw data from two-photon experiments. I tried to do this by [searching for `TwoPhotonSeries`](https://gui.dandiarchive.org/#/dandiset/search?search=TwoPhotonSeries), the neurodata_type that holds raw data from two-photon experiments. Several datasets e.g. https://dandiarchive.org/dandiset/000039/0.210902.2328 have 

>Variable Measured: TwoPhotonSeries

but the files are clearly too small to contain such data, and when I open the files they are indeed missing this data. Why is this dandiset being annotated with TwoPhotonSeries?

**Comment by satra** [comment]
because twophotonseries is a neural data type in those datasets. so someone stuck some information under that neural data type in the nwb file. we don't look to assess what's in a neural data type, simply extract any neural data types and stick into variable measured.

**Comment by bendichter** [comment]
Ah, I found it. They (ab)used it here

`nwb.processing['brain_observatory_pipeline'].data_interfaces['max_project']`

to provide a single frame of the max projection. I would have used a `GrayscaleImage` for this.

**Comment by satra** [comment]
perhaps the nwb validator can check to see that anything that's called a series has more than one data point.
