### ISSUE TITLE
Ensure organize (and any other dandi command) produces the log file with INFO level log

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#838]
follow up to https://github.com/dandi/dandi-cli/issues/837#issuecomment-972976801

**Comment by jwodder** [comment]
@yarikoptic Every command produces a log file, including `organize`.  I don't know why that user can't find the logs in question.

**Comment by jwodder** [comment]
@jwodder One possible explanation: The "setting files_mode" message only occurs when running `dandi organize` with the default `auto` file mode.  If the user specified a different mode, the message would not be emitted.

**Comment by emilyasterjones** [comment]
@jwodder The issue isn't that I can't find the logs, it's that the log file `dandi organize` and `dandi upload` produced didn't include information @yarikoptic was expecting.

@yarikoptic I didn't include flags. I just called `dandi organize`.

**Comment by jwodder** [comment]
@emilyasterjones So the complete command you ran was just "`dandi organize`"?  Can you rerun this command on your unorganized Dandiset and provide both the output and log file contents here?  (Also, what version of the client are you using?)

**Comment by yarikoptic** [comment]
I guess it would be a bit too late now to dig out the details of "intriguing" operation back then.  I will close this issue but @emilyasterjones - please follow up if you feel we could improve any behavior/output. Cheers
