### ISSUE TITLE
review dandi-api CI tests against dandi-cli fails 

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#842]
those had been going on for awhile but I didn't track when they began and either they are all related to https://github.com/dandi/dandi-api/issues/567 (which seems to be "occasionally" although I think current state of tests -- "always fail").

Those failures need to be reviewed, relevant issues filed/addressed or followed up upon.

**Comment by jwodder** [comment]
@yarikoptic Are you referring to the failures of [this workflow](https://github.com/dandi/dandi-api/actions/workflows/cli-integration.yml)?  Those appear to only be failing for one PR which changed the set of environment variables needed to bring up the Docker Compose containers.

**Comment by yarikoptic** [comment]
wow, I was wrong -- I was under impression somehow that I saw those integration tests failing generally recently.  But I see master and other PRs green indeed. My bad
