### ISSUE TITLE
identifiers.org no longer seems to recognize "DANDI" namespace

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-cli#847]
dandi-cli's tests have been failing since the fourth due to requests to `https://identifiers.org/DANDI:...` URLs returning 400.  Specifically, the tests try to access https://identifiers.org/dandi:000027 and https://identifiers.org/dandi:000027/0.210831.2033, both of which return 400 with a response body of the form:

    INVALID resolution request for 'dandi:000027', due to 'Resolution request 'dandi:000027' is NOT ABOUT A NAMESPACE; UNKNOWN namespace 'dandi' when verifying local ID '000027''

The problem even occurs when making a request to https://identifiers.org/DANDI:000027 (capitalized).

**Comment by satra** [comment]
i believe this has been resolved.
