### ISSUE TITLE
Add support for uploading embargoed files

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-cli#856]
The dandi-api changes are currently still in draft PRs, but the external API shouldn't change.

* [x] https://github.com/dandi/dandi-api/pull/643 adds an `embargo_status` field to the dandiset list and fetch endpoints. If `embargo_status == "EMBARGOED"`, then any assets should be uploaded as embargoed assets. See https://github.com/dandi/dandi-api/blob/65dc262ea565d03b089cd435c8a0d912638a95ae/doc/design/embargo-mvp.md?plain=1#L64-L74 and https://github.com/dandi/dandi-api/blob/65dc262ea565d03b089cd435c8a0d912638a95ae/doc/design/embargo-mvp.md?plain=1#L108
* When uploading an embargoed asset, `{..., "embargoed_dandiset": "123456"}` should be included in the JSON request body. This will begin an embargoed upload. No other upload endpoints need this additional argument. See https://github.com/dandi/dandi-api/blob/65dc262ea565d03b089cd435c8a0d912638a95ae/doc/design/embargo-mvp.md?plain=1#L142-L155
* Creating an asset from the blob_id will work exactly the same as normal uploads, but this has not yet been implemented.

edit my @yarikoptic, other relevant PRs
- [ ] https://github.com/dandi/dandi-api/pull/647

**Comment by dchiquito** [comment]
The API surface relevant to the CLI has changed a bit:
When uploading ANY asset, {..., "dandiset": "123456"} should be included in the JSON request body. The API server will determine if the dandiset is embargoed or not and upload the data to the appropriate location in the appropriate bucket.

The API server should ignore that field right now, but it will be required as soon as https://github.com/dandi/dandi-api/pull/647 is released. This issue should no longer be blocked.

**Comment by jwodder** [comment]
@dchiquito 

> When uploading ANY asset, {..., "dandiset": "123456"} should be included in the JSON request body

For which request?  `POST /dandisets/{versions__dandiset__pk}/versions/{versions__version}/assets/`?

**Comment by yarikoptic** [comment]
> The API surface relevant to the CLI has changed a bit:
> When uploading ANY asset, {..., "dandiset": "123456"} should be included in the JSON request body. The API server will determine if the dandiset is embargoed or not and upload the data to the appropriate location in the appropriate bucket.

Do you mean that old dandi-cli would no longer upload data?

**Comment by dchiquito** [comment]
Correct, users would need to update.

**Comment by dchiquito** [comment]
> For which request?
@jwodder No, when uploading the asset blob: `/api/uploads/initialize/`
```
    api_client.post(
        '/api/uploads/initialize/',
        {
            'contentSize': content_size,
            'digest': {'algorithm': 'dandi:dandi-etag', 'value': etag},
            'dandiset': dandiset.identifier,
        },
        format='json',
    )
```

**Comment by jwodder** [comment]
@dchiquito

* How will that work when uploading Zarrs, which don't use that endpoint?
* Is the addition of the "dandiset" field to `/uploads/initialize/` the only net change to the API that the client needs to be aware of now?

**Comment by dchiquito** [comment]
Embargoed zarrs have not been implemented yet, we are focusing on nailing down zarr and normal embargo first.

Yes, specifying the dandiset in `/uploads/initialize/` should be the only change required in the CLI to upload embargoed data.

**Comment by dchiquito** [comment]
> Is the addition of the "dandiset" field to /uploads/initialize/ the only net change to the API that the client needs to be aware of now?

A slight correction: it's the only change necessary right now for normal asset embargo, but there will be some more small changes to support zarr embargo (assuming the CLI already has zarr support). It might be a good idea to include a useful error message like "embargoed zarr isn't supported in this CLI version, please update" if they are ever encountered. 

@jwodder @yarikoptic

**Comment by jwodder** [comment]
@dchiquito 

> It might be a good idea to include a useful error message like "embargoed zarr isn't supported in this CLI version, please update" if they are ever encountered.

If what are ever encountered?  Are you suggesting checking the embargo status of Dandisets when performing an upload just for the purposes of this intelligent error message?

**Comment by dchiquito** [comment]
I am suggesting checking for zarr files in an embargoed dandiset, yes. If this check is not present, then once embargoing zarr is implemented, an outdated CLI would naively upload the zarr file publicly, then add it to the embargoed dandiset, which defeats the whole purpose of embargo.

**Comment by jwodder** [comment]
@dchiquito Just to be clear, a Dandiset should be considered embargoed iff its `embargo_status` is `"EMBARGOED"`, and not for other values, correct?

**Comment by dchiquito** [comment]
Right now the possible states are `EMBARGOED`, `UNEMBARGOING`, and `OPEN`. `UNEMBARGOING` means that the dandiset is currently locked and will not accept any changes, so the CLI can either yield a special error message or just let the API fail.

Soon-ish we will also be adding a `RESTRICTED` state that for the purposes of upload also means that the data in the dandiset is embargoed.
