### ISSUE TITLE
Call dandi_authenticate() during dandi download

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-cli#867]
Presently, `dandi_authenticate()` is only done on modification operations, i.e. `upload` or `delete`. To read embargoed dandisets, the API server needs to know who is requesting data, so `dandi_authenticate()` also needs to be called during `download`.

**Comment by jwodder** [comment]
Should this always be done, or should it only happen if a certain `--embargoed`/`--anonymous` (or `--auth`/`--no-auth` or whatever) option is given/not given?

CC: @yarikoptic

**Comment by dchiquito** [comment]
https://github.com/dandi/dandi-cli/blob/433380a07d01a8fd859b98a00c89141ddc4cd960/dandi/dandiarchive.py#L146-L147 is at least one of the places that `dandi_authenticate` needs to be called.

**Comment by yarikoptic** [comment]
Ideally authentication should be requested only if http return code instructs to do so, so HTTP return code 401 (requires authentication). I don't think that ATM we should do that on 403 (Forbidden) which would mean that user doesn't have credentials provided specifically for the requested resource.

**Comment by jwodder** [comment]
@yarikoptic Why not request authentication iff the Dandiset's data indicates it's embargoed instead of relying on response codes?

@dchiquito What exactly is returned currently if an unauthenticated request is made to `GET /dandisets/{versions__dandiset__pk}/versions/{versions__version}/assets/`?

**Comment by dchiquito** [comment]
@jwodder Right now it is a 200 with this body:
```json
{
  "count": 0,
  "next": null,
  "previous": null,
  "results": []
}
```
In #869 there is discussion of changing it, however.

**Comment by yarikoptic** [comment]
> @yarikoptic Why not request authentication iff the Dandiset's data indicates it's embargoed instead of relying on response codes?

I feel that relying on "standard" response codes would make it more robust.  E.g. would we need to adjust code if later we introduce some "restricted" dandisets?  Also it allows for per-asset control of needing authentication or not: e.g. if some assets of interest in embargoed dandiset are "public" (I believe current implementation allows for that and such assets could be downloaded without authentication) -- why should we require authentication?

**Comment by jwodder** [comment]
@yarikoptic

> if some assets of interest in embargoed dandiset are "public"

How would the API work in that case?  If an embargoed Dandiset has public assets, then I would expect a request to its `../assets/` endpoint to list only the public assets, in which case there would be no reason to make a request that would result in a 401.

**Comment by yarikoptic** [comment]
100$ questn ;-) i guess the same 401/403 regardless if any asset is public as long as dandiset is not.

**Comment by dchiquito** [comment]
AFAIK this is the only remaining blocker for releasing embargo. It seems like the easiest path forward would be to simply send Authorization headers on all requests if they are available. @jwodder @yarikoptic are you asking for the API to respond with a 401 rather than 404 on all embargo endpoints if the user is not logged in? That is a non-trivial change that will take me some time to add, and the deadline is looming.

**Comment by jwodder** [comment]
@dchiquito What does "if they are available" mean?  Getting an API key can potentially involve prompting the user for input — possibly even when just trying to query the keyring.  Doing that every time a command is run seems like bad UX.

**Comment by yarikoptic** [comment]
> @jwodder @yarikoptic are you asking for the API to respond with a 401 rather than 404 on all embargo endpoints if the user is not logged in?

401 or 403 to be exact. Ref: https://github.com/dandi/dandi-archive/issues/669

agree with @jwodder on UX concern.  What we could do interim may be - do authenticate unconditionally iff `DANDI_API_KEY` env var is set, and let people know about such necessity. Wdyt @jwodder ?  But in the longer run I do think we need proper return codes to react to

**Comment by dchiquito** [comment]
I had assumed that the keyring/env var were "free" and could be checked and included without user intervention. If they are costly UX wise then I agree that the API should be used to mitigate that.
I'm still working on the zarr embargo feature though. so if there is a short-term fix that would be ideal. I would be fine with "requiring" `DANDI_API_KEY` for now and documenting that clearly in the embargo instructions.

**Comment by jwodder** [comment]
@yarikoptic @dchiquito Are public assets in embargoed Dandisets a thing that needs to be supported?  If yes, then I would expect unauthenticated requests to `.../assets/` to always return 200 (assuming the Dandiset & version exist) with a list of public assets, and in that case we would be unable to use return codes or embargo status to decide whether authentication is needed; `dandi download` would then need explicit an `--auth` (or whatever) option in order to enable downloading of embargoed assets.

If embargoed Dandisets cannot have public assets, then the client should be able to detect whether authentication is needed for a download based on the embargo status of the Dandiset, in which case we could triggre the ususal authentication routines.

In the long term, I think we should toss the whole keyring thing and add a "login" command that stores an API key in plain text in a config file somewhere, which is what things like [GitHub's official client](https://github.com/cli/cli) do.

**Comment by jwodder** [comment]
@satra That seems to suggest that an individual version would be composed of either all public assets or all embargoed assets, not a mix of the two, which is what I meant.

**Comment by satra** [comment]
it can be a mix. i publish and turn the draft into embargoed state and add new assets. the new assets would be embargoed, the existing assets from the draft would be public.

**Comment by dchiquito** [comment]
@jwodder I think it would be fine to return a 401 from `api/dandisets/{did}/versions/{vid}/assets/` if the version is embargoed, even if it contains assets that are public. The 401 would indicate that the client does not have permission to see which assets belong to that version, even though the client could access those assets directly through other API endpoints.

>In the long term, I think we should toss the whole keyring thing and add a "login" command that stores an API key in clear text in a config file somewhere, which is what things like GitHub's official client do.
:+1: I like the idea of a `dandi login` that lets users adjust their API keys at will

**Comment by yarikoptic** [comment]
> @yarikoptic @dchiquito Are public assets in embargoed Dandisets a thing that needs to be supported? If yes, then I would expect unauthenticated requests to `.../assets/` to ...

I [keep thinking](https://github.com/dandi/dandi-cli/issues/867#issuecomment-1015782661) API should just return 401/403 for embargoed regardless either it has any (or all) public assets.  Returning only public (if non-auth) could lead to undesired data disappearance (download dandiset forgetting to `--auth`, add asset, upload with --sync)

**Comment by satra** [comment]
> API should just return 401/403 for embargoed regardless 

i think the challenge is not for things that have a notion of embargoed (e.g., upload to an embargoed dandiset), but for direct asset download links, where it's not known if the asset is in an embargoed dataset. a public asset is public, it's presence in an embargoed dandiset is irrelevant. so 401/403 should only apply to endpoints that have direct notion of dandiset information i.e under `/dandiset` or asset id, where it's known if the asset is in public or embargoed bucket.

**Comment by yarikoptic** [comment]
@satra I think we are on the same page ;) discussion above was primarily about `/api/dandisets/{did}/versions/{vid}/assets/` end point listing assets of an embargoed dandiset. so - it would have "direct notion".

**Comment by dchiquito** [comment]
https://github.com/dandi/dandi-archive/pull/831 will make it so that 401 is always returned when querying embargoed stuff without authenticating, and 403 is always returned when querying embargoed stuff without having ownership of the dandiset.
