### ISSUE TITLE
Login when downloading embargoed dandisets

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-cli#869]
When testing embargoed upload I had some problems with authentication. I was using a fresh installation (so no existing login info) and trying to upload a a new embargoed dandiset.
Normally the first step to upload data is to do a `dandi download` of the dandiset to initialize the directory, but when you `dandi download` an embargoed dandiset, it gives an error 404. This is expected as the dandiset is not visible to unauthenticated users, but the CLI does not prompt the user to log in.

I resolved the issue by specifying `DANDI_API_KEY` as an environment variable, but the UX around that isn't great. 

Some options:
* Add a `dandi login` command that prompts the user for their API key and saves it in the keyring for later use. In whatever embargo documentation we have, tell users that they should run that if it ever appears that their embargoed dandisets do not exist. Perhaps print a warning to that effect in the 404 error message in the CLI.
* As discussed in https://github.com/dandi/dandi-cli/issues/867#issuecomment-1014737524, require an `--embargoed` flag that ensures the user is authenticated whenever dealing with embargoed dandisets.
* Make the API server return error 401 unauthorized instead of 404 not found for embargoed dandisets. When the CLI encounters that 401 it should prompt for login. For various reasons this isn't very convenient in Django, but it can be done.

attn @yarikoptic

**Comment by yarikoptic** [comment]
I would not mind `dandi login` option but I think that the latter (401/403) would be the most kosher way to implement interactions. References:  https://github.com/dandi/dandi-archive/issues/669 and https://github.com/dandi/dandi-cli/issues/867#issuecomment-1015671225 .

**Comment by yarikoptic** [comment]
I think this issue is redundant now that #867 has a way forward (401/403 return codes from API), so we can just say that the latter way is our agreed way forward on this. Please reopen if I am mistaken
