### ISSUE TITLE
RemoteDandiset.delete - add `*, all_versions: bool=False`?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#873]
IMHO seems to be a use case for any test fixture to clean up after itself, so would be suboptimal to re-implement such looping each time?

**Comment by jwodder** [comment]
@yarikoptic
* This would not be used in dandi-cli's fixtures, as they keep the Dandisets around rather than deleting them so that they can be inspected afterwards in the Docker Compose setup if necessary.
* This would not be useful for general users, as only admins can delete versions.

**Comment by yarikoptic** [comment]
ok, let's postpone until another need arises
