### ISSUE TITLE
Modify Zarr assets in-place when uploading to an extant Zarr path

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-cli#884]
Currently, when a Zarr is uploaded to a remote path where a Zarr asset already exists, a new Zarr asset is created from scratch, which involves uploading all of the files in the Zarr.  The client should instead optimize for the common case (a Zarr being reuploaded after some local modifications) by modifying the Zarr asset already on the server, only uploading new & changed Zarr entries and deleting any old ones.

CC @dchiquito: Just to confirm, this is a reasonable thing to implement, right?  Can a Zarr object be modified after it's made into an asset, and does the server correctly handle modification of Zarr data that multiple assets point to?

**Comment by dchiquito** [comment]
Yes, Zarr archives behave differently from asset blobs in that respect. They are long-lived, mutable objects that can and should be modified after being added to assets.

**Comment by yarikoptic** [comment]
extra note: zarr becomes immutable when it is included in a published version of a dandiset.  IIRC we floated different ideas on how to proceed with changing a published zarr (e.g., creating a copy, relying on versionIds etc) any of which AFAIK is yet implemented, right?

**Comment by dchiquito** [comment]
Currently zarrs are just mutable all the time, but you are correct that published zarrs should and eventually will be immutable.
