### ISSUE TITLE
provide "update zarr" functionality

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#906]
zarr folders are heavy, and likely to fail to upload at any specific point in time and would need to be "continued" or "fixed up" (that is our C2 in #903).

Also relates to https://github.com/dandi/dandi-cli/issues/903 as possibly solution might incorporate "in band" compute of the checksum across files to be uploaded (or not).

We need to

- generate an asset immediately when we initiate a new `zarr_id` -- that would associate a given dandiset (id) and zarr path with a `zarr_id` so we could re-upload
- when we encounter already existing zarr asset for the path, we should not initiate a new zarr but modify existing
  - unless it is completely empty (all of those have the same checksum; but also size 0 and filenumber 0) we need to
    - get a list of files in the zarr
    - get a list of files locally
    - for those which are present on both, compare checksums
    - "schedule" the ones missing or different on the server to be uploaded
    - after uploads complete, remove files which are not present locally but present remotely
  - if it was completely empty, we can avoid getting a list and assume it is `[]` and proceed with the same algorithm really, so no need of special casing

**Comment by jwodder** [comment]
@yarikoptic Problem: If a Zarr contains a file at, say, `foo/bar/baz` and a later update tries to upload a file to `foo/bar/baz/quux`, then ... I actually don't know what will happen, but I doubt it'll be good.  There does not seem to be a way to guard against this at the moment other than checking the remote file-ness of every ancestor of every Zarr entry being uploaded, which seems excessive.

**Comment by satra** [comment]
in the short term for initial uploads we should consider that the local dataset is not undergoing modifications, and there is only one upload operation. 

simple process: for each file, check if file exists (i.e. exists and etag matches). upload only if one or more of those checks fail.

the process we were hoping with checksums for general updates:
- some treehash checking would first tell us what the differences are between local and remote (additions/deletions/changes). then one would perform all these operations.
- since s3 only has keys and no concept of directories, there is no consideration of directories other than as an optimization for tree hash checking. i.e. one can ignore objects below a certain node if the node checksums match.

**Comment by yarikoptic** [comment]
@jwodder 

> Problem: If a Zarr contains a file at, say, `foo/bar/baz` and a later update tries to upload a file to `foo/bar/baz/quux`, then ... I actually don't know what will happen, but I doubt it'll be good.

I don't think anything bad would happen since IIRC S3 doesn't care and I think there could be both `foo/bar/baz` and `foo/bar/baz/quux` keys, so we could upload the new `foo/bar/baz/quux` first and remove `foo/bar/baz` key later - I don't think it would remove all keys which start with `foo/bar/baz`. But worth checking ;)

@satra 

> in the short term for initial uploads we should consider that the local dataset is not undergoing modifications, and there is only one upload operation.

I don't think we even need such an assumption since it doesn't simplify our life much since I believe we do have API for delete and listing of remote zarr structure.  Indeed optimizing (later or right away, I will let @jwodder to decide either to do in a single PR or in 2 ;) ) for using tree hash instead of getting a complete list would be preferable.

**Comment by jwodder** [comment]
@yarikoptic It turns out S3 (or at least minio) won't let you upload to `foo/bar/baz/quux` if `foo/bar/baz` is already a file.  I managed to handle this in the latest commit.
