### ISSUE TITLE
organize: provide cmdline options for explicit number_ values

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#91]
per our zoomchat with Tom, he recommended to let users specify target numbers of subjects etc they expect in the dandiset.  So might be worth adding an option to `organize`.  for "validate" separate issue #90

**Comment by yarikoptic** [comment]
@satra -- do you think we better still have that or just remove all `number_` tuning from `organize` (which I thought we would do)?

**Comment by satra** [comment]
i would remove number tuning. all of this should happen on the server side from the asset metadata.

**Comment by yarikoptic** [comment]
I think we no longer do that since stats computed on server now
