### ISSUE TITLE
Add VIDEO_FILE_EXTENSIONS into the "default" set

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#920]
part of https://github.com/dandi/dandi-cli/issues/918 by @Saksham20 .  to avoid needing DANDI_DEVEL modes of operation on video files, we should treat them as 1st class citizens for `organize` and `upload` operations

**Comment by jwodder** [comment]
@yarikoptic In what way are they not "first class citizens" for `organize`?  What behavior change is needed there?

**Comment by yarikoptic** [comment]
#841 by @Saksham20 I believe made it possible to organize NWB + video files into a dandiset. So there should be no need for `DANDI_DEVEL=1` switch to make `organize` consider them... if that is not the case already -- then may be no more need to be done and they just need to become "first class citizen" for all other commands which have to deal with them, e.g. `upload`
