### ISSUE TITLE
NWBInspector Integration

### ISSUE THREAD

**Issue by CodyCBakerPhD** [dandi/dandi-cli#924]
Hey all,

Linking this to ongoing NWBInspector To-Do list items https://github.com/NeurodataWithoutBorders/nwbinspector/issues/35 and https://github.com/NeurodataWithoutBorders/nwbinspector/issues/37.

I believe we will very soon

- [x] have all of the NWBFile metadata checks that DANDI auto-parsing expects or requires
- [x] ~add the `intention` flag that can be used to elevate those checks (which we normally consider pretty low priority) to maximum criticality~ `intention` flag became a `config` file that allows filtering of importance levels for various checks as well as built-in SKIP: https://github.com/NeurodataWithoutBorders/nwbinspector/pull/86 
- [ ] Optional: could also have an option to the NWBInspector CLI (perhaps `--fail-on-critical`) which will allow it to behave more like a true linter in that it would actually return or flag `False` if there are any failing `CRITICAL` checks returned. DANDI CLI could then use that result to say the file is not passing `dandi validate` in that sense; ~though one thing `dandi validate` may still need to do on its own is check external links.~ (looks like we are probably going to add checks for existence of external links as well!: https://github.com/NeurodataWithoutBorders/nwbinspector/issues/87)

CC: @bendichter

**Comment by bendichter** [comment]
Let's solidify where and how this would fit in the user workflow. I think it should be step 1, even before the user creates a dandiset. Should we have the user run:
`nwbinspector nwb_path -config upload_to_dandi`
or
`dandi inspect nwb_path`

then I think the output should be a text report in terminal

**Comment by CodyCBakerPhD** [comment]
This has been done for some time
