### ISSUE TITLE
etelemetry doesn't seem to run consistently

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#95]
this line https://github.com/dandi/dandi-cli/blob/master/dandi/__init__.py#L44 returns `False` when dandi cli is called in the terminal.

```
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x107f7b250>, 
'__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, 
'__file__': '/Users/satra/software/miniconda3/envs/dandi/bin/dandi', '__cached__': None,
 're': <module 're' from '/Users/satra/software/miniconda3/envs/dandi/lib/python3.7/re.py'>, 
'sys': <module 'sys' (built-in)>}
```

so possibly remove the if statement and call it anytime?

**Comment by yarikoptic** [comment]
ha -- I thought I was just always up to date! ;-) (which I think I was)

To keep it in "terminal only" mode we just need to see proper way to embed it into some `click` handler of some kind to be ran for each command (but not for `--help`) if executed. Although someone could argue that informing about new versions on `--help` could be the actual help ;)
