### ISSUE TITLE
Tests are failing on windows

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#963]
Need to be checked/fixed

**Comment by jwodder** [comment]
@yarikoptic The failures were two BIDS tests, and they're passing now that #955 is merged.

**Comment by yarikoptic** [comment]
coolio, thanks!

**Comment by TheChymera** [comment]
Yes, sorry about that, I updated the test data to include some examples with hidden sub-directories before the PR got merged.
