### ISSUE TITLE
`test_parse_dandi_url_not_found` broken

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-cli#967]
Due to changes in dandi-archive, `https://dandiarchive.org/dandiset/999999` no longer returns a 404, and so this test no longer passes:

https://github.com/dandi/dandi-cli/blob/00ee4ddf8785a91ff5bd893497b018ef5fce6437/dandi/tests/test_dandiarchive.py#L323-L327

CC @yarikoptic

**Comment by jwodder** [comment]
@yarikoptic What exactly do you want me to do for this?  Should I just open an issue in dandi-archive?

**Comment by yarikoptic** [comment]
It seems that the world remains round at the UX level:

```shell
$> dandi download https://dandiarchive.org/dandiset/999999
2022-04-20 17:51:37,531 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20220420215135Z-154310.log
Error: No such Dandiset: '999999'
```
so let's just announce this test as xfail until closure reached on https://github.com/dandi/dandi-archive/issues/1020
