### ISSUE TITLE
`test_parse_api_url[DANDI:000027]` broken

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-cli#968]
Due to changes in the redirector etc., `parse_dandi_url("DANDI:000027")` is currently returning a `DandisetURL` in which the `version_id` is `None`, whereas it was previously `"draft"`, leading to a failing test.  I'm uncertain exactly what the critical behavior change on the archive side was.

CC: @yarikoptic

**Comment by satra** [comment]
on this front `https://identifiers.org/DANDI:000027` now maps directly to the latest version, rather than draft.

**Comment by yarikoptic** [comment]
Thank you @jwodder for filing them and I would appreciate if you address them as well.  We do not need to remember about the glorious past of the `#` based urls, so no backward compatibility is needed IMHO.

**Comment by jwodder** [comment]
@yarikoptic So are you saying you just want the test updated to expect `None` instead of `"draft"`?

**Comment by yarikoptic** [comment]
I guess that would be the correct behavior.  FWIW the `dandi download` does download the latest version of `DANDI:000027` .
