### ISSUE TITLE
test_server_info failing due to no good version provided

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#976]
now that there is no redirector with hardcoded version and version is reported of dandi-archive itself we hit good old https://github.com/dandi/dandi-archive/issues/222 leading to

```
_______________________________ test_server_info _______________________________
dandi/tests/test_utils.py:321: in test_server_info
    assert Version(data["version"]) >= Version("1.2.0")
/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/semantic_version/base.py:105: in __init__
    major, minor, patch, prerelease, build = self.parse(version_string, partial)
/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/semantic_version/base.py:311: in parse
    raise ValueError('Invalid version string: %r' % version_string)
E   ValueError: Invalid version string: '0+unknown'
```

https://github.com/dandi/dandi-archive/pull/1054 might be the one to resolve it for the main deployments but I don't know if it would apply to our dockerized server testing since it hardcodes to 0.0.0 in  https://github.com/dandi/dandi-archive/pull/1054/files#diff-8fbdfcdd92c90a7625fcf215e3b363869ff8ce725869824d28380b863498d35dR14

**Comment by jwodder** [comment]
@yarikoptic That test is not run against the local Docker setup.  The references to Docker in the test's code are for the integration tests of the old redirector.

**Comment by yarikoptic** [comment]
so you think test would pass after https://github.com/dandi/dandi-archive/pull/1054 merged/deployed?

since placing into production would take time, should we just for now mark it as xfail and then reenable after deployed?

**Comment by jwodder** [comment]
@yarikoptic 

> so you think test would pass after https://github.com/dandi/dandi-archive/pull/1054 merged/deployed?

Yes.

> since placing into production would take time, should we just for now mark it as xfail and then reenable after deployed?

You tell me.
