### ISSUE TITLE
ngff upload running into validation errors

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#983]
i don't think there is a directory more the 5 levels into the ngff file. also, if there is, it would be good to know an example of one in the error.

```
$ dandi validate .
2022-04-25 09:34:22,018 [   ERROR] micr/sub-MITU01_ses-20210521h17m17s06_sample-178_stain-NPY_run-1_chunk-1_SPIM.ngff: 1 error(s)
2022-04-25 09:34:22,019 [   ERROR]   Zarr directory tree more than 5 directories deep
```

this error repeats for all ngff files in the directory

**Comment by jwodder** [comment]
@satra The error message is saying that `micr/sub-MITU01_ses-20210521h17m17s06_sample-178_stain-NPY_run-1_chunk-1_SPIM.ngff` itself is a directory tree with more than five levels.  If you believe this is inaccurate, can you point to somewhere that I can inspect this dataset?

**Comment by satra** [comment]
this is the file: https://api.dandiarchive.org/api/dandisets/000108/versions/draft/assets/1838aeed-c773-400e-84b1-be0b8fa63dd9/

**Comment by jwodder** [comment]
@satra That Zarr doesn't seem to have been processed by the API server; specifically, the `/zarr/{zarr_id}.zarr/` endpoint returns 404.  Hence, I can't inspect the filetree, and I'm not about to download some ginormous Zarr just to list its files.

**Comment by satra** [comment]
it's there: https://dandiarchive.s3.amazonaws.com/zarr/56509720-870c-4f43-ae41-7b75f9590722/.zattrs

**Comment by jwodder** [comment]
@satra The files under `0/0/0/0/0/` are too deep.

**Comment by satra** [comment]
then the cli needs to be fixed to add that level. those files are perfectly legitimate files for ngff.

`ls micr/sub-MITU01_ses-20210521h17m17s06_sample-178_stain-LEC_run-1_chunk-1_SPIM.ngff/0/0/0/0/0/0`

the last 0 is a leaf node.

**Comment by yarikoptic** [comment]
:+1: to increase to 7 for now
