### ISSUE TITLE
allow for redirector URLs (e.g., identifiers.org, bit.ly)

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#99]
```
$ dandi download https://identifiers.org/DANDI:000004
Error: We do not know how to map URL https://identifiers.org/DANDI:000004 to girder.
Regular expressions for known setups:
 - https?://dandiarchive.org/.*
 - https?://[^/]*dandiarchive-org.netlify.app/.*
 - (?P<server>(?P<protocol>https?)://(?P<hostname>[^/]+)/)#.*/(?P<asset_type>folder|collection|dandiset)/(?P<id>[a-f0-9]{24})$
 - (?P<server>(?P<protocol>https?)://(?P<hostname>[^/]+)/)#/folder/[a-f0-9]{24}/selected(?P<multiitem>(/item\+(?P<id>[a-f0-9]{24}))+)$
 - (?P<server>(?P<protocol>https?)://(?P<hostname>[^/]+)/)api/v1/(?P<asset_type>item)/(?P<id>[a-f0-9]{24})/download$
```

more generally follow redirects to determine if you can parse a url, should also help in the future with dois.

**Comment by yarikoptic** [comment]
should be just a matter of adding 
```
"https?://identifiers.org/DANDI:.*": {"handle_redirect": True},
```
to https://github.com/dandi/dandi-cli/blob/master/dandi/download.py#L20

**Comment by satra** [comment]
i meant to go more general. first doing redirect and then checking on whether urls map onto our services. this would allow more generalizability to people creating all kinds of shortcuts (bit.ly, etc.,.)

**Comment by yarikoptic** [comment]
oh... then I will keep this one open.  Meanwhile I will submit a dedicated fix PR for identifiers

**Comment by yarikoptic** [comment]
to support generally -- we could just add catch all 
```
"https?://.*": {"handle_redirect": True},
```
at the end of the list. But we would need to check first if our current code doesn't cause immediate download of the content and just follows redirect, and either in general it would be a good/safe idea ;-)
