### ISSUE TITLE
[Bug?] Schema version error with latest dandi install

### ISSUE THREAD

**Issue by CodyCBakerPhD** [dandi/dandi-cli#995]
Hey guys, we just started running into something like this with the standard dandi upload workflow using current `pip install dandi`:

```
Error: Server requires schema version 0.6.3; client only supports 0.6.2.  You may need to upgrade dandi and/or dandischema.
```

Is there a workaround or an ETA for new release?

Assuming related to https://github.com/dandi/dandi-cli/pull/987

**Comment by yarikoptic** [comment]
we are talking about staging right??

```
$> curl -s -X GET "https://api-staging.dandiarchive.org/api/info/" -H "accept: application/json" | jq '.schema_version'
"0.6.3"
$> curl -s -X GET "https://api.dandiarchive.org/api/info/" -H "accept: application/json" | jq '.schema_version'       
"0.6.2"
```
then indeed just try that #987 version -- I just tried, seems to work.  if we are not talking about staging -- then it is odd and please reopen.

**Comment by CodyCBakerPhD** [comment]
>  if we are not talking about staging -- then it is odd and please reopen.

I don't have permissions to reopen. Would you prefer a different ticket #?

**Comment by CodyCBakerPhD** [comment]
Or, rather, it seems the error is reversed for the non-staging set.

```
Error: Server requires schema version 0.6.2; client only supports 0.6.3.  You may need to upgrade dandi and/or dandischema.
```

**Comment by CodyCBakerPhD** [comment]
Downgrading (despite the error message above) to `dandi==0.39.2` fixed this for the non-staging.

**Comment by satra** [comment]
@yarikoptic - it's because no api-server release was done with the merge you did. only staging was updated. 

@CodyCBakerPhD - the production server is indeed on a separate mode.

**Comment by yarikoptic** [comment]
> @yarikoptic - it's because no api-server release was done with the merge you did. only staging was updated.

yeap.  We are releasing main deployment now... 
the main point is that the original issue occurred against the staging with not patched client, after using patched client -- worked.  What happened against production in https://github.com/dandi/dandi-cli/issues/995#issuecomment-1117740982 -- most likely that the patched client (pip install would not downgrade) was used, so it didn't work for similar reason. explicit downgrade installed released version compatible with the deployed server
