### ISSUE TITLE
upload: Channel back error message from server

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#996]
I tried to upload a 0-length file into staging (again hitting the old sore point of https://github.com/dandi/dandi-archive/issues/168), and got:

```shell
lena:/tmp/200589
$> DANDI_DEVEL=1 dandi upload --allow-any-path -i dandi-staging 123.txt
2022-05-03 17:23:19,397 [    INFO] Found 1 files to consider
PATH                 SIZE    ERRORS UPLOAD STATUS                MESSAGE                                                                                               
123.txt              0 Bytes   0           ERROR                 Error 400 while sending POST request to https://api-staging.dandiarchive.org/api/uploads/initialize/  
Summary:             0 Bytes               1 ERROR               1 Error 400 while sending POST request to https://api-staging.dandiarchive.org/api/uploads/initialize/
2022-05-03 17:23:19,728 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20220503212317Z-2206752.log
```
which isn't very telling.  The (very verbose DEBUG) log file did have the actual reason present

```
2022-05-03T17:23:19-0400 [DEBUG   ] urllib3.connectionpool 2206752:139731256288832 https://api-staging.dandiarchive.org:443 "POST /api/uploads/initialize/ HTTP/1.1" 400 68
2022-05-03T17:23:19-0400 [ERROR   ] dandi 2206752:139731256288832 Error 400 while sending POST request to https://api-staging.dandiarchive.org/api/uploads/initialize/: {"contentSize":["Ensure this value is greater than or equal to 1."]}
```

I wonder what should we do.  Possibilities

- do similar check on client size and ensure that filesize > 0.  But I would prefer avoid such ad-hoc checks, especially since it is simply due to a shortcoming  in current server implementation (https://github.com/dandi/dandi-archive/issues/168)
- somehow channel body of the error back to the user. May be instead of 

```
Error 400 while sending POST request to https://api-staging.dandiarchive.org/api/uploads/initialize/
```

display 

```
Error 400: {"contentSize":["Ensure this value is greater than or equal to 1."]}
```

WDYT @jwodder and @satra ?

**Comment by satra** [comment]
@yarikoptic - the server is already responding with the appropriate message. i would say trap that and pass it to the client. in this case since this is dandi-cli, i don't think uploading a 0-byte file is an ad hoc case. this would be like a 0.00001% case that an empty file should be uploaded. i think it is safe to assume that a 0-byte file is not acceptable as a valid file for dandi.

**Comment by yarikoptic** [comment]
> i would say trap that and pass it to the client

that is what I think and it is aligned with the title. The question was more of "how detailed our message should be so we still have reasonable UX in our tabular pyout form"? ;)  and indeed for that we should pass it within client from "trap" point to "display"

Either 0-length file legit upload target or not I think should be decided in a single place, and I think it should be server. That is why I decided against adding ad-hoc test in client.

**Comment by satra** [comment]
> Either 0-length file legit upload target or not I think should be decided in a single place

i think it can be part of validation step. and i think there are good reasons for validating on client before hitting the server.

**Comment by yarikoptic** [comment]
then I guess it should be "encoded" in the dandischema on `contentSize` so both client and server use the same logic.

**Comment by satra** [comment]
the server part i think doesn't try to validate metadata at that stage, i think. i don't think upload initialize requires any metadata other than dandiset id and contentsize.

**Comment by yarikoptic** [comment]
true enough! indeed it is just due to limitation in the server implementation, not metadata. But if we were to add some consistent constraint -- then we might want to do it at metadata level. Any other logic, must not be "shared" from server into client(s).

**But** I just worry that we might hit a use case for a valid 0-length file being needed (e.g. some empty mandatory README or CHANGES for BIDS), so I would prefer to not introduce some artificial limitation anyways. We do need to address original issue though -- channel details from the error message into displayed information.

@jwodder, let's for now just make that message compete, as 

```
Error 400 while sending POST request to https://api-staging.dandiarchive.org/api/uploads/initialize/ : {"contentSize":["Ensure this value is greater than or equal to 1."]}
```

**Comment by jwodder** [comment]
@yarikoptic Exactly under what conditions do you want the response body included in the exception message?  Note that it's possible for the body to be arbitrarily large.

**Comment by yarikoptic** [comment]
good point! what if we limit to 1kB, and if greater -- "Response was {len(response.data)} big, started with {response.data[:100]}" or smth alike?
